CREATE TABLE "content_revisions" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "content_revisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"content_id" uuid NOT NULL,
	"revision_number" integer NOT NULL,
	"content_version" integer NOT NULL,
	"content_type" text NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"category_id" uuid,
	"content" text,
	"content_json" jsonb,
	"meta_title" text,
	"meta_description" text,
	"excerpt" text,
	"cover_image" text,
	"status" text NOT NULL,
	"published_at" timestamp with time zone,
	"publish_at" timestamp with time zone,
	"unpublish_at" timestamp with time zone,
	"homepage" boolean DEFAULT false NOT NULL,
	"visibility" jsonb DEFAULT '{"public":true,"roles":[]}'::jsonb NOT NULL,
	"enable_comments" boolean DEFAULT false NOT NULL,
	"auto_publish_comments" boolean DEFAULT false NOT NULL,
	"allow_anonymous_comments" boolean DEFAULT false NOT NULL,
	"author_id" text NOT NULL,
	"updated_by" text,
	"created_by" text NOT NULL,
	"change_type" text NOT NULL,
	"change_note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "content_revisions_content_number_unique" UNIQUE("content_id","revision_number"),
	CONSTRAINT "content_revisions_type_check" CHECK ("content_revisions"."content_type" IN ('page','blog_post','hero_slider')),
	CONSTRAINT "content_revisions_status_check" CHECK ("content_revisions"."status" IN ('draft','in_review','approved','published','archived')),
	CONSTRAINT "content_revisions_schedule_window_check" CHECK ("content_revisions"."unpublish_at" IS NULL OR "content_revisions"."publish_at" IS NULL OR "content_revisions"."unpublish_at" > "content_revisions"."publish_at"),
	CONSTRAINT "content_revisions_change_type_check" CHECK ("content_revisions"."change_type" IN ('created','saved','submitted_for_review','approved','published','unpublished','archived','scheduled','restored','deleted_snapshot'))
);
--> statement-breakpoint
CREATE INDEX "content_revisions_content_created_idx" ON "content_revisions" USING btree ("content_id","created_at");--> statement-breakpoint
CREATE INDEX "content_revisions_created_by_idx" ON "content_revisions" USING btree ("created_by","created_at");