CREATE TABLE "webshop_addon_entitlements" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'license_required' NOT NULL,
	"license_key_ref" text,
	"entitlement_token" text,
	"provider" text,
	"provider_mode" text,
	"provider_owner_id" text,
	"provider_project_id" text,
	"deployment_environment" text,
	"package_name" text,
	"package_version" text,
	"package_installed_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" text,
	CONSTRAINT "webshop_addon_entitlements_singleton_check" CHECK ("webshop_addon_entitlements"."id" = 1),
	CONSTRAINT "webshop_addon_entitlements_status_check" CHECK ("webshop_addon_entitlements"."status" IN ('license_required','ready','expired','invalid','install_pending')),
	CONSTRAINT "webshop_addon_entitlements_provider_check" CHECK ("webshop_addon_entitlements"."provider" IS NULL OR "webshop_addon_entitlements"."provider" IN ('vercel')),
	CONSTRAINT "webshop_addon_entitlements_environment_check" CHECK ("webshop_addon_entitlements"."deployment_environment" IS NULL OR "webshop_addon_entitlements"."deployment_environment" IN ('production'))
);
