CREATE TABLE IF NOT EXISTS "cms_addon_installations" (
  "addon_key" text PRIMARY KEY NOT NULL,
  "installation_id" uuid NOT NULL,
  "desired_package_name" text NOT NULL,
  "desired_package_version" text NOT NULL,
  "desired_artifact_sha256" text NOT NULL,
  "installed_package_name" text,
  "installed_package_version" text,
  "installed_artifact_sha256" text,
  "runtime_contract_version" text,
  "schema_version" integer,
  "status" text NOT NULL DEFAULT 'license_accepted',
  "deployment_job_id" text,
  "install_attempt_count" integer NOT NULL DEFAULT 0,
  "last_error_code" text,
  "last_error_message" text,
  "requested_at" timestamp with time zone NOT NULL DEFAULT now(),
  "deployed_at" timestamp with time zone,
  "reconciled_at" timestamp with time zone,
  "ready_at" timestamp with time zone,
  "version" integer NOT NULL DEFAULT 0,
  CONSTRAINT "cms_addon_installations_status_check" CHECK ("status" IN ('license_accepted','install_pending','installed','migration_pending','ready','failed','disabled','update_pending')),
  CONSTRAINT "cms_addon_installations_key_check" CHECK ("addon_key" IN ('webshop','license-server'))
);
