import type { Metadata } from "next";
import { ClerkProvider, Show, SignInButton, SignUpButton } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { UserButtonClient } from "@/components/user-button-client";
import { shadcn } from "@clerk/themes";
import { Geist, Geist_Mono } from "next/font/google";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import { getRoles, hasRole } from "@/lib/roles";
import { SiteTopMenu } from "@/components/site-top-menu";
import { SiteTopMenuParentTrigger } from "@/components/site-top-menu-parent-trigger";
import { getGlobalSettings } from "@/data/global-settings";
import { cn } from "@/lib/utils";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const roles = getRoles(user?.publicMetadata);
  const isBackendUser =
    hasRole(roles, "admin") ||
    hasRole(roles, "publisher") ||
    hasRole(roles, "author");
  const isAdmin = hasRole(roles, "admin");
  const settings = await getGlobalSettings();
  const siteName = settings.siteName;
  const logoUrl = settings.siteLogo
    ? `/api/files/${settings.siteLogo.fileId}`
    : null;
  const stickyHeaderH = settings.stickyHeaderHeight;
  const stickyFooterH = settings.stickyFooterHeight;
  const headerIsSticky = settings.headerSettings.sticky;
  const footerIsSticky = settings.footerSettings.sticky;
  const headerBg = settings.headerSettings.background;
  const footerBg = settings.footerSettings.background;
  const headerH = stickyHeaderH > 0 ? stickyHeaderH : 64;
  const rootStyle = {
    ["--header-h" as string]: `${headerH}px`,
    ...(headerIsSticky
      ? { ["--sticky-header-h" as string]: `${headerH}px` }
      : {}),
    ...(footerIsSticky && stickyFooterH > 0
      ? { ["--sticky-footer-h" as string]: `${stickyFooterH}px` }
      : {}),
  } as React.CSSProperties;
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={rootStyle}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider appearance={{ theme: shadcn }}>
          <header
            className={cn(
              "bg-background flex items-center justify-between p-4 gap-4",
              headerIsSticky && "sticky top-0 z-50",
            )}
            style={{
              borderBottom: "1px solid #349aee",
              boxShadow: "0 1px 16px 2px #349aee88, 0 2px 32px 4px #349aee33",
              height: `${headerH}px`,
              ...(headerBg ? { backgroundColor: headerBg } : {}),
            }}
          >
            <a
              href="/"
              className="text-xl font-bold tracking-tight text-gray-400 hover:text-foreground transition-colors flex items-center gap-2"
            >
              {logoUrl && settings.headerSettings.showLogo && (
                <div
                  style={{
                    width: "calc(var(--header-h) * 0.85)",
                    height: "calc(var(--header-h) * 0.85)",
                    borderRadius: "50%",
                    border: "1px solid #6b7280",
                    overflow: "hidden",
                    flexShrink: 0,
                  }}
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={logoUrl}
                    alt={settings.siteLogo?.alt ?? siteName}
                    style={{
                      width: "100%",
                      height: "100%",
                      borderRadius: "50%",
                    }}
                    className="object-contain"
                  />
                </div>
              )}
              {settings.headerSettings.showSiteName && <span>{siteName}</span>}
            </a>
            <div className="flex items-center gap-4">
              <SiteTopMenu isBackendUser={isBackendUser} isAdmin={isAdmin} />
              {isBackendUser && (
                <div className="hidden lg:block">
                  <NavigationMenu viewport={false}>
                    <NavigationMenuList>
                      <NavigationMenuItem>
                        {isAdmin ? (
                          <>
                            <SiteTopMenuParentTrigger
                              url="/dashboard"
                              target="_self"
                              label="Dashboard"
                            />
                            <NavigationMenuContent>
                              <ul className="grid w-48 gap-1 p-2">
                                <li>
                                  <NavigationMenuLink asChild>
                                    <Link
                                      href="/dashboard/global-settings"
                                      className="block rounded px-3 py-2 text-sm hover:bg-accent hover:text-accent-foreground"
                                    >
                                      Global Settings
                                    </Link>
                                  </NavigationMenuLink>
                                </li>
                              </ul>
                            </NavigationMenuContent>
                          </>
                        ) : (
                          <NavigationMenuLink
                            asChild
                            className={navigationMenuTriggerStyle()}
                          >
                            <Link href="/dashboard">Dashboard</Link>
                          </NavigationMenuLink>
                        )}
                      </NavigationMenuItem>
                      <NavigationMenuItem>
                        {isAdmin ? (
                          <>
                            <SiteTopMenuParentTrigger
                              url="/dashboard/content"
                              target="_self"
                              label="Content"
                            />
                            <NavigationMenuContent>
                              <ul className="grid w-52 gap-1 p-2">
                                <li>
                                  <NavigationMenuLink asChild>
                                    <Link
                                      href="/dashboard/content-categories"
                                      className="block rounded px-3 py-2 text-sm hover:bg-accent hover:text-accent-foreground"
                                    >
                                      Content Categories
                                    </Link>
                                  </NavigationMenuLink>
                                </li>
                              </ul>
                            </NavigationMenuContent>
                          </>
                        ) : (
                          <NavigationMenuLink
                            asChild
                            className={navigationMenuTriggerStyle()}
                          >
                            <Link href="/dashboard/content">Content</Link>
                          </NavigationMenuLink>
                        )}
                      </NavigationMenuItem>
                      <NavigationMenuItem>
                        <SiteTopMenuParentTrigger
                          url="/dashboard/filemanager"
                          target="_self"
                          label="File Manager"
                        />
                        <NavigationMenuContent>
                          <ul className="grid w-52 gap-1 p-2">
                            <li>
                              <NavigationMenuLink asChild>
                                <Link
                                  href="/dashboard/gallerymanager"
                                  className="block rounded px-3 py-2 text-sm hover:bg-accent hover:text-accent-foreground"
                                >
                                  Gallery Manager
                                </Link>
                              </NavigationMenuLink>
                            </li>
                          </ul>
                        </NavigationMenuContent>
                      </NavigationMenuItem>
                      {isAdmin && (
                        <>
                          <NavigationMenuItem>
                            <NavigationMenuLink
                              asChild
                              className={navigationMenuTriggerStyle()}
                            >
                              <Link href="/dashboard/users">Users</Link>
                            </NavigationMenuLink>
                          </NavigationMenuItem>
                          <NavigationMenuItem>
                            <NavigationMenuLink
                              asChild
                              className={navigationMenuTriggerStyle()}
                            >
                              <Link href="/dashboard/top-menu">Top Menu</Link>
                            </NavigationMenuLink>
                          </NavigationMenuItem>
                          <NavigationMenuItem>
                            <NavigationMenuLink
                              asChild
                              className={navigationMenuTriggerStyle()}
                            >
                              <Link href="/dashboard/form-builder">
                                Form Builder
                              </Link>
                            </NavigationMenuLink>
                          </NavigationMenuItem>
                        </>
                      )}
                    </NavigationMenuList>
                  </NavigationMenu>
                </div>
              )}
              <Show when="signed-out">
                <SignInButton mode="modal">
                  <Button variant="ghost" size="lg" className="cursor-pointer">
                    Sign in
                  </Button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <Button
                    variant="outline"
                    size="lg"
                    className="cursor-pointer"
                  >
                    Sign up
                  </Button>
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserButtonClient />
              </Show>
            </div>
          </header>
          <div
            style={{
              ...(headerIsSticky && stickyHeaderH > 0
                ? { paddingTop: `${stickyHeaderH}px` }
                : {}),
              ...(footerIsSticky && stickyFooterH > 0
                ? { paddingBottom: `${stickyFooterH}px` }
                : {}),
            }}
          >
            {children}
          </div>
          <footer
            className={cn(
              "bg-background mt-auto px-6 py-8 text-sm text-muted-foreground",
              footerIsSticky && "sticky bottom-0 z-50",
            )}
            style={{
              borderTop: "1px solid #349aee",
              boxShadow: "0 -1px 16px 2px #349aee88, 0 -2px 32px 4px #349aee33",
              ...(stickyFooterH > 0 ? { height: `${stickyFooterH}px` } : {}),
              ...(footerBg ? { backgroundColor: footerBg } : {}),
            }}
          >
            {(settings.footerContent || settings.footerSettings.copyright) && (
              <div className="mx-auto flex max-w-5xl flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
                {settings.footerContent && (
                  <div
                    className="prose prose-invert max-w-none text-sm text-muted-foreground [&_a]:underline [&_a]:hover:text-foreground"
                    dangerouslySetInnerHTML={{ __html: settings.footerContent }}
                  />
                )}
                {settings.footerSettings.copyright && (
                  <div className="sm:text-right shrink-0">
                    <span>{settings.footerSettings.copyright}</span>
                  </div>
                )}
              </div>
            )}
          </footer>
        </ClerkProvider>
      </body>
    </html>
  );
}
