import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const CONTENT_CATEGORIES_SOURCE_STRINGS = [
  "Content Categories",
  "Manage categories for pages and blog posts. Admin access only.",
  "Page categories",
  "Blog post categories",
  "Webshop categories",
  "Blog Post",
  "page",
  "blog post",
  "Search by name...",
  "All authors",
  "{type} Categories",
  "Name",
  "Items",
  "Author",
  "Updated",
  "Actions",
  "Select all",
  "Select {name}",
  "by {name}",
  "No {type} categories match your search.",
  "No {type} categories yet.",
  "Add Category",
  "Add {type} Category",
  "Enter a name for the new {type} category.",
  "Edit {type} Category",
  "Update the name or reassign the author of this category.",
  "Delete category?",
  "This will permanently delete the category {name}. This action cannot be undone.",
  "Delete selected ({count})",
  "Delete selected categories?",
  "This will permanently delete {count} selected category. This action cannot be undone.",
  "This will permanently delete {count} selected categories. This action cannot be undone.",
  "Category Name",
  "e.g. News",
  "Select a user...",
  "Name is required.",
  "Name must be 100 characters or fewer.",
  "Author is required.",
  "Owner is required.",
  "Invalid category ID.",
  "A category with that name already exists for this content type.",
  "Target user must be a backend user.",
  "This category is assigned to content items and cannot be deleted.",
  "One or more selected categories are assigned to content items and cannot be deleted.",
  "Something went wrong. Please try again.",
  "Read-only",
  "Edit existing only",
  "Management happens in the Webshop dashboard. These rows link to the paid add-on category editor.",
  "Manage in Webshop",
  "No Webshop categories yet.",
  "Slug",
  "Status",
  "Products",
  "Open",
  "Open {name}",
  "active",
  "draft",
  "hidden",
  "archived",
  "inactive",
] as const;

type ContentCategoriesSource =
  (typeof CONTENT_CATEGORIES_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "Kategorije sadržaja|Upravljaj kategorijama za stranice i blog objave. Samo za admine.|Kategorije stranica|Kategorije blog objava|Webshop kategorije|Blog objava|stranica|blog objava|Pretraži po nazivu...|Svi autori|Kategorije: {type}|Naziv|Stavke|Autor|Ažurirano|Akcije|Izaberi sve|Izaberi {name}|od {name}|Nijedna {type} kategorija ne odgovara pretrazi.|Još nema {type} kategorija.|Dodaj kategoriju|Dodaj kategoriju: {type}|Unesi naziv za novu {type} kategoriju.|Izmeni kategoriju: {type}|Ažuriraj naziv ili dodeli drugog autora ovoj kategoriji.|Obrisati kategoriju?|Ovo će trajno obrisati kategoriju {name}. Ova radnja se ne može opozvati.|Obriši izabrano ({count})|Obrisati izabrane kategorije?|Ovo će trajno obrisati {count} izabranu kategoriju. Ova radnja se ne može opozvati.|Ovo će trajno obrisati {count} izabranih kategorija. Ova radnja se ne može opozvati.|Naziv kategorije|npr. Vesti|Izaberi korisnika...|Naziv je obavezan.|Naziv mora imati 100 znakova ili manje.|Autor je obavezan.|Vlasnik je obavezan.|Neispravan ID kategorije.|Kategorija sa tim nazivom već postoji za ovaj tip sadržaja.|Ciljni korisnik mora biti backend korisnik.|Ova kategorija je dodeljena stavkama sadržaja i ne može biti obrisana.|Jedna ili više izabranih kategorija su dodeljene stavkama sadržaja i ne mogu biti obrisane.|Nešto je pošlo naopako. Pokušaj ponovo.|Samo za čitanje|Samo izmena postojećeg|Upravljanje se obavlja u Webshop kontrolnoj tabli. Ovi redovi vode do editora kategorija plaćenog dodatka.|Upravljaj u Webshopu|Još nema Webshop kategorija.|URL oznaka|Status|Proizvodi|Otvori|Otvori {name}|aktivno|nacrt|skriveno|arhivirano|neaktivno",
  "sr-Cyrl":
    "Категорије садржаја|Управљај категоријама за странице и блог објаве. Само за администраторе.|Категорије страница|Категорије блог објава|Webshop категорије|Блог објава|страница|блог објава|Претражи по називу...|Сви аутори|Категорије: {type}|Назив|Ставке|Аутор|Ажурирано|Акције|Изабери све|Изабери {name}|од {name}|Ниједна {type} категорија не одговара претрази.|Још нема {type} категорија.|Додај категорију|Додај категорију: {type}|Унеси назив за нову {type} категорију.|Измени категорију: {type}|Ажурирај назив или додели другог аутора овој категорији.|Обрисати категорију?|Ово ће трајно обрисати категорију {name}. Ова радња се не може опозвати.|Обриши изабрано ({count})|Обрисати изабране категорије?|Ово ће трајно обрисати {count} изабрану категорију. Ова радња се не може опозвати.|Ово ће трајно обрисати {count} изабраних категорија. Ова радња се не може опозвати.|Назив категорије|нпр. Вести|Изабери корисника...|Назив је обавезан.|Назив мора имати 100 знакова или мање.|Аутор је обавезан.|Власник је обавезан.|Неисправан ID категорије.|Категорија са тим називом већ постоји за овај тип садржаја.|Циљни корисник мора бити backend корисник.|Ова категорија је додељена ставкама садржаја и не може бити обрисана.|Једна или више изабраних категорија су додељене ставкама садржаја и не могу бити обрисане.|Нешто је пошло наопако. Покушај поново.|Само за читање|Само измена постојећег|Управљање се обавља у Webshop контролној табли. Ови редови воде до едитора категорија плаћеног додатка.|Управљај у Webshop-у|Још нема Webshop категорија.|URL ознака|Статус|Производи|Отвори|Отвори {name}|активно|нацрт|скривено|архивирано|неактивно",
  hr: "Kategorije sadržaja|Upravljajte kategorijama za stranice i blog objave. Samo za administratore.|Kategorije stranica|Kategorije blog objava|Webshop kategorije|Blog objava|stranica|blog objava|Pretraži po nazivu...|Svi autori|Kategorije: {type}|Naziv|Stavke|Autor|Ažurirano|Akcije|Odaberi sve|Odaberi {name}|od {name}|Nijedna {type} kategorija ne odgovara pretrazi.|Još nema {type} kategorija.|Dodaj kategoriju|Dodaj kategoriju: {type}|Unesite naziv za novu {type} kategoriju.|Uredi kategoriju: {type}|Ažurirajte naziv ili ponovno dodijelite autora ove kategorije.|Izbrisati kategoriju?|Ovo će trajno izbrisati kategoriju {name}. Ova se radnja ne može poništiti.|Izbriši odabrano ({count})|Izbrisati odabrane kategorije?|Ovo će trajno izbrisati {count} odabranu kategoriju. Ova se radnja ne može poništiti.|Ovo će trajno izbrisati {count} odabranih kategorija. Ova se radnja ne može poništiti.|Naziv kategorije|npr. Vijesti|Odaberite korisnika...|Naziv je obavezan.|Naziv mora imati 100 znakova ili manje.|Autor je obavezan.|Vlasnik je obavezan.|Neispravan ID kategorije.|Kategorija s tim nazivom već postoji za ovu vrstu sadržaja.|Ciljani korisnik mora biti backend korisnik.|Ova kategorija dodijeljena je stavkama sadržaja i ne može se izbrisati.|Jedna ili više odabranih kategorija dodijeljene su stavkama sadržaja i ne mogu se izbrisati.|Nešto je pošlo po zlu. Pokušajte ponovo.|Samo za čitanje|Samo uređivanje postojećeg|Upravljanje se odvija u Webshop nadzornoj ploči. Ovi redovi vode do editora kategorija plaćenog dodatka.|Upravljaj u Webshopu|Još nema Webshop kategorija.|URL oznaka|Status|Proizvodi|Otvori|Otvori {name}|aktivno|skica|skriveno|arhivirano|neaktivno",
  de: "Inhaltskategorien|Verwalte Kategorien für Seiten und Blogbeiträge. Nur Adminzugriff.|Seitenkategorien|Blogbeitragskategorien|Webshop-Kategorien|Blogbeitrag|Seite|Blogbeitrag|Nach Name suchen...|Alle Autoren|{type}-Kategorien|Name|Einträge|Autor|Aktualisiert|Aktionen|Alle auswählen|{name} auswählen|von {name}|Keine {type}-Kategorien entsprechen deiner Suche.|Noch keine {type}-Kategorien.|Kategorie hinzufügen|{type}-Kategorie hinzufügen|Gib einen Namen für die neue {type}-Kategorie ein.|{type}-Kategorie bearbeiten|Aktualisiere den Namen oder weise dieser Kategorie einen anderen Autor zu.|Kategorie löschen?|Die Kategorie {name} wird dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.|Ausgewählte löschen ({count})|Ausgewählte Kategorien löschen?|{count} ausgewählte Kategorie wird dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.|{count} ausgewählte Kategorien werden dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.|Kategoriename|z. B. News|Benutzer auswählen...|Name ist erforderlich.|Der Name darf höchstens 100 Zeichen haben.|Autor ist erforderlich.|Besitzer ist erforderlich.|Ungültige Kategorie-ID.|Für diesen Inhaltstyp existiert bereits eine Kategorie mit diesem Namen.|Der Zielbenutzer muss ein Backend-Benutzer sein.|Diese Kategorie ist Inhaltselementen zugewiesen und kann nicht gelöscht werden.|Eine oder mehrere ausgewählte Kategorien sind Inhaltselementen zugewiesen und können nicht gelöscht werden.|Etwas ist schiefgelaufen. Bitte versuche es erneut.|Schreibgeschützt|Nur Bestehendes bearbeiten|Die Verwaltung erfolgt im Webshop-Dashboard. Diese Zeilen verlinken zum Kategorie-Editor des kostenpflichtigen Add-ons.|Im Webshop verwalten|Noch keine Webshop-Kategorien.|URL-Kennung|Status|Produkte|Öffnen|{name} öffnen|aktiv|Entwurf|ausgeblendet|archiviert|inaktiv",
  fr: "Catégories de contenu|Gérez les catégories des pages et des articles de blog. Accès administrateur uniquement.|Catégories de pages|Catégories d’articles de blog|Catégories Webshop|Article de blog|page|article de blog|Rechercher par nom...|Tous les auteurs|Catégories {type}|Nom|Éléments|Auteur|Mis à jour|Actions|Tout sélectionner|Sélectionner {name}|par {name}|Aucune catégorie {type} ne correspond à votre recherche.|Aucune catégorie {type} pour l’instant.|Ajouter une catégorie|Ajouter une catégorie {type}|Saisissez un nom pour la nouvelle catégorie {type}.|Modifier la catégorie {type}|Mettez à jour le nom ou réattribuez l’auteur de cette catégorie.|Supprimer la catégorie ?|Cela supprimera définitivement la catégorie {name}. Cette action est irréversible.|Supprimer la sélection ({count})|Supprimer les catégories sélectionnées ?|Cela supprimera définitivement {count} catégorie sélectionnée. Cette action est irréversible.|Cela supprimera définitivement {count} catégories sélectionnées. Cette action est irréversible.|Nom de la catégorie|p. ex. Actualités|Sélectionner un utilisateur...|Le nom est obligatoire.|Le nom doit contenir 100 caractères ou moins.|L’auteur est obligatoire.|Le propriétaire est obligatoire.|ID de catégorie invalide.|Une catégorie portant ce nom existe déjà pour ce type de contenu.|L’utilisateur cible doit être un utilisateur backend.|Cette catégorie est assignée à des éléments de contenu et ne peut pas être supprimée.|Une ou plusieurs catégories sélectionnées sont assignées à des éléments de contenu et ne peuvent pas être supprimées.|Une erreur s’est produite. Veuillez réessayer.|Lecture seule|Modifier l’existant uniquement|La gestion se fait dans le tableau de bord Webshop. Ces lignes mènent à l’éditeur de catégories de l’add-on payant.|Gérer dans Webshop|Aucune catégorie Webshop pour l’instant.|Identifiant URL|Statut|Produits|Ouvrir|Ouvrir {name}|actif|brouillon|masqué|archivé|inactif",
  es: "Categorías de contenido|Administra categorías para páginas y entradas de blog. Solo acceso de administradores.|Categorías de páginas|Categorías de entradas de blog|Categorías de Webshop|Entrada de blog|página|entrada de blog|Buscar por nombre...|Todos los autores|Categorías de {type}|Nombre|Elementos|Autor|Actualizado|Acciones|Seleccionar todo|Seleccionar {name}|por {name}|Ninguna categoría de {type} coincide con tu búsqueda.|Aún no hay categorías de {type}.|Añadir categoría|Añadir categoría de {type}|Introduce un nombre para la nueva categoría de {type}.|Editar categoría de {type}|Actualiza el nombre o reasigna el autor de esta categoría.|¿Eliminar categoría?|Esto eliminará permanentemente la categoría {name}. Esta acción no se puede deshacer.|Eliminar seleccionadas ({count})|¿Eliminar categorías seleccionadas?|Esto eliminará permanentemente {count} categoría seleccionada. Esta acción no se puede deshacer.|Esto eliminará permanentemente {count} categorías seleccionadas. Esta acción no se puede deshacer.|Nombre de categoría|p. ej. Noticias|Seleccionar un usuario...|El nombre es obligatorio.|El nombre debe tener 100 caracteres o menos.|El autor es obligatorio.|El propietario es obligatorio.|ID de categoría inválido.|Ya existe una categoría con ese nombre para este tipo de contenido.|El usuario destino debe ser un usuario backend.|Esta categoría está asignada a elementos de contenido y no se puede eliminar.|Una o más categorías seleccionadas están asignadas a elementos de contenido y no se pueden eliminar.|Algo salió mal. Inténtalo de nuevo.|Solo lectura|Solo editar existentes|La gestión se realiza en el panel de Webshop. Estas filas enlazan al editor de categorías del add-on de pago.|Gestionar en Webshop|Aún no hay categorías de Webshop.|Identificador URL|Estado|Productos|Abrir|Abrir {name}|activo|borrador|oculto|archivado|inactivo",
  it: "Categorie contenuto|Gestisci le categorie per pagine e articoli del blog. Accesso solo amministratori.|Categorie pagine|Categorie articoli blog|Categorie Webshop|Articolo blog|pagina|articolo blog|Cerca per nome...|Tutti gli autori|Categorie {type}|Nome|Elementi|Autore|Aggiornato|Azioni|Seleziona tutto|Seleziona {name}|di {name}|Nessuna categoria {type} corrisponde alla ricerca.|Nessuna categoria {type} ancora presente.|Aggiungi categoria|Aggiungi categoria {type}|Inserisci un nome per la nuova categoria {type}.|Modifica categoria {type}|Aggiorna il nome o riassegna l’autore di questa categoria.|Eliminare la categoria?|Questo eliminerà definitivamente la categoria {name}. L’azione non può essere annullata.|Elimina selezionate ({count})|Eliminare le categorie selezionate?|Questo eliminerà definitivamente {count} categoria selezionata. L’azione non può essere annullata.|Questo eliminerà definitivamente {count} categorie selezionate. L’azione non può essere annullata.|Nome categoria|es. Notizie|Seleziona un utente...|Il nome è obbligatorio.|Il nome deve contenere al massimo 100 caratteri.|L’autore è obbligatorio.|Il proprietario è obbligatorio.|ID categoria non valido.|Esiste già una categoria con questo nome per questo tipo di contenuto.|L’utente di destinazione deve essere un utente backend.|Questa categoria è assegnata a elementi di contenuto e non può essere eliminata.|Una o più categorie selezionate sono assegnate a elementi di contenuto e non possono essere eliminate.|Si è verificato un errore. Riprova.|Sola lettura|Solo modifica esistenti|La gestione avviene nella dashboard Webshop. Queste righe portano all’editor categorie dell’add-on a pagamento.|Gestisci in Webshop|Nessuna categoria Webshop ancora presente.|Identificatore URL|Stato|Prodotti|Apri|Apri {name}|attivo|bozza|nascosto|archiviato|inattivo",
  pt: "Categorias de conteúdo|Gira categorias para páginas e artigos de blog. Acesso apenas para administradores.|Categorias de páginas|Categorias de artigos de blog|Categorias Webshop|Artigo de blog|página|artigo de blog|Pesquisar por nome...|Todos os autores|Categorias de {type}|Nome|Itens|Autor|Atualizado|Ações|Selecionar tudo|Selecionar {name}|por {name}|Nenhuma categoria de {type} corresponde à pesquisa.|Ainda não há categorias de {type}.|Adicionar categoria|Adicionar categoria de {type}|Introduza um nome para a nova categoria de {type}.|Editar categoria de {type}|Atualize o nome ou reatribua o autor desta categoria.|Eliminar categoria?|Isto eliminará permanentemente a categoria {name}. Esta ação não pode ser anulada.|Eliminar selecionadas ({count})|Eliminar categorias selecionadas?|Isto eliminará permanentemente {count} categoria selecionada. Esta ação não pode ser anulada.|Isto eliminará permanentemente {count} categorias selecionadas. Esta ação não pode ser anulada.|Nome da categoria|ex. Notícias|Selecionar um utilizador...|O nome é obrigatório.|O nome deve ter 100 caracteres ou menos.|O autor é obrigatório.|O proprietário é obrigatório.|ID de categoria inválido.|Já existe uma categoria com esse nome para este tipo de conteúdo.|O utilizador de destino tem de ser um utilizador backend.|Esta categoria está atribuída a itens de conteúdo e não pode ser eliminada.|Uma ou mais categorias selecionadas estão atribuídas a itens de conteúdo e não podem ser eliminadas.|Algo correu mal. Tente novamente.|Só de leitura|Editar apenas existentes|A gestão acontece no painel Webshop. Estas linhas ligam ao editor de categorias do add-on pago.|Gerir no Webshop|Ainda não há categorias Webshop.|Identificador URL|Estado|Produtos|Abrir|Abrir {name}|ativo|rascunho|oculto|arquivado|inativo",
  "pt-BR":
    "Categorias de conteúdo|Gerencie categorias para páginas e posts de blog. Acesso apenas para administradores.|Categorias de páginas|Categorias de posts de blog|Categorias do Webshop|Post de blog|página|post de blog|Pesquisar por nome...|Todos os autores|Categorias de {type}|Nome|Itens|Autor|Atualizado|Ações|Selecionar tudo|Selecionar {name}|por {name}|Nenhuma categoria de {type} corresponde à sua busca.|Ainda não há categorias de {type}.|Adicionar categoria|Adicionar categoria de {type}|Insira um nome para a nova categoria de {type}.|Editar categoria de {type}|Atualize o nome ou reatribua o autor desta categoria.|Excluir categoria?|Isso excluirá permanentemente a categoria {name}. Essa ação não pode ser desfeita.|Excluir selecionadas ({count})|Excluir categorias selecionadas?|Isso excluirá permanentemente {count} categoria selecionada. Essa ação não pode ser desfeita.|Isso excluirá permanentemente {count} categorias selecionadas. Essa ação não pode ser desfeita.|Nome da categoria|ex. Notícias|Selecionar um usuário...|O nome é obrigatório.|O nome deve ter 100 caracteres ou menos.|O autor é obrigatório.|O proprietário é obrigatório.|ID de categoria inválido.|Já existe uma categoria com esse nome para este tipo de conteúdo.|O usuário de destino deve ser um usuário backend.|Esta categoria está atribuída a itens de conteúdo e não pode ser excluída.|Uma ou mais categorias selecionadas estão atribuídas a itens de conteúdo e não podem ser excluídas.|Algo deu errado. Tente novamente.|Somente leitura|Editar somente existentes|O gerenciamento acontece no painel do Webshop. Estas linhas levam ao editor de categorias do add-on pago.|Gerenciar no Webshop|Ainda não há categorias do Webshop.|Identificador URL|Status|Produtos|Abrir|Abrir {name}|ativo|rascunho|oculto|arquivado|inativo",
  nl: "Contentcategorieën|Beheer categorieën voor pagina’s en blogberichten. Alleen voor beheerders.|Paginacategorieën|Blogberichtcategorieën|Webshopcategorieën|Blogbericht|pagina|blogbericht|Zoeken op naam...|Alle auteurs|{type}-categorieën|Naam|Items|Auteur|Bijgewerkt|Acties|Alles selecteren|{name} selecteren|door {name}|Geen {type}-categorieën komen overeen met je zoekopdracht.|Nog geen {type}-categorieën.|Categorie toevoegen|{type}-categorie toevoegen|Voer een naam in voor de nieuwe {type}-categorie.|{type}-categorie bewerken|Werk de naam bij of wijs de auteur van deze categorie opnieuw toe.|Categorie verwijderen?|Dit verwijdert de categorie {name} permanent. Deze actie kan niet ongedaan worden gemaakt.|Geselecteerde verwijderen ({count})|Geselecteerde categorieën verwijderen?|Dit verwijdert {count} geselecteerde categorie permanent. Deze actie kan niet ongedaan worden gemaakt.|Dit verwijdert {count} geselecteerde categorieën permanent. Deze actie kan niet ongedaan worden gemaakt.|Categorienaam|bijv. Nieuws|Selecteer een gebruiker...|Naam is verplicht.|Naam mag maximaal 100 tekens bevatten.|Auteur is verplicht.|Eigenaar is verplicht.|Ongeldige categorie-ID.|Er bestaat al een categorie met die naam voor dit inhoudstype.|De doelgebruiker moet een backendgebruiker zijn.|Deze categorie is toegewezen aan contentitems en kan niet worden verwijderd.|Een of meer geselecteerde categorieën zijn toegewezen aan contentitems en kunnen niet worden verwijderd.|Er is iets misgegaan. Probeer het opnieuw.|Alleen-lezen|Alleen bestaande bewerken|Beheer gebeurt in het Webshop-dashboard. Deze rijen linken naar de categorie-editor van de betaalde add-on.|Beheren in Webshop|Nog geen Webshopcategorieën.|URL-kenmerk|Status|Producten|Openen|{name} openen|actief|concept|verborgen|gearchiveerd|inactief",
  pl: "Kategorie treści|Zarządzaj kategoriami stron i wpisów blogowych. Dostęp tylko dla administratorów.|Kategorie stron|Kategorie wpisów blogowych|Kategorie Webshop|Wpis blogowy|strona|wpis blogowy|Szukaj po nazwie...|Wszyscy autorzy|Kategorie: {type}|Nazwa|Elementy|Autor|Zaktualizowano|Akcje|Zaznacz wszystko|Zaznacz {name}|przez {name}|Żadna kategoria {type} nie pasuje do wyszukiwania.|Brak kategorii {type}.|Dodaj kategorię|Dodaj kategorię: {type}|Wpisz nazwę nowej kategorii {type}.|Edytuj kategorię: {type}|Zaktualizuj nazwę lub przypisz tej kategorii innego autora.|Usunąć kategorię?|Kategoria {name} zostanie trwale usunięta. Tej akcji nie można cofnąć.|Usuń zaznaczone ({count})|Usunąć zaznaczone kategorie?|{count} zaznaczona kategoria zostanie trwale usunięta. Tej akcji nie można cofnąć.|{count} zaznaczonych kategorii zostanie trwale usuniętych. Tej akcji nie można cofnąć.|Nazwa kategorii|np. Aktualności|Wybierz użytkownika...|Nazwa jest wymagana.|Nazwa może mieć maksymalnie 100 znaków.|Autor jest wymagany.|Właściciel jest wymagany.|Nieprawidłowy identyfikator kategorii.|Kategoria o tej nazwie już istnieje dla tego typu treści.|Docelowy użytkownik musi być użytkownikiem backendu.|Ta kategoria jest przypisana do elementów treści i nie może zostać usunięta.|Co najmniej jedna zaznaczona kategoria jest przypisana do elementów treści i nie może zostać usunięta.|Coś poszło nie tak. Spróbuj ponownie.|Tylko do odczytu|Tylko edycja istniejących|Zarządzanie odbywa się w panelu Webshop. Te wiersze prowadzą do edytora kategorii płatnego dodatku.|Zarządzaj w Webshopie|Brak kategorii Webshop.|Identyfikator URL|Status|Produkty|Otwórz|Otwórz {name}|aktywne|szkic|ukryte|zarchiwizowane|nieaktywne",
  tr: "İçerik kategorileri|Sayfalar ve blog yazıları için kategorileri yönetin. Yalnızca yönetici erişimi.|Sayfa kategorileri|Blog yazısı kategorileri|Webshop kategorileri|Blog yazısı|sayfa|blog yazısı|Ada göre ara...|Tüm yazarlar|{type} kategorileri|Ad|Öğeler|Yazar|Güncellendi|İşlemler|Tümünü seç|{name} seç|{name} tarafından|Aramanızla eşleşen {type} kategorisi yok.|Henüz {type} kategorisi yok.|Kategori ekle|{type} kategorisi ekle|Yeni {type} kategorisi için bir ad girin.|{type} kategorisini düzenle|Bu kategorinin adını güncelleyin veya yazarını yeniden atayın.|Kategori silinsin mi?|Bu, {name} kategorisini kalıcı olarak siler. Bu işlem geri alınamaz.|Seçilenleri sil ({count})|Seçilen kategoriler silinsin mi?|Bu, {count} seçili kategoriyi kalıcı olarak siler. Bu işlem geri alınamaz.|Bu, {count} seçili kategoriyi kalıcı olarak siler. Bu işlem geri alınamaz.|Kategori adı|örn. Haberler|Kullanıcı seçin...|Ad gereklidir.|Ad 100 karakter veya daha kısa olmalıdır.|Yazar gereklidir.|Sahip gereklidir.|Geçersiz kategori ID’si.|Bu içerik türü için bu ada sahip bir kategori zaten var.|Hedef kullanıcı bir backend kullanıcısı olmalıdır.|Bu kategori içerik öğelerine atanmış ve silinemez.|Seçilen kategorilerden biri veya daha fazlası içerik öğelerine atanmış ve silinemez.|Bir şeyler ters gitti. Lütfen tekrar deneyin.|Salt okunur|Yalnızca mevcutları düzenle|Yönetim Webshop panelinde yapılır. Bu satırlar ücretli eklentinin kategori düzenleyicisine bağlanır.|Webshop’ta yönet|Henüz Webshop kategorisi yok.|URL kimliği|Durum|Ürünler|Aç|{name} aç|aktif|taslak|gizli|arşivlendi|pasif",
  mk: "Категории на содржина|Управувајте со категории за страници и блог објави. Само за администратори.|Категории на страници|Категории на блог објави|Webshop категории|Блог објава|страница|блог објава|Пребарај по име...|Сите автори|Категории: {type}|Име|Ставки|Автор|Ажурирано|Акции|Избери сè|Избери {name}|од {name}|Ниту една {type} категорија не одговара на пребарувањето.|Сè уште нема {type} категории.|Додај категорија|Додај категорија: {type}|Внесете име за новата {type} категорија.|Уреди категорија: {type}|Ажурирајте го името или преназначете го авторот на оваа категорија.|Да се избрише категоријата?|Ова трајно ќе ја избрише категоријата {name}. Оваа акција не може да се врати.|Избриши избрани ({count})|Да се избришат избраните категории?|Ова трајно ќе избрише {count} избрана категорија. Оваа акција не може да се врати.|Ова трајно ќе избрише {count} избрани категории. Оваа акција не може да се врати.|Име на категорија|на пр. Вести|Изберете корисник...|Името е задолжително.|Името мора да има 100 знаци или помалку.|Авторот е задолжителен.|Сопственикот е задолжителен.|Невалиден ID на категорија.|Категорија со тоа име веќе постои за овој тип содржина.|Целниот корисник мора да биде backend корисник.|Оваа категорија е доделена на ставки со содржина и не може да се избрише.|Една или повеќе избрани категории се доделени на ставки со содржина и не можат да се избришат.|Нешто тргна наопаку. Обидете се повторно.|Само за читање|Само уредување постоечки|Управувањето се врши во Webshop контролната табла. Овие редови водат до уредувачот на категории на платениот додаток.|Управувај во Webshop|Сè уште нема Webshop категории.|URL ознака|Статус|Производи|Отвори|Отвори {name}|активно|нацрт|скриено|архивирано|неактивно",
  bs: "Kategorije sadržaja|Upravljajte kategorijama za stranice i blog objave. Samo za administratore.|Kategorije stranica|Kategorije blog objava|Webshop kategorije|Blog objava|stranica|blog objava|Pretraži po nazivu...|Svi autori|Kategorije: {type}|Naziv|Stavke|Autor|Ažurirano|Akcije|Izaberi sve|Izaberi {name}|od {name}|Nijedna {type} kategorija ne odgovara pretrazi.|Još nema {type} kategorija.|Dodaj kategoriju|Dodaj kategoriju: {type}|Unesite naziv za novu {type} kategoriju.|Uredi kategoriju: {type}|Ažurirajte naziv ili dodijelite drugog autora ovoj kategoriji.|Obrisati kategoriju?|Ovo će trajno obrisati kategoriju {name}. Ova radnja se ne može poništiti.|Obriši izabrano ({count})|Obrisati izabrane kategorije?|Ovo će trajno obrisati {count} izabranu kategoriju. Ova radnja se ne može poništiti.|Ovo će trajno obrisati {count} izabranih kategorija. Ova radnja se ne može poništiti.|Naziv kategorije|npr. Vijesti|Izaberite korisnika...|Naziv je obavezan.|Naziv mora imati 100 znakova ili manje.|Autor je obavezan.|Vlasnik je obavezan.|Neispravan ID kategorije.|Kategorija s tim nazivom već postoji za ovaj tip sadržaja.|Ciljni korisnik mora biti backend korisnik.|Ova kategorija je dodijeljena stavkama sadržaja i ne može se obrisati.|Jedna ili više izabranih kategorija dodijeljene su stavkama sadržaja i ne mogu se obrisati.|Nešto je pošlo po zlu. Pokušajte ponovo.|Samo za čitanje|Samo uređivanje postojećeg|Upravljanje se odvija u Webshop kontrolnoj tabli. Ovi redovi vode do editora kategorija plaćenog dodatka.|Upravljaj u Webshopu|Još nema Webshop kategorija.|URL oznaka|Status|Proizvodi|Otvori|Otvori {name}|aktivno|nacrt|skriveno|arhivirano|neaktivno",
  sl: "Kategorije vsebine|Upravljajte kategorije za strani in blog objave. Dostop samo za skrbnike.|Kategorije strani|Kategorije blog objav|Webshop kategorije|Blog objava|stran|blog objava|Išči po imenu...|Vsi avtorji|Kategorije: {type}|Ime|Elementi|Avtor|Posodobljeno|Dejanja|Izberi vse|Izberi {name}|od {name}|Nobena kategorija {type} se ne ujema z iskanjem.|Kategorij {type} še ni.|Dodaj kategorijo|Dodaj kategorijo: {type}|Vnesite ime za novo kategorijo {type}.|Uredi kategorijo: {type}|Posodobite ime ali znova dodelite avtorja te kategorije.|Izbrisati kategorijo?|To bo trajno izbrisalo kategorijo {name}. Tega dejanja ni mogoče razveljaviti.|Izbriši izbrano ({count})|Izbrisati izbrane kategorije?|To bo trajno izbrisalo {count} izbrano kategorijo. Tega dejanja ni mogoče razveljaviti.|To bo trajno izbrisalo {count} izbranih kategorij. Tega dejanja ni mogoče razveljaviti.|Ime kategorije|npr. Novice|Izberite uporabnika...|Ime je obvezno.|Ime mora imeti največ 100 znakov.|Avtor je obvezen.|Lastnik je obvezen.|Neveljaven ID kategorije.|Kategorija s tem imenom že obstaja za to vrsto vsebine.|Ciljni uporabnik mora biti backend uporabnik.|Ta kategorija je dodeljena elementom vsebine in je ni mogoče izbrisati.|Ena ali več izbranih kategorij je dodeljenih elementom vsebine in jih ni mogoče izbrisati.|Nekaj je šlo narobe. Poskusite znova.|Samo za branje|Samo urejanje obstoječih|Upravljanje poteka v nadzorni plošči Webshop. Te vrstice vodijo do urejevalnika kategorij plačljivega dodatka.|Upravljaj v Webshopu|Webshop kategorij še ni.|URL oznaka|Stanje|Izdelki|Odpri|Odpri {name}|aktivno|osnutek|skrito|arhivirano|neaktivno",
  ru: "Категории контента|Управляйте категориями страниц и записей блога. Доступ только для администраторов.|Категории страниц|Категории записей блога|Категории Webshop|Запись блога|страница|запись блога|Поиск по названию...|Все авторы|Категории: {type}|Название|Элементы|Автор|Обновлено|Действия|Выбрать все|Выбрать {name}|от {name}|Нет категорий {type}, соответствующих поиску.|Категорий {type} пока нет.|Добавить категорию|Добавить категорию: {type}|Введите название новой категории {type}.|Изменить категорию: {type}|Обновите название или переназначьте автора этой категории.|Удалить категорию?|Категория {name} будет удалена навсегда. Это действие нельзя отменить.|Удалить выбранные ({count})|Удалить выбранные категории?|Будет навсегда удалена {count} выбранная категория. Это действие нельзя отменить.|Будет навсегда удалено {count} выбранных категорий. Это действие нельзя отменить.|Название категории|например Новости|Выберите пользователя...|Название обязательно.|Название должно содержать не более 100 символов.|Автор обязателен.|Владелец обязателен.|Недопустимый ID категории.|Категория с таким названием уже существует для этого типа контента.|Целевой пользователь должен быть backend-пользователем.|Эта категория назначена элементам контента и не может быть удалена.|Одна или несколько выбранных категорий назначены элементам контента и не могут быть удалены.|Что-то пошло не так. Попробуйте еще раз.|Только чтение|Только редактирование существующих|Управление выполняется в панели Webshop. Эти строки ведут в редактор категорий платного дополнения.|Управлять в Webshop|Категорий Webshop пока нет.|URL-метка|Статус|Товары|Открыть|Открыть {name}|активно|черновик|скрыто|архивировано|неактивно",
  hu: "Tartalomkategóriák|Kezelje az oldalak és blogbejegyzések kategóriáit. Csak adminisztrátori hozzáférés.|Oldalkategóriák|Blogbejegyzés-kategóriák|Webshop kategóriák|Blogbejegyzés|oldal|blogbejegyzés|Keresés név szerint...|Összes szerző|{type} kategóriák|Név|Elemek|Szerző|Frissítve|Műveletek|Összes kijelölése|{name} kijelölése|{name} által|Nincs a keresésnek megfelelő {type} kategória.|Még nincs {type} kategória.|Kategória hozzáadása|{type} kategória hozzáadása|Adjon meg nevet az új {type} kategóriának.|{type} kategória szerkesztése|Frissítse a nevet vagy rendelje újra a kategória szerzőjét.|Törli a kategóriát?|Ez végleg törli a(z) {name} kategóriát. Ez a művelet nem vonható vissza.|Kijelöltek törlése ({count})|Törli a kijelölt kategóriákat?|Ez végleg töröl {count} kijelölt kategóriát. Ez a művelet nem vonható vissza.|Ez végleg töröl {count} kijelölt kategóriát. Ez a művelet nem vonható vissza.|Kategória neve|pl. Hírek|Válasszon felhasználót...|A név kötelező.|A név legfeljebb 100 karakter lehet.|A szerző kötelező.|A tulajdonos kötelező.|Érvénytelen kategóriaazonosító.|Már létezik ilyen nevű kategória ehhez a tartalomtípushoz.|A célfelhasználónak backend felhasználónak kell lennie.|Ez a kategória tartalmi elemekhez van rendelve, ezért nem törölhető.|Egy vagy több kijelölt kategória tartalmi elemekhez van rendelve, ezért nem törölhető.|Valami hiba történt. Próbálja újra.|Csak olvasható|Csak meglévők szerkesztése|A kezelés a Webshop vezérlőpultján történik. Ezek a sorok a fizetős bővítmény kategóriaszerkesztőjéhez vezetnek.|Kezelés a Webshopban|Még nincs Webshop kategória.|URL-azonosító|Állapot|Termékek|Megnyitás|{name} megnyitása|aktív|vázlat|rejtett|archivált|inaktív",
  bg: "Категории съдържание|Управлявайте категории за страници и блог публикации. Достъп само за администратори.|Категории страници|Категории блог публикации|Webshop категории|Блог публикация|страница|блог публикация|Търсене по име...|Всички автори|Категории: {type}|Име|Елементи|Автор|Актуализирано|Действия|Избери всички|Избери {name}|от {name}|Няма {type} категории, които съвпадат с търсенето.|Все още няма {type} категории.|Добави категория|Добави категория: {type}|Въведете име за новата {type} категория.|Редактирай категория: {type}|Актуализирайте името или преназначете автора на тази категория.|Да се изтрие ли категорията?|Това ще изтрие завинаги категорията {name}. Това действие не може да бъде отменено.|Изтрий избраните ({count})|Да се изтрият ли избраните категории?|Това ще изтрие завинаги {count} избрана категория. Това действие не може да бъде отменено.|Това ще изтрие завинаги {count} избрани категории. Това действие не може да бъде отменено.|Име на категория|напр. Новини|Изберете потребител...|Името е задължително.|Името трябва да е 100 знака или по-малко.|Авторът е задължителен.|Собственикът е задължителен.|Невалиден ID на категория.|Категория с това име вече съществува за този тип съдържание.|Целевият потребител трябва да бъде backend потребител.|Тази категория е зададена на елементи съдържание и не може да бъде изтрита.|Една или повече избрани категории са зададени на елементи съдържание и не могат да бъдат изтрити.|Нещо се обърка. Опитайте отново.|Само за четене|Само редактиране на съществуващи|Управлението се извършва в таблото на Webshop. Тези редове водят към редактора на категории на платената добавка.|Управлявай в Webshop|Все още няма Webshop категории.|URL означение|Статус|Продукти|Отвори|Отвори {name}|активно|чернова|скрито|архивирано|неактивно",
  ja: "コンテンツカテゴリ|ページとブログ投稿のカテゴリを管理します。管理者のみアクセスできます。|ページカテゴリ|ブログ投稿カテゴリ|Webshopカテゴリ|ブログ投稿|ページ|ブログ投稿|名前で検索...|すべての作成者|{type}カテゴリ|名前|項目|作成者|更新日時|操作|すべて選択|{name}を選択|{name}による更新|検索に一致する{type}カテゴリはありません。|{type}カテゴリはまだありません。|カテゴリを追加|{type}カテゴリを追加|新しい{type}カテゴリの名前を入力してください。|{type}カテゴリを編集|このカテゴリの名前を更新するか作成者を再割り当てします。|カテゴリを削除しますか？|カテゴリ{name}を完全に削除します。この操作は元に戻せません。|選択項目を削除（{count}）|選択したカテゴリを削除しますか？|選択したカテゴリ{count}件を完全に削除します。この操作は元に戻せません。|選択したカテゴリ{count}件を完全に削除します。この操作は元に戻せません。|カテゴリ名|例：ニュース|ユーザーを選択...|名前は必須です。|名前は100文字以下にしてください。|作成者は必須です。|所有者は必須です。|カテゴリIDが無効です。|このコンテンツタイプには同じ名前のカテゴリが既に存在します。|対象ユーザーはバックエンドユーザーである必要があります。|このカテゴリはコンテンツ項目に割り当てられているため削除できません。|選択したカテゴリの一部またはすべてがコンテンツ項目に割り当てられているため削除できません。|問題が発生しました。もう一度お試しください。|読み取り専用|既存のみ編集|管理はWebshopダッシュボードで行います。これらの行は有料アドオンのカテゴリ編集画面にリンクしています。|Webshopで管理|Webshopカテゴリはまだありません。|URL識別子|ステータス|商品|開く|{name}を開く|有効|下書き|非表示|アーカイブ済み|無効",
  "zh-Hans":
    "内容分类|管理页面和博客文章的分类。仅管理员可访问。|页面分类|博客文章分类|Webshop 分类|博客文章|页面|博客文章|按名称搜索...|所有作者|{type} 分类|名称|项目|作者|已更新|操作|全选|选择 {name}|由 {name}|没有与搜索匹配的 {type} 分类。|还没有 {type} 分类。|添加分类|添加 {type} 分类|输入新 {type} 分类的名称。|编辑 {type} 分类|更新名称或重新分配此分类的作者。|删除分类？|这将永久删除分类 {name}。此操作无法撤销。|删除已选（{count}）|删除已选分类？|这将永久删除 {count} 个已选分类。此操作无法撤销。|这将永久删除 {count} 个已选分类。此操作无法撤销。|分类名称|例如 新闻|选择用户...|名称为必填项。|名称必须为 100 个字符或更少。|作者为必填项。|所有者为必填项。|无效的分类 ID。|此内容类型已存在同名分类。|目标用户必须是后台用户。|此分类已分配给内容项目，无法删除。|一个或多个已选分类已分配给内容项目，无法删除。|出了点问题。请重试。|只读|仅编辑现有项|管理在 Webshop 仪表板中进行。这些行链接到付费附加组件的分类编辑器。|在 Webshop 中管理|还没有 Webshop 分类。|URL 标识|状态|产品|打开|打开 {name}|启用|草稿|隐藏|已归档|未启用",
  "zh-Hant":
    "內容分類|管理頁面和部落格文章的分類。僅限管理員存取。|頁面分類|部落格文章分類|Webshop 分類|部落格文章|頁面|部落格文章|依名稱搜尋...|所有作者|{type} 分類|名稱|項目|作者|已更新|操作|全選|選取 {name}|由 {name}|沒有符合搜尋的 {type} 分類。|尚無 {type} 分類。|新增分類|新增 {type} 分類|輸入新 {type} 分類的名稱。|編輯 {type} 分類|更新名稱或重新指派此分類的作者。|刪除分類？|這會永久刪除分類 {name}。此動作無法復原。|刪除所選（{count}）|刪除所選分類？|這會永久刪除 {count} 個所選分類。此動作無法復原。|這會永久刪除 {count} 個所選分類。此動作無法復原。|分類名稱|例如 新聞|選取使用者...|名稱為必填。|名稱必須為 100 個字元或更少。|作者為必填。|擁有者為必填。|無效的分類 ID。|此內容類型已存在同名分類。|目標使用者必須是後台使用者。|此分類已指派給內容項目，無法刪除。|一個或多個所選分類已指派給內容項目，無法刪除。|發生錯誤。請再試一次。|唯讀|僅編輯現有項目|管理會在 Webshop 儀表板中進行。這些列會連到付費附加元件的分類編輯器。|在 Webshop 管理|尚無 Webshop 分類。|URL 識別碼|狀態|產品|開啟|開啟 {name}|啟用|草稿|隱藏|已封存|未啟用",
  ar: "فئات المحتوى|إدارة فئات الصفحات ومقالات المدونة. وصول المسؤولين فقط.|فئات الصفحات|فئات مقالات المدونة|فئات Webshop|مقال مدونة|صفحة|مقال مدونة|البحث بالاسم...|كل المؤلفين|فئات {type}|الاسم|العناصر|المؤلف|تم التحديث|الإجراءات|تحديد الكل|تحديد {name}|بواسطة {name}|لا توجد فئات {type} تطابق بحثك.|لا توجد فئات {type} بعد.|إضافة فئة|إضافة فئة {type}|أدخل اسمًا للفئة {type} الجديدة.|تعديل فئة {type}|حدّث الاسم أو أعد تعيين مؤلف هذه الفئة.|حذف الفئة؟|سيؤدي هذا إلى حذف الفئة {name} نهائيًا. لا يمكن التراجع عن هذا الإجراء.|حذف المحدد ({count})|حذف الفئات المحددة؟|سيؤدي هذا إلى حذف {count} فئة محددة نهائيًا. لا يمكن التراجع عن هذا الإجراء.|سيؤدي هذا إلى حذف {count} فئات محددة نهائيًا. لا يمكن التراجع عن هذا الإجراء.|اسم الفئة|مثال: الأخبار|اختر مستخدمًا...|الاسم مطلوب.|يجب أن يكون الاسم 100 حرف أو أقل.|المؤلف مطلوب.|المالك مطلوب.|معرّف الفئة غير صالح.|توجد فئة بهذا الاسم بالفعل لهذا النوع من المحتوى.|يجب أن يكون المستخدم الهدف مستخدمًا في الواجهة الخلفية.|هذه الفئة مخصصة لعناصر محتوى ولا يمكن حذفها.|فئة واحدة أو أكثر من الفئات المحددة مخصصة لعناصر محتوى ولا يمكن حذفها.|حدث خطأ ما. يرجى المحاولة مرة أخرى.|للقراءة فقط|تعديل الموجود فقط|تتم الإدارة في لوحة Webshop. ترتبط هذه الصفوف بمحرر فئات الإضافة المدفوعة.|الإدارة في Webshop|لا توجد فئات Webshop بعد.|معرّف URL|الحالة|المنتجات|فتح|فتح {name}|نشط|مسودة|مخفي|مؤرشف|غير نشط",
  id: "Kategori konten|Kelola kategori untuk halaman dan posting blog. Hanya akses admin.|Kategori halaman|Kategori posting blog|Kategori Webshop|Posting blog|halaman|posting blog|Cari berdasarkan nama...|Semua penulis|Kategori {type}|Nama|Item|Penulis|Diperbarui|Tindakan|Pilih semua|Pilih {name}|oleh {name}|Tidak ada kategori {type} yang cocok dengan pencarian Anda.|Belum ada kategori {type}.|Tambah kategori|Tambah kategori {type}|Masukkan nama untuk kategori {type} baru.|Edit kategori {type}|Perbarui nama atau tetapkan ulang penulis kategori ini.|Hapus kategori?|Ini akan menghapus kategori {name} secara permanen. Tindakan ini tidak dapat dibatalkan.|Hapus yang dipilih ({count})|Hapus kategori yang dipilih?|Ini akan menghapus {count} kategori terpilih secara permanen. Tindakan ini tidak dapat dibatalkan.|Ini akan menghapus {count} kategori terpilih secara permanen. Tindakan ini tidak dapat dibatalkan.|Nama kategori|mis. Berita|Pilih pengguna...|Nama wajib diisi.|Nama harus 100 karakter atau kurang.|Penulis wajib diisi.|Pemilik wajib diisi.|ID kategori tidak valid.|Kategori dengan nama tersebut sudah ada untuk jenis konten ini.|Pengguna tujuan harus merupakan pengguna backend.|Kategori ini ditetapkan ke item konten dan tidak dapat dihapus.|Satu atau lebih kategori yang dipilih ditetapkan ke item konten dan tidak dapat dihapus.|Terjadi kesalahan. Silakan coba lagi.|Hanya baca|Hanya edit yang ada|Pengelolaan dilakukan di dasbor Webshop. Baris ini menaut ke editor kategori add-on berbayar.|Kelola di Webshop|Belum ada kategori Webshop.|Penanda URL|Status|Produk|Buka|Buka {name}|aktif|draf|tersembunyi|diarsipkan|nonaktif",
  cs: "Kategorie obsahu|Spravujte kategorie pro stránky a blogové příspěvky. Přístup pouze pro administrátory.|Kategorie stránek|Kategorie blogových příspěvků|Kategorie Webshopu|Blogový příspěvek|stránka|blogový příspěvek|Hledat podle názvu...|Všichni autoři|Kategorie: {type}|Název|Položky|Autor|Aktualizováno|Akce|Vybrat vše|Vybrat {name}|od {name}|Žádná kategorie {type} neodpovídá hledání.|Zatím nejsou žádné kategorie {type}.|Přidat kategorii|Přidat kategorii: {type}|Zadejte název nové kategorie {type}.|Upravit kategorii: {type}|Aktualizujte název nebo znovu přiřaďte autora této kategorie.|Smazat kategorii?|Tím trvale smažete kategorii {name}. Tuto akci nelze vrátit zpět.|Smazat vybrané ({count})|Smazat vybrané kategorie?|Tím trvale smažete {count} vybranou kategorii. Tuto akci nelze vrátit zpět.|Tím trvale smažete {count} vybraných kategorií. Tuto akci nelze vrátit zpět.|Název kategorie|např. Novinky|Vyberte uživatele...|Název je povinný.|Název musí mít 100 znaků nebo méně.|Autor je povinný.|Vlastník je povinný.|Neplatné ID kategorie.|Kategorie s tímto názvem již pro tento typ obsahu existuje.|Cílový uživatel musí být backendový uživatel.|Tato kategorie je přiřazena k položkám obsahu a nelze ji smazat.|Jedna nebo více vybraných kategorií je přiřazena k položkám obsahu a nelze je smazat.|Něco se pokazilo. Zkuste to prosím znovu.|Pouze pro čtení|Pouze úprava existujících|Správa probíhá v ovládacím panelu Webshopu. Tyto řádky odkazují na editor kategorií placeného doplňku.|Spravovat ve Webshopu|Zatím nejsou žádné kategorie Webshopu.|URL označení|Stav|Produkty|Otevřít|Otevřít {name}|aktivní|koncept|skryté|archivováno|neaktivní",
  ro: "Categorii de conținut|Gestionează categoriile pentru pagini și articole de blog. Acces doar pentru administratori.|Categorii de pagini|Categorii de articole de blog|Categorii Webshop|Articol de blog|pagină|articol de blog|Caută după nume...|Toți autorii|Categorii {type}|Nume|Elemente|Autor|Actualizat|Acțiuni|Selectează tot|Selectează {name}|de {name}|Nicio categorie {type} nu corespunde căutării.|Nu există încă categorii {type}.|Adaugă categorie|Adaugă categorie {type}|Introdu un nume pentru noua categorie {type}.|Editează categoria {type}|Actualizează numele sau reatribuie autorul acestei categorii.|Ștergi categoria?|Aceasta va șterge definitiv categoria {name}. Acțiunea nu poate fi anulată.|Șterge selectate ({count})|Ștergi categoriile selectate?|Aceasta va șterge definitiv {count} categorie selectată. Acțiunea nu poate fi anulată.|Aceasta va șterge definitiv {count} categorii selectate. Acțiunea nu poate fi anulată.|Numele categoriei|ex. Știri|Selectează un utilizator...|Numele este obligatoriu.|Numele trebuie să aibă cel mult 100 de caractere.|Autorul este obligatoriu.|Proprietarul este obligatoriu.|ID de categorie nevalid.|Există deja o categorie cu acest nume pentru acest tip de conținut.|Utilizatorul țintă trebuie să fie utilizator backend.|Această categorie este atribuită unor elemente de conținut și nu poate fi ștearsă.|Una sau mai multe categorii selectate sunt atribuite unor elemente de conținut și nu pot fi șterse.|Ceva nu a mers bine. Încearcă din nou.|Doar citire|Doar editare existente|Gestionarea se face în panoul Webshop. Aceste rânduri duc la editorul de categorii al add-on-ului plătit.|Gestionează în Webshop|Nu există încă categorii Webshop.|Identificator URL|Stare|Produse|Deschide|Deschide {name}|activ|ciornă|ascuns|arhivat|inactiv",
  el: "Κατηγορίες περιεχομένου|Διαχειριστείτε κατηγορίες για σελίδες και αναρτήσεις ιστολογίου. Πρόσβαση μόνο για διαχειριστές.|Κατηγορίες σελίδων|Κατηγορίες αναρτήσεων ιστολογίου|Κατηγορίες Webshop|Ανάρτηση ιστολογίου|σελίδα|ανάρτηση ιστολογίου|Αναζήτηση με όνομα...|Όλοι οι συντάκτες|Κατηγορίες {type}|Όνομα|Στοιχεία|Συντάκτης|Ενημερώθηκε|Ενέργειες|Επιλογή όλων|Επιλογή {name}|από {name}|Καμία κατηγορία {type} δεν ταιριάζει με την αναζήτησή σας.|Δεν υπάρχουν ακόμη κατηγορίες {type}.|Προσθήκη κατηγορίας|Προσθήκη κατηγορίας {type}|Εισαγάγετε όνομα για τη νέα κατηγορία {type}.|Επεξεργασία κατηγορίας {type}|Ενημερώστε το όνομα ή αναθέστε ξανά τον συντάκτη αυτής της κατηγορίας.|Να διαγραφεί η κατηγορία;|Αυτό θα διαγράψει οριστικά την κατηγορία {name}. Η ενέργεια δεν μπορεί να αναιρεθεί.|Διαγραφή επιλεγμένων ({count})|Να διαγραφούν οι επιλεγμένες κατηγορίες;|Αυτό θα διαγράψει οριστικά {count} επιλεγμένη κατηγορία. Η ενέργεια δεν μπορεί να αναιρεθεί.|Αυτό θα διαγράψει οριστικά {count} επιλεγμένες κατηγορίες. Η ενέργεια δεν μπορεί να αναιρεθεί.|Όνομα κατηγορίας|π.χ. Νέα|Επιλέξτε χρήστη...|Το όνομα είναι υποχρεωτικό.|Το όνομα πρέπει να έχει 100 χαρακτήρες ή λιγότερους.|Ο συντάκτης είναι υποχρεωτικός.|Ο κάτοχος είναι υποχρεωτικός.|Μη έγκυρο ID κατηγορίας.|Υπάρχει ήδη κατηγορία με αυτό το όνομα για αυτόν τον τύπο περιεχομένου.|Ο χρήστης προορισμού πρέπει να είναι χρήστης backend.|Αυτή η κατηγορία έχει ανατεθεί σε στοιχεία περιεχομένου και δεν μπορεί να διαγραφεί.|Μία ή περισσότερες επιλεγμένες κατηγορίες έχουν ανατεθεί σε στοιχεία περιεχομένου και δεν μπορούν να διαγραφούν.|Κάτι πήγε στραβά. Δοκιμάστε ξανά.|Μόνο για ανάγνωση|Επεξεργασία μόνο υπαρχόντων|Η διαχείριση γίνεται στον πίνακα Webshop. Αυτές οι γραμμές οδηγούν στον επεξεργαστή κατηγοριών του επί πληρωμή πρόσθετου.|Διαχείριση στο Webshop|Δεν υπάρχουν ακόμη κατηγορίες Webshop.|Αναγνωριστικό URL|Κατάσταση|Προϊόντα|Άνοιγμα|Άνοιγμα {name}|ενεργό|πρόχειρο|κρυφό|αρχειοθετημένο|ανενεργό",
  da: "Indholdskategorier|Administrer kategorier for sider og blogindlæg. Kun administratoradgang.|Sidekategorier|Blogindlægskategorier|Webshop-kategorier|Blogindlæg|side|blogindlæg|Søg efter navn...|Alle forfattere|{type}-kategorier|Navn|Elementer|Forfatter|Opdateret|Handlinger|Vælg alle|Vælg {name}|af {name}|Ingen {type}-kategorier matcher din søgning.|Der er endnu ingen {type}-kategorier.|Tilføj kategori|Tilføj {type}-kategori|Indtast et navn til den nye {type}-kategori.|Rediger {type}-kategori|Opdater navnet eller tildel kategorien en anden forfatter.|Slet kategori?|Dette sletter kategorien {name} permanent. Handlingen kan ikke fortrydes.|Slet valgte ({count})|Slet valgte kategorier?|Dette sletter {count} valgt kategori permanent. Handlingen kan ikke fortrydes.|Dette sletter {count} valgte kategorier permanent. Handlingen kan ikke fortrydes.|Kategorinavn|f.eks. Nyheder|Vælg en bruger...|Navn er påkrævet.|Navnet skal være 100 tegn eller færre.|Forfatter er påkrævet.|Ejer er påkrævet.|Ugyldigt kategori-ID.|Der findes allerede en kategori med det navn for denne indholdstype.|Målbrugeren skal være en backend-bruger.|Denne kategori er tildelt indholdselementer og kan ikke slettes.|En eller flere valgte kategorier er tildelt indholdselementer og kan ikke slettes.|Noget gik galt. Prøv igen.|Skrivebeskyttet|Rediger kun eksisterende|Administration foregår i Webshop-dashboardet. Disse rækker linker til kategori-editoren i det betalte add-on.|Administrer i Webshop|Der er endnu ingen Webshop-kategorier.|URL-id|Status|Produkter|Åbn|Åbn {name}|aktiv|kladde|skjult|arkiveret|inaktiv",
  sv: "Innehållskategorier|Hantera kategorier för sidor och blogginlägg. Endast administratörer.|Sidkategorier|Blogginläggskategorier|Webshop-kategorier|Blogginlägg|sida|blogginlägg|Sök efter namn...|Alla författare|{type}-kategorier|Namn|Objekt|Författare|Uppdaterad|Åtgärder|Markera alla|Markera {name}|av {name}|Inga {type}-kategorier matchar din sökning.|Det finns inga {type}-kategorier än.|Lägg till kategori|Lägg till {type}-kategori|Ange ett namn för den nya {type}-kategorin.|Redigera {type}-kategori|Uppdatera namnet eller tilldela kategorin en annan författare.|Ta bort kategori?|Detta tar bort kategorin {name} permanent. Åtgärden kan inte ångras.|Ta bort markerade ({count})|Ta bort markerade kategorier?|Detta tar bort {count} markerad kategori permanent. Åtgärden kan inte ångras.|Detta tar bort {count} markerade kategorier permanent. Åtgärden kan inte ångras.|Kategorinamn|t.ex. Nyheter|Välj en användare...|Namn krävs.|Namnet får vara högst 100 tecken.|Författare krävs.|Ägare krävs.|Ogiltigt kategori-ID.|Det finns redan en kategori med det namnet för den här innehållstypen.|Målanvändaren måste vara en backend-användare.|Den här kategorin är tilldelad innehållsobjekt och kan inte tas bort.|En eller flera markerade kategorier är tilldelade innehållsobjekt och kan inte tas bort.|Något gick fel. Försök igen.|Skrivskyddad|Redigera endast befintliga|Hanteringen sker i Webshop-panelen. Dessa rader länkar till kategori-redigeraren i det betalda tillägget.|Hantera i Webshop|Det finns inga Webshop-kategorier än.|URL-id|Status|Produkter|Öppna|Öppna {name}|aktiv|utkast|dold|arkiverad|inaktiv",
  nb: "Innholdskategorier|Administrer kategorier for sider og blogginnlegg. Kun administratorer.|Sidekategorier|Blogginnleggskategorier|Webshop-kategorier|Blogginnlegg|side|blogginnlegg|Søk etter navn...|Alle forfattere|{type}-kategorier|Navn|Elementer|Forfatter|Oppdatert|Handlinger|Velg alle|Velg {name}|av {name}|Ingen {type}-kategorier samsvarer med søket ditt.|Det finnes ingen {type}-kategorier ennå.|Legg til kategori|Legg til {type}-kategori|Skriv inn et navn for den nye {type}-kategorien.|Rediger {type}-kategori|Oppdater navnet eller tildel kategorien en annen forfatter.|Slette kategori?|Dette sletter kategorien {name} permanent. Handlingen kan ikke angres.|Slett valgte ({count})|Slette valgte kategorier?|Dette sletter {count} valgt kategori permanent. Handlingen kan ikke angres.|Dette sletter {count} valgte kategorier permanent. Handlingen kan ikke angres.|Kategorinavn|f.eks. Nyheter|Velg en bruker...|Navn er påkrevd.|Navnet må være 100 tegn eller færre.|Forfatter er påkrevd.|Eier er påkrevd.|Ugyldig kategori-ID.|Det finnes allerede en kategori med dette navnet for denne innholdstypen.|Målbrukeren må være en backend-bruker.|Denne kategorien er tilordnet innholdselementer og kan ikke slettes.|En eller flere valgte kategorier er tilordnet innholdselementer og kan ikke slettes.|Noe gikk galt. Prøv igjen.|Skrivebeskyttet|Rediger bare eksisterende|Administrasjonen skjer i Webshop-panelet. Disse radene lenker til kategori-editoren i det betalte tillegget.|Administrer i Webshop|Det finnes ingen Webshop-kategorier ennå.|URL-id|Status|Produkter|Åpne|Åpne {name}|aktiv|utkast|skjult|arkivert|inaktiv",
  nn: "Innhaldskategoriar|Administrer kategoriar for sider og blogginnlegg. Berre administratorar.|Sidekategoriar|Blogginnleggskategoriar|Webshop-kategoriar|Blogginnlegg|side|blogginnlegg|Søk etter namn...|Alle forfattarar|{type}-kategoriar|Namn|Element|Forfattar|Oppdatert|Handlingar|Vel alle|Vel {name}|av {name}|Ingen {type}-kategoriar samsvarar med søket ditt.|Det finst ingen {type}-kategoriar enno.|Legg til kategori|Legg til {type}-kategori|Skriv inn eit namn for den nye {type}-kategorien.|Rediger {type}-kategori|Oppdater namnet eller tildel kategorien ein annan forfattar.|Slette kategori?|Dette slettar kategorien {name} permanent. Handlinga kan ikkje angrast.|Slett valde ({count})|Slette valde kategoriar?|Dette slettar {count} vald kategori permanent. Handlinga kan ikkje angrast.|Dette slettar {count} valde kategoriar permanent. Handlinga kan ikkje angrast.|Kategorinamn|t.d. Nyhende|Vel ein brukar...|Namn er påkravd.|Namnet må vere 100 teikn eller færre.|Forfattar er påkravd.|Eigar er påkravd.|Ugyldig kategori-ID.|Det finst allereie ein kategori med dette namnet for denne innhaldstypen.|Målbrukaren må vere ein backend-brukar.|Denne kategorien er tilordna innhaldselement og kan ikkje slettast.|Ein eller fleire valde kategoriar er tilordna innhaldselement og kan ikkje slettast.|Noko gjekk gale. Prøv igjen.|Skriveverna|Rediger berre eksisterande|Administrasjonen skjer i Webshop-panelet. Desse radene lenkjer til kategori-editoren i det betalte tillegget.|Administrer i Webshop|Det finst ingen Webshop-kategoriar enno.|URL-id|Status|Produkt|Opne|Opne {name}|aktiv|utkast|skjult|arkivert|inaktiv",
  fi: "Sisältökategoriat|Hallitse sivujen ja blogikirjoitusten kategorioita. Vain ylläpitäjille.|Sivukategoriat|Blogikirjoitusten kategoriat|Webshop-kategoriat|Blogikirjoitus|sivu|blogikirjoitus|Hae nimellä...|Kaikki tekijät|{type}-kategoriat|Nimi|Kohteet|Tekijä|Päivitetty|Toiminnot|Valitse kaikki|Valitse {name}|tekijä {name}|Hakua vastaavia {type}-kategorioita ei ole.|{type}-kategorioita ei ole vielä.|Lisää kategoria|Lisää {type}-kategoria|Anna nimi uudelle {type}-kategorialle.|Muokkaa {type}-kategoriaa|Päivitä nimi tai määritä tämän kategorian tekijä uudelleen.|Poistetaanko kategoria?|Tämä poistaa kategorian {name} pysyvästi. Toimintoa ei voi kumota.|Poista valitut ({count})|Poistetaanko valitut kategoriat?|Tämä poistaa {count} valitun kategorian pysyvästi. Toimintoa ei voi kumota.|Tämä poistaa {count} valittua kategoriaa pysyvästi. Toimintoa ei voi kumota.|Kategorian nimi|esim. Uutiset|Valitse käyttäjä...|Nimi on pakollinen.|Nimen on oltava enintään 100 merkkiä.|Tekijä on pakollinen.|Omistaja on pakollinen.|Virheellinen kategoria-ID.|Tällä sisältötyypillä on jo samanniminen kategoria.|Kohdekäyttäjän on oltava backend-käyttäjä.|Tämä kategoria on liitetty sisältökohteisiin eikä sitä voi poistaa.|Yksi tai useampi valittu kategoria on liitetty sisältökohteisiin eikä sitä voi poistaa.|Jokin meni pieleen. Yritä uudelleen.|Vain luku|Muokkaa vain olemassa olevia|Hallinta tapahtuu Webshop-hallintapaneelissa. Nämä rivit linkittävät maksullisen lisäosan kategoriaeditoriin.|Hallitse Webshopissa|Webshop-kategorioita ei ole vielä.|URL-tunniste|Tila|Tuotteet|Avaa|Avaa {name}|aktiivinen|luonnos|piilotettu|arkistoitu|passiivinen",
  is: "Efnisflokkar|Stjórnaðu flokkum fyrir síður og bloggfærslur. Aðeins stjórnendur.|Síðuflokkar|Bloggfærsluflokkar|Webshop-flokkar|Bloggfærsla|síða|bloggfærsla|Leita eftir nafni...|Allir höfundar|{type}-flokkar|Nafn|Atriði|Höfundur|Uppfært|Aðgerðir|Velja allt|Velja {name}|eftir {name}|Engir {type}-flokkar passa við leitina.|Engir {type}-flokkar enn.|Bæta við flokki|Bæta við {type}-flokki|Sláðu inn nafn fyrir nýja {type}-flokkinn.|Breyta {type}-flokki|Uppfærðu nafnið eða úthlutaðu höfundi þessa flokks upp á nýtt.|Eyða flokki?|Þetta eyðir flokknum {name} varanlega. Ekki er hægt að afturkalla aðgerðina.|Eyða völdum ({count})|Eyða völdum flokkum?|Þetta eyðir {count} völdum flokki varanlega. Ekki er hægt að afturkalla aðgerðina.|Þetta eyðir {count} völdum flokkum varanlega. Ekki er hægt að afturkalla aðgerðina.|Nafn flokks|t.d. Fréttir|Veldu notanda...|Nafn er nauðsynlegt.|Nafnið verður að vera 100 stafir eða færri.|Höfundur er nauðsynlegur.|Eigandi er nauðsynlegur.|Ógilt flokks-ID.|Flokkur með þessu nafni er þegar til fyrir þessa efnisgerð.|Marknotandinn verður að vera backend-notandi.|Þessi flokkur er tengdur efnisatriðum og ekki er hægt að eyða honum.|Einn eða fleiri valdir flokkar eru tengdir efnisatriðum og ekki er hægt að eyða þeim.|Eitthvað fór úrskeiðis. Reyndu aftur.|Skrifvarið|Breyta aðeins núverandi|Stjórnun fer fram í Webshop-stjórnborðinu. Þessar línur tengja við flokkaritil greidda viðbótarinnar.|Stjórna í Webshop|Engir Webshop-flokkar enn.|URL-auðkenni|Staða|Vörur|Opna|Opna {name}|virkt|drög|falið|sett í safn|óvirkt",
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<ContentCategoriesSource, string> {
  const translations = row.split("|");
  if (translations.length !== CONTENT_CATEGORIES_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} content categories translations must have ${CONTENT_CATEGORIES_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    CONTENT_CATEGORIES_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<ContentCategoriesSource, string>;
}

export const CONTENT_CATEGORIES_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<ContentCategoriesSource, string>>;
