import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const FILE_MANAGER_SOURCE_STRINGS = [
  "File Manager",
  "Upload and manage images, videos, and documents.",
  "Files",
  "File manager folders",
  "Search filenames, titles, or alt text...",
  "No files found in {folder}.",
  "{count} selected",
  "Upload",
  "Date range",
  "Showing {count} of {total} files",
  "{count} folder",
  "{count} folders",
  "Edit file",
  "Rename",
  "Move files",
  "Image",
  "Images",
  "Video",
  "Document",
  "Documents",
  "Other",
  "New folder",
  "Create a folder in the current location.",
  "Folder name",
  "Rename folder",
  "Update this folder's name.",
  "Delete folder",
  "Delete folder?",
  "You can only delete an empty folder. The physical files are not changed.",
  "Folder",
  "Folder: {name}",
  "Update the file's display metadata. The physical file is not changed.",
  "Filename",
  "Title",
  "Alt text",
  "Delete file?",
  "Delete {count} files?",
  "this file",
  "{count} files",
  "You are about to permanently delete {target}. References to {reference} inside content items will also be removed. This action cannot be undone.",
  "these files",
  "Choose where to place this file.",
  "Choose where to place these files.",
  "Root",
  "Loading folders...",
  "Reassign file owner",
  'Transfer ownership of "{name}" to another CMS user.',
  "New owner",
  "Please select a user.",
  "Upload failed.",
  "Upload failed. Please try again.",
  "Network error",
  "{name}: exceeds {limit} limit.",
  '{name}: file type "{type}" is not allowed.',
  "Total size {size} exceeds batch limit of {limit}.",
  "Uploaded {count} file(s).",
  "Processing {count} file(s)...",
  "Uploading {count} file(s)...",
  "Drop files here, or click to browse",
  "Up to {limit} per file. Images, video, and documents.",
  "Choose files",
  "Choose logo from File Manager",
  "Search image files and choose one to use as the site logo.",
  "Search images...",
  "No images found.",
  "Showing {count} of {total}",
  "Use selected image",
  "Copy URL",
  "Move",
  "Reassign owner",
  "Move selected",
  "Delete selected",
  "Clear",
  "Load more",
  "All types",
  "All users",
  "Type",
  "Uploaded by",
  "URL copied to clipboard.",
  "Could not copy URL.",
] as const;

type FileManagerSource = (typeof FILE_MANAGER_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    'Menadžer fajlova|Otpremi i upravljaj slikama, video snimcima i dokumentima.|Fajlovi|Fascikle menadžera fajlova|Pretraži nazive fajlova, naslove ili alt tekst...|Nema fajlova u {folder}.|{count} izabrano|Otpremi|Opseg datuma|Prikazano {count} od {total} fajlova|{count} fascikla|{count} fascikli|Izmeni fajl|Preimenuj|Premesti fajlove|Slika|Slike|Video|Dokument|Dokumenti|Ostalo|Nova fascikla|Kreiraj fasciklu na trenutnoj lokaciji.|Naziv fascikle|Preimenuj fasciklu|Ažuriraj naziv ove fascikle.|Obriši fasciklu|Obrisati fasciklu?|Možeš obrisati samo praznu fasciklu. Fizički fajlovi se ne menjaju.|Fascikla|Fascikla: {name}|Ažuriraj prikazne metapodatke fajla. Fizički fajl se ne menja.|Naziv fajla|Naslov|Alt tekst|Obrisati fajl?|Obrisati {count} fajlova?|ovaj fajl|{count} fajlova|Trajno ćeš obrisati {target}. Reference na {reference} u stavkama sadržaja takođe će biti uklonjene. Ova radnja se ne može opozvati.|ove fajlove|Izaberi gde da se smesti ovaj fajl.|Izaberi gde da se smeste ovi fajlovi.|Koren|Učitavanje fascikli...|Dodeli fajl drugom vlasniku|Prenesi vlasništvo nad "{name}" na drugog CMS korisnika.|Novi vlasnik|Izaberi korisnika.|Otpremanje nije uspelo.|Otpremanje nije uspelo. Pokušaj ponovo.|Mrežna greška|{name}: prelazi ograničenje od {limit}.|{name}: tip fajla "{type}" nije dozvoljen.|Ukupna veličina {size} prelazi grupno ograničenje od {limit}.|Otpremljeno {count} fajlova.|Obrada {count} fajlova...|Otpremanje {count} fajlova...|Prevuci fajlove ovde ili klikni za izbor|Do {limit} po fajlu. Slike, video i dokumenti.|Izaberi fajlove|Izaberi logo iz Menadžera fajlova|Pretraži slikovne fajlove i izaberi jedan za logo sajta.|Pretraži slike...|Nema pronađenih slika.|Prikazano {count} od {total}|Koristi izabranu sliku|Kopiraj URL|Premesti|Dodeli drugom vlasniku|Premesti izabrano|Obriši izabrano|Obriši izbor|Učitaj još|Svi tipovi|Svi korisnici|Tip|Otpremio|URL je kopiran u clipboard.|Nije moguće kopirati URL.',
  "sr-Cyrl":
    'Менаџер фајлова|Отпреми и управљај сликама, видео снимцима и документима.|Фајлови|Фолдери менаџера фајлова|Претражи називе фајлова, наслове или alt текст...|Нема фајлова у {folder}.|{count} изабрано|Отпреми|Опсег датума|Приказано {count} од {total} фајлова|{count} фолдер|{count} фолдера|Измени фајл|Преименуј|Премести фајлове|Слика|Слике|Видео|Документ|Документи|Остало|Нови фолдер|Креирај фолдер на тренутној локацији.|Назив фолдера|Преименуј фолдер|Ажурирај назив овог фолдера.|Обриши фолдер|Обрисати фолдер?|Можеш обрисати само празан фолдер. Физички фајлови се не мењају.|Фолдер|Фолдер: {name}|Ажурирај приказне метаподатке фајла. Физички фајл се не мења.|Назив фајла|Наслов|Alt текст|Обрисати фајл?|Обрисати {count} фајлова?|овај фајл|{count} фајлова|Трајно ћеш обрисати {target}. Референце на {reference} у ставкама садржаја такође ће бити уклоњене. Ова радња се не може опозвати.|ове фајлове|Изабери где да се смести овај фајл.|Изабери где да се сместе ови фајлови.|Корен|Учитавање фолдера...|Додели фајл другом власнику|Пренеси власништво над "{name}" на другог CMS корисника.|Нови власник|Изабери корисника.|Отпремање није успело.|Отпремање није успело. Покушај поново.|Мрежна грешка|{name}: прелази ограничење од {limit}.|{name}: тип фајла "{type}" није дозвољен.|Укупна величина {size} прелази групно ограничење од {limit}.|Отпремљено {count} фајлова.|Обрада {count} фајлова...|Отпремање {count} фајлова...|Превуци фајлове овде или кликни за избор|До {limit} по фајлу. Слике, видео и документи.|Изабери фајлове|Изабери лого из Менаџера фајлова|Претражи сликовне фајлове и изабери један за лого сајта.|Претражи слике...|Нема пронађених слика.|Приказано {count} од {total}|Користи изабрану слику|Копирај URL|Премести|Додели другом власнику|Премести изабрано|Обриши изабрано|Обриши избор|Учитај још|Сви типови|Сви корисници|Тип|Отпремио|URL је копиран у clipboard.|Није могуће копирати URL.',
  hr: 'Upravitelj datoteka|Prenesite i upravljajte slikama, videozapisima i dokumentima.|Datoteke|Mape upravitelja datoteka|Pretraži nazive datoteka, naslove ili alt tekst...|Nema datoteka u {folder}.|{count} odabrano|Prenesi|Raspon datuma|Prikazano {count} od {total} datoteka|{count} mapa|{count} mapa|Uredi datoteku|Preimenuj|Premjesti datoteke|Slika|Slike|Video|Dokument|Dokumenti|Ostalo|Nova mapa|Stvori mapu na trenutačnoj lokaciji.|Naziv mape|Preimenuj mapu|Ažurirajte naziv ove mape.|Izbriši mapu|Izbrisati mapu?|Možete izbrisati samo praznu mapu. Fizičke datoteke se ne mijenjaju.|Mapa|Mapa: {name}|Ažurirajte prikazne metapodatke datoteke. Fizička datoteka se ne mijenja.|Naziv datoteke|Naslov|Alt tekst|Izbrisati datoteku?|Izbrisati {count} datoteka?|ovu datoteku|{count} datoteka|Trajno ćete izbrisati {target}. Reference na {reference} unutar stavki sadržaja također će biti uklonjene. Ova se radnja ne može poništiti.|ove datoteke|Odaberite gdje smjestiti ovu datoteku.|Odaberite gdje smjestiti ove datoteke.|Korijen|Učitavanje mapa...|Ponovno dodijeli vlasnika datoteke|Prenesite vlasništvo nad "{name}" na drugog CMS korisnika.|Novi vlasnik|Odaberite korisnika.|Prijenos nije uspio.|Prijenos nije uspio. Pokušajte ponovno.|Mrežna pogreška|{name}: prelazi ograničenje od {limit}.|{name}: vrsta datoteke "{type}" nije dopuštena.|Ukupna veličina {size} prelazi skupno ograničenje od {limit}.|Preneseno {count} datoteka.|Obrada {count} datoteka...|Prijenos {count} datoteka...|Ispustite datoteke ovdje ili kliknite za odabir|Do {limit} po datoteci. Slike, video i dokumenti.|Odaberi datoteke|Odaberi logo iz Upravitelja datoteka|Pretražite slikovne datoteke i odaberite jednu za logo stranice.|Pretraži slike...|Nema pronađenih slika.|Prikazano {count} od {total}|Koristi odabranu sliku|Kopiraj URL|Premjesti|Ponovno dodijeli vlasnika|Premjesti odabrano|Izbriši odabrano|Očisti|Učitaj više|Sve vrste|Svi korisnici|Vrsta|Prenio|URL je kopiran u međuspremnik.|Nije moguće kopirati URL.',
  de: 'Dateimanager|Bilder, Videos und Dokumente hochladen und verwalten.|Dateien|Dateimanager-Ordner|Dateinamen, Titel oder Alt-Text suchen...|Keine Dateien in {folder} gefunden.|{count} ausgewählt|Hochladen|Datumsbereich|Zeige {count} von {total} Dateien|{count} Ordner|{count} Ordner|Datei bearbeiten|Umbenennen|Dateien verschieben|Bild|Bilder|Video|Dokument|Dokumente|Sonstiges|Neuer Ordner|Erstelle einen Ordner am aktuellen Speicherort.|Ordnername|Ordner umbenennen|Aktualisiere den Namen dieses Ordners.|Ordner löschen|Ordner löschen?|Du kannst nur einen leeren Ordner löschen. Die physischen Dateien werden nicht geändert.|Ordner|Ordner: {name}|Aktualisiere die Anzeigemetadaten der Datei. Die physische Datei wird nicht geändert.|Dateiname|Titel|Alt-Text|Datei löschen?|{count} Dateien löschen?|diese Datei|{count} Dateien|Du bist dabei, {target} dauerhaft zu löschen. Verweise auf {reference} in Inhaltselementen werden ebenfalls entfernt. Diese Aktion kann nicht rückgängig gemacht werden.|diese Dateien|Wähle aus, wo diese Datei abgelegt werden soll.|Wähle aus, wo diese Dateien abgelegt werden sollen.|Stammverzeichnis|Ordner werden geladen...|Dateibesitzer neu zuweisen|Übertrage die Eigentümerschaft von "{name}" an einen anderen CMS-Benutzer.|Neuer Besitzer|Bitte wähle einen Benutzer aus.|Upload fehlgeschlagen.|Upload fehlgeschlagen. Bitte versuche es erneut.|Netzwerkfehler|{name}: überschreitet das Limit von {limit}.|{name}: Dateityp "{type}" ist nicht erlaubt.|Gesamtgröße {size} überschreitet das Batch-Limit von {limit}.|{count} Datei(en) hochgeladen.|{count} Datei(en) werden verarbeitet...|{count} Datei(en) werden hochgeladen...|Dateien hier ablegen oder zum Auswählen klicken|Bis zu {limit} pro Datei. Bilder, Videos und Dokumente.|Dateien auswählen|Logo aus dem Dateimanager auswählen|Bilddateien suchen und eine als Website-Logo auswählen.|Bilder suchen...|Keine Bilder gefunden.|Zeige {count} von {total}|Ausgewähltes Bild verwenden|URL kopieren|Verschieben|Besitzer neu zuweisen|Ausgewählte verschieben|Ausgewählte löschen|Zurücksetzen|Mehr laden|Alle Typen|Alle Benutzer|Typ|Hochgeladen von|URL in die Zwischenablage kopiert.|URL konnte nicht kopiert werden.',
  fr: 'Gestionnaire de fichiers|Téléversez et gérez des images, vidéos et documents.|Fichiers|Dossiers du gestionnaire de fichiers|Rechercher des noms de fichier, titres ou textes alt...|Aucun fichier trouvé dans {folder}.|{count} sélectionné(s)|Téléverser|Plage de dates|Affichage de {count} sur {total} fichiers|{count} dossier|{count} dossiers|Modifier le fichier|Renommer|Déplacer les fichiers|Image|Images|Vidéo|Document|Documents|Autre|Nouveau dossier|Créer un dossier à l’emplacement actuel.|Nom du dossier|Renommer le dossier|Mettez à jour le nom de ce dossier.|Supprimer le dossier|Supprimer le dossier ?|Vous ne pouvez supprimer qu’un dossier vide. Les fichiers physiques ne sont pas modifiés.|Dossier|Dossier : {name}|Mettez à jour les métadonnées d’affichage du fichier. Le fichier physique n’est pas modifié.|Nom du fichier|Titre|Texte alt|Supprimer le fichier ?|Supprimer {count} fichiers ?|ce fichier|{count} fichiers|Vous êtes sur le point de supprimer définitivement {target}. Les références à {reference} dans les éléments de contenu seront également supprimées. Cette action est irréversible.|ces fichiers|Choisissez où placer ce fichier.|Choisissez où placer ces fichiers.|Racine|Chargement des dossiers...|Réattribuer le propriétaire du fichier|Transférer la propriété de « {name} » à un autre utilisateur CMS.|Nouveau propriétaire|Veuillez sélectionner un utilisateur.|Échec du téléversement.|Échec du téléversement. Veuillez réessayer.|Erreur réseau|{name} : dépasse la limite de {limit}.|{name} : le type de fichier « {type} » n’est pas autorisé.|La taille totale {size} dépasse la limite de lot de {limit}.|{count} fichier(s) téléversé(s).|Traitement de {count} fichier(s)...|Téléversement de {count} fichier(s)...|Déposez les fichiers ici ou cliquez pour parcourir|Jusqu’à {limit} par fichier. Images, vidéos et documents.|Choisir des fichiers|Choisir le logo dans le Gestionnaire de fichiers|Recherchez des fichiers image et choisissez-en un comme logo du site.|Rechercher des images...|Aucune image trouvée.|Affichage de {count} sur {total}|Utiliser l’image sélectionnée|Copier l’URL|Déplacer|Réattribuer le propriétaire|Déplacer la sélection|Supprimer la sélection|Effacer|Charger plus|Tous les types|Tous les utilisateurs|Type|Téléversé par|URL copiée dans le presse-papiers.|Impossible de copier l’URL.',
  es: 'Gestor de archivos|Sube y administra imágenes, vídeos y documentos.|Archivos|Carpetas del gestor de archivos|Buscar nombres de archivo, títulos o texto alt...|No se encontraron archivos en {folder}.|{count} seleccionados|Subir|Rango de fechas|Mostrando {count} de {total} archivos|{count} carpeta|{count} carpetas|Editar archivo|Renombrar|Mover archivos|Imagen|Imágenes|Vídeo|Documento|Documentos|Otro|Nueva carpeta|Crea una carpeta en la ubicación actual.|Nombre de carpeta|Renombrar carpeta|Actualiza el nombre de esta carpeta.|Eliminar carpeta|¿Eliminar carpeta?|Solo puedes eliminar una carpeta vacía. Los archivos físicos no cambian.|Carpeta|Carpeta: {name}|Actualiza los metadatos visibles del archivo. El archivo físico no cambia.|Nombre de archivo|Título|Texto alt|¿Eliminar archivo?|¿Eliminar {count} archivos?|este archivo|{count} archivos|Estás a punto de eliminar permanentemente {target}. Las referencias a {reference} dentro de elementos de contenido también se eliminarán. Esta acción no se puede deshacer.|estos archivos|Elige dónde colocar este archivo.|Elige dónde colocar estos archivos.|Raíz|Cargando carpetas...|Reasignar propietario del archivo|Transfiere la propiedad de "{name}" a otro usuario CMS.|Nuevo propietario|Selecciona un usuario.|La subida falló.|La subida falló. Inténtalo de nuevo.|Error de red|{name}: supera el límite de {limit}.|{name}: el tipo de archivo "{type}" no está permitido.|El tamaño total {size} supera el límite de lote de {limit}.|Se subieron {count} archivo(s).|Procesando {count} archivo(s)...|Subiendo {count} archivo(s)...|Suelta archivos aquí o haz clic para buscar|Hasta {limit} por archivo. Imágenes, vídeos y documentos.|Elegir archivos|Elegir logo desde el Gestor de archivos|Busca archivos de imagen y elige uno para usarlo como logo del sitio.|Buscar imágenes...|No se encontraron imágenes.|Mostrando {count} de {total}|Usar imagen seleccionada|Copiar URL|Mover|Reasignar propietario|Mover seleccionados|Eliminar seleccionados|Limpiar|Cargar más|Todos los tipos|Todos los usuarios|Tipo|Subido por|URL copiada al portapapeles.|No se pudo copiar la URL.',
  it: 'Gestore file|Carica e gestisci immagini, video e documenti.|File|Cartelle del gestore file|Cerca nomi file, titoli o testo alt...|Nessun file trovato in {folder}.|{count} selezionati|Carica|Intervallo date|Mostrati {count} di {total} file|{count} cartella|{count} cartelle|Modifica file|Rinomina|Sposta file|Immagine|Immagini|Video|Documento|Documenti|Altro|Nuova cartella|Crea una cartella nella posizione corrente.|Nome cartella|Rinomina cartella|Aggiorna il nome di questa cartella.|Elimina cartella|Eliminare la cartella?|Puoi eliminare solo una cartella vuota. I file fisici non vengono modificati.|Cartella|Cartella: {name}|Aggiorna i metadati di visualizzazione del file. Il file fisico non viene modificato.|Nome file|Titolo|Testo alt|Eliminare il file?|Eliminare {count} file?|questo file|{count} file|Stai per eliminare definitivamente {target}. Anche i riferimenti a {reference} negli elementi di contenuto verranno rimossi. L’azione non può essere annullata.|questi file|Scegli dove posizionare questo file.|Scegli dove posizionare questi file.|Radice|Caricamento cartelle...|Riassegna proprietario file|Trasferisci la proprietà di "{name}" a un altro utente CMS.|Nuovo proprietario|Seleziona un utente.|Caricamento non riuscito.|Caricamento non riuscito. Riprova.|Errore di rete|{name}: supera il limite di {limit}.|{name}: il tipo di file "{type}" non è consentito.|La dimensione totale {size} supera il limite batch di {limit}.|Caricati {count} file.|Elaborazione di {count} file...|Caricamento di {count} file...|Trascina i file qui o fai clic per sfogliare|Fino a {limit} per file. Immagini, video e documenti.|Scegli file|Scegli logo dal Gestore file|Cerca file immagine e scegline uno come logo del sito.|Cerca immagini...|Nessuna immagine trovata.|Mostrati {count} di {total}|Usa immagine selezionata|Copia URL|Sposta|Riassegna proprietario|Sposta selezionati|Elimina selezionati|Cancella|Carica altro|Tutti i tipi|Tutti gli utenti|Tipo|Caricato da|URL copiato negli appunti.|Impossibile copiare l’URL.',
  pt: 'Gestor de ficheiros|Carregue e gira imagens, vídeos e documentos.|Ficheiros|Pastas do gestor de ficheiros|Pesquisar nomes de ficheiro, títulos ou texto alt...|Nenhum ficheiro encontrado em {folder}.|{count} selecionados|Carregar|Intervalo de datas|A mostrar {count} de {total} ficheiros|{count} pasta|{count} pastas|Editar ficheiro|Renomear|Mover ficheiros|Imagem|Imagens|Vídeo|Documento|Documentos|Outro|Nova pasta|Crie uma pasta na localização atual.|Nome da pasta|Renomear pasta|Atualize o nome desta pasta.|Eliminar pasta|Eliminar pasta?|Só pode eliminar uma pasta vazia. Os ficheiros físicos não são alterados.|Pasta|Pasta: {name}|Atualize os metadados de apresentação do ficheiro. O ficheiro físico não é alterado.|Nome do ficheiro|Título|Texto alt|Eliminar ficheiro?|Eliminar {count} ficheiros?|este ficheiro|{count} ficheiros|Está prestes a eliminar permanentemente {target}. As referências a {reference} nos itens de conteúdo também serão removidas. Esta ação não pode ser anulada.|estes ficheiros|Escolha onde colocar este ficheiro.|Escolha onde colocar estes ficheiros.|Raiz|A carregar pastas...|Reatribuir proprietário do ficheiro|Transfira a propriedade de "{name}" para outro utilizador CMS.|Novo proprietário|Selecione um utilizador.|Falha no carregamento.|Falha no carregamento. Tente novamente.|Erro de rede|{name}: excede o limite de {limit}.|{name}: o tipo de ficheiro "{type}" não é permitido.|O tamanho total {size} excede o limite de lote de {limit}.|{count} ficheiro(s) carregado(s).|A processar {count} ficheiro(s)...|A carregar {count} ficheiro(s)...|Largue ficheiros aqui ou clique para procurar|Até {limit} por ficheiro. Imagens, vídeo e documentos.|Escolher ficheiros|Escolher logótipo no Gestor de ficheiros|Pesquise ficheiros de imagem e escolha um para usar como logótipo do site.|Pesquisar imagens...|Nenhuma imagem encontrada.|A mostrar {count} de {total}|Usar imagem selecionada|Copiar URL|Mover|Reatribuir proprietário|Mover selecionados|Eliminar selecionados|Limpar|Carregar mais|Todos os tipos|Todos os utilizadores|Tipo|Carregado por|URL copiado para a área de transferência.|Não foi possível copiar o URL.',
  "pt-BR":
    'Gerenciador de arquivos|Envie e gerencie imagens, vídeos e documentos.|Arquivos|Pastas do gerenciador de arquivos|Pesquisar nomes de arquivo, títulos ou texto alt...|Nenhum arquivo encontrado em {folder}.|{count} selecionados|Enviar|Intervalo de datas|Mostrando {count} de {total} arquivos|{count} pasta|{count} pastas|Editar arquivo|Renomear|Mover arquivos|Imagem|Imagens|Vídeo|Documento|Documentos|Outro|Nova pasta|Crie uma pasta no local atual.|Nome da pasta|Renomear pasta|Atualize o nome desta pasta.|Excluir pasta|Excluir pasta?|Você só pode excluir uma pasta vazia. Os arquivos físicos não são alterados.|Pasta|Pasta: {name}|Atualize os metadados de exibição do arquivo. O arquivo físico não é alterado.|Nome do arquivo|Título|Texto alt|Excluir arquivo?|Excluir {count} arquivos?|este arquivo|{count} arquivos|Você está prestes a excluir permanentemente {target}. As referências a {reference} nos itens de conteúdo também serão removidas. Essa ação não pode ser desfeita.|estes arquivos|Escolha onde colocar este arquivo.|Escolha onde colocar estes arquivos.|Raiz|Carregando pastas...|Reatribuir proprietário do arquivo|Transfira a propriedade de "{name}" para outro usuário CMS.|Novo proprietário|Selecione um usuário.|Falha no envio.|Falha no envio. Tente novamente.|Erro de rede|{name}: excede o limite de {limit}.|{name}: o tipo de arquivo "{type}" não é permitido.|O tamanho total {size} excede o limite de lote de {limit}.|{count} arquivo(s) enviado(s).|Processando {count} arquivo(s)...|Enviando {count} arquivo(s)...|Solte arquivos aqui ou clique para procurar|Até {limit} por arquivo. Imagens, vídeo e documentos.|Escolher arquivos|Escolher logo no Gerenciador de arquivos|Pesquise arquivos de imagem e escolha um para usar como logo do site.|Pesquisar imagens...|Nenhuma imagem encontrada.|Mostrando {count} de {total}|Usar imagem selecionada|Copiar URL|Mover|Reatribuir proprietário|Mover selecionados|Excluir selecionados|Limpar|Carregar mais|Todos os tipos|Todos os usuários|Tipo|Enviado por|URL copiada para a área de transferência.|Não foi possível copiar a URL.',
  nl: 'Bestandsbeheer|Upload en beheer afbeeldingen, video’s en documenten.|Bestanden|Mappen van bestandsbeheer|Zoek bestandsnamen, titels of alt-tekst...|Geen bestanden gevonden in {folder}.|{count} geselecteerd|Uploaden|Datumbereik|Toont {count} van {total} bestanden|{count} map|{count} mappen|Bestand bewerken|Hernoemen|Bestanden verplaatsen|Afbeelding|Afbeeldingen|Video|Document|Documenten|Overig|Nieuwe map|Maak een map op de huidige locatie.|Mapnaam|Map hernoemen|Werk de naam van deze map bij.|Map verwijderen|Map verwijderen?|Je kunt alleen een lege map verwijderen. De fysieke bestanden worden niet gewijzigd.|Map|Map: {name}|Werk de weergavemetadata van het bestand bij. Het fysieke bestand wordt niet gewijzigd.|Bestandsnaam|Titel|Alt-tekst|Bestand verwijderen?|{count} bestanden verwijderen?|dit bestand|{count} bestanden|Je staat op het punt {target} permanent te verwijderen. Verwijzingen naar {reference} in contentitems worden ook verwijderd. Deze actie kan niet ongedaan worden gemaakt.|deze bestanden|Kies waar dit bestand geplaatst moet worden.|Kies waar deze bestanden geplaatst moeten worden.|Hoofdmap|Mappen laden...|Bestandseigenaar opnieuw toewijzen|Draag eigendom van "{name}" over aan een andere CMS-gebruiker.|Nieuwe eigenaar|Selecteer een gebruiker.|Upload mislukt.|Upload mislukt. Probeer het opnieuw.|Netwerkfout|{name}: overschrijdt de limiet van {limit}.|{name}: bestandstype "{type}" is niet toegestaan.|Totale grootte {size} overschrijdt de batchlimiet van {limit}.|{count} bestand(en) geüpload.|{count} bestand(en) verwerken...|{count} bestand(en) uploaden...|Sleep bestanden hierheen of klik om te bladeren|Tot {limit} per bestand. Afbeeldingen, video en documenten.|Bestanden kiezen|Logo kiezen uit Bestandsbeheer|Zoek afbeeldingsbestanden en kies er een als sitelogo.|Afbeeldingen zoeken...|Geen afbeeldingen gevonden.|Toont {count} van {total}|Geselecteerde afbeelding gebruiken|URL kopiëren|Verplaatsen|Eigenaar opnieuw toewijzen|Geselecteerde verplaatsen|Geselecteerde verwijderen|Wissen|Meer laden|Alle typen|Alle gebruikers|Type|Geüpload door|URL gekopieerd naar klembord.|URL kon niet worden gekopieerd.',
  pl: 'Menedżer plików|Przesyłaj i zarządzaj obrazami, filmami i dokumentami.|Pliki|Katalogi menedżera plików|Szukaj nazw plików, tytułów lub tekstu alt...|Nie znaleziono plików w {folder}.|Wybrano {count}|Prześlij|Zakres dat|Pokazano {count} z {total} plików|{count} katalog|{count} katalogów|Edytuj plik|Zmień nazwę|Przenieś pliki|Obraz|Obrazy|Wideo|Dokument|Dokumenty|Inne|Nowy katalog|Utwórz katalog w bieżącej lokalizacji.|Nazwa katalogu|Zmień nazwę katalogu|Zaktualizuj nazwę tego katalogu.|Usuń katalog|Usunąć katalog?|Możesz usunąć tylko pusty katalog. Fizyczne pliki nie zostaną zmienione.|Katalog|Katalog: {name}|Zaktualizuj metadane wyświetlania pliku. Fizyczny plik nie zostanie zmieniony.|Nazwa pliku|Tytuł|Tekst alt|Usunąć plik?|Usunąć {count} plików?|ten plik|{count} plików|Zamierzasz trwale usunąć {target}. Odwołania do {reference} w elementach treści również zostaną usunięte. Tej akcji nie można cofnąć.|te pliki|Wybierz, gdzie umieścić ten plik.|Wybierz, gdzie umieścić te pliki.|Katalog główny|Ładowanie katalogów...|Przypisz właściciela pliku ponownie|Przenieś własność "{name}" na innego użytkownika CMS.|Nowy właściciel|Wybierz użytkownika.|Przesyłanie nie powiodło się.|Przesyłanie nie powiodło się. Spróbuj ponownie.|Błąd sieci|{name}: przekracza limit {limit}.|{name}: typ pliku "{type}" nie jest dozwolony.|Łączny rozmiar {size} przekracza limit partii {limit}.|Przesłano {count} plik(ów).|Przetwarzanie {count} plik(ów)...|Przesyłanie {count} plik(ów)...|Upuść pliki tutaj lub kliknij, aby wybrać|Do {limit} na plik. Obrazy, wideo i dokumenty.|Wybierz pliki|Wybierz logo z Menedżera plików|Wyszukaj pliki obrazów i wybierz jeden jako logo witryny.|Szukaj obrazów...|Nie znaleziono obrazów.|Pokazano {count} z {total}|Użyj wybranego obrazu|Kopiuj URL|Przenieś|Przypisz właściciela ponownie|Przenieś wybrane|Usuń wybrane|Wyczyść|Załaduj więcej|Wszystkie typy|Wszyscy użytkownicy|Typ|Przesłane przez|URL skopiowano do schowka.|Nie można skopiować URL.',
  tr: 'Dosya Yöneticisi|Görselleri, videoları ve belgeleri yükleyip yönetin.|Dosyalar|Dosya yöneticisi klasörleri|Dosya adlarında, başlıklarda veya alt metinde ara...|{folder} içinde dosya bulunamadı.|{count} seçildi|Yükle|Tarih aralığı|{total} dosyadan {count} gösteriliyor|{count} klasör|{count} klasör|Dosyayı düzenle|Yeniden adlandır|Dosyaları taşı|Görsel|Görseller|Video|Belge|Belgeler|Diğer|Yeni klasör|Geçerli konumda bir klasör oluştur.|Klasör adı|Klasörü yeniden adlandır|Bu klasörün adını güncelle.|Klasörü sil|Klasör silinsin mi?|Yalnızca boş bir klasörü silebilirsiniz. Fiziksel dosyalar değiştirilmez.|Klasör|Klasör: {name}|Dosyanın görüntü meta verilerini güncelle. Fiziksel dosya değiştirilmez.|Dosya adı|Başlık|Alt metin|Dosya silinsin mi?|{count} dosya silinsin mi?|bu dosya|{count} dosya|{target} kalıcı olarak silinecek. İçerik öğelerindeki {reference} başvuruları da kaldırılacak. Bu işlem geri alınamaz.|bu dosyalar|Bu dosyanın nereye yerleştirileceğini seçin.|Bu dosyaların nereye yerleştirileceğini seçin.|Kök|Klasörler yükleniyor...|Dosya sahibini yeniden ata|"{name}" sahipliğini başka bir CMS kullanıcısına aktar.|Yeni sahip|Lütfen bir kullanıcı seçin.|Yükleme başarısız.|Yükleme başarısız. Lütfen tekrar deneyin.|Ağ hatası|{name}: {limit} sınırını aşıyor.|{name}: "{type}" dosya türüne izin verilmiyor.|Toplam boyut {size}, {limit} toplu sınırını aşıyor.|{count} dosya yüklendi.|{count} dosya işleniyor...|{count} dosya yükleniyor...|Dosyaları buraya bırakın veya göz atmak için tıklayın|Dosya başına en fazla {limit}. Görseller, video ve belgeler.|Dosyaları seç|Dosya Yöneticisinden logo seç|Görsel dosyalarını arayın ve site logosu olarak birini seçin.|Görselleri ara...|Görsel bulunamadı.|{total} öğeden {count} gösteriliyor|Seçili görseli kullan|URL kopyala|Taşı|Sahibi yeniden ata|Seçilenleri taşı|Seçilenleri sil|Temizle|Daha fazla yükle|Tüm türler|Tüm kullanıcılar|Tür|Yükleyen|URL panoya kopyalandı.|URL kopyalanamadı.',
  mk: 'Менаџер на датотеки|Прикачувајте и управувајте со слики, видеа и документи.|Датотеки|Папки на менаџерот на датотеки|Пребарај имиња на датотеки, наслови или alt текст...|Не се пронајдени датотеки во {folder}.|Избрани {count}|Прикачи|Опсег на датуми|Прикажани {count} од {total} датотеки|{count} папка|{count} папки|Уреди датотека|Преименувај|Премести датотеки|Слика|Слики|Видео|Документ|Документи|Друго|Нова папка|Креирај папка на тековната локација.|Име на папка|Преименувај папка|Ажурирај го името на оваа папка.|Избриши папка|Да се избрише папката?|Можете да избришете само празна папка. Физичките датотеки не се менуваат.|Папка|Папка: {name}|Ажурирај ги приказните метаподатоци на датотеката. Физичката датотека не се менува.|Име на датотека|Наслов|Alt текст|Да се избрише датотеката?|Да се избришат {count} датотеки?|оваа датотека|{count} датотеки|Ќе избришете трајно {target}. Референците кон {reference} во содржинските ставки исто така ќе се отстранат. Оваа акција не може да се поништи.|овие датотеки|Изберете каде да се постави оваа датотека.|Изберете каде да се постават овие датотеки.|Корен|Се вчитуваат папки...|Пренамени сопственик на датотека|Пренеси сопственост на "{name}" на друг CMS корисник.|Нов сопственик|Изберете корисник.|Прикачувањето не успеа.|Прикачувањето не успеа. Обидете се повторно.|Мрежна грешка|{name}: го надминува лимитот од {limit}.|{name}: типот на датотека "{type}" не е дозволен.|Вкупната големина {size} го надминува групниот лимит од {limit}.|Прикачени {count} датотеки.|Обработка на {count} датотеки...|Прикачување на {count} датотеки...|Пуштете датотеки тука или кликнете за избор|До {limit} по датотека. Слики, видео и документи.|Избери датотеки|Избери лого од Менаџерот на датотеки|Пребарајте датотеки со слики и изберете една за логото на сајтот.|Пребарај слики...|Не се пронајдени слики.|Прикажани {count} од {total}|Користи избрана слика|Копирај URL|Премести|Пренамени сопственик|Премести избрано|Избриши избрано|Исчисти|Вчитај повеќе|Сите типови|Сите корисници|Тип|Прикачено од|URL е копиран во clipboard.|Не може да се копира URL.',
  bs: 'Menadžer datoteka|Otpremi i upravljaj slikama, videozapisima i dokumentima.|Datoteke|Fascikle menadžera datoteka|Pretraži nazive datoteka, naslove ili alt tekst...|Nema datoteka u {folder}.|{count} odabrano|Otpremi|Raspon datuma|Prikazano {count} od {total} datoteka|{count} fascikla|{count} fascikli|Uredi datoteku|Preimenuj|Premjesti datoteke|Slika|Slike|Video|Dokument|Dokumenti|Ostalo|Nova fascikla|Kreiraj fasciklu na trenutnoj lokaciji.|Naziv fascikle|Preimenuj fasciklu|Ažuriraj naziv ove fascikle.|Obriši fasciklu|Obrisati fasciklu?|Možeš obrisati samo praznu fasciklu. Fizičke datoteke se ne mijenjaju.|Fascikla|Fascikla: {name}|Ažuriraj prikazne metapodatke datoteke. Fizička datoteka se ne mijenja.|Naziv datoteke|Naslov|Alt tekst|Obrisati datoteku?|Obrisati {count} datoteka?|ovu datoteku|{count} datoteka|Trajno ćeš obrisati {target}. Reference na {reference} unutar stavki sadržaja također će biti uklonjene. Ova radnja se ne može poništiti.|ove datoteke|Izaberi gdje smjestiti ovu datoteku.|Izaberi gdje smjestiti ove datoteke.|Korijen|Učitavanje fascikli...|Dodijeli datoteku drugom vlasniku|Prenesi vlasništvo nad "{name}" na drugog CMS korisnika.|Novi vlasnik|Izaberi korisnika.|Otpremanje nije uspjelo.|Otpremanje nije uspjelo. Pokušaj ponovo.|Mrežna greška|{name}: prelazi ograničenje od {limit}.|{name}: tip datoteke "{type}" nije dozvoljen.|Ukupna veličina {size} prelazi grupno ograničenje od {limit}.|Otpremljeno {count} datoteka.|Obrada {count} datoteka...|Otpremanje {count} datoteka...|Prevuci datoteke ovdje ili klikni za izbor|Do {limit} po datoteci. Slike, video i dokumenti.|Izaberi datoteke|Izaberi logo iz Menadžera datoteka|Pretraži slikovne datoteke i izaberi jednu za logo sajta.|Pretraži slike...|Nema pronađenih slika.|Prikazano {count} od {total}|Koristi odabranu sliku|Kopiraj URL|Premjesti|Dodijeli drugom vlasniku|Premjesti odabrano|Obriši odabrano|Očisti|Učitaj još|Svi tipovi|Svi korisnici|Tip|Otpremio|URL je kopiran u clipboard.|Nije moguće kopirati URL.',
  sl: 'Upravitelj datotek|Naložite in upravljajte slike, videe in dokumente.|Datoteke|Mape upravitelja datotek|Išči imena datotek, naslove ali alt besedilo...|V {folder} ni najdenih datotek.|Izbranih {count}|Naloži|Datumski razpon|Prikazano {count} od {total} datotek|{count} mapa|{count} map|Uredi datoteko|Preimenuj|Premakni datoteke|Slika|Slike|Video|Dokument|Dokumenti|Drugo|Nova mapa|Ustvari mapo na trenutni lokaciji.|Ime mape|Preimenuj mapo|Posodobi ime te mape.|Izbriši mapo|Izbrisati mapo?|Izbrišete lahko samo prazno mapo. Fizične datoteke se ne spremenijo.|Mapa|Mapa: {name}|Posodobi prikazne metapodatke datoteke. Fizična datoteka se ne spremeni.|Ime datoteke|Naslov|Alt besedilo|Izbrisati datoteko?|Izbrisati {count} datotek?|to datoteko|{count} datotek|Trajno boste izbrisali {target}. Sklici na {reference} v vsebinskih elementih bodo prav tako odstranjeni. Tega dejanja ni mogoče razveljaviti.|te datoteke|Izberite, kam postaviti to datoteko.|Izberite, kam postaviti te datoteke.|Koren|Nalaganje map...|Ponovno dodeli lastnika datoteke|Prenesite lastništvo "{name}" na drugega uporabnika CMS.|Novi lastnik|Izberite uporabnika.|Nalaganje ni uspelo.|Nalaganje ni uspelo. Poskusite znova.|Omrežna napaka|{name}: presega omejitev {limit}.|{name}: vrsta datoteke "{type}" ni dovoljena.|Skupna velikost {size} presega paketno omejitev {limit}.|Naloženih {count} datotek.|Obdelava {count} datotek...|Nalaganje {count} datotek...|Spustite datoteke sem ali kliknite za brskanje|Do {limit} na datoteko. Slike, video in dokumenti.|Izberi datoteke|Izberi logotip iz Upravitelja datotek|Poiščite slikovne datoteke in izberite eno za logotip strani.|Išči slike...|Ni najdenih slik.|Prikazano {count} od {total}|Uporabi izbrano sliko|Kopiraj URL|Premakni|Ponovno dodeli lastnika|Premakni izbrano|Izbriši izbrano|Počisti|Naloži več|Vse vrste|Vsi uporabniki|Vrsta|Naložil|URL kopiran v odložišče.|URL-ja ni bilo mogoče kopirati.',
  ru: 'Файловый менеджер|Загружайте изображения, видео и документы и управляйте ими.|Файлы|Папки файлового менеджера|Поиск по именам файлов, заголовкам или alt-тексту...|В {folder} файлы не найдены.|Выбрано {count}|Загрузить|Диапазон дат|Показано {count} из {total} файлов|{count} папка|{count} папок|Редактировать файл|Переименовать|Переместить файлы|Изображение|Изображения|Видео|Документ|Документы|Другое|Новая папка|Создать папку в текущем расположении.|Имя папки|Переименовать папку|Обновите имя этой папки.|Удалить папку|Удалить папку?|Можно удалить только пустую папку. Физические файлы не изменяются.|Папка|Папка: {name}|Обновите отображаемые метаданные файла. Физический файл не изменяется.|Имя файла|Заголовок|Alt-текст|Удалить файл?|Удалить {count} файлов?|этот файл|{count} файлов|Вы собираетесь навсегда удалить {target}. Ссылки на {reference} в элементах контента также будут удалены. Это действие нельзя отменить.|эти файлы|Выберите, куда поместить этот файл.|Выберите, куда поместить эти файлы.|Корень|Загрузка папок...|Назначить нового владельца файла|Передать владение "{name}" другому пользователю CMS.|Новый владелец|Выберите пользователя.|Загрузка не удалась.|Загрузка не удалась. Попробуйте еще раз.|Сетевая ошибка|{name}: превышает лимит {limit}.|{name}: тип файла "{type}" не разрешен.|Общий размер {size} превышает пакетный лимит {limit}.|Загружено файлов: {count}.|Обработка файлов: {count}...|Загрузка файлов: {count}...|Перетащите файлы сюда или нажмите для выбора|До {limit} на файл. Изображения, видео и документы.|Выбрать файлы|Выбрать логотип из файлового менеджера|Найдите файлы изображений и выберите один как логотип сайта.|Поиск изображений...|Изображения не найдены.|Показано {count} из {total}|Использовать выбранное изображение|Копировать URL|Переместить|Назначить нового владельца|Переместить выбранное|Удалить выбранное|Очистить|Загрузить еще|Все типы|Все пользователи|Тип|Загружено пользователем|URL скопирован в буфер обмена.|Не удалось скопировать URL.',
  hu: 'Fájlkezelő|Képek, videók és dokumentumok feltöltése és kezelése.|Fájlok|Fájlkezelő mappái|Keresés fájlnevekben, címekben vagy alt szövegben...|Nem találhatók fájlok itt: {folder}.|{count} kijelölve|Feltöltés|Dátumtartomány|{count} / {total} fájl megjelenítve|{count} mappa|{count} mappa|Fájl szerkesztése|Átnevezés|Fájlok áthelyezése|Kép|Képek|Videó|Dokumentum|Dokumentumok|Egyéb|Új mappa|Mappa létrehozása az aktuális helyen.|Mappa neve|Mappa átnevezése|A mappa nevének frissítése.|Mappa törlése|Törlöd a mappát?|Csak üres mappát törölhetsz. A fizikai fájlok nem változnak.|Mappa|Mappa: {name}|A fájl megjelenítési metaadatainak frissítése. A fizikai fájl nem változik.|Fájlnév|Cím|Alt szöveg|Törlöd a fájlt?|Törlöd ezt a(z) {count} fájlt?|ez a fájl|{count} fájl|Végleg törölni fogod ezt: {target}. A {reference} hivatkozásai a tartalmi elemekben szintén eltávolításra kerülnek. Ez a művelet nem vonható vissza.|ezek a fájlok|Válaszd ki, hova kerüljön ez a fájl.|Válaszd ki, hova kerüljenek ezek a fájlok.|Gyökér|Mappák betöltése...|Fájl tulajdonosának újra hozzárendelése|A(z) "{name}" tulajdonjogának átadása egy másik CMS-felhasználónak.|Új tulajdonos|Válassz felhasználót.|A feltöltés sikertelen.|A feltöltés sikertelen. Próbáld újra.|Hálózati hiba|{name}: meghaladja a(z) {limit} korlátot.|{name}: a(z) "{type}" fájltípus nem engedélyezett.|A teljes méret {size} meghaladja a(z) {limit} kötegkorlátot.|{count} fájl feltöltve.|{count} fájl feldolgozása...|{count} fájl feltöltése...|Húzd ide a fájlokat, vagy kattints a böngészéshez|Legfeljebb {limit} fájlonként. Képek, videó és dokumentumok.|Fájlok kiválasztása|Logó kiválasztása a Fájlkezelőből|Keress képfájlokat, és válassz egyet webhelylogónak.|Képek keresése...|Nem találhatók képek.|{count} / {total} megjelenítve|Kijelölt kép használata|URL másolása|Áthelyezés|Tulajdonos újra hozzárendelése|Kijelöltek áthelyezése|Kijelöltek törlése|Törlés|Továbbiak betöltése|Minden típus|Minden felhasználó|Típus|Feltöltötte|URL a vágólapra másolva.|Nem sikerült másolni az URL-t.',
  bg: 'Файлов мениджър|Качвайте и управлявайте изображения, видеа и документи.|Файлове|Папки на файловия мениджър|Търсене по имена на файлове, заглавия или alt текст...|Не са намерени файлове в {folder}.|Избрани {count}|Качи|Диапазон от дати|Показани {count} от {total} файла|{count} папка|{count} папки|Редактиране на файл|Преименуване|Преместване на файлове|Изображение|Изображения|Видео|Документ|Документи|Друго|Нова папка|Създай папка на текущото място.|Име на папка|Преименуване на папка|Актуализирай името на тази папка.|Изтриване на папка|Изтриване на папката?|Можеш да изтриеш само празна папка. Физическите файлове не се променят.|Папка|Папка: {name}|Актуализирай метаданните за показване на файла. Физическият файл не се променя.|Име на файл|Заглавие|Alt текст|Изтриване на файла?|Изтриване на {count} файла?|този файл|{count} файла|Ще изтриеш окончателно {target}. Препратките към {reference} в елементите на съдържанието също ще бъдат премахнати. Това действие не може да бъде отменено.|тези файлове|Избери къде да се постави този файл.|Избери къде да се поставят тези файлове.|Корен|Зареждане на папки...|Преназначаване на собственик на файл|Прехвърли собствеността върху "{name}" на друг CMS потребител.|Нов собственик|Избери потребител.|Качването не бе успешно.|Качването не бе успешно. Опитай отново.|Мрежова грешка|{name}: надвишава лимита от {limit}.|{name}: типът файл "{type}" не е разрешен.|Общият размер {size} надвишава пакетния лимит от {limit}.|Качени {count} файла.|Обработка на {count} файла...|Качване на {count} файла...|Пусни файлове тук или щракни за избор|До {limit} на файл. Изображения, видео и документи.|Избери файлове|Избери лого от Файловия мениджър|Потърси файлове с изображения и избери един за лого на сайта.|Търсене на изображения...|Не са намерени изображения.|Показани {count} от {total}|Използвай избраното изображение|Копирай URL|Премести|Преназначи собственик|Премести избраните|Изтрий избраните|Изчисти|Зареди още|Всички типове|Всички потребители|Тип|Качено от|URL адресът е копиран в клипборда.|URL адресът не може да бъде копиран.',
  ja: 'ファイルマネージャー|画像、動画、ドキュメントをアップロードして管理します。|ファイル|ファイルマネージャーのフォルダー|ファイル名、タイトル、代替テキストを検索...|{folder} にファイルは見つかりません。|{count} 件選択中|アップロード|日付範囲|{total} 件中 {count} 件のファイルを表示|{count} 個のフォルダー|{count} 個のフォルダー|ファイルを編集|名前を変更|ファイルを移動|画像|画像|動画|ドキュメント|ドキュメント|その他|新しいフォルダー|現在の場所にフォルダーを作成します。|フォルダー名|フォルダー名を変更|このフォルダー名を更新します。|フォルダーを削除|フォルダーを削除しますか？|削除できるのは空のフォルダーだけです。物理ファイルは変更されません。|フォルダー|フォルダー: {name}|ファイルの表示メタデータを更新します。物理ファイルは変更されません。|ファイル名|タイトル|代替テキスト|ファイルを削除しますか？|{count} 件のファイルを削除しますか？|このファイル|{count} 件のファイル|{target} を完全に削除しようとしています。コンテンツ項目内の {reference} への参照も削除されます。この操作は元に戻せません。|これらのファイル|このファイルの移動先を選択してください。|これらのファイルの移動先を選択してください。|ルート|フォルダーを読み込み中...|ファイル所有者を再割り当て|"{name}" の所有権を別の CMS ユーザーへ移します。|新しい所有者|ユーザーを選択してください。|アップロードに失敗しました。|アップロードに失敗しました。もう一度お試しください。|ネットワークエラー|{name}: {limit} の制限を超えています。|{name}: ファイル形式 "{type}" は許可されていません。|合計サイズ {size} はバッチ制限 {limit} を超えています。|{count} 件のファイルをアップロードしました。|{count} 件のファイルを処理中...|{count} 件のファイルをアップロード中...|ここにファイルをドロップするか、クリックして参照|1ファイルあたり最大 {limit}。画像、動画、ドキュメントに対応。|ファイルを選択|ファイルマネージャーからロゴを選択|画像ファイルを検索し、サイトロゴとして使うものを選択します。|画像を検索...|画像は見つかりません。|{total} 件中 {count} 件を表示|選択した画像を使用|URL をコピー|移動|所有者を再割り当て|選択項目を移動|選択項目を削除|クリア|さらに読み込む|すべてのタイプ|すべてのユーザー|タイプ|アップロード者|URL をクリップボードにコピーしました。|URL をコピーできませんでした。',
  "zh-Hans":
    '文件管理器|上传并管理图片、视频和文档。|文件|文件管理器文件夹|搜索文件名、标题或替代文本...|在 {folder} 中未找到文件。|已选择 {count} 项|上传|日期范围|正在显示 {count} / {total} 个文件|{count} 个文件夹|{count} 个文件夹|编辑文件|重命名|移动文件|图片|图片|视频|文档|文档|其他|新建文件夹|在当前位置创建文件夹。|文件夹名称|重命名文件夹|更新此文件夹的名称。|删除文件夹|删除文件夹？|只能删除空文件夹。物理文件不会被更改。|文件夹|文件夹：{name}|更新文件的显示元数据。物理文件不会被更改。|文件名|标题|替代文本|删除文件？|删除 {count} 个文件？|此文件|{count} 个文件|你即将永久删除 {target}。内容项中对 {reference} 的引用也会被移除。此操作无法撤销。|这些文件|选择此文件的放置位置。|选择这些文件的放置位置。|根目录|正在加载文件夹...|重新分配文件所有者|将 "{name}" 的所有权转移给另一位 CMS 用户。|新所有者|请选择用户。|上传失败。|上传失败。请重试。|网络错误|{name}：超过 {limit} 限制。|{name}：不允许文件类型 "{type}"。|总大小 {size} 超过批量限制 {limit}。|已上传 {count} 个文件。|正在处理 {count} 个文件...|正在上传 {count} 个文件...|将文件拖到此处，或点击浏览|每个文件最大 {limit}。支持图片、视频和文档。|选择文件|从文件管理器选择徽标|搜索图片文件并选择一个作为站点徽标。|搜索图片...|未找到图片。|正在显示 {count} / {total}|使用所选图片|复制 URL|移动|重新分配所有者|移动所选项|删除所选项|清除|加载更多|所有类型|所有用户|类型|上传者|URL 已复制到剪贴板。|无法复制 URL。',
  "zh-Hant":
    '檔案管理器|上傳並管理圖片、影片和文件。|檔案|檔案管理器資料夾|搜尋檔案名稱、標題或替代文字...|在 {folder} 中找不到檔案。|已選取 {count} 項|上傳|日期範圍|正在顯示 {count} / {total} 個檔案|{count} 個資料夾|{count} 個資料夾|編輯檔案|重新命名|移動檔案|圖片|圖片|影片|文件|文件|其他|新增資料夾|在目前位置建立資料夾。|資料夾名稱|重新命名資料夾|更新此資料夾名稱。|刪除資料夾|刪除資料夾？|只能刪除空資料夾。實體檔案不會變更。|資料夾|資料夾：{name}|更新檔案的顯示中繼資料。實體檔案不會變更。|檔案名稱|標題|替代文字|刪除檔案？|刪除 {count} 個檔案？|此檔案|{count} 個檔案|你即將永久刪除 {target}。內容項目中對 {reference} 的參照也會移除。此操作無法復原。|這些檔案|選擇此檔案的放置位置。|選擇這些檔案的放置位置。|根目錄|正在載入資料夾...|重新指派檔案擁有者|將 "{name}" 的擁有權轉移給另一位 CMS 使用者。|新擁有者|請選擇使用者。|上傳失敗。|上傳失敗。請再試一次。|網路錯誤|{name}：超過 {limit} 限制。|{name}：不允許檔案類型 "{type}"。|總大小 {size} 超過批次限制 {limit}。|已上傳 {count} 個檔案。|正在處理 {count} 個檔案...|正在上傳 {count} 個檔案...|將檔案拖放到這裡，或點擊瀏覽|每個檔案最高 {limit}。支援圖片、影片和文件。|選擇檔案|從檔案管理器選擇標誌|搜尋圖片檔案並選擇一個作為網站標誌。|搜尋圖片...|找不到圖片。|正在顯示 {count} / {total}|使用選取的圖片|複製 URL|移動|重新指派擁有者|移動所選項目|刪除所選項目|清除|載入更多|所有類型|所有使用者|類型|上傳者|URL 已複製到剪貼簿。|無法複製 URL。',
  ar: 'مدير الملفات|ارفع الصور ومقاطع الفيديو والمستندات وأدرها.|الملفات|مجلدات مدير الملفات|ابحث في أسماء الملفات أو العناوين أو النص البديل...|لم يتم العثور على ملفات في {folder}.|تم تحديد {count}|رفع|نطاق التاريخ|عرض {count} من أصل {total} ملفًا|{count} مجلد|{count} مجلدات|تحرير الملف|إعادة تسمية|نقل الملفات|صورة|صور|فيديو|مستند|مستندات|أخرى|مجلد جديد|أنشئ مجلدًا في الموقع الحالي.|اسم المجلد|إعادة تسمية المجلد|حدّث اسم هذا المجلد.|حذف المجلد|حذف المجلد؟|يمكنك حذف مجلد فارغ فقط. لن تتغير الملفات الفعلية.|مجلد|المجلد: {name}|حدّث بيانات عرض الملف. لن يتغير الملف الفعلي.|اسم الملف|العنوان|النص البديل|حذف الملف؟|حذف {count} ملفات؟|هذا الملف|{count} ملفات|أنت على وشك حذف {target} نهائيًا. ستُزال أيضًا الإشارات إلى {reference} داخل عناصر المحتوى. لا يمكن التراجع عن هذا الإجراء.|هذه الملفات|اختر مكان وضع هذا الملف.|اختر مكان وضع هذه الملفات.|الجذر|جار تحميل المجلدات...|إعادة تعيين مالك الملف|انقل ملكية "{name}" إلى مستخدم CMS آخر.|المالك الجديد|يرجى اختيار مستخدم.|فشل الرفع.|فشل الرفع. يرجى المحاولة مرة أخرى.|خطأ في الشبكة|{name}: يتجاوز حد {limit}.|{name}: نوع الملف "{type}" غير مسموح.|الحجم الإجمالي {size} يتجاوز حد الدفعة {limit}.|تم رفع {count} ملف.|جار معالجة {count} ملف...|جار رفع {count} ملف...|أفلت الملفات هنا أو انقر للتصفح|حتى {limit} لكل ملف. صور وفيديو ومستندات.|اختيار الملفات|اختر الشعار من مدير الملفات|ابحث عن ملفات الصور واختر واحدًا لاستخدامه كشعار للموقع.|البحث عن الصور...|لم يتم العثور على صور.|عرض {count} من أصل {total}|استخدم الصورة المحددة|نسخ URL|نقل|إعادة تعيين المالك|نقل المحدد|حذف المحدد|مسح|تحميل المزيد|كل الأنواع|كل المستخدمين|النوع|رفعه|تم نسخ URL إلى الحافظة.|تعذر نسخ URL.',
  id: 'Manajer Berkas|Unggah dan kelola gambar, video, dan dokumen.|Berkas|Direktori manajer berkas|Cari nama berkas, judul, atau teks alt...|Tidak ada berkas ditemukan di {folder}.|{count} dipilih|Unggah|Rentang tanggal|Menampilkan {count} dari {total} berkas|{count} direktori|{count} direktori|Edit berkas|Ganti nama|Pindahkan berkas|Gambar|Gambar|Video|Dokumen|Dokumen|Lainnya|Direktori baru|Buat direktori di lokasi saat ini.|Nama direktori|Ganti nama direktori|Perbarui nama direktori ini.|Hapus direktori|Hapus direktori?|Anda hanya dapat menghapus direktori kosong. Berkas fisik tidak diubah.|Direktori|Direktori: {name}|Perbarui metadata tampilan berkas. Berkas fisik tidak diubah.|Nama berkas|Judul|Teks alt|Hapus berkas?|Hapus {count} berkas?|berkas ini|{count} berkas|Anda akan menghapus {target} secara permanen. Referensi ke {reference} di item konten juga akan dihapus. Tindakan ini tidak dapat dibatalkan.|berkas ini|Pilih tempat untuk menaruh berkas ini.|Pilih tempat untuk menaruh berkas-berkas ini.|Akar|Memuat direktori...|Tetapkan ulang pemilik berkas|Alihkan kepemilikan "{name}" ke pengguna CMS lain.|Pemilik baru|Silakan pilih pengguna.|Unggahan gagal.|Unggahan gagal. Silakan coba lagi.|Kesalahan jaringan|{name}: melebihi batas {limit}.|{name}: jenis berkas "{type}" tidak diizinkan.|Total ukuran {size} melebihi batas batch {limit}.|{count} berkas diunggah.|Memproses {count} berkas...|Mengunggah {count} berkas...|Jatuhkan berkas di sini, atau klik untuk menelusuri|Hingga {limit} per berkas. Gambar, video, dan dokumen.|Pilih berkas|Pilih logo dari Manajer Berkas|Cari berkas gambar dan pilih satu untuk digunakan sebagai logo situs.|Cari gambar...|Tidak ada gambar ditemukan.|Menampilkan {count} dari {total}|Gunakan gambar yang dipilih|Salin URL|Pindahkan|Tetapkan ulang pemilik|Pindahkan yang dipilih|Hapus yang dipilih|Bersihkan|Muat lagi|Semua jenis|Semua pengguna|Jenis|Diunggah oleh|URL disalin ke clipboard.|Tidak dapat menyalin URL.',
  cs: 'Správce souborů|Nahrávejte a spravujte obrázky, videa a dokumenty.|Soubory|Složky správce souborů|Hledat názvy souborů, titulky nebo alternativní text...|Ve složce {folder} nebyly nalezeny žádné soubory.|Vybráno {count}|Nahrát|Rozsah dat|Zobrazeno {count} z {total} souborů|{count} složka|{count} složek|Upravit soubor|Přejmenovat|Přesunout soubory|Obrázek|Obrázky|Video|Dokument|Dokumenty|Jiné|Nová složka|Vytvořit složku v aktuálním umístění.|Název složky|Přejmenovat složku|Aktualizujte název této složky.|Smazat složku|Smazat složku?|Smazat lze pouze prázdnou složku. Fyzické soubory se nezmění.|Složka|Složka: {name}|Aktualizujte zobrazovaná metadata souboru. Fyzický soubor se nezmění.|Název souboru|Titulek|Alternativní text|Smazat soubor?|Smazat {count} souborů?|tento soubor|{count} souborů|Chystáte se trvale smazat {target}. Odkazy na {reference} v položkách obsahu budou také odstraněny. Tuto akci nelze vrátit zpět.|tyto soubory|Vyberte, kam umístit tento soubor.|Vyberte, kam umístit tyto soubory.|Kořen|Načítání složek...|Znovu přiřadit vlastníka souboru|Přeneste vlastnictví "{name}" na jiného uživatele CMS.|Nový vlastník|Vyberte uživatele.|Nahrávání selhalo.|Nahrávání selhalo. Zkuste to znovu.|Chyba sítě|{name}: překračuje limit {limit}.|{name}: typ souboru "{type}" není povolen.|Celková velikost {size} překračuje dávkový limit {limit}.|Nahráno {count} souborů.|Zpracování {count} souborů...|Nahrávání {count} souborů...|Přetáhněte soubory sem nebo klikněte pro výběr|Až {limit} na soubor. Obrázky, video a dokumenty.|Vybrat soubory|Vybrat logo ze Správce souborů|Vyhledejte obrazové soubory a vyberte jeden jako logo webu.|Hledat obrázky...|Nebyly nalezeny žádné obrázky.|Zobrazeno {count} z {total}|Použít vybraný obrázek|Kopírovat URL|Přesunout|Znovu přiřadit vlastníka|Přesunout vybrané|Smazat vybrané|Vymazat|Načíst další|Všechny typy|Všichni uživatelé|Typ|Nahrál|URL zkopírována do schránky.|URL se nepodařilo zkopírovat.',
  ro: 'Manager de fișiere|Încarcă și gestionează imagini, videoclipuri și documente.|Fișiere|Dosarele managerului de fișiere|Caută nume de fișiere, titluri sau text alt...|Nu s-au găsit fișiere în {folder}.|{count} selectate|Încarcă|Interval de date|Se afișează {count} din {total} fișiere|{count} dosar|{count} dosare|Editează fișierul|Redenumește|Mută fișiere|Imagine|Imagini|Video|Document|Documente|Altele|Dosar nou|Creează un dosar în locația curentă.|Numele dosarului|Redenumește dosarul|Actualizează numele acestui dosar.|Șterge dosar|Ștergi dosarul?|Poți șterge doar un dosar gol. Fișierele fizice nu sunt modificate.|Dosar|Dosar: {name}|Actualizează metadatele de afișare ale fișierului. Fișierul fizic nu este modificat.|Nume fișier|Titlu|Text alt|Ștergi fișierul?|Ștergi {count} fișiere?|acest fișier|{count} fișiere|Ești pe cale să ștergi definitiv {target}. Referințele la {reference} din elementele de conținut vor fi eliminate și ele. Această acțiune nu poate fi anulată.|aceste fișiere|Alege unde să plasezi acest fișier.|Alege unde să plasezi aceste fișiere.|Rădăcină|Se încarcă dosarele...|Reatribuie proprietarul fișierului|Transferă proprietatea asupra "{name}" către un alt utilizator CMS.|Proprietar nou|Selectează un utilizator.|Încărcarea a eșuat.|Încărcarea a eșuat. Încearcă din nou.|Eroare de rețea|{name}: depășește limita de {limit}.|{name}: tipul de fișier "{type}" nu este permis.|Dimensiunea totală {size} depășește limita de lot de {limit}.|S-au încărcat {count} fișiere.|Se procesează {count} fișiere...|Se încarcă {count} fișiere...|Trage fișierele aici sau fă clic pentru a răsfoi|Până la {limit} per fișier. Imagini, video și documente.|Alege fișiere|Alege logo din Managerul de fișiere|Caută fișiere imagine și alege unul ca logo al site-ului.|Caută imagini...|Nu s-au găsit imagini.|Se afișează {count} din {total}|Folosește imaginea selectată|Copiază URL|Mută|Reatribuie proprietarul|Mută selectate|Șterge selectate|Șterge|Încarcă mai multe|Toate tipurile|Toți utilizatorii|Tip|Încărcat de|URL copiat în clipboard.|Nu s-a putut copia URL-ul.',
  el: 'Διαχειριστής αρχείων|Ανεβάστε και διαχειριστείτε εικόνες, βίντεο και έγγραφα.|Αρχεία|Φάκελοι διαχειριστή αρχείων|Αναζήτηση ονομάτων αρχείων, τίτλων ή εναλλακτικού κειμένου...|Δεν βρέθηκαν αρχεία στο {folder}.|Επιλεγμένα {count}|Μεταφόρτωση|Εύρος ημερομηνιών|Εμφάνιση {count} από {total} αρχεία|{count} φάκελος|{count} φάκελοι|Επεξεργασία αρχείου|Μετονομασία|Μετακίνηση αρχείων|Εικόνα|Εικόνες|Βίντεο|Έγγραφο|Έγγραφα|Άλλο|Νέος φάκελος|Δημιουργήστε φάκελο στην τρέχουσα τοποθεσία.|Όνομα φακέλου|Μετονομασία φακέλου|Ενημερώστε το όνομα αυτού του φακέλου.|Διαγραφή φακέλου|Να διαγραφεί ο φάκελος;|Μπορείτε να διαγράψετε μόνο κενό φάκελο. Τα φυσικά αρχεία δεν αλλάζουν.|Φάκελος|Φάκελος: {name}|Ενημερώστε τα μεταδεδομένα εμφάνισης του αρχείου. Το φυσικό αρχείο δεν αλλάζει.|Όνομα αρχείου|Τίτλος|Εναλλακτικό κείμενο|Να διαγραφεί το αρχείο;|Να διαγραφούν {count} αρχεία;|αυτό το αρχείο|{count} αρχεία|Πρόκειται να διαγράψετε οριστικά {target}. Οι αναφορές σε {reference} μέσα σε στοιχεία περιεχομένου θα αφαιρεθούν επίσης. Αυτή η ενέργεια δεν αναιρείται.|αυτά τα αρχεία|Επιλέξτε πού θα τοποθετηθεί αυτό το αρχείο.|Επιλέξτε πού θα τοποθετηθούν αυτά τα αρχεία.|Ρίζα|Φόρτωση φακέλων...|Εκ νέου ανάθεση κατόχου αρχείου|Μεταφέρετε την ιδιοκτησία του "{name}" σε άλλο χρήστη CMS.|Νέος κάτοχος|Επιλέξτε χρήστη.|Η μεταφόρτωση απέτυχε.|Η μεταφόρτωση απέτυχε. Δοκιμάστε ξανά.|Σφάλμα δικτύου|{name}: υπερβαίνει το όριο {limit}.|{name}: ο τύπος αρχείου "{type}" δεν επιτρέπεται.|Το συνολικό μέγεθος {size} υπερβαίνει το όριο παρτίδας {limit}.|Μεταφορτώθηκαν {count} αρχεία.|Επεξεργασία {count} αρχείων...|Μεταφόρτωση {count} αρχείων...|Αποθέστε αρχεία εδώ ή κάντε κλικ για αναζήτηση|Έως {limit} ανά αρχείο. Εικόνες, βίντεο και έγγραφα.|Επιλογή αρχείων|Επιλογή λογότυπου από τον Διαχειριστή αρχείων|Αναζητήστε αρχεία εικόνας και επιλέξτε ένα ως λογότυπο ιστότοπου.|Αναζήτηση εικόνων...|Δεν βρέθηκαν εικόνες.|Εμφάνιση {count} από {total}|Χρήση επιλεγμένης εικόνας|Αντιγραφή URL|Μετακίνηση|Εκ νέου ανάθεση κατόχου|Μετακίνηση επιλεγμένων|Διαγραφή επιλεγμένων|Εκκαθάριση|Φόρτωση περισσότερων|Όλοι οι τύποι|Όλοι οι χρήστες|Τύπος|Μεταφορτώθηκε από|Το URL αντιγράφηκε στο πρόχειρο.|Δεν ήταν δυνατή η αντιγραφή του URL.',
  da: 'Filhåndtering|Upload og administrer billeder, videoer og dokumenter.|Filer|Mapper i filhåndtering|Søg i filnavne, titler eller alt-tekst...|Ingen filer fundet i {folder}.|{count} valgt|Overfør|Datointerval|Viser {count} af {total} filer|{count} mappe|{count} mapper|Rediger fil|Omdøb|Flyt filer|Billede|Billeder|Video|Dokument|Dokumenter|Andet|Ny mappe|Opret en mappe på den aktuelle placering.|Mappenavn|Omdøb mappe|Opdater denne mappes navn.|Slet mappe|Slet mappe?|Du kan kun slette en tom mappe. De fysiske filer ændres ikke.|Mappe|Mappe: {name}|Opdater filens visningsmetadata. Den fysiske fil ændres ikke.|Filnavn|Titel|Alt-tekst|Slet fil?|Slet {count} filer?|denne fil|{count} filer|Du er ved at slette {target} permanent. Referencer til {reference} i indholdselementer fjernes også. Handlingen kan ikke fortrydes.|disse filer|Vælg hvor denne fil skal placeres.|Vælg hvor disse filer skal placeres.|Rod|Indlæser mapper...|Tildel filejer igen|Overfør ejerskab af "{name}" til en anden CMS-bruger.|Ny ejer|Vælg en bruger.|Upload mislykkedes.|Upload mislykkedes. Prøv igen.|Netværksfejl|{name}: overskrider grænsen på {limit}.|{name}: filtypen "{type}" er ikke tilladt.|Samlet størrelse {size} overskrider batchgrænsen på {limit}.|Uploadede {count} fil(er).|Behandler {count} fil(er)...|Uploader {count} fil(er)...|Slip filer her, eller klik for at gennemse|Op til {limit} pr. fil. Billeder, video og dokumenter.|Vælg filer|Vælg logo fra Filhåndtering|Søg efter billedfiler, og vælg en som sitets logo.|Søg billeder...|Ingen billeder fundet.|Viser {count} af {total}|Brug valgt billede|Kopiér URL|Flyt|Tildel ejer igen|Flyt valgte|Slet valgte|Ryd|Indlæs flere|Alle typer|Alle brugere|Type|Uploadet af|URL kopieret til udklipsholderen.|Kunne ikke kopiere URL.',
  sv: 'Filhanterare|Ladda upp och hantera bilder, videor och dokument.|Filer|Filhanterarens mappar|Sök filnamn, titlar eller alt-text...|Inga filer hittades i {folder}.|{count} markerade|Ladda upp|Datumintervall|Visar {count} av {total} filer|{count} mapp|{count} mappar|Redigera fil|Byt namn|Flytta filer|Bild|Bilder|Video|Dokument|Dokument|Annat|Ny mapp|Skapa en mapp på den aktuella platsen.|Mappnamn|Byt namn på mapp|Uppdatera den här mappens namn.|Ta bort mapp|Ta bort mapp?|Du kan bara ta bort en tom mapp. De fysiska filerna ändras inte.|Mapp|Mapp: {name}|Uppdatera filens visningsmetadata. Den fysiska filen ändras inte.|Filnamn|Titel|Alt-text|Ta bort fil?|Ta bort {count} filer?|den här filen|{count} filer|Du håller på att ta bort {target} permanent. Referenser till {reference} i innehållsobjekt tas också bort. Åtgärden kan inte ångras.|dessa filer|Välj var den här filen ska placeras.|Välj var dessa filer ska placeras.|Rot|Läser in mappar...|Tilldela filägare på nytt|Överför ägarskapet för "{name}" till en annan CMS-användare.|Ny ägare|Välj en användare.|Uppladdning misslyckades.|Uppladdning misslyckades. Försök igen.|Nätverksfel|{name}: överskrider gränsen {limit}.|{name}: filtypen "{type}" är inte tillåten.|Total storlek {size} överskrider batchgränsen {limit}.|{count} fil(er) uppladdade.|Bearbetar {count} fil(er)...|Laddar upp {count} fil(er)...|Släpp filer här eller klicka för att bläddra|Upp till {limit} per fil. Bilder, video och dokument.|Välj filer|Välj logotyp från Filhanteraren|Sök bildfiler och välj en som webbplatsens logotyp.|Sök bilder...|Inga bilder hittades.|Visar {count} av {total}|Använd vald bild|Kopiera URL|Flytta|Tilldela ägare på nytt|Flytta markerade|Ta bort markerade|Rensa|Ladda fler|Alla typer|Alla användare|Typ|Uppladdad av|URL kopierad till urklipp.|Kunde inte kopiera URL.',
  nb: 'Filbehandling|Last opp og administrer bilder, videoer og dokumenter.|Filer|Mapper i filbehandling|Søk i filnavn, titler eller alt-tekst...|Ingen filer funnet i {folder}.|{count} valgt|Last opp|Datointervall|Viser {count} av {total} filer|{count} mappe|{count} mapper|Rediger fil|Gi nytt navn|Flytt filer|Bilde|Bilder|Video|Dokument|Dokumenter|Annet|Ny mappe|Opprett en mappe på gjeldende plassering.|Mappenavn|Gi mappen nytt navn|Oppdater navnet på denne mappen.|Slett mappe|Slette mappe?|Du kan bare slette en tom mappe. De fysiske filene endres ikke.|Mappe|Mappe: {name}|Oppdater filens visningsmetadata. Den fysiske filen endres ikke.|Filnavn|Tittel|Alt-tekst|Slette fil?|Slette {count} filer?|denne filen|{count} filer|Du er i ferd med å slette {target} permanent. Referanser til {reference} i innholdselementer blir også fjernet. Denne handlingen kan ikke angres.|disse filene|Velg hvor denne filen skal plasseres.|Velg hvor disse filene skal plasseres.|Rot|Laster mapper...|Tildel fileier på nytt|Overfør eierskap til "{name}" til en annen CMS-bruker.|Ny eier|Velg en bruker.|Opplasting mislyktes.|Opplasting mislyktes. Prøv igjen.|Nettverksfeil|{name}: overskrider grensen på {limit}.|{name}: filtypen "{type}" er ikke tillatt.|Total størrelse {size} overskrider batchgrensen på {limit}.|Lastet opp {count} fil(er).|Behandler {count} fil(er)...|Laster opp {count} fil(er)...|Slipp filer her, eller klikk for å bla gjennom|Opptil {limit} per fil. Bilder, video og dokumenter.|Velg filer|Velg logo fra Filbehandling|Søk etter bildefiler og velg én som nettstedets logo.|Søk bilder...|Ingen bilder funnet.|Viser {count} av {total}|Bruk valgt bilde|Kopier URL|Flytt|Tildel eier på nytt|Flytt valgte|Slett valgte|Tøm|Last inn mer|Alle typer|Alle brukere|Type|Lastet opp av|URL kopiert til utklippstavlen.|Kunne ikke kopiere URL.',
  nn: 'Filhandsaming|Last opp og administrer bilete, videoar og dokument.|Filer|Mapper i filhandsaming|Søk i filnamn, titlar eller alt-tekst...|Ingen filer funne i {folder}.|{count} valde|Last opp|Datointervall|Viser {count} av {total} filer|{count} mappe|{count} mapper|Rediger fil|Gje nytt namn|Flytt filer|Bilete|Bilete|Video|Dokument|Dokument|Anna|Ny mappe|Opprett ei mappe på gjeldande plassering.|Mappenamn|Gje mappa nytt namn|Oppdater namnet på denne mappa.|Slett mappe|Slette mappe?|Du kan berre slette ei tom mappe. Dei fysiske filene blir ikkje endra.|Mappe|Mappe: {name}|Oppdater visingsmetadata for fila. Den fysiske fila blir ikkje endra.|Filnamn|Tittel|Alt-tekst|Slette fil?|Slette {count} filer?|denne fila|{count} filer|Du er i ferd med å slette {target} permanent. Referansar til {reference} i innhaldselement blir òg fjerna. Denne handlinga kan ikkje angrast.|desse filene|Vel kvar denne fila skal plasserast.|Vel kvar desse filene skal plasserast.|Rot|Lastar mapper...|Tildel fileigar på nytt|Overfør eigarskap til "{name}" til ein annan CMS-brukar.|Ny eigar|Vel ein brukar.|Opplasting feila.|Opplasting feila. Prøv igjen.|Nettverksfeil|{name}: overskrid grensa på {limit}.|{name}: filtypen "{type}" er ikkje tillaten.|Samla storleik {size} overskrid batchgrensa på {limit}.|Lasta opp {count} fil(er).|Handsamar {count} fil(er)...|Lastar opp {count} fil(er)...|Slepp filer her, eller klikk for å bla gjennom|Opptil {limit} per fil. Bilete, video og dokument.|Vel filer|Vel logo frå Filhandsaming|Søk etter biletfiler og vel éi som nettstadlogo.|Søk bilete...|Ingen bilete funne.|Viser {count} av {total}|Bruk valt bilete|Kopier URL|Flytt|Tildel eigar på nytt|Flytt valde|Slett valde|Tøm|Last inn meir|Alle typar|Alle brukarar|Type|Lasta opp av|URL kopiert til utklippstavla.|Kunne ikkje kopiere URL.',
  fi: 'Tiedostonhallinta|Lataa ja hallitse kuvia, videoita ja asiakirjoja.|Tiedostot|Tiedostonhallinnan kansiot|Hae tiedostonimiä, otsikoita tai alt-tekstiä...|Kansiosta {folder} ei löytynyt tiedostoja.|{count} valittu|Lataa|Päivämääräväli|Näytetään {count} / {total} tiedostoa|{count} kansio|{count} kansiota|Muokkaa tiedostoa|Nimeä uudelleen|Siirrä tiedostoja|Kuva|Kuvat|Video|Asiakirja|Asiakirjat|Muu|Uusi kansio|Luo kansio nykyiseen sijaintiin.|Kansion nimi|Nimeä kansio uudelleen|Päivitä tämän kansion nimi.|Poista kansio|Poistetaanko kansio?|Voit poistaa vain tyhjän kansion. Fyysisiä tiedostoja ei muuteta.|Kansio|Kansio: {name}|Päivitä tiedoston näyttömetatiedot. Fyysistä tiedostoa ei muuteta.|Tiedostonimi|Otsikko|Alt-teksti|Poistetaanko tiedosto?|Poistetaanko {count} tiedostoa?|tämä tiedosto|{count} tiedostoa|Olet poistamassa pysyvästi kohteen {target}. Viittaukset kohteeseen {reference} sisältökohteissa poistetaan myös. Tätä toimintoa ei voi perua.|nämä tiedostot|Valitse, mihin tämä tiedosto sijoitetaan.|Valitse, mihin nämä tiedostot sijoitetaan.|Juuri|Ladataan kansioita...|Määritä tiedoston omistaja uudelleen|Siirrä kohteen "{name}" omistajuus toiselle CMS-käyttäjälle.|Uusi omistaja|Valitse käyttäjä.|Lataus epäonnistui.|Lataus epäonnistui. Yritä uudelleen.|Verkkovirhe|{name}: ylittää {limit} rajan.|{name}: tiedostotyyppi "{type}" ei ole sallittu.|Kokonaiskoko {size} ylittää erärajauksen {limit}.|Ladattu {count} tiedostoa.|Käsitellään {count} tiedostoa...|Ladataan {count} tiedostoa...|Pudota tiedostot tähän tai selaa napsauttamalla|Enintään {limit} tiedostoa kohti. Kuvat, video ja asiakirjat.|Valitse tiedostot|Valitse logo Tiedostonhallinnasta|Hae kuvatiedostoja ja valitse yksi sivuston logoksi.|Hae kuvia...|Kuvia ei löytynyt.|Näytetään {count} / {total}|Käytä valittua kuvaa|Kopioi URL|Siirrä|Määritä omistaja uudelleen|Siirrä valitut|Poista valitut|Tyhjennä|Lataa lisää|Kaikki tyypit|Kaikki käyttäjät|Tyyppi|Ladannut|URL kopioitu leikepöydälle.|URL-osoitetta ei voitu kopioida.',
  is: 'Skráastjóri|Hladdu upp og stjórnaðu myndum, myndböndum og skjölum.|Skrár|Möppur skráastjóra|Leita í skráarnöfnum, titlum eða alt-texta...|Engar skrár fundust í {folder}.|{count} valið|Hlaða upp|Dagsetningabil|Sýnir {count} af {total} skrám|{count} mappa|{count} möppur|Breyta skrá|Endurnefna|Færa skrár|Mynd|Myndir|Myndband|Skjal|Skjöl|Annað|Ný mappa|Búðu til möppu á núverandi stað.|Nafn möppu|Endurnefna möppu|Uppfærðu nafn þessarar möppu.|Eyða möppu|Eyða möppu?|Þú getur aðeins eytt tómri möppu. Raunverulegu skrárnar breytast ekki.|Mappa|Mappa: {name}|Uppfærðu birtingarlýsigögn skráarinnar. Raunverulega skráin breytist ekki.|Skráarnafn|Titill|Alt-texti|Eyða skrá?|Eyða {count} skrám?|þessari skrá|{count} skrár|Þú ert að fara að eyða {target} varanlega. Tilvísanir í {reference} inni í efnisatriðum verða einnig fjarlægðar. Ekki er hægt að afturkalla þessa aðgerð.|þessum skrám|Veldu hvar á að setja þessa skrá.|Veldu hvar á að setja þessar skrár.|Rót|Hleð möppum...|Endurúthluta eiganda skráar|Flyttu eignarhald á "{name}" til annars CMS-notanda.|Nýr eigandi|Veldu notanda.|Upphleðsla mistókst.|Upphleðsla mistókst. Reyndu aftur.|Netvilla|{name}: fer yfir hámarkið {limit}.|{name}: skráartegundin "{type}" er ekki leyfð.|Heildarstærð {size} fer yfir lotuhámarkið {limit}.|Hlaðið upp {count} skrá(m).|Vinn úr {count} skrá(m)...|Hleð upp {count} skrá(m)...|Slepptu skrám hér eða smelltu til að fletta|Allt að {limit} á hverja skrá. Myndir, myndbönd og skjöl.|Velja skrár|Velja merki úr Skráastjóra|Leitaðu að myndskrám og veldu eina sem merki vefsins.|Leita í myndum...|Engar myndir fundust.|Sýnir {count} af {total}|Nota valda mynd|Afrita URL|Færa|Endurúthluta eiganda|Færa valið|Eyða völdu|Hreinsa|Hlaða meira|Allar tegundir|Allir notendur|Tegund|Hlaðið upp af|URL afritað á klemmuspjald.|Ekki tókst að afrita URL.',
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<FileManagerSource, string> {
  const translations = row.split("|");
  if (translations.length !== FILE_MANAGER_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} file manager translations must have ${FILE_MANAGER_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    FILE_MANAGER_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<FileManagerSource, string>;
}

export const FILE_MANAGER_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<FileManagerSource, string>>;
