import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const GALLERY_MANAGER_SOURCE_STRINGS = [
  "Organize images from the File Manager into named galleries.",
  "Search galleries...",
  "No galleries yet.",
  "Managed in Webshop",
  "Webshop gallery",
  "Create Gallery",
  "Filter by user",
  "Gallery created.",
  "Gallery updated.",
  "Gallery deleted.",
  "Something went wrong.",
  "Create gallery",
  "Pick a name and (optionally) a description. You can add images after creating it.",
  "e.g. Spring 2026 Collection",
  "Edit gallery",
  "Rename the gallery or update its description.",
  "Delete gallery?",
  "This permanently deletes the gallery {name}. The underlying images in the File Manager are not deleted. This cannot be undone.",
  "Type the gallery name to confirm:",
  "Reassign Owner",
  'Assign "{name}" to a different user.',
  "New Owner",
  "Please select a user.",
  "Back to galleries",
  "File Manager - Images",
  "Add selected",
  "Search images...",
  "Newest first",
  "Oldest first",
  "No images.",
  "Gallery contents",
  "Drag images here from the left, or check images and click {action}.",
  "Remove from gallery",
  "This image is already in the gallery.",
  "All selected images are already in the gallery.",
  "{count} image(s) are already in this gallery.",
  "Added {count} image(s).",
  "Image removed from gallery.",
  "Product media",
  "This gallery is managed outside the public Gallery Manager.",
  "Webshop editor is unavailable for this deployment state: {status}.",
  "Existing product media can be edited while expired.",
  "No images are linked to this gallery.",
  "Name must be 120 characters or fewer.",
  "Description must be 1000 characters or fewer.",
  "Something went wrong. Please try again.",
  "Invalid id.",
  "Gallery not found or access denied.",
  "Gallery not found.",
  "Select at least one image.",
  "Cannot add more than 200 images at once.",
  "Image not found in gallery or access denied.",
  "Target user must be a backend user.",
  "Webshop galleries are managed from the Webshop editor.",
  "Only image files can be added to galleries.",
] as const;

type GalleryManagerSource = (typeof GALLERY_MANAGER_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn": `Organizuj slike iz Menadžera fajlova u imenovane galerije.|Pretraži galerije...|Još nema galerija.|Upravljano u Webshopu|Webshop galerija|Kreiraj galeriju|Filtriraj po korisniku|Galerija je kreirana.|Galerija je ažurirana.|Galerija je obrisana.|Nešto je pošlo naopako.|Kreiraj galeriju|Izaberi naziv i opcioni opis. Slike možeš dodati nakon kreiranja.|npr. Prolećna kolekcija 2026|Izmeni galeriju|Preimenuj galeriju ili ažuriraj njen opis.|Obrisati galeriju?|Ovo trajno briše galeriju {name}. Slike u Menadžeru fajlova neće biti obrisane. Ova radnja se ne može opozvati.|Unesi naziv galerije za potvrdu:|Dodeli drugom vlasniku|Dodeli {name} drugom korisniku.|Novi vlasnik|Izaberi korisnika.|Nazad na galerije|Menadžer fajlova - slike|Dodaj izabrano|Pretraži slike...|Najnovije prvo|Najstarije prvo|Nema slika.|Sadržaj galerije|Prevuci slike ovde sa leve strane ili označi slike i klikni {action}.|Ukloni iz galerije|Ova slika je već u galeriji.|Sve izabrane slike su već u galeriji.|{count} slika je već u ovoj galeriji.|Dodato {count} slika.|Slika je uklonjena iz galerije.|Mediji proizvoda|Ovom galerijom se upravlja izvan javnog Menadžera galerija.|Webshop editor nije dostupan za ovo stanje implementacije: {status}.|Postojeći mediji proizvoda mogu se uređivati dok je licenca istekla.|Nijedna slika nije povezana sa ovom galerijom.|Naziv mora imati 120 znakova ili manje.|Opis mora imati 1000 znakova ili manje.|Nešto je pošlo naopako. Pokušaj ponovo.|Neispravan ID.|Galerija nije pronađena ili je pristup odbijen.|Galerija nije pronađena.|Izaberi bar jednu sliku.|Nije moguće dodati više od 200 slika odjednom.|Slika nije pronađena u galeriji ili je pristup odbijen.|Ciljni korisnik mora biti backend korisnik.|Webshop galerijama se upravlja iz Webshop editora.|U galerije se mogu dodati samo slikovni fajlovi.`,
  "sr-Cyrl": `Организуј слике из Менаџера фајлова у именоване галерије.|Претражи галерије...|Још нема галерија.|Управљано у Webshop-у|Webshop галерија|Креирај галерију|Филтрирај по кориснику|Галерија је креирана.|Галерија је ажурирана.|Галерија је обрисана.|Нешто је пошло наопако.|Креирај галерију|Изабери назив и опциони опис. Слике можеш додати након креирања.|нпр. Пролећна колекција 2026|Измени галерију|Преименуј галерију или ажурирај њен опис.|Обрисати галерију?|Ово трајно брише галерију {name}. Слике у Менаџеру фајлова неће бити обрисане. Ова радња се не може опозвати.|Унеси назив галерије за потврду:|Додели другом власнику|Додели {name} другом кориснику.|Нови власник|Изабери корисника.|Назад на галерије|Менаџер фајлова - слике|Додај изабрано|Претражи слике...|Најновије прво|Најстарије прво|Нема слика.|Садржај галерије|Превуци слике овде са леве стране или означи слике и кликни {action}.|Уклони из галерије|Ова слика је већ у галерији.|Све изабране слике су већ у галерији.|{count} слика је већ у овој галерији.|Додато {count} слика.|Слика је уклоњена из галерије.|Медији производа|Овом галеријом се управља изван јавног Менаџера галерија.|Webshop едитор није доступан за ово стање имплементације: {status}.|Постојећи медији производа могу се уређивати док је лиценца истекла.|Ниједна слика није повезана са овом галеријом.|Назив мора имати 120 знакова или мање.|Опис мора имати 1000 знакова или мање.|Нешто је пошло наопако. Покушај поново.|Неисправан ID.|Галерија није пронађена или је приступ одбијен.|Галерија није пронађена.|Изабери бар једну слику.|Није могуће додати више од 200 слика одједном.|Слика није пронађена у галерији или је приступ одбијен.|Циљни корисник мора бити backend корисник.|Webshop галеријама се управља из Webshop едитора.|У галерије се могу додати само сликовни фајлови.`,
  hr: `Organizirajte slike iz Upravitelja datoteka u imenovane galerije.|Pretraži galerije...|Još nema galerija.|Upravljano u Webshopu|Webshop galerija|Stvori galeriju|Filtriraj po korisniku|Galerija je stvorena.|Galerija je ažurirana.|Galerija je izbrisana.|Nešto je pošlo po zlu.|Stvori galeriju|Odaberite naziv i opcionalni opis. Slike možete dodati nakon stvaranja.|npr. Proljetna kolekcija 2026|Uredi galeriju|Preimenujte galeriju ili ažurirajte njezin opis.|Izbrisati galeriju?|Ovo trajno briše galeriju {name}. Slike u Upravitelju datoteka neće biti izbrisane. Ova se radnja ne može poništiti.|Upišite naziv galerije za potvrdu:|Ponovno dodijeli vlasnika|Dodijeli {name} drugom korisniku.|Novi vlasnik|Odaberite korisnika.|Natrag na galerije|Upravitelj datoteka - slike|Dodaj odabrano|Pretraži slike...|Najnovije prvo|Najstarije prvo|Nema slika.|Sadržaj galerije|Povucite slike ovdje s lijeve strane ili označite slike i kliknite {action}.|Ukloni iz galerije|Ova slika već je u galeriji.|Sve odabrane slike već su u galeriji.|{count} slika već je u ovoj galeriji.|Dodano {count} slika.|Slika je uklonjena iz galerije.|Mediji proizvoda|Ovom se galerijom upravlja izvan javnog Upravitelja galerija.|Webshop editor nije dostupan za ovo stanje implementacije: {status}.|Postojeći mediji proizvoda mogu se uređivati dok je licenca istekla.|Nijedna slika nije povezana s ovom galerijom.|Naziv mora imati 120 znakova ili manje.|Opis mora imati 1000 znakova ili manje.|Nešto je pošlo po zlu. Pokušajte ponovno.|Neispravan ID.|Galerija nije pronađena ili je pristup odbijen.|Galerija nije pronađena.|Odaberite barem jednu sliku.|Nije moguće dodati više od 200 slika odjednom.|Slika nije pronađena u galeriji ili je pristup odbijen.|Ciljani korisnik mora biti backend korisnik.|Webshop galerijama upravlja se iz Webshop editora.|U galerije se mogu dodati samo slikovne datoteke.`,
  de: `Organisiere Bilder aus dem Dateimanager in benannte Galerien.|Galerien suchen...|Noch keine Galerien.|Im Webshop verwaltet|Webshop-Galerie|Galerie erstellen|Nach Benutzer filtern|Galerie erstellt.|Galerie aktualisiert.|Galerie gelöscht.|Etwas ist schiefgelaufen.|Galerie erstellen|Wähle einen Namen und optional eine Beschreibung. Bilder kannst du nach dem Erstellen hinzufügen.|z. B. Frühjahrskollektion 2026|Galerie bearbeiten|Benenne die Galerie um oder aktualisiere ihre Beschreibung.|Galerie löschen?|Die Galerie {name} wird dauerhaft gelöscht. Die zugrunde liegenden Bilder im Dateimanager werden nicht gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.|Gib den Galerienamen zur Bestätigung ein:|Besitzer neu zuweisen|Weise {name} einem anderen Benutzer zu.|Neuer Besitzer|Bitte wähle einen Benutzer aus.|Zurück zu Galerien|Dateimanager - Bilder|Ausgewählte hinzufügen|Bilder suchen...|Neueste zuerst|Älteste zuerst|Keine Bilder.|Galerieinhalt|Ziehe Bilder von links hierher oder markiere Bilder und klicke auf {action}.|Aus Galerie entfernen|Dieses Bild ist bereits in der Galerie.|Alle ausgewählten Bilder sind bereits in der Galerie.|{count} Bild(er) sind bereits in dieser Galerie.|{count} Bild(er) hinzugefügt.|Bild aus der Galerie entfernt.|Produktmedien|Diese Galerie wird außerhalb des öffentlichen Galerie-Managers verwaltet.|Der Webshop-Editor ist für diesen Bereitstellungsstatus nicht verfügbar: {status}.|Bestehende Produktmedien können bearbeitet werden, während die Lizenz abgelaufen ist.|Mit dieser Galerie sind keine Bilder verknüpft.|Der Name darf höchstens 120 Zeichen haben.|Die Beschreibung darf höchstens 1000 Zeichen haben.|Etwas ist schiefgelaufen. Bitte versuche es erneut.|Ungültige ID.|Galerie nicht gefunden oder Zugriff verweigert.|Galerie nicht gefunden.|Wähle mindestens ein Bild aus.|Es können nicht mehr als 200 Bilder auf einmal hinzugefügt werden.|Bild nicht in der Galerie gefunden oder Zugriff verweigert.|Der Zielbenutzer muss ein Backend-Benutzer sein.|Webshop-Galerien werden im Webshop-Editor verwaltet.|Nur Bilddateien können zu Galerien hinzugefügt werden.`,
  fr: `Organisez les images du Gestionnaire de fichiers en galeries nommées.|Rechercher des galeries...|Aucune galerie pour l'instant.|Géré dans Webshop|Galerie Webshop|Créer une galerie|Filtrer par utilisateur|Galerie créée.|Galerie mise à jour.|Galerie supprimée.|Une erreur s'est produite.|Créer une galerie|Choisissez un nom et éventuellement une description. Vous pourrez ajouter des images après la création.|p. ex. Collection printemps 2026|Modifier la galerie|Renommez la galerie ou mettez à jour sa description.|Supprimer la galerie ?|Cela supprimera définitivement la galerie {name}. Les images sous-jacentes dans le Gestionnaire de fichiers ne seront pas supprimées. Cette action est irréversible.|Saisissez le nom de la galerie pour confirmer :|Réattribuer le propriétaire|Attribuer {name} à un autre utilisateur.|Nouveau propriétaire|Veuillez sélectionner un utilisateur.|Retour aux galeries|Gestionnaire de fichiers - images|Ajouter la sélection|Rechercher des images...|Plus récentes d'abord|Plus anciennes d'abord|Aucune image.|Contenu de la galerie|Faites glisser des images ici depuis la gauche, ou cochez des images et cliquez sur {action}.|Retirer de la galerie|Cette image est déjà dans la galerie.|Toutes les images sélectionnées sont déjà dans la galerie.|{count} image(s) sont déjà dans cette galerie.|{count} image(s) ajoutée(s).|Image retirée de la galerie.|Médias produit|Cette galerie est gérée en dehors du Gestionnaire de galeries public.|L'éditeur Webshop n'est pas disponible pour cet état de déploiement : {status}.|Les médias produit existants peuvent être modifiés pendant l'expiration.|Aucune image n'est liée à cette galerie.|Le nom doit contenir 120 caractères ou moins.|La description doit contenir 1000 caractères ou moins.|Une erreur s'est produite. Veuillez réessayer.|ID invalide.|Galerie introuvable ou accès refusé.|Galerie introuvable.|Sélectionnez au moins une image.|Impossible d'ajouter plus de 200 images à la fois.|Image introuvable dans la galerie ou accès refusé.|L'utilisateur cible doit être un utilisateur backend.|Les galeries Webshop sont gérées depuis l'éditeur Webshop.|Seuls des fichiers image peuvent être ajoutés aux galeries.`,
  es: `Organiza imágenes del Gestor de archivos en galerías con nombre.|Buscar galerías...|Aún no hay galerías.|Gestionado en Webshop|Galería de Webshop|Crear galería|Filtrar por usuario|Galería creada.|Galería actualizada.|Galería eliminada.|Algo salió mal.|Crear galería|Elige un nombre y, opcionalmente, una descripción. Puedes añadir imágenes después de crearla.|p. ej. Colección primavera 2026|Editar galería|Cambia el nombre de la galería o actualiza su descripción.|¿Eliminar galería?|Esto elimina permanentemente la galería {name}. Las imágenes subyacentes en el Gestor de archivos no se eliminarán. Esta acción no se puede deshacer.|Escribe el nombre de la galería para confirmar:|Reasignar propietario|Asignar {name} a otro usuario.|Nuevo propietario|Selecciona un usuario.|Volver a galerías|Gestor de archivos - imágenes|Añadir seleccionadas|Buscar imágenes...|Más recientes primero|Más antiguas primero|No hay imágenes.|Contenido de la galería|Arrastra imágenes aquí desde la izquierda, o marca imágenes y haz clic en {action}.|Quitar de la galería|Esta imagen ya está en la galería.|Todas las imágenes seleccionadas ya están en la galería.|{count} imagen(es) ya están en esta galería.|Añadidas {count} imagen(es).|Imagen quitada de la galería.|Medios de producto|Esta galería se gestiona fuera del Gestor de galerías público.|El editor de Webshop no está disponible para este estado de despliegue: {status}.|Los medios de producto existentes pueden editarse mientras la licencia está expirada.|No hay imágenes vinculadas a esta galería.|El nombre debe tener 120 caracteres o menos.|La descripción debe tener 1000 caracteres o menos.|Algo salió mal. Inténtalo de nuevo.|ID no válido.|Galería no encontrada o acceso denegado.|Galería no encontrada.|Selecciona al menos una imagen.|No se pueden añadir más de 200 imágenes a la vez.|Imagen no encontrada en la galería o acceso denegado.|El usuario destino debe ser un usuario backend.|Las galerías de Webshop se gestionan desde el editor de Webshop.|Solo se pueden añadir archivos de imagen a las galerías.`,
  it: `Organizza le immagini dal Gestore file in gallerie nominate.|Cerca gallerie...|Nessuna galleria ancora presente.|Gestita in Webshop|Galleria Webshop|Crea galleria|Filtra per utente|Galleria creata.|Galleria aggiornata.|Galleria eliminata.|Si è verificato un errore.|Crea galleria|Scegli un nome e, facoltativamente, una descrizione. Potrai aggiungere immagini dopo la creazione.|es. Collezione primavera 2026|Modifica galleria|Rinomina la galleria o aggiorna la sua descrizione.|Eliminare la galleria?|Questo elimina definitivamente la galleria {name}. Le immagini sottostanti nel Gestore file non vengono eliminate. L'azione non può essere annullata.|Digita il nome della galleria per confermare:|Riassegna proprietario|Assegna {name} a un altro utente.|Nuovo proprietario|Seleziona un utente.|Torna alle gallerie|Gestore file - immagini|Aggiungi selezionate|Cerca immagini...|Più recenti prima|Più vecchie prima|Nessuna immagine.|Contenuto galleria|Trascina qui le immagini da sinistra oppure seleziona immagini e fai clic su {action}.|Rimuovi dalla galleria|Questa immagine è già nella galleria.|Tutte le immagini selezionate sono già nella galleria.|{count} immagine/i sono già in questa galleria.|Aggiunte {count} immagine/i.|Immagine rimossa dalla galleria.|Media prodotto|Questa galleria è gestita fuori dal Gestore gallerie pubblico.|L'editor Webshop non è disponibile per questo stato di distribuzione: {status}.|I media prodotto esistenti possono essere modificati mentre la licenza è scaduta.|Nessuna immagine è collegata a questa galleria.|Il nome deve contenere al massimo 120 caratteri.|La descrizione deve contenere al massimo 1000 caratteri.|Si è verificato un errore. Riprova.|ID non valido.|Galleria non trovata o accesso negato.|Galleria non trovata.|Seleziona almeno un'immagine.|Non puoi aggiungere più di 200 immagini alla volta.|Immagine non trovata nella galleria o accesso negato.|L'utente di destinazione deve essere un utente backend.|Le gallerie Webshop sono gestite dall'editor Webshop.|Alle gallerie possono essere aggiunti solo file immagine.`,
  pt: `Organize imagens do Gestor de ficheiros em galerias com nome.|Pesquisar galerias...|Ainda não há galerias.|Gerido no Webshop|Galeria Webshop|Criar galeria|Filtrar por utilizador|Galeria criada.|Galeria atualizada.|Galeria eliminada.|Algo correu mal.|Criar galeria|Escolha um nome e, opcionalmente, uma descrição. Pode adicionar imagens depois de a criar.|ex. Coleção Primavera 2026|Editar galeria|Altere o nome da galeria ou atualize a descrição.|Eliminar galeria?|Isto elimina permanentemente a galeria {name}. As imagens subjacentes no Gestor de ficheiros não são eliminadas. Esta ação não pode ser anulada.|Escreva o nome da galeria para confirmar:|Reatribuir proprietário|Atribuir {name} a outro utilizador.|Novo proprietário|Selecione um utilizador.|Voltar às galerias|Gestor de ficheiros - imagens|Adicionar selecionadas|Pesquisar imagens...|Mais recentes primeiro|Mais antigas primeiro|Sem imagens.|Conteúdo da galeria|Arraste imagens para aqui a partir da esquerda ou selecione imagens e clique em {action}.|Remover da galeria|Esta imagem já está na galeria.|Todas as imagens selecionadas já estão na galeria.|{count} imagem(ns) já estão nesta galeria.|Adicionadas {count} imagem(ns).|Imagem removida da galeria.|Multimédia do produto|Esta galeria é gerida fora do Gestor de galerias público.|O editor Webshop não está disponível para este estado de implementação: {status}.|Os multimédia de produto existentes podem ser editados enquanto a licença está expirada.|Nenhuma imagem está associada a esta galeria.|O nome deve ter 120 caracteres ou menos.|A descrição deve ter 1000 caracteres ou menos.|Algo correu mal. Tente novamente.|ID inválido.|Galeria não encontrada ou acesso negado.|Galeria não encontrada.|Selecione pelo menos uma imagem.|Não é possível adicionar mais de 200 imagens de uma vez.|Imagem não encontrada na galeria ou acesso negado.|O utilizador de destino tem de ser um utilizador backend.|As galerias Webshop são geridas a partir do editor Webshop.|Só podem ser adicionados ficheiros de imagem às galerias.`,
  "pt-BR": `Organize imagens do Gerenciador de arquivos em galerias nomeadas.|Pesquisar galerias...|Ainda não há galerias.|Gerenciado no Webshop|Galeria do Webshop|Criar galeria|Filtrar por usuário|Galeria criada.|Galeria atualizada.|Galeria excluída.|Algo deu errado.|Criar galeria|Escolha um nome e, opcionalmente, uma descrição. Você pode adicionar imagens depois de criá-la.|ex. Coleção Primavera 2026|Editar galeria|Renomeie a galeria ou atualize sua descrição.|Excluir galeria?|Isso exclui permanentemente a galeria {name}. As imagens originais no Gerenciador de arquivos não serão excluídas. Essa ação não pode ser desfeita.|Digite o nome da galeria para confirmar:|Reatribuir proprietário|Atribuir {name} a outro usuário.|Novo proprietário|Selecione um usuário.|Voltar para galerias|Gerenciador de arquivos - imagens|Adicionar selecionadas|Pesquisar imagens...|Mais recentes primeiro|Mais antigas primeiro|Sem imagens.|Conteúdo da galeria|Arraste imagens da esquerda para cá ou marque imagens e clique em {action}.|Remover da galeria|Esta imagem já está na galeria.|Todas as imagens selecionadas já estão na galeria.|{count} imagem(ns) já estão nesta galeria.|Adicionadas {count} imagem(ns).|Imagem removida da galeria.|Mídia do produto|Esta galeria é gerenciada fora do Gerenciador de galerias público.|O editor do Webshop não está disponível para este estado de implantação: {status}.|As mídias de produto existentes podem ser editadas enquanto a licença estiver expirada.|Nenhuma imagem está vinculada a esta galeria.|O nome deve ter 120 caracteres ou menos.|A descrição deve ter 1000 caracteres ou menos.|Algo deu errado. Tente novamente.|ID inválido.|Galeria não encontrada ou acesso negado.|Galeria não encontrada.|Selecione pelo menos uma imagem.|Não é possível adicionar mais de 200 imagens de uma vez.|Imagem não encontrada na galeria ou acesso negado.|O usuário de destino deve ser um usuário backend.|As galerias do Webshop são gerenciadas pelo editor do Webshop.|Somente arquivos de imagem podem ser adicionados às galerias.`,
  nl: `Orden afbeeldingen uit Bestandsbeheer in benoemde galerijen.|Galerijen zoeken...|Nog geen galerijen.|Beheerd in Webshop|Webshop-galerij|Galerij maken|Filteren op gebruiker|Galerij gemaakt.|Galerij bijgewerkt.|Galerij verwijderd.|Er is iets misgegaan.|Galerij maken|Kies een naam en eventueel een beschrijving. Je kunt na het maken afbeeldingen toevoegen.|bijv. Voorjaarscollectie 2026|Galerij bewerken|Wijzig de naam van de galerij of werk de beschrijving bij.|Galerij verwijderen?|Dit verwijdert de galerij {name} permanent. De onderliggende afbeeldingen in Bestandsbeheer worden niet verwijderd. Deze actie kan niet ongedaan worden gemaakt.|Typ de galerijnaam om te bevestigen:|Eigenaar opnieuw toewijzen|Wijs {name} toe aan een andere gebruiker.|Nieuwe eigenaar|Selecteer een gebruiker.|Terug naar galerijen|Bestandsbeheer - afbeeldingen|Geselecteerde toevoegen|Afbeeldingen zoeken...|Nieuwste eerst|Oudste eerst|Geen afbeeldingen.|Galerij-inhoud|Sleep afbeeldingen hierheen vanaf links, of vink afbeeldingen aan en klik op {action}.|Uit galerij verwijderen|Deze afbeelding staat al in de galerij.|Alle geselecteerde afbeeldingen staan al in de galerij.|{count} afbeelding(en) staan al in deze galerij.|{count} afbeelding(en) toegevoegd.|Afbeelding uit galerij verwijderd.|Productmedia|Deze galerij wordt buiten de openbare Galerijbeheerder beheerd.|De Webshop-editor is niet beschikbaar voor deze implementatiestatus: {status}.|Bestaande productmedia kunnen worden bewerkt terwijl de licentie is verlopen.|Er zijn geen afbeeldingen aan deze galerij gekoppeld.|De naam mag maximaal 120 tekens bevatten.|De beschrijving mag maximaal 1000 tekens bevatten.|Er is iets misgegaan. Probeer het opnieuw.|Ongeldige ID.|Galerij niet gevonden of toegang geweigerd.|Galerij niet gevonden.|Selecteer ten minste één afbeelding.|Er kunnen niet meer dan 200 afbeeldingen tegelijk worden toegevoegd.|Afbeelding niet gevonden in galerij of toegang geweigerd.|De doelgebruiker moet een backend-gebruiker zijn.|Webshop-galerijen worden beheerd vanuit de Webshop-editor.|Alleen afbeeldingsbestanden kunnen aan galerijen worden toegevoegd.`,
  pl: `Organizuj obrazy z Menedżera plików w nazwane galerie.|Szukaj galerii...|Nie ma jeszcze galerii.|Zarządzane w Webshopie|Galeria Webshop|Utwórz galerię|Filtruj według użytkownika|Galeria utworzona.|Galeria zaktualizowana.|Galeria usunięta.|Coś poszło nie tak.|Utwórz galerię|Wybierz nazwę i opcjonalnie opis. Obrazy możesz dodać po utworzeniu.|np. Kolekcja wiosna 2026|Edytuj galerię|Zmień nazwę galerii lub zaktualizuj jej opis.|Usunąć galerię?|To trwale usunie galerię {name}. Bazowe obrazy w Menedżerze plików nie zostaną usunięte. Tej akcji nie można cofnąć.|Wpisz nazwę galerii, aby potwierdzić:|Przypisz właściciela ponownie|Przypisz {name} do innego użytkownika.|Nowy właściciel|Wybierz użytkownika.|Wróć do galerii|Menedżer plików - obrazy|Dodaj zaznaczone|Szukaj obrazów...|Najnowsze najpierw|Najstarsze najpierw|Brak obrazów.|Zawartość galerii|Przeciągnij tutaj obrazy z lewej strony albo zaznacz obrazy i kliknij {action}.|Usuń z galerii|Ten obraz jest już w galerii.|Wszystkie zaznaczone obrazy są już w galerii.|{count} obraz(ów) jest już w tej galerii.|Dodano {count} obraz(ów).|Obraz usunięty z galerii.|Media produktu|Ta galeria jest zarządzana poza publicznym Menedżerem galerii.|Edytor Webshop jest niedostępny dla tego stanu wdrożenia: {status}.|Istniejące media produktu można edytować, gdy licencja wygasła.|Z tą galerią nie są powiązane żadne obrazy.|Nazwa może mieć maksymalnie 120 znaków.|Opis może mieć maksymalnie 1000 znaków.|Coś poszło nie tak. Spróbuj ponownie.|Nieprawidłowy ID.|Nie znaleziono galerii lub odmówiono dostępu.|Nie znaleziono galerii.|Wybierz co najmniej jeden obraz.|Nie można dodać więcej niż 200 obrazów naraz.|Nie znaleziono obrazu w galerii lub odmówiono dostępu.|Użytkownik docelowy musi być użytkownikiem backendu.|Galerie Webshop są zarządzane z edytora Webshop.|Do galerii można dodawać tylko pliki obrazów.`,
  tr: `Dosya Yöneticisi'ndeki görselleri adlandırılmış galeriler halinde düzenleyin.|Galerilerde ara...|Henüz galeri yok.|Webshop'ta yönetiliyor|Webshop galerisi|Galeri oluştur|Kullanıcıya göre filtrele|Galeri oluşturuldu.|Galeri güncellendi.|Galeri silindi.|Bir şeyler ters gitti.|Galeri oluştur|Bir ad ve isteğe bağlı bir açıklama seçin. Oluşturduktan sonra görseller ekleyebilirsiniz.|örn. İlkbahar 2026 Koleksiyonu|Galeriyi düzenle|Galeriyi yeniden adlandırın veya açıklamasını güncelleyin.|Galeri silinsin mi?|Bu, {name} galerisini kalıcı olarak siler. Dosya Yöneticisi'ndeki temel görseller silinmez. Bu işlem geri alınamaz.|Onaylamak için galeri adını yazın:|Sahibi yeniden ata|{name} öğesini farklı bir kullanıcıya ata.|Yeni sahip|Lütfen bir kullanıcı seçin.|Galerilere dön|Dosya Yöneticisi - görseller|Seçilenleri ekle|Görsellerde ara...|En yeniler önce|En eskiler önce|Görsel yok.|Galeri içeriği|Soldaki görselleri buraya sürükleyin veya görselleri işaretleyip {action} düğmesine tıklayın.|Galeriden kaldır|Bu görsel zaten galeride.|Seçilen tüm görseller zaten galeride.|{count} görsel zaten bu galeride.|{count} görsel eklendi.|Görsel galeriden kaldırıldı.|Ürün medyası|Bu galeri genel Galeri Yöneticisi dışında yönetiliyor.|Webshop düzenleyicisi bu dağıtım durumu için kullanılamıyor: {status}.|Lisans süresi dolmuşken mevcut ürün medyası düzenlenebilir.|Bu galeriye bağlı görsel yok.|Ad 120 karakter veya daha kısa olmalıdır.|Açıklama 1000 karakter veya daha kısa olmalıdır.|Bir şeyler ters gitti. Lütfen tekrar deneyin.|Geçersiz kimlik.|Galeri bulunamadı veya erişim reddedildi.|Galeri bulunamadı.|En az bir görsel seçin.|Bir kerede 200'den fazla görsel eklenemez.|Görsel galeride bulunamadı veya erişim reddedildi.|Hedef kullanıcı bir backend kullanıcısı olmalıdır.|Webshop galerileri Webshop düzenleyicisinden yönetilir.|Galerilere yalnızca görsel dosyaları eklenebilir.`,
  mk: `Организирајте слики од Менаџерот на датотеки во именувани галерии.|Пребарај галерии...|Сè уште нема галерии.|Се управува во Webshop|Webshop галерија|Креирај галерија|Филтрирај по корисник|Галеријата е креирана.|Галеријата е ажурирана.|Галеријата е избришана.|Нешто тргна наопаку.|Креирај галерија|Изберете име и опционален опис. Слики може да додадете по креирањето.|на пр. Пролетна колекција 2026|Уреди галерија|Преименувајте ја галеријата или ажурирајте го описот.|Да се избрише галеријата?|Ова трајно ја брише галеријата {name}. Основните слики во Менаџерот на датотеки нема да се избришат. Ова дејство не може да се врати.|Внесете го името на галеријата за потврда:|Пренамени сопственик|Додели {name} на друг корисник.|Нов сопственик|Изберете корисник.|Назад кон галерии|Менаџер на датотеки - слики|Додај избрани|Пребарај слики...|Најнови прво|Најстари прво|Нема слики.|Содржина на галерија|Повлечете слики тука од левата страна или означете слики и кликнете {action}.|Отстрани од галерија|Оваа слика веќе е во галеријата.|Сите избрани слики веќе се во галеријата.|{count} слика(и) веќе се во оваа галерија.|Додадени се {count} слика(и).|Сликата е отстранета од галеријата.|Медиуми на производ|Со оваа галерија се управува надвор од јавниот Менаџер на галерии.|Webshop уредникот не е достапен за оваа состојба на распоредување: {status}.|Постоечките медиуми на производот може да се уредуваат додека лиценцата е истечена.|Нема слики поврзани со оваа галерија.|Името мора да има 120 знаци или помалку.|Описот мора да има 1000 знаци или помалку.|Нешто тргна наопаку. Обидете се повторно.|Невалиден ID.|Галеријата не е пронајдена или пристапот е одбиен.|Галеријата не е пронајдена.|Изберете барем една слика.|Не може да се додадат повеќе од 200 слики одеднаш.|Сликата не е пронајдена во галеријата или пристапот е одбиен.|Целниот корисник мора да биде backend корисник.|Со Webshop галериите се управува од Webshop уредникот.|Во галерии може да се додаваат само датотеки со слики.`,
  bs: `Organizujte slike iz Menadžera datoteka u imenovane galerije.|Pretraži galerije...|Još nema galerija.|Upravlja se u Webshopu|Webshop galerija|Kreiraj galeriju|Filtriraj po korisniku|Galerija je kreirana.|Galerija je ažurirana.|Galerija je obrisana.|Nešto je pošlo naopako.|Kreiraj galeriju|Odaberite naziv i opcionalni opis. Slike možete dodati nakon kreiranja.|npr. Proljetna kolekcija 2026|Uredi galeriju|Preimenujte galeriju ili ažurirajte njen opis.|Obrisati galeriju?|Ovo trajno briše galeriju {name}. Slike u Menadžeru datoteka neće biti obrisane. Ova radnja se ne može poništiti.|Unesite naziv galerije za potvrdu:|Dodijeli drugog vlasnika|Dodijeli {name} drugom korisniku.|Novi vlasnik|Odaberite korisnika.|Nazad na galerije|Menadžer datoteka - slike|Dodaj odabrano|Pretraži slike...|Najnovije prvo|Najstarije prvo|Nema slika.|Sadržaj galerije|Prevucite slike ovdje s lijeve strane ili označite slike i kliknite {action}.|Ukloni iz galerije|Ova slika je već u galeriji.|Sve odabrane slike su već u galeriji.|{count} slika je već u ovoj galeriji.|Dodano {count} slika.|Slika je uklonjena iz galerije.|Mediji proizvoda|Ovom galerijom se upravlja izvan javnog Menadžera galerija.|Webshop editor nije dostupan za ovo stanje implementacije: {status}.|Postojeći mediji proizvoda mogu se uređivati dok je licenca istekla.|Nijedna slika nije povezana s ovom galerijom.|Naziv mora imati 120 znakova ili manje.|Opis mora imati 1000 znakova ili manje.|Nešto je pošlo naopako. Pokušajte ponovo.|Neispravan ID.|Galerija nije pronađena ili je pristup odbijen.|Galerija nije pronađena.|Odaberite barem jednu sliku.|Nije moguće dodati više od 200 slika odjednom.|Slika nije pronađena u galeriji ili je pristup odbijen.|Ciljni korisnik mora biti backend korisnik.|Webshop galerijama se upravlja iz Webshop editora.|U galerije se mogu dodati samo slikovne datoteke.`,
  sl: `Organizirajte slike iz Upravitelja datotek v poimenovane galerije.|Išči galerije...|Galerij še ni.|Upravljano v Webshopu|Webshop galerija|Ustvari galerijo|Filtriraj po uporabniku|Galerija je ustvarjena.|Galerija je posodobljena.|Galerija je izbrisana.|Nekaj je šlo narobe.|Ustvari galerijo|Izberite ime in po želji opis. Slike lahko dodate po ustvarjanju.|npr. Pomladna kolekcija 2026|Uredi galerijo|Preimenujte galerijo ali posodobite njen opis.|Izbrisati galerijo?|To trajno izbriše galerijo {name}. Osnovne slike v Upravitelju datotek ne bodo izbrisane. Tega dejanja ni mogoče razveljaviti.|Za potrditev vnesite ime galerije:|Znova dodeli lastnika|Dodeli {name} drugemu uporabniku.|Novi lastnik|Izberite uporabnika.|Nazaj na galerije|Upravitelj datotek - slike|Dodaj izbrano|Išči slike...|Najnovejše najprej|Najstarejše najprej|Ni slik.|Vsebina galerije|Povlecite slike sem z leve strani ali označite slike in kliknite {action}.|Odstrani iz galerije|Ta slika je že v galeriji.|Vse izbrane slike so že v galeriji.|{count} slik je že v tej galeriji.|Dodano {count} slik.|Slika odstranjena iz galerije.|Mediji izdelka|Ta galerija se upravlja zunaj javnega Upravitelja galerij.|Urejevalnik Webshop ni na voljo za to stanje uvedbe: {status}.|Obstoječe medije izdelka je mogoče urejati, ko je licenca potekla.|S to galerijo ni povezanih slik.|Ime mora imeti 120 znakov ali manj.|Opis mora imeti 1000 znakov ali manj.|Nekaj je šlo narobe. Poskusite znova.|Neveljaven ID.|Galerija ni najdena ali je dostop zavrnjen.|Galerija ni najdena.|Izberite vsaj eno sliko.|Ni mogoče dodati več kot 200 slik hkrati.|Slika ni najdena v galeriji ali je dostop zavrnjen.|Ciljni uporabnik mora biti backend uporabnik.|Webshop galerije se upravljajo iz urejevalnika Webshop.|V galerije je mogoče dodati samo slikovne datoteke.`,
  ru: `Организуйте изображения из файлового менеджера в именованные галереи.|Искать галереи...|Галерей пока нет.|Управляется в Webshop|Галерея Webshop|Создать галерею|Фильтр по пользователю|Галерея создана.|Галерея обновлена.|Галерея удалена.|Что-то пошло не так.|Создать галерею|Выберите имя и, при необходимости, описание. Изображения можно добавить после создания.|например, Весенняя коллекция 2026|Редактировать галерею|Переименуйте галерею или обновите ее описание.|Удалить галерею?|Это навсегда удалит галерею {name}. Исходные изображения в файловом менеджере не будут удалены. Это действие нельзя отменить.|Введите имя галереи для подтверждения:|Переназначить владельца|Назначить {name} другому пользователю.|Новый владелец|Выберите пользователя.|Назад к галереям|Файловый менеджер - изображения|Добавить выбранные|Искать изображения...|Сначала новые|Сначала старые|Изображений нет.|Содержимое галереи|Перетащите изображения сюда слева или отметьте изображения и нажмите {action}.|Удалить из галереи|Это изображение уже находится в галерее.|Все выбранные изображения уже находятся в галерее.|{count} изображение(й) уже есть в этой галерее.|Добавлено {count} изображение(й).|Изображение удалено из галереи.|Медиа продукта|Эта галерея управляется вне публичного менеджера галерей.|Редактор Webshop недоступен для этого состояния развертывания: {status}.|Существующие медиа продукта можно редактировать, пока лицензия истекла.|К этой галерее не привязаны изображения.|Имя должно содержать не более 120 символов.|Описание должно содержать не более 1000 символов.|Что-то пошло не так. Попробуйте еще раз.|Недействительный ID.|Галерея не найдена или доступ запрещен.|Галерея не найдена.|Выберите хотя бы одно изображение.|Нельзя добавить более 200 изображений за раз.|Изображение не найдено в галерее или доступ запрещен.|Целевой пользователь должен быть backend-пользователем.|Галереи Webshop управляются из редактора Webshop.|В галереи можно добавлять только файлы изображений.`,
  hu: `Rendezze a Fájlkezelő képeit elnevezett galériákba.|Galériák keresése...|Még nincsenek galériák.|Webshopban kezelve|Webshop-galéria|Galéria létrehozása|Szűrés felhasználó szerint|Galéria létrehozva.|Galéria frissítve.|Galéria törölve.|Valami hiba történt.|Galéria létrehozása|Válasszon nevet és opcionálisan leírást. A képeket a létrehozás után adhatja hozzá.|pl. 2026 tavaszi kollekció|Galéria szerkesztése|Nevezze át a galériát, vagy frissítse a leírását.|Törli a galériát?|Ez végleg törli a(z) {name} galériát. A Fájlkezelőben lévő alapképek nem törlődnek. A művelet nem vonható vissza.|A megerősítéshez írja be a galéria nevét:|Tulajdonos újrahozzárendelése|A(z) {name} hozzárendelése másik felhasználóhoz.|Új tulajdonos|Válasszon felhasználót.|Vissza a galériákhoz|Fájlkezelő - képek|Kijelöltek hozzáadása|Képek keresése...|Legújabbak előre|Legrégebbiek előre|Nincsenek képek.|Galéria tartalma|Húzza ide a képeket balról, vagy jelöljön ki képeket és kattintson: {action}.|Eltávolítás a galériából|Ez a kép már szerepel a galériában.|Az összes kijelölt kép már szerepel a galériában.|{count} kép már szerepel ebben a galériában.|{count} kép hozzáadva.|Kép eltávolítva a galériából.|Termékmédia|Ezt a galériát a nyilvános Galériakezelőn kívül kezelik.|A Webshop-szerkesztő nem érhető el ehhez a telepítési állapothoz: {status}.|A meglévő termékmédia szerkeszthető lejárt licenc mellett.|Ehhez a galériához nincs kép kapcsolva.|A név legfeljebb 120 karakter lehet.|A leírás legfeljebb 1000 karakter lehet.|Valami hiba történt. Próbálja újra.|Érvénytelen azonosító.|A galéria nem található, vagy a hozzáférés megtagadva.|A galéria nem található.|Válasszon legalább egy képet.|Egyszerre legfeljebb 200 kép adható hozzá.|A kép nem található a galériában, vagy a hozzáférés megtagadva.|A célfelhasználónak backend-felhasználónak kell lennie.|A Webshop-galériák a Webshop-szerkesztőből kezelhetők.|Galériákhoz csak képfájlok adhatók hozzá.`,
  bg: `Организирайте изображения от Файловия мениджър в именувани галерии.|Търсене в галерии...|Все още няма галерии.|Управлява се в Webshop|Webshop галерия|Създай галерия|Филтър по потребител|Галерията е създадена.|Галерията е обновена.|Галерията е изтрита.|Нещо се обърка.|Създай галерия|Изберете име и по желание описание. Можете да добавите изображения след създаването.|напр. Пролетна колекция 2026|Редактирай галерия|Преименувайте галерията или обновете описанието й.|Да се изтрие ли галерията?|Това изтрива завинаги галерията {name}. Основните изображения във Файловия мениджър няма да бъдат изтрити. Това действие не може да се отмени.|Въведете името на галерията за потвърждение:|Преназначи собственик|Назначи {name} на друг потребител.|Нов собственик|Изберете потребител.|Назад към галериите|Файлов мениджър - изображения|Добави избраните|Търсене на изображения...|Най-новите първо|Най-старите първо|Няма изображения.|Съдържание на галерията|Плъзнете изображения тук отляво или маркирайте изображения и натиснете {action}.|Премахни от галерията|Това изображение вече е в галерията.|Всички избрани изображения вече са в галерията.|{count} изображение(я) вече са в тази галерия.|Добавени са {count} изображение(я).|Изображението е премахнато от галерията.|Медия на продукта|Тази галерия се управлява извън публичния Мениджър на галерии.|Редакторът Webshop не е достъпен за това състояние на внедряване: {status}.|Съществуващите медии на продукта могат да се редактират, докато лицензът е изтекъл.|Няма изображения, свързани с тази галерия.|Името трябва да е 120 знака или по-малко.|Описанието трябва да е 1000 знака или по-малко.|Нещо се обърка. Опитайте отново.|Невалиден ID.|Галерията не е намерена или достъпът е отказан.|Галерията не е намерена.|Изберете поне едно изображение.|Не може да се добавят повече от 200 изображения наведнъж.|Изображението не е намерено в галерията или достъпът е отказан.|Целевият потребител трябва да бъде backend потребител.|Webshop галериите се управляват от редактора Webshop.|Към галерии могат да се добавят само файлове с изображения.`,
  ja: `ファイルマネージャーの画像を名前付きギャラリーに整理します。|ギャラリーを検索...|ギャラリーはまだありません。|Webshopで管理|Webshopギャラリー|ギャラリーを作成|ユーザーで絞り込み|ギャラリーを作成しました。|ギャラリーを更新しました。|ギャラリーを削除しました。|問題が発生しました。|ギャラリーを作成|名前と任意の説明を入力します。作成後に画像を追加できます。|例: 2026春コレクション|ギャラリーを編集|ギャラリー名または説明を更新します。|ギャラリーを削除しますか？|ギャラリー {name} を完全に削除します。ファイルマネージャー内の元画像は削除されません。この操作は元に戻せません。|確認のためギャラリー名を入力:|所有者を再割り当て|{name} を別のユーザーに割り当てます。|新しい所有者|ユーザーを選択してください。|ギャラリーに戻る|ファイルマネージャー - 画像|選択項目を追加|画像を検索...|新しい順|古い順|画像はありません。|ギャラリー内容|左から画像をここへドラッグするか、画像をチェックして {action} をクリックします。|ギャラリーから削除|この画像はすでにギャラリーにあります。|選択した画像はすべてすでにギャラリーにあります。|{count} 件の画像はすでにこのギャラリーにあります。|{count} 件の画像を追加しました。|画像をギャラリーから削除しました。|商品メディア|このギャラリーは公開ギャラリーマネージャーの外で管理されています。|このデプロイ状態ではWebshopエディターを利用できません: {status}。|ライセンス期限切れ中も既存の商品メディアは編集できます。|このギャラリーにリンクされた画像はありません。|名前は120文字以内で入力してください。|説明は1000文字以内で入力してください。|問題が発生しました。もう一度お試しください。|無効なIDです。|ギャラリーが見つからないか、アクセスが拒否されました。|ギャラリーが見つかりません。|少なくとも1つの画像を選択してください。|一度に200件を超える画像は追加できません。|画像がギャラリー内に見つからないか、アクセスが拒否されました。|対象ユーザーはバックエンドユーザーである必要があります。|WebshopギャラリーはWebshopエディターから管理されます。|ギャラリーに追加できるのは画像ファイルのみです。`,
  "zh-Hans": `将文件管理器中的图片整理为命名图库。|搜索图库...|还没有图库。|在 Webshop 中管理|Webshop 图库|创建图库|按用户筛选|图库已创建。|图库已更新。|图库已删除。|出现错误。|创建图库|选择名称和可选说明。创建后可以添加图片。|例如：2026 春季系列|编辑图库|重命名图库或更新说明。|删除图库？|这将永久删除图库 {name}。文件管理器中的原始图片不会被删除。此操作无法撤销。|输入图库名称以确认：|重新分配所有者|将 {name} 分配给其他用户。|新所有者|请选择用户。|返回图库|文件管理器 - 图片|添加所选项|搜索图片...|最新优先|最旧优先|没有图片。|图库内容|从左侧拖动图片到这里，或勾选图片并点击 {action}。|从图库移除|此图片已在图库中。|所有选中的图片都已在图库中。|{count} 张图片已在此图库中。|已添加 {count} 张图片。|图片已从图库移除。|商品媒体|此图库在公共图库管理器之外管理。|当前部署状态无法使用 Webshop 编辑器：{status}。|许可证过期时仍可编辑现有商品媒体。|没有图片链接到此图库。|名称必须为 120 个字符或更少。|说明必须为 1000 个字符或更少。|出现错误。请重试。|无效 ID。|找不到图库或访问被拒绝。|找不到图库。|请至少选择一张图片。|一次不能添加超过 200 张图片。|在图库中找不到图片或访问被拒绝。|目标用户必须是后端用户。|Webshop 图库从 Webshop 编辑器管理。|只能向图库添加图片文件。`,
  "zh-Hant": `將檔案管理器中的圖片整理為命名圖庫。|搜尋圖庫...|尚無圖庫。|在 Webshop 中管理|Webshop 圖庫|建立圖庫|依使用者篩選|圖庫已建立。|圖庫已更新。|圖庫已刪除。|發生錯誤。|建立圖庫|選擇名稱和選填描述。建立後可以加入圖片。|例如：2026 春季系列|編輯圖庫|重新命名圖庫或更新描述。|刪除圖庫？|這會永久刪除圖庫 {name}。檔案管理器中的原始圖片不會被刪除。此動作無法復原。|輸入圖庫名稱以確認：|重新指派擁有者|將 {name} 指派給其他使用者。|新擁有者|請選擇使用者。|返回圖庫|檔案管理器 - 圖片|加入所選項目|搜尋圖片...|最新優先|最舊優先|沒有圖片。|圖庫內容|從左側拖曳圖片到這裡，或勾選圖片並點擊 {action}。|從圖庫移除|此圖片已在圖庫中。|所有選取的圖片都已在圖庫中。|{count} 張圖片已在此圖庫中。|已加入 {count} 張圖片。|圖片已從圖庫移除。|商品媒體|此圖庫在公開圖庫管理器之外管理。|目前部署狀態無法使用 Webshop 編輯器：{status}。|授權過期時仍可編輯既有商品媒體。|沒有圖片連結到此圖庫。|名稱必須為 120 個字元或更少。|描述必須為 1000 個字元或更少。|發生錯誤。請再試一次。|無效 ID。|找不到圖庫或拒絕存取。|找不到圖庫。|請至少選擇一張圖片。|一次不能加入超過 200 張圖片。|在圖庫中找不到圖片或拒絕存取。|目標使用者必須是後端使用者。|Webshop 圖庫從 Webshop 編輯器管理。|只能將圖片檔案加入圖庫。`,
  ar: `نظّم الصور من مدير الملفات في معارض مسماة.|البحث في المعارض...|لا توجد معارض بعد.|تدار في Webshop|معرض Webshop|إنشاء معرض|تصفية حسب المستخدم|تم إنشاء المعرض.|تم تحديث المعرض.|تم حذف المعرض.|حدث خطأ ما.|إنشاء معرض|اختر اسما ووصفا اختياريا. يمكنك إضافة الصور بعد إنشائه.|مثال: مجموعة ربيع 2026|تحرير المعرض|أعد تسمية المعرض أو حدّث وصفه.|حذف المعرض؟|سيؤدي هذا إلى حذف المعرض {name} نهائيا. لن يتم حذف الصور الأصلية في مدير الملفات. لا يمكن التراجع عن هذا الإجراء.|اكتب اسم المعرض للتأكيد:|إعادة تعيين المالك|تعيين {name} إلى مستخدم آخر.|مالك جديد|يرجى اختيار مستخدم.|العودة إلى المعارض|مدير الملفات - الصور|إضافة المحدد|البحث عن الصور...|الأحدث أولا|الأقدم أولا|لا توجد صور.|محتويات المعرض|اسحب الصور هنا من اليسار، أو حدد الصور وانقر على {action}.|إزالة من المعرض|هذه الصورة موجودة بالفعل في المعرض.|كل الصور المحددة موجودة بالفعل في المعرض.|{count} صورة موجودة بالفعل في هذا المعرض.|تمت إضافة {count} صورة.|تمت إزالة الصورة من المعرض.|وسائط المنتج|تتم إدارة هذا المعرض خارج مدير المعارض العام.|محرر Webshop غير متاح لحالة النشر هذه: {status}.|يمكن تحرير وسائط المنتج الحالية أثناء انتهاء صلاحية الترخيص.|لا توجد صور مرتبطة بهذا المعرض.|يجب أن يكون الاسم 120 حرفا أو أقل.|يجب أن يكون الوصف 1000 حرف أو أقل.|حدث خطأ ما. يرجى المحاولة مرة أخرى.|معرّف غير صالح.|لم يتم العثور على المعرض أو تم رفض الوصول.|لم يتم العثور على المعرض.|حدد صورة واحدة على الأقل.|لا يمكن إضافة أكثر من 200 صورة دفعة واحدة.|لم يتم العثور على الصورة في المعرض أو تم رفض الوصول.|يجب أن يكون المستخدم الهدف مستخدم backend.|تتم إدارة معارض Webshop من محرر Webshop.|يمكن إضافة ملفات الصور فقط إلى المعارض.`,
  id: `Atur gambar dari Pengelola file ke dalam galeri bernama.|Cari galeri...|Belum ada galeri.|Dikelola di Webshop|Galeri Webshop|Buat galeri|Filter berdasarkan pengguna|Galeri dibuat.|Galeri diperbarui.|Galeri dihapus.|Terjadi kesalahan.|Buat galeri|Pilih nama dan deskripsi opsional. Anda dapat menambahkan gambar setelah membuatnya.|mis. Koleksi Musim Semi 2026|Edit galeri|Ganti nama galeri atau perbarui deskripsinya.|Hapus galeri?|Ini akan menghapus galeri {name} secara permanen. Gambar asli di Pengelola file tidak dihapus. Tindakan ini tidak dapat dibatalkan.|Ketik nama galeri untuk mengonfirmasi:|Tetapkan ulang pemilik|Tetapkan {name} ke pengguna lain.|Pemilik baru|Silakan pilih pengguna.|Kembali ke galeri|Pengelola file - gambar|Tambah yang dipilih|Cari gambar...|Terbaru dulu|Terlama dulu|Tidak ada gambar.|Isi galeri|Seret gambar dari kiri ke sini, atau centang gambar dan klik {action}.|Hapus dari galeri|Gambar ini sudah ada di galeri.|Semua gambar yang dipilih sudah ada di galeri.|{count} gambar sudah ada di galeri ini.|Menambahkan {count} gambar.|Gambar dihapus dari galeri.|Media produk|Galeri ini dikelola di luar Pengelola galeri publik.|Editor Webshop tidak tersedia untuk status deployment ini: {status}.|Media produk yang ada dapat diedit saat lisensi kedaluwarsa.|Tidak ada gambar yang tertaut ke galeri ini.|Nama harus 120 karakter atau kurang.|Deskripsi harus 1000 karakter atau kurang.|Terjadi kesalahan. Silakan coba lagi.|ID tidak valid.|Galeri tidak ditemukan atau akses ditolak.|Galeri tidak ditemukan.|Pilih setidaknya satu gambar.|Tidak dapat menambahkan lebih dari 200 gambar sekaligus.|Gambar tidak ditemukan di galeri atau akses ditolak.|Pengguna tujuan harus merupakan pengguna backend.|Galeri Webshop dikelola dari editor Webshop.|Hanya file gambar yang dapat ditambahkan ke galeri.`,
  cs: `Uspořádejte obrázky ze Správce souborů do pojmenovaných galerií.|Hledat galerie...|Zatím nejsou žádné galerie.|Spravováno ve Webshopu|Galerie Webshopu|Vytvořit galerii|Filtrovat podle uživatele|Galerie vytvořena.|Galerie aktualizována.|Galerie smazána.|Něco se pokazilo.|Vytvořit galerii|Zvolte název a volitelně popis. Obrázky můžete přidat po vytvoření.|např. Jarní kolekce 2026|Upravit galerii|Přejmenujte galerii nebo aktualizujte její popis.|Smazat galerii?|Tím trvale smažete galerii {name}. Podkladové obrázky ve Správci souborů nebudou smazány. Tuto akci nelze vrátit zpět.|Pro potvrzení zadejte název galerie:|Znovu přiřadit vlastníka|Přiřadit {name} jinému uživateli.|Nový vlastník|Vyberte uživatele.|Zpět na galerie|Správce souborů - obrázky|Přidat vybrané|Hledat obrázky...|Nejnovější první|Nejstarší první|Žádné obrázky.|Obsah galerie|Přetáhněte sem obrázky zleva nebo zaškrtněte obrázky a klikněte na {action}.|Odebrat z galerie|Tento obrázek už je v galerii.|Všechny vybrané obrázky už jsou v galerii.|{count} obrázků už je v této galerii.|Přidáno {count} obrázků.|Obrázek odebrán z galerie.|Média produktu|Tato galerie je spravována mimo veřejného Správce galerií.|Editor Webshopu není pro tento stav nasazení dostupný: {status}.|Stávající média produktu lze upravovat i při vypršené licenci.|K této galerii nejsou připojeny žádné obrázky.|Název musí mít 120 znaků nebo méně.|Popis musí mít 1000 znaků nebo méně.|Něco se pokazilo. Zkuste to prosím znovu.|Neplatné ID.|Galerie nebyla nalezena nebo byl odepřen přístup.|Galerie nebyla nalezena.|Vyberte alespoň jeden obrázek.|Nelze přidat více než 200 obrázků najednou.|Obrázek nebyl v galerii nalezen nebo byl odepřen přístup.|Cílový uživatel musí být backendový uživatel.|Galerie Webshopu jsou spravovány z editoru Webshopu.|Do galerií lze přidávat pouze obrazové soubory.`,
  ro: `Organizează imaginile din Managerul de fișiere în galerii numite.|Caută galerii...|Nu există încă galerii.|Gestionată în Webshop|Galerie Webshop|Creează galerie|Filtrează după utilizator|Galeria a fost creată.|Galeria a fost actualizată.|Galeria a fost ștearsă.|Ceva nu a mers bine.|Creează galerie|Alege un nume și, opțional, o descriere. Poți adăuga imagini după creare.|ex. Colecția primăvară 2026|Editează galeria|Redenumește galeria sau actualizează descrierea.|Ștergi galeria?|Aceasta va șterge definitiv galeria {name}. Imaginile de bază din Managerul de fișiere nu sunt șterse. Acțiunea nu poate fi anulată.|Tastează numele galeriei pentru confirmare:|Reatribuie proprietarul|Atribuie {name} unui alt utilizator.|Proprietar nou|Selectează un utilizator.|Înapoi la galerii|Manager de fișiere - imagini|Adaugă selectate|Caută imagini...|Cele mai noi primele|Cele mai vechi primele|Nu există imagini.|Conținutul galeriei|Trage imagini aici din stânga sau bifează imagini și fă clic pe {action}.|Elimină din galerie|Această imagine este deja în galerie.|Toate imaginile selectate sunt deja în galerie.|{count} imagine(i) sunt deja în această galerie.|S-au adăugat {count} imagine(i).|Imagine eliminată din galerie.|Media produsului|Această galerie este gestionată în afara Managerului public de galerii.|Editorul Webshop nu este disponibil pentru această stare de implementare: {status}.|Media produsului existente pot fi editate cât timp licența este expirată.|Nu există imagini legate de această galerie.|Numele trebuie să aibă cel mult 120 de caractere.|Descrierea trebuie să aibă cel mult 1000 de caractere.|Ceva nu a mers bine. Încearcă din nou.|ID nevalid.|Galeria nu a fost găsită sau accesul a fost refuzat.|Galeria nu a fost găsită.|Selectează cel puțin o imagine.|Nu se pot adăuga mai mult de 200 de imagini odată.|Imaginea nu a fost găsită în galerie sau accesul a fost refuzat.|Utilizatorul țintă trebuie să fie utilizator backend.|Galeriile Webshop sunt gestionate din editorul Webshop.|În galerii pot fi adăugate doar fișiere imagine.`,
  el: `Οργανώστε εικόνες από τον Διαχειριστή αρχείων σε ονομασμένες γκαλερί.|Αναζήτηση γκαλερί...|Δεν υπάρχουν ακόμη γκαλερί.|Διαχείριση στο Webshop|Γκαλερί Webshop|Δημιουργία γκαλερί|Φιλτράρισμα ανά χρήστη|Η γκαλερί δημιουργήθηκε.|Η γκαλερί ενημερώθηκε.|Η γκαλερί διαγράφηκε.|Κάτι πήγε στραβά.|Δημιουργία γκαλερί|Επιλέξτε όνομα και προαιρετικά περιγραφή. Μπορείτε να προσθέσετε εικόνες μετά τη δημιουργία.|π.χ. Ανοιξιάτικη συλλογή 2026|Επεξεργασία γκαλερί|Μετονομάστε τη γκαλερί ή ενημερώστε την περιγραφή της.|Να διαγραφεί η γκαλερί;|Αυτό θα διαγράψει οριστικά τη γκαλερί {name}. Οι υποκείμενες εικόνες στον Διαχειριστή αρχείων δεν θα διαγραφούν. Αυτή η ενέργεια δεν αναιρείται.|Πληκτρολογήστε το όνομα της γκαλερί για επιβεβαίωση:|Εκ νέου ανάθεση κατόχου|Ανάθεση του {name} σε διαφορετικό χρήστη.|Νέος κάτοχος|Επιλέξτε χρήστη.|Πίσω στις γκαλερί|Διαχειριστής αρχείων - εικόνες|Προσθήκη επιλεγμένων|Αναζήτηση εικόνων...|Νεότερα πρώτα|Παλαιότερα πρώτα|Δεν υπάρχουν εικόνες.|Περιεχόμενο γκαλερί|Σύρετε εικόνες εδώ από αριστερά ή επιλέξτε εικόνες και κάντε κλικ στο {action}.|Αφαίρεση από τη γκαλερί|Αυτή η εικόνα υπάρχει ήδη στη γκαλερί.|Όλες οι επιλεγμένες εικόνες υπάρχουν ήδη στη γκαλερί.|{count} εικόνα/ες υπάρχουν ήδη σε αυτήν τη γκαλερί.|Προστέθηκαν {count} εικόνα/ες.|Η εικόνα αφαιρέθηκε από τη γκαλερί.|Πολυμέσα προϊόντος|Αυτή η γκαλερί διαχειρίζεται εκτός του δημόσιου Διαχειριστή γκαλερί.|Ο επεξεργαστής Webshop δεν είναι διαθέσιμος για αυτήν την κατάσταση ανάπτυξης: {status}.|Τα υπάρχοντα πολυμέσα προϊόντος μπορούν να επεξεργαστούν ενώ η άδεια έχει λήξει.|Δεν υπάρχουν εικόνες συνδεδεμένες με αυτήν τη γκαλερί.|Το όνομα πρέπει να έχει 120 χαρακτήρες ή λιγότερους.|Η περιγραφή πρέπει να έχει 1000 χαρακτήρες ή λιγότερους.|Κάτι πήγε στραβά. Δοκιμάστε ξανά.|Μη έγκυρο ID.|Η γκαλερί δεν βρέθηκε ή η πρόσβαση απορρίφθηκε.|Η γκαλερί δεν βρέθηκε.|Επιλέξτε τουλάχιστον μία εικόνα.|Δεν είναι δυνατή η προσθήκη περισσότερων από 200 εικόνων ταυτόχρονα.|Η εικόνα δεν βρέθηκε στη γκαλερί ή η πρόσβαση απορρίφθηκε.|Ο χρήστης προορισμού πρέπει να είναι χρήστης backend.|Οι γκαλερί Webshop διαχειρίζονται από τον επεξεργαστή Webshop.|Στις γκαλερί μπορούν να προστεθούν μόνο αρχεία εικόνας.`,
  da: `Organiser billeder fra Filhåndtering i navngivne gallerier.|Søg i gallerier...|Ingen gallerier endnu.|Administreres i Webshop|Webshop-galleri|Opret galleri|Filtrer efter bruger|Galleri oprettet.|Galleri opdateret.|Galleri slettet.|Noget gik galt.|Opret galleri|Vælg et navn og eventuelt en beskrivelse. Du kan tilføje billeder efter oprettelsen.|f.eks. Forårskollektion 2026|Rediger galleri|Omdøb galleriet eller opdater beskrivelsen.|Slet galleri?|Dette sletter galleriet {name} permanent. De underliggende billeder i Filhåndtering slettes ikke. Handlingen kan ikke fortrydes.|Skriv galleriets navn for at bekræfte:|Tildel ejer igen|Tildel {name} til en anden bruger.|Ny ejer|Vælg en bruger.|Tilbage til gallerier|Filhåndtering - billeder|Tilføj valgte|Søg billeder...|Nyeste først|Ældste først|Ingen billeder.|Galleriindhold|Træk billeder hertil fra venstre, eller markér billeder og klik på {action}.|Fjern fra galleri|Dette billede er allerede i galleriet.|Alle valgte billeder er allerede i galleriet.|{count} billede(r) er allerede i dette galleri.|Tilføjet {count} billede(r).|Billede fjernet fra galleri.|Produktmedier|Dette galleri administreres uden for den offentlige galleriadministrator.|Webshop-editoren er ikke tilgængelig for denne udrulningstilstand: {status}.|Eksisterende produktmedier kan redigeres, mens licensen er udløbet.|Der er ingen billeder knyttet til dette galleri.|Navnet må højst være 120 tegn.|Beskrivelsen må højst være 1000 tegn.|Noget gik galt. Prøv igen.|Ugyldigt ID.|Galleri ikke fundet eller adgang nægtet.|Galleri ikke fundet.|Vælg mindst ét billede.|Der kan ikke tilføjes mere end 200 billeder ad gangen.|Billede ikke fundet i galleri eller adgang nægtet.|Målbrugeren skal være en backend-bruger.|Webshop-gallerier administreres fra Webshop-editoren.|Kun billedfiler kan føjes til gallerier.`,
  sv: `Organisera bilder från Filhanteraren i namngivna gallerier.|Sök gallerier...|Det finns inga gallerier än.|Hanteras i Webshop|Webshop-galleri|Skapa galleri|Filtrera efter användare|Galleri skapat.|Galleri uppdaterat.|Galleri borttaget.|Något gick fel.|Skapa galleri|Välj ett namn och eventuellt en beskrivning. Du kan lägga till bilder efter att det har skapats.|t.ex. Vårkollektion 2026|Redigera galleri|Byt namn på galleriet eller uppdatera beskrivningen.|Ta bort galleri?|Detta tar bort galleriet {name} permanent. De underliggande bilderna i Filhanteraren tas inte bort. Åtgärden kan inte ångras.|Skriv galleriets namn för att bekräfta:|Tilldela ägare på nytt|Tilldela {name} till en annan användare.|Ny ägare|Välj en användare.|Tillbaka till gallerier|Filhanteraren - bilder|Lägg till markerade|Sök bilder...|Nyaste först|Äldsta först|Inga bilder.|Galleriinnehåll|Dra bilder hit från vänster eller markera bilder och klicka på {action}.|Ta bort från galleri|Den här bilden finns redan i galleriet.|Alla markerade bilder finns redan i galleriet.|{count} bild(er) finns redan i detta galleri.|Lade till {count} bild(er).|Bilden togs bort från galleriet.|Produktmedia|Detta galleri hanteras utanför den offentliga gallerihanteraren.|Webshop-redigeraren är inte tillgänglig för denna distributionsstatus: {status}.|Befintliga produktmedier kan redigeras medan licensen har löpt ut.|Inga bilder är kopplade till detta galleri.|Namnet får vara högst 120 tecken.|Beskrivningen får vara högst 1000 tecken.|Något gick fel. Försök igen.|Ogiltigt ID.|Galleriet hittades inte eller åtkomst nekades.|Galleriet hittades inte.|Välj minst en bild.|Det går inte att lägga till fler än 200 bilder samtidigt.|Bilden hittades inte i galleriet eller åtkomst nekades.|Målanvändaren måste vara en backend-användare.|Webshop-gallerier hanteras från Webshop-redigeraren.|Endast bildfiler kan läggas till i gallerier.`,
  nb: `Organiser bilder fra Filbehandling i navngitte gallerier.|Søk i gallerier...|Ingen gallerier ennå.|Administreres i Webshop|Webshop-galleri|Opprett galleri|Filtrer etter bruker|Galleri opprettet.|Galleri oppdatert.|Galleri slettet.|Noe gikk galt.|Opprett galleri|Velg et navn og eventuelt en beskrivelse. Du kan legge til bilder etter at det er opprettet.|f.eks. Vårkolleksjon 2026|Rediger galleri|Gi galleriet nytt navn eller oppdater beskrivelsen.|Slette galleri?|Dette sletter galleriet {name} permanent. De underliggende bildene i Filbehandling slettes ikke. Denne handlingen kan ikke angres.|Skriv inn gallerinavnet for å bekrefte:|Tildel eier på nytt|Tildel {name} til en annen bruker.|Ny eier|Velg en bruker.|Tilbake til gallerier|Filbehandling - bilder|Legg til valgte|Søk bilder...|Nyeste først|Eldste først|Ingen bilder.|Galleriinnhold|Dra bilder hit fra venstre, eller merk bilder og klikk på {action}.|Fjern fra galleri|Dette bildet finnes allerede i galleriet.|Alle valgte bilder finnes allerede i galleriet.|{count} bilde(r) finnes allerede i dette galleriet.|La til {count} bilde(r).|Bildet er fjernet fra galleriet.|Produktmedier|Dette galleriet administreres utenfor den offentlige Galleriadministratoren.|Webshop-redigereren er ikke tilgjengelig for denne distribusjonsstatusen: {status}.|Eksisterende produktmedier kan redigeres mens lisensen er utløpt.|Ingen bilder er knyttet til dette galleriet.|Navnet må være 120 tegn eller færre.|Beskrivelsen må være 1000 tegn eller færre.|Noe gikk galt. Prøv igjen.|Ugyldig ID.|Galleriet ble ikke funnet eller tilgang ble nektet.|Galleriet ble ikke funnet.|Velg minst ett bilde.|Kan ikke legge til mer enn 200 bilder om gangen.|Bildet ble ikke funnet i galleriet eller tilgang ble nektet.|Målbrukeren må være en backend-bruker.|Webshop-gallerier administreres fra Webshop-redigereren.|Bare bildefiler kan legges til i gallerier.`,
  nn: `Organiser bilete frå Filhandsaming i namngjevne galleri.|Søk i galleri...|Ingen galleri enno.|Administrert i Webshop|Webshop-galleri|Opprett galleri|Filtrer etter brukar|Galleri oppretta.|Galleri oppdatert.|Galleri sletta.|Noko gjekk gale.|Opprett galleri|Vel eit namn og eventuelt ei skildring. Du kan leggje til bilete etter oppretting.|t.d. Vårkolleksjon 2026|Rediger galleri|Gje galleriet nytt namn eller oppdater skildringa.|Slette galleri?|Dette slettar galleriet {name} permanent. Dei underliggjande bileta i Filhandsaming blir ikkje sletta. Handlinga kan ikkje angrast.|Skriv inn gallerinamnet for å stadfeste:|Tildel eigar på nytt|Tildel {name} til ein annan brukar.|Ny eigar|Vel ein brukar.|Tilbake til galleri|Filhandsaming - bilete|Legg til valde|Søk bilete...|Nyaste først|Eldste først|Ingen bilete.|Galleriinnhald|Dra bilete hit frå venstre, eller merk bilete og klikk på {action}.|Fjern frå galleri|Dette biletet finst allereie i galleriet.|Alle valde bilete finst allereie i galleriet.|{count} bilete finst allereie i dette galleriet.|La til {count} bilete.|Biletet er fjerna frå galleriet.|Produktmedium|Dette galleriet blir administrert utanfor den offentlege galleriadministrasjonen.|Webshop-redigeraren er ikkje tilgjengeleg for denne distribusjonsstatusen: {status}.|Eksisterande produktmedium kan redigerast medan lisensen er utgått.|Ingen bilete er knytte til dette galleriet.|Namnet må vere 120 teikn eller færre.|Skildringa må vere 1000 teikn eller færre.|Noko gjekk gale. Prøv igjen.|Ugyldig ID.|Galleriet vart ikkje funne eller tilgang vart nekta.|Galleriet vart ikkje funne.|Vel minst eitt bilete.|Kan ikkje leggje til meir enn 200 bilete om gongen.|Biletet vart ikkje funne i galleriet eller tilgang vart nekta.|Målbrukaren må vere ein backend-brukar.|Webshop-galleri blir administrerte frå Webshop-redigeraren.|Berre biletfiler kan leggjast til i galleri.`,
  fi: `Järjestä Tiedostonhallinnan kuvat nimetyiksi gallerioiksi.|Hae gallerioita...|Gallerioita ei vielä ole.|Hallitaan Webshopissa|Webshop-galleria|Luo galleria|Suodata käyttäjän mukaan|Galleria luotu.|Galleria päivitetty.|Galleria poistettu.|Jokin meni pieleen.|Luo galleria|Valitse nimi ja halutessasi kuvaus. Voit lisätä kuvia luomisen jälkeen.|esim. Kevätmallisto 2026|Muokkaa galleriaa|Nimeä galleria uudelleen tai päivitä sen kuvaus.|Poistetaanko galleria?|Tämä poistaa gallerian {name} pysyvästi. Tiedostonhallinnan alkuperäisiä kuvia ei poisteta. Toimintoa ei voi kumota.|Vahvista kirjoittamalla gallerian nimi:|Määritä omistaja uudelleen|Määritä {name} toiselle käyttäjälle.|Uusi omistaja|Valitse käyttäjä.|Takaisin gallerioihin|Tiedostonhallinta - kuvat|Lisää valitut|Hae kuvia...|Uusimmat ensin|Vanhimmat ensin|Ei kuvia.|Gallerian sisältö|Vedä kuvia tähän vasemmalta tai valitse kuvia ja napsauta {action}.|Poista galleriasta|Tämä kuva on jo galleriassa.|Kaikki valitut kuvat ovat jo galleriassa.|{count} kuvaa on jo tässä galleriassa.|Lisätty {count} kuvaa.|Kuva poistettu galleriasta.|Tuotemedia|Tätä galleriaa hallitaan julkisen gallerianhallinnan ulkopuolella.|Webshop-editori ei ole käytettävissä tässä käyttöönoton tilassa: {status}.|Olemassa olevaa tuotemediaa voi muokata lisenssin vanhennuttua.|Tähän galleriaan ei ole linkitetty kuvia.|Nimessä saa olla enintään 120 merkkiä.|Kuvauksessa saa olla enintään 1000 merkkiä.|Jokin meni pieleen. Yritä uudelleen.|Virheellinen ID.|Galleriaa ei löydy tai käyttö estetty.|Galleriaa ei löydy.|Valitse vähintään yksi kuva.|Kerralla ei voi lisätä yli 200 kuvaa.|Kuvaa ei löydy galleriasta tai käyttö estetty.|Kohdekäyttäjän on oltava backend-käyttäjä.|Webshop-gallerioita hallitaan Webshop-editorista.|Gallerioihin voi lisätä vain kuvatiedostoja.`,
  is: `Skipuleggðu myndir úr Skráastjóra í nafngreind gallerí.|Leita í galleríum...|Engin gallerí enn.|Stjórnað í Webshop|Webshop-gallerí|Búa til gallerí|Sía eftir notanda|Gallerí búið til.|Gallerí uppfært.|Galleríi eytt.|Eitthvað fór úrskeiðis.|Búa til gallerí|Veldu nafn og valfrjálsa lýsingu. Þú getur bætt myndum við eftir stofnun.|t.d. Vorlína 2026|Breyta galleríi|Endurnefndu galleríið eða uppfærðu lýsinguna.|Eyða galleríi?|Þetta eyðir galleríinu {name} varanlega. Undirliggjandi myndum í Skráastjóra verður ekki eytt. Ekki er hægt að afturkalla þessa aðgerð.|Sláðu inn nafn gallerísins til staðfestingar:|Endurúthluta eiganda|Úthluta {name} til annars notanda.|Nýr eigandi|Veldu notanda.|Til baka í gallerí|Skráastjóri - myndir|Bæta völdu við|Leita í myndum...|Nýjast fyrst|Elst fyrst|Engar myndir.|Innihald gallerís|Dragðu myndir hingað frá vinstri eða merktu myndir og smelltu á {action}.|Fjarlægja úr galleríi|Þessi mynd er þegar í galleríinu.|Allar valdar myndir eru þegar í galleríinu.|{count} mynd(ir) eru þegar í þessu galleríi.|Bætt við {count} mynd(um).|Mynd fjarlægð úr galleríi.|Vörumiðlar|Þessu galleríi er stjórnað utan opinbera gallerístjórans.|Webshop-ritillinn er ekki tiltækur fyrir þessa dreifingarstöðu: {status}.|Hægt er að breyta núverandi vörumiðlum meðan leyfið er útrunnið.|Engar myndir eru tengdar þessu galleríi.|Nafnið má vera 120 stafir eða færri.|Lýsingin má vera 1000 stafir eða færri.|Eitthvað fór úrskeiðis. Reyndu aftur.|Ógilt ID.|Gallerí fannst ekki eða aðgangi var hafnað.|Gallerí fannst ekki.|Veldu að minnsta kosti eina mynd.|Ekki er hægt að bæta við meira en 200 myndum í einu.|Mynd fannst ekki í galleríinu eða aðgangi var hafnað.|Marknotandinn verður að vera backend-notandi.|Webshop-galleríum er stjórnað úr Webshop-ritlinum.|Aðeins er hægt að bæta myndskrám við gallerí.`,
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<GalleryManagerSource, string> {
  const translations = row.split("|");
  if (translations.length !== GALLERY_MANAGER_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} gallery manager translations must have ${GALLERY_MANAGER_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    GALLERY_MANAGER_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<GalleryManagerSource, string>;
}

export const GALLERY_MANAGER_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<GalleryManagerSource, string>>;
