import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const GLOBAL_SETTINGS_OPTION_SOURCE_STRINGS = [
  "Default",
  "Dark",
  "Minimal",
  "Corporate",
  "Cyberpunk",
  "Elegant",
  "Forest",
  "Ocean",
  "Sunset",
  "Pastel",
  "Luxury",
  "Obsidian",
  "Midnight",
  "Aurora",
  "Nordic",
  "Graphite",
  "Paper",
  "Sage",
  "Terracotta",
  "Lavender",
  "Monochrome",
  "Terminal",
  "Rose",
  "High Contrast",
  "Full Width",
  "Contained",
  "Narrow",
  "Wide",
  "Ultra Wide",
  "System",
  "Sans",
  "Serif",
  "Mono",
  "Display",
  "Humanist",
  "None",
  "Small",
  "Medium",
  "Large",
  "Rounded",
  "Soft",
  "Strong",
  "Full-bleed Builder",
  "Full bleed builder",
  "Framed content",
  "Contained Builder",
  "Framed Builder",
  "Landing Mode",
  "List",
  "Cards",
  "Magazine Grid",
  "Compact Archive",
  "Featured First",
  "Inline",
  "Stacked",
  "Eyebrow",
  "Compact",
  "Top",
  "After Title",
  "Hero",
  "Lead",
  "Subtle",
  "Callout",
  "After Content",
  "Before Content",
  "Title Inline",
  "Header Actions",
  "Footer Actions",
  "Dynamic alias: OpenAI may change the underlying model, pricing, and behavior. Use a pinned model for predictable CMS costs.",
  "VERY HIGH COST: pro reasoning can bill hidden reasoning as output. Avoid for routine CMS text.",
  "Reasoning model: hidden reasoning may use output tokens. Keep the token cap low and watch billing.",
  "Premium model: use only for difficult edits where lower-cost models are not enough.",
  "Higher-cost model: reserve for complex prompts, not routine short suggestions.",
  "Higher-cost model: use when smaller Mistral models are not enough.",
  "Premium model: check usage costs before enabling for frequent editor actions.",
] as const;

type OptionSource = (typeof GLOBAL_SETTINGS_OPTION_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "Podrazumevano|Tamno|Minimalno|Korporativno|Sajberpank|Elegantno|Šuma|Okean|Zalazak|Pastelno|Luksuzno|Opsidijan|Ponoć|Aurora|Nordijsko|Grafit|Papir|Žalfija|Terakota|Lavanda|Monohromno|Terminal|Ruža|Visok kontrast|Puna širina|Ograničeno|Usko|Široko|Ultra široko|Sistemski|Bez serif|Serif|Mono|Displej|Humanistički|Nema|Malo|Srednje|Veliko|Zaobljeno|Meko|Jako|Builder preko cele širine|Builder preko cele širine|Uokviren sadržaj|Ograničeni builder|Uokvireni builder|Landing režim|Lista|Kartice|Magazinska mreža|Kompaktna arhiva|Istaknuto prvo|U liniji|Naslagano|Nadnaslov|Kompaktno|Vrh|Posle naslova|Hero sekcija|Uvodno|Suptilno|Istaknuto|Posle sadržaja|Pre sadržaja|U liniji sa naslovom|Akcije u zaglavlju|Akcije u podnožju|Dinamički alias: OpenAI može promeniti osnovni model, cenu i ponašanje. Koristi fiksirani model za predvidljive CMS troškove.|VEOMA VISOK TROŠAK: pro rasuđivanje može naplatiti skriveno rasuđivanje kao izlaz. Izbegavaj za rutinski CMS tekst.|Model za rasuđivanje: skriveno rasuđivanje može trošiti izlazne tokene. Drži limit tokena nisko i prati naplatu.|Premium model: koristi samo za teške izmene kada jeftiniji modeli nisu dovoljni.|Skuplji model: čuvaj za složene promptove, ne za rutinske kratke predloge.|Skuplji model: koristi kada manji Mistral modeli nisu dovoljni.|Premium model: proveri troškove korišćenja pre uključivanja za česte akcije u editoru.",
  "sr-Cyrl":
    "Подразумевано|Тамно|Минимално|Корпоративно|Сајберпанк|Елегантно|Шума|Океан|Залазак|Пастелно|Луксузно|Опсидијан|Поноћ|Аурора|Нордијско|Графит|Папир|Жалфија|Теракота|Лаванда|Монохромно|Терминал|Ружа|Висок контраст|Пуна ширина|Ограничено|Уско|Широко|Ултра широко|Системски|Без серифа|Сериф|Моно|Дисплеј|Хуманистички|Нема|Мало|Средње|Велико|Заобљено|Меко|Јако|Builder преко целе ширине|Builder преко целе ширине|Уоквирен садржај|Ограничени builder|Уоквирени builder|Landing режим|Листа|Картице|Магазинска мрежа|Компактна архива|Истакнуто прво|У линији|Наслагано|Наднаслов|Компактно|Врх|После наслова|Херо секција|Уводно|Суптилно|Истакнуто|После садржаја|Пре садржаја|У линији са насловом|Акције у заглављу|Акције у подножју|Динамички alias: OpenAI може променити основни модел, цену и понашање. Користи фиксирани модел за предвидљиве CMS трошкове.|ВЕОМА ВИСОК ТРОШАК: pro расуђивање може наплатити скривено расуђивање као излаз. Избегавај за рутински CMS текст.|Модел за расуђивање: скривено расуђивање може трошити излазне токене. Држи лимит токена ниско и прати наплату.|Premium модел: користи само за тешке измене када јефтинији модели нису довољни.|Скупљи модел: чувај за сложене prompt-ове, не за рутинске кратке предлоге.|Скупљи модел: користи када мањи Mistral модели нису довољни.|Premium модел: провери трошкове коришћења пре укључивања за честе акције у едитору.",
  hr: "Zadano|Tamno|Minimalno|Korporativno|Cyberpunk|Elegantno|Šuma|Ocean|Zalazak|Pastelno|Luksuzno|Opsidijan|Ponoć|Aurora|Nordijsko|Grafit|Papir|Kadulja|Terakota|Lavanda|Monokromatsko|Terminal|Ruža|Visoki kontrast|Puna širina|Ograničeno|Usko|Široko|Ultra široko|Sustav|Bez serif|Serif|Mono|Prikazni|Humanistički|Nema|Malo|Srednje|Veliko|Zaobljeno|Meko|Jako|Builder pune širine|Builder pune širine|Uokviren sadržaj|Ograničeni builder|Uokvireni builder|Landing način|Popis|Kartice|Magazinska mreža|Kompaktna arhiva|Istaknuto prvo|U liniji|Složeno|Nadnaslov|Kompaktno|Vrh|Nakon naslova|Hero|Uvodno|Suptilno|Istaknuto|Nakon sadržaja|Prije sadržaja|U liniji s naslovom|Akcije u zaglavlju|Akcije u podnožju|Dinamički alias: OpenAI može promijeniti osnovni model, cijene i ponašanje. Koristite fiksirani model za predvidljive CMS troškove.|VRLO VISOK TROŠAK: pro rasuđivanje može naplatiti skriveno rasuđivanje kao izlaz. Izbjegavajte za rutinski CMS tekst.|Model za rasuđivanje: skriveno rasuđivanje može trošiti izlazne tokene. Držite limit tokena nisko i pratite naplatu.|Premium model: koristite samo za teške izmjene kada jeftiniji modeli nisu dovoljni.|Skuplji model: čuvajte za složene promptove, ne za rutinske kratke prijedloge.|Skuplji model: koristite kada manji Mistral modeli nisu dovoljni.|Premium model: provjerite troškove korištenja prije uključivanja za česte radnje u editoru.",
  de: "Standard|Dunkel|Minimal|Corporate|Cyberpunk|Elegant|Wald|Ozean|Sonnenuntergang|Pastell|Luxus|Obsidian|Mitternacht|Aurora|Nordisch|Graphit|Papier|Salbei|Terrakotta|Lavendel|Monochrom|Terminal|Rose|Hoher Kontrast|Volle Breite|Begrenzt|Schmal|Breit|Ultrabreit|System|Sans|Serif|Mono|Display|Humanistisch|Keine|Klein|Mittel|Groß|Abgerundet|Weich|Stark|Full-Bleed-Builder|Full-Bleed-Builder|Gerahmter Inhalt|Begrenzter Builder|Gerahmter Builder|Landing-Modus|Liste|Karten|Magazinraster|Kompaktes Archiv|Hervorgehoben zuerst|Inline|Gestapelt|Überzeile|Kompakt|Oben|Nach Titel|Hero|Lead|Dezent|Callout|Nach Inhalt|Vor Inhalt|Inline im Titel|Header-Aktionen|Footer-Aktionen|Dynamischer Alias: OpenAI kann das zugrunde liegende Modell, Preise und Verhalten ändern. Nutze ein festes Modell für planbare CMS-Kosten.|SEHR HOHE KOSTEN: Pro-Reasoning kann verstecktes Reasoning als Output abrechnen. Für routinemäßige CMS-Texte vermeiden.|Reasoning-Modell: verstecktes Reasoning kann Output-Tokens verbrauchen. Halte das Token-Limit niedrig und beobachte die Abrechnung.|Premium-Modell: nur für schwierige Bearbeitungen nutzen, bei denen günstigere Modelle nicht ausreichen.|Teureres Modell: für komplexe Prompts reservieren, nicht für routinemäßige kurze Vorschläge.|Teureres Modell: nutzen, wenn kleinere Mistral-Modelle nicht ausreichen.|Premium-Modell: prüfe Nutzungskosten, bevor es für häufige Editor-Aktionen aktiviert wird.",
  fr: "Par défaut|Sombre|Minimal|Corporate|Cyberpunk|Élégant|Forêt|Océan|Coucher de soleil|Pastel|Luxe|Obsidienne|Minuit|Aurore|Nordique|Graphite|Papier|Sauge|Terre cuite|Lavande|Monochrome|Terminal|Rose|Contraste élevé|Pleine largeur|Contenu cadré|Étroit|Large|Ultra large|Système|Sans serif|Serif|Mono|Affichage|Humaniste|Aucun|Petit|Moyen|Grand|Arrondi|Doux|Fort|Builder pleine largeur|Builder pleine largeur|Contenu encadré|Builder contenu|Builder encadré|Mode landing|Liste|Cartes|Grille magazine|Archive compacte|Mis en avant d'abord|Inline|Empilé|Surtitre|Compact|Haut|Après le titre|Hero|Chapeau|Discret|Encadré|Après le contenu|Avant le contenu|Titre en ligne|Actions d'en-tête|Actions de pied de page|Alias dynamique : OpenAI peut modifier le modèle sous-jacent, les tarifs et le comportement. Utilisez un modèle épinglé pour des coûts CMS prévisibles.|COÛT TRÈS ÉLEVÉ : le raisonnement pro peut facturer le raisonnement masqué comme sortie. À éviter pour le texte CMS courant.|Modèle de raisonnement : le raisonnement masqué peut utiliser des tokens de sortie. Gardez le plafond de tokens bas et surveillez la facturation.|Modèle premium : à utiliser seulement pour les modifications difficiles quand les modèles moins coûteux ne suffisent pas.|Modèle plus coûteux : réservez-le aux prompts complexes, pas aux courtes suggestions courantes.|Modèle plus coûteux : utilisez-le quand les plus petits modèles Mistral ne suffisent pas.|Modèle premium : vérifiez les coûts d'utilisation avant de l'activer pour des actions fréquentes dans l'éditeur.",
  es: "Predeterminado|Oscuro|Mínimo|Corporativo|Cyberpunk|Elegante|Bosque|Océano|Atardecer|Pastel|Lujo|Obsidiana|Medianoche|Aurora|Nórdico|Grafito|Papel|Salvia|Terracota|Lavanda|Monocromo|Terminal|Rosa|Alto contraste|Ancho completo|Contenido contenido|Estrecho|Ancho|Ultra ancho|Sistema|Sans|Serif|Mono|Display|Humanista|Ninguno|Pequeño|Medio|Grande|Redondeado|Suave|Fuerte|Builder de ancho completo|Builder de ancho completo|Contenido enmarcado|Builder contenido|Builder enmarcado|Modo landing|Lista|Tarjetas|Cuadrícula de revista|Archivo compacto|Destacado primero|En línea|Apilado|Antetítulo|Compacto|Arriba|Después del título|Hero|Entradilla|Sutil|Llamada destacada|Después del contenido|Antes del contenido|Título en línea|Acciones del encabezado|Acciones del pie|Alias dinámico: OpenAI puede cambiar el modelo subyacente, los precios y el comportamiento. Usa un modelo fijado para costes CMS predecibles.|COSTE MUY ALTO: el razonamiento pro puede facturar razonamiento oculto como salida. Evítalo para texto CMS rutinario.|Modelo de razonamiento: el razonamiento oculto puede usar tokens de salida. Mantén bajo el límite de tokens y vigila la facturación.|Modelo premium: úsalo solo para ediciones difíciles cuando los modelos de menor coste no sean suficientes.|Modelo de mayor coste: resérvalo para prompts complejos, no para sugerencias cortas rutinarias.|Modelo de mayor coste: úsalo cuando los modelos Mistral más pequeños no sean suficientes.|Modelo premium: revisa los costes de uso antes de activarlo para acciones frecuentes del editor.",
  it: "Predefinito|Scuro|Minimale|Corporate|Cyberpunk|Elegante|Foresta|Oceano|Tramonto|Pastello|Lusso|Ossidiana|Mezzanotte|Aurora|Nordico|Grafite|Carta|Salvia|Terracotta|Lavanda|Monocromatico|Terminale|Rosa|Alto contrasto|Larghezza piena|Contenuto contenuto|Stretto|Ampio|Ultra ampio|Sistema|Sans|Serif|Mono|Display|Umanista|Nessuno|Piccolo|Medio|Grande|Arrotondato|Morbido|Forte|Builder a larghezza piena|Builder a larghezza piena|Contenuto incorniciato|Builder contenuto|Builder incorniciato|Modalità landing|Elenco|Schede|Griglia magazine|Archivio compatto|In evidenza per primo|Inline|Impilato|Occhiello|Compatto|In alto|Dopo il titolo|Hero|Lead|Discreto|Richiamo|Dopo il contenuto|Prima del contenuto|Titolo inline|Azioni intestazione|Azioni piè di pagina|Alias dinamico: OpenAI può cambiare il modello sottostante, i prezzi e il comportamento. Usa un modello fissato per costi CMS prevedibili.|COSTO MOLTO ALTO: il reasoning pro può fatturare il reasoning nascosto come output. Evitalo per testo CMS di routine.|Modello di reasoning: il reasoning nascosto può usare token di output. Mantieni basso il limite di token e controlla la fatturazione.|Modello premium: usalo solo per modifiche difficili quando i modelli meno costosi non bastano.|Modello più costoso: riservalo a prompt complessi, non a brevi suggerimenti di routine.|Modello più costoso: usalo quando i modelli Mistral più piccoli non bastano.|Modello premium: controlla i costi d'uso prima di abilitarlo per azioni frequenti nell'editor.",
  pt: "Predefinido|Escuro|Minimal|Corporativo|Cyberpunk|Elegante|Floresta|Oceano|Pôr do sol|Pastel|Luxo|Obsidiana|Meia-noite|Aurora|Nórdico|Grafite|Papel|Sálvia|Terracota|Lavanda|Monocromático|Terminal|Rosa|Alto contraste|Largura total|Contido|Estreito|Largo|Ultra largo|Sistema|Sans|Serif|Mono|Display|Humanista|Nenhum|Pequeno|Médio|Grande|Arredondado|Suave|Forte|Builder de largura total|Builder de largura total|Conteúdo emoldurado|Builder contido|Builder emoldurado|Modo landing|Lista|Cartões|Grelha de revista|Arquivo compacto|Destaque primeiro|Em linha|Empilhado|Sobretítulo|Compacto|Topo|Após o título|Hero|Lead|Subtil|Destaque|Após o conteúdo|Antes do conteúdo|Título em linha|Ações do cabeçalho|Ações do rodapé|Alias dinâmico: a OpenAI pode alterar o modelo subjacente, os preços e o comportamento. Use um modelo fixo para custos CMS previsíveis.|CUSTO MUITO ELEVADO: o raciocínio pro pode faturar raciocínio oculto como saída. Evite para texto CMS rotineiro.|Modelo de raciocínio: raciocínio oculto pode usar tokens de saída. Mantenha o limite de tokens baixo e acompanhe a faturação.|Modelo premium: use apenas para edições difíceis quando modelos mais baratos não forem suficientes.|Modelo de custo mais elevado: reserve para prompts complexos, não para sugestões curtas rotineiras.|Modelo de custo mais elevado: use quando modelos Mistral menores não forem suficientes.|Modelo premium: verifique os custos de utilização antes de ativar para ações frequentes no editor.",
  "pt-BR":
    "Padrão|Escuro|Mínimo|Corporativo|Cyberpunk|Elegante|Floresta|Oceano|Pôr do sol|Pastel|Luxo|Obsidiana|Meia-noite|Aurora|Nórdico|Grafite|Papel|Sálvia|Terracota|Lavanda|Monocromático|Terminal|Rosa|Alto contraste|Largura total|Contido|Estreito|Amplo|Ultra amplo|Sistema|Sans|Serif|Mono|Display|Humanista|Nenhum|Pequeno|Médio|Grande|Arredondado|Suave|Forte|Builder de largura total|Builder de largura total|Conteúdo emoldurado|Builder contido|Builder emoldurado|Modo landing|Lista|Cards|Grade de revista|Arquivo compacto|Destaque primeiro|Inline|Empilhado|Chamada superior|Compacto|Topo|Após o título|Hero|Lead|Sutil|Chamada|Após o conteúdo|Antes do conteúdo|Título inline|Ações do cabeçalho|Ações do rodapé|Alias dinâmico: a OpenAI pode alterar o modelo subjacente, os preços e o comportamento. Use um modelo fixo para custos CMS previsíveis.|CUSTO MUITO ALTO: o raciocínio pro pode cobrar raciocínio oculto como saída. Evite para texto CMS rotineiro.|Modelo de raciocínio: raciocínio oculto pode usar tokens de saída. Mantenha o limite de tokens baixo e monitore a cobrança.|Modelo premium: use apenas para edições difíceis quando modelos mais baratos não forem suficientes.|Modelo de custo mais alto: reserve para prompts complexos, não para sugestões curtas rotineiras.|Modelo de custo mais alto: use quando modelos Mistral menores não forem suficientes.|Modelo premium: verifique os custos de uso antes de ativar para ações frequentes no editor.",
  nl: "Standaard|Donker|Minimaal|Zakelijk|Cyberpunk|Elegant|Bos|Oceaan|Zonsondergang|Pastel|Luxe|Obsidiaan|Middernacht|Aurora|Noords|Grafiet|Papier|Salie|Terracotta|Lavendel|Monochroom|Terminal|Roos|Hoog contrast|Volledige breedte|Ingeperkt|Smal|Breed|Ultrabreed|Systeem|Sans|Serif|Mono|Display|Humanistisch|Geen|Klein|Middel|Groot|Afgerond|Zacht|Sterk|Builder over volle breedte|Builder over volle breedte|Ingekaderde inhoud|Ingeperkte builder|Ingekaderde builder|Landingmodus|Lijst|Kaarten|Magazineraster|Compact archief|Uitgelicht eerst|Inline|Gestapeld|Bovenkop|Compact|Boven|Na titel|Hero|Lead|Subtiel|Callout|Na inhoud|Voor inhoud|Titel inline|Headeracties|Footeracties|Dynamische alias: OpenAI kan het onderliggende model, de prijzen en het gedrag wijzigen. Gebruik een vastgepind model voor voorspelbare CMS-kosten.|ZEER HOGE KOSTEN: pro-reasoning kan verborgen reasoning als output factureren. Vermijd dit voor routinematige CMS-tekst.|Reasoningmodel: verborgen reasoning kan outputtokens gebruiken. Houd de tokenlimiet laag en bewaak de facturatie.|Premium model: alleen gebruiken voor moeilijke bewerkingen waar goedkopere modellen niet volstaan.|Duurder model: reserveer voor complexe prompts, niet voor korte routinesuggesties.|Duurder model: gebruik wanneer kleinere Mistral-modellen niet volstaan.|Premium model: controleer gebruikskosten voordat je dit activeert voor frequente editoracties.",
  pl: "Domyślny|Ciemny|Minimalny|Korporacyjny|Cyberpunk|Elegancki|Las|Ocean|Zachód słońca|Pastelowy|Luksusowy|Obsydian|Północ|Aurora|Nordycki|Grafit|Papier|Szałwia|Terakota|Lawenda|Monochromatyczny|Terminal|Róża|Wysoki kontrast|Pełna szerokość|Ograniczony|Wąski|Szeroki|Ultraszeroki|Systemowy|Sans|Serif|Mono|Display|Humanistyczny|Brak|Mały|Średni|Duży|Zaokrąglony|Miękki|Mocny|Builder pełnej szerokości|Builder pełnej szerokości|Treść w ramce|Builder ograniczony|Builder w ramce|Tryb landing|Lista|Karty|Siatka magazynowa|Kompaktowe archiwum|Najpierw wyróżnione|Inline|Ułożone|Nadtytuł|Kompaktowy|Góra|Po tytule|Hero|Lead|Subtelne|Wyróżnienie|Po treści|Przed treścią|Tytuł inline|Akcje nagłówka|Akcje stopki|Dynamiczny alias: OpenAI może zmienić bazowy model, ceny i zachowanie. Użyj przypiętego modelu dla przewidywalnych kosztów CMS.|BARDZO WYSOKI KOSZT: rozumowanie pro może rozliczać ukryte rozumowanie jako wyjście. Unikaj przy rutynowym tekście CMS.|Model rozumowania: ukryte rozumowanie może używać tokenów wyjściowych. Utrzymuj niski limit tokenów i pilnuj rozliczeń.|Model premium: używaj tylko do trudnych edycji, gdy tańsze modele nie wystarczają.|Droższy model: rezerwuj dla złożonych promptów, nie dla rutynowych krótkich sugestii.|Droższy model: używaj, gdy mniejsze modele Mistral nie wystarczają.|Model premium: sprawdź koszty użycia przed włączeniem dla częstych akcji edytora.",
  tr: "Varsayılan|Koyu|Minimal|Kurumsal|Cyberpunk|Zarif|Orman|Okyanus|Gün batımı|Pastel|Lüks|Obsidyen|Gece yarısı|Aurora|Nordik|Grafit|Kağıt|Adaçayı|Terracotta|Lavanta|Tek renk|Terminal|Gül|Yüksek kontrast|Tam genişlik|Sınırlı|Dar|Geniş|Ultra geniş|Sistem|Sans|Serif|Mono|Display|Humanist|Yok|Küçük|Orta|Büyük|Yuvarlatılmış|Yumuşak|Güçlü|Tam genişlik builder|Tam genişlik builder|Çerçeveli içerik|Sınırlı builder|Çerçeveli builder|Landing modu|Liste|Kartlar|Dergi ızgarası|Kompakt arşiv|Öne çıkan önce|Satır içi|Yığılmış|Üst başlık|Kompakt|Üst|Başlıktan sonra|Hero|Giriş|Sade|Vurgu|İçerikten sonra|İçerikten önce|Başlık satır içi|Başlık eylemleri|Alt bilgi eylemleri|Dinamik alias: OpenAI temel modeli, fiyatları ve davranışı değiştirebilir. Öngörülebilir CMS maliyetleri için sabitlenmiş bir model kullanın.|ÇOK YÜKSEK MALİYET: pro akıl yürütme gizli akıl yürütmeyi çıktı olarak faturalandırabilir. Rutin CMS metni için kaçının.|Akıl yürütme modeli: gizli akıl yürütme çıktı tokenları kullanabilir. Token sınırını düşük tutun ve faturayı izleyin.|Premium model: daha düşük maliyetli modeller yetmediğinde yalnızca zor düzenlemeler için kullanın.|Daha yüksek maliyetli model: rutin kısa öneriler için değil, karmaşık promptlar için ayırın.|Daha yüksek maliyetli model: daha küçük Mistral modelleri yetmediğinde kullanın.|Premium model: sık editör işlemleri için etkinleştirmeden önce kullanım maliyetlerini kontrol edin.",
  mk: "Стандардно|Темно|Минимално|Корпоративно|Cyberpunk|Елегантно|Шума|Океан|Зајдисонце|Пастелно|Луксузно|Опсидијан|Полноќ|Аурора|Нордиско|Графит|Хартија|Жалфија|Теракота|Лаванда|Монохроматско|Терминал|Роза|Висок контраст|Пуна ширина|Ограничено|Тесно|Широко|Ултра широко|Системски|Без сериф|Сериф|Моно|Дисплеј|Хуманистички|Нема|Мало|Средно|Големо|Заоблено|Меко|Силно|Builder преку цела ширина|Builder преку цела ширина|Врамена содржина|Ограничен builder|Врамен builder|Landing режим|Листа|Картички|Магазинска мрежа|Компактна архива|Истакнато прво|Во линија|Наслагано|Наднаслов|Компактно|Врв|По насловот|Hero|Вовед|Суптилно|Истакнато|По содржината|Пред содржината|Во линија со насловот|Акции во заглавие|Акции во подножје|Динамички alias: OpenAI може да го промени основниот модел, цените и однесувањето. Користете фиксиран модел за предвидливи CMS трошоци.|МНОГУ ВИСОК ТРОШОК: pro расудување може да наплати скриено расудување како излез. Избегнувајте за рутински CMS текст.|Модел за расудување: скриеното расудување може да користи излезни токени. Држете го лимитот на токени низок и следете ја наплатата.|Premium модел: користете само за тешки измени кога поевтините модели не се доволни.|Поскап модел: резервирајте за сложени prompt-ови, не за рутински кратки предлози.|Поскап модел: користете кога помалите Mistral модели не се доволни.|Premium модел: проверете ги трошоците за користење пред да го вклучите за чести акции во едиторот.",
  bs: "Zadano|Tamno|Minimalno|Korporativno|Cyberpunk|Elegantno|Šuma|Okean|Zalazak|Pastelno|Luksuzno|Opsidijan|Ponoć|Aurora|Nordijsko|Grafit|Papir|Žalfija|Terakota|Lavanda|Monohromatsko|Terminal|Ruža|Visok kontrast|Puna širina|Ograničeno|Usko|Široko|Ultra široko|Sistemski|Bez serif|Serif|Mono|Displej|Humanistički|Nema|Malo|Srednje|Veliko|Zaobljeno|Meko|Jako|Builder preko cijele širine|Builder preko cijele širine|Uokviren sadržaj|Ograničeni builder|Uokvireni builder|Landing režim|Lista|Kartice|Magazinska mreža|Kompaktna arhiva|Istaknuto prvo|U liniji|Naslagano|Nadnaslov|Kompaktno|Vrh|Nakon naslova|Hero|Uvodno|Suptilno|Istaknuto|Nakon sadržaja|Prije sadržaja|U liniji s naslovom|Akcije u zaglavlju|Akcije u podnožju|Dinamički alias: OpenAI može promijeniti osnovni model, cijenu i ponašanje. Koristite fiksirani model za predvidljive CMS troškove.|VEOMA VISOK TROŠAK: pro rasuđivanje može naplatiti skriveno rasuđivanje kao izlaz. Izbjegavajte za rutinski CMS tekst.|Model za rasuđivanje: skriveno rasuđivanje može trošiti izlazne tokene. Držite limit tokena nisko i pratite naplatu.|Premium model: koristite samo za teške izmjene kada jeftiniji modeli nisu dovoljni.|Skuplji model: čuvajte za složene promptove, ne za rutinske kratke prijedloge.|Skuplji model: koristite kada manji Mistral modeli nisu dovoljni.|Premium model: provjerite troškove korištenja prije uključivanja za česte akcije u editoru.",
  sl: "Privzeto|Temno|Minimalno|Korporativno|Cyberpunk|Elegantno|Gozd|Ocean|Sončni zahod|Pastelno|Luksuzno|Obsidian|Polnoč|Aurora|Nordijsko|Grafit|Papir|Žajbelj|Terakota|Sivka|Monokromatsko|Terminal|Vrtnica|Visok kontrast|Polna širina|Omejeno|Ozko|Široko|Ultra široko|Sistemsko|Sans|Serif|Mono|Prikazno|Humanistično|Brez|Majhno|Srednje|Veliko|Zaobljeno|Mehko|Močno|Builder polne širine|Builder polne širine|Uokvirjena vsebina|Omejeni builder|Uokvirjeni builder|Landing način|Seznam|Kartice|Revijalna mreža|Kompakten arhiv|Najprej izpostavljeno|V vrstici|Zloženo|Nadnaslov|Kompaktno|Vrh|Po naslovu|Hero|Uvod|Subtilno|Poudarek|Po vsebini|Pred vsebino|Naslov v vrstici|Dejanja v glavi|Dejanja v nogi|Dinamični alias: OpenAI lahko spremeni osnovni model, cene in vedenje. Uporabite pripeti model za predvidljive CMS stroške.|ZELO VISOK STROŠEK: pro sklepanje lahko zaračuna skrito sklepanje kot izhod. Izogibajte se za rutinsko CMS besedilo.|Model sklepanja: skrito sklepanje lahko uporablja izhodne tokene. Omejitev tokenov naj bo nizka in spremljajte obračun.|Premium model: uporabite samo za zahtevne popravke, ko cenejši modeli niso dovolj.|Dražji model: prihranite za kompleksne prompte, ne za rutinske kratke predloge.|Dražji model: uporabite, ko manjši modeli Mistral niso dovolj.|Premium model: preverite stroške uporabe, preden ga omogočite za pogosta dejanja v urejevalniku.",
  ru: "По умолчанию|Тёмная|Минимальная|Корпоративная|Киберпанк|Элегантная|Лес|Океан|Закат|Пастель|Люкс|Обсидиан|Полночь|Аврора|Северная|Графит|Бумага|Шалфей|Терракота|Лаванда|Монохром|Терминал|Роза|Высокий контраст|Полная ширина|Ограниченная|Узкая|Широкая|Ультраширокая|Системный|Без засечек|С засечками|Моно|Дисплейный|Гуманистический|Нет|Малый|Средний|Большой|Скруглённый|Мягкая|Сильная|Builder на полную ширину|Builder на полную ширину|Контент в рамке|Ограниченный builder|Builder в рамке|Landing-режим|Список|Карточки|Журнальная сетка|Компактный архив|Сначала избранное|В строке|Стопкой|Надзаголовок|Компактный|Сверху|После заголовка|Hero|Вводный текст|Ненавязчиво|Выноска|После содержимого|Перед содержимым|Заголовок в строке|Действия в шапке|Действия в подвале|Динамический alias: OpenAI может изменить базовую модель, цены и поведение. Используйте закреплённую модель для предсказуемых CMS-расходов.|ОЧЕНЬ ВЫСОКАЯ СТОИМОСТЬ: pro reasoning может тарифицировать скрытое рассуждение как вывод. Не используйте для обычного CMS-текста.|Модель рассуждения: скрытое рассуждение может использовать выходные токены. Держите лимит токенов низким и следите за оплатой.|Премиум-модель: используйте только для сложных правок, когда более дешёвых моделей недостаточно.|Более дорогая модель: оставьте для сложных prompt-ов, а не для обычных коротких предложений.|Более дорогая модель: используйте, когда меньших моделей Mistral недостаточно.|Премиум-модель: проверьте стоимость использования перед включением для частых действий редактора.",
  hu: "Alapértelmezett|Sötét|Minimál|Vállalati|Cyberpunk|Elegáns|Erdő|Óceán|Naplemente|Pasztell|Luxus|Obszidián|Éjfél|Auróra|Északi|Grafit|Papír|Zsálya|Terrakotta|Levendula|Monokróm|Terminál|Rózsa|Nagy kontraszt|Teljes szélesség|Korlátozott|Keskeny|Széles|Ultraszéles|Rendszer|Sans|Serif|Mono|Display|Humanista|Nincs|Kicsi|Közepes|Nagy|Lekerekített|Lágy|Erős|Teljes szélességű builder|Teljes szélességű builder|Keretezett tartalom|Korlátozott builder|Keretezett builder|Landing mód|Lista|Kártyák|Magazinrács|Kompakt archívum|Kiemelt először|Soron belüli|Halmozott|Felcím|Kompakt|Felül|Cím után|Hero|Lead|Visszafogott|Kiemelés|Tartalom után|Tartalom előtt|Cím soron belül|Fejléc műveletei|Lábléc műveletei|Dinamikus alias: az OpenAI módosíthatja az alapmodellt, az árazást és a viselkedést. Kiszámítható CMS-költségekhez használjon rögzített modellt.|NAGYON MAGAS KÖLTSÉG: a pro reasoning a rejtett reasoninget kimenetként számlázhatja. Rutinszerű CMS-szöveghez kerülje.|Reasoning modell: a rejtett reasoning kimeneti tokeneket használhat. Tartsa alacsonyan a tokenlimitet és figyelje a számlázást.|Prémium modell: csak nehéz szerkesztésekhez használja, amikor az olcsóbb modellek nem elegendők.|Drágább modell: összetett promptokhoz tartsa fenn, ne rutinszerű rövid javaslatokhoz.|Drágább modell: használja, ha a kisebb Mistral modellek nem elegendők.|Prémium modell: gyakori szerkesztői műveletek előtt ellenőrizze a használati költségeket.",
  bg: "По подразбиране|Тъмна|Минимална|Корпоративна|Cyberpunk|Елегантна|Гора|Океан|Залез|Пастелна|Лукс|Обсидиан|Полунощ|Аврора|Северна|Графит|Хартия|Салвия|Теракота|Лавандула|Монохромна|Терминал|Роза|Висок контраст|Пълна ширина|Ограничено|Тясно|Широко|Ултра широко|Системен|Без сериф|Сериф|Моно|Дисплей|Хуманистичен|Няма|Малко|Средно|Голямо|Заоблено|Меко|Силно|Builder на пълна ширина|Builder на пълна ширина|Съдържание в рамка|Ограничен builder|Builder в рамка|Landing режим|Списък|Карти|Магазинна мрежа|Компактен архив|Първо избраното|В ред|Насложено|Надзаглавие|Компактно|Горе|След заглавието|Hero|Въведение|Дискретно|Акцент|След съдържанието|Преди съдържанието|Заглавие в реда|Действия в заглавката|Действия във футъра|Динамичен alias: OpenAI може да промени основния модел, цените и поведението. Използвайте фиксиран модел за предвидими CMS разходи.|МНОГО ВИСОК РАЗХОД: pro reasoning може да таксува скритото разсъждение като изход. Избягвайте за рутинен CMS текст.|Модел за разсъждение: скритото разсъждение може да използва изходни токени. Дръжте лимита на токени нисък и следете таксуването.|Премиум модел: използвайте само за трудни редакции, когато по-евтините модели не са достатъчни.|По-скъп модел: запазете за сложни prompt-и, не за рутинни кратки предложения.|По-скъп модел: използвайте, когато по-малките Mistral модели не са достатъчни.|Премиум модел: проверете разходите за използване, преди да го активирате за чести действия в редактора.",
  ja: "デフォルト|ダーク|ミニマル|コーポレート|サイバーパンク|エレガント|フォレスト|オーシャン|サンセット|パステル|ラグジュアリー|オブシディアン|ミッドナイト|オーロラ|ノルディック|グラファイト|ペーパー|セージ|テラコッタ|ラベンダー|モノクローム|ターミナル|ローズ|高コントラスト|全幅|コンテナ幅|狭い|広い|超広幅|システム|サンセリフ|セリフ|モノ|ディスプレイ|ヒューマニスト|なし|小|中|大|角丸|ソフト|強い|全幅ビルダー|全幅ビルダー|フレーム付きコンテンツ|コンテナ幅ビルダー|フレーム付きビルダー|ランディングモード|リスト|カード|マガジングリッド|コンパクトアーカイブ|注目を先頭|インライン|積み重ね|アイブロウ|コンパクト|上部|タイトル後|Hero|リード|控えめ|コールアウト|コンテンツ後|コンテンツ前|タイトル内インライン|ヘッダーアクション|フッターアクション|動的エイリアス: OpenAI は基盤モデル、価格、動作を変更する場合があります。予測可能な CMS コストには固定モデルを使用してください。|非常に高コスト: pro reasoning は隠れた reasoning を出力として課金する場合があります。通常の CMS テキストには避けてください。|Reasoning モデル: 隠れた reasoning が出力トークンを使う場合があります。トークン上限を低く保ち、課金を確認してください。|プレミアムモデル: 低コストモデルでは足りない難しい編集にのみ使用してください。|高コストモデル: 通常の短い提案ではなく、複雑なプロンプト用に予約してください。|高コストモデル: 小さい Mistral モデルでは足りない場合に使用してください。|プレミアムモデル: エディターで頻繁に使う前に利用コストを確認してください。",
  "zh-Hans":
    "默认|深色|极简|企业|赛博朋克|优雅|森林|海洋|日落|柔彩|奢华|黑曜石|午夜|极光|北欧|石墨|纸张|鼠尾草|陶土|薰衣草|单色|终端|玫瑰|高对比度|全宽|受限|窄|宽|超宽|系统|无衬线|衬线|等宽|展示|人文|无|小|中|大|圆角|柔和|强烈|全宽构建器|全宽构建器|带框内容|受限构建器|带框构建器|落地页模式|列表|卡片|杂志网格|紧凑归档|精选优先|行内|堆叠|眉题|紧凑|顶部|标题后|Hero|导语|弱化|强调框|内容后|内容前|标题内联|页眉操作|页脚操作|动态别名：OpenAI 可能会更改底层模型、价格和行为。请使用固定模型以获得可预测的 CMS 成本。|成本极高：pro 推理可能会把隐藏推理作为输出计费。请避免用于常规 CMS 文本。|推理模型：隐藏推理可能会使用输出 token。请保持 token 上限较低并关注计费。|高级模型：仅在低成本模型不足以完成困难编辑时使用。|较高成本模型：留给复杂提示词，不要用于常规短建议。|较高成本模型：当较小的 Mistral 模型不足时使用。|高级模型：为频繁编辑器操作启用前，请检查使用成本。",
  "zh-Hant":
    "預設|深色|極簡|企業|賽博龐克|優雅|森林|海洋|日落|柔彩|奢華|黑曜石|午夜|極光|北歐|石墨|紙張|鼠尾草|陶土|薰衣草|單色|終端|玫瑰|高對比|全寬|受限|窄|寬|超寬|系統|無襯線|襯線|等寬|展示|人文|無|小|中|大|圓角|柔和|強烈|全寬建構器|全寬建構器|加框內容|受限建構器|加框建構器|Landing 模式|清單|卡片|雜誌網格|精簡封存|精選優先|行內|堆疊|眉題|精簡|頂部|標題後|Hero|導語|低調|提示框|內容後|內容前|標題內嵌|頁首動作|頁尾動作|動態別名：OpenAI 可能會變更底層模型、價格和行為。請使用固定模型以獲得可預測的 CMS 成本。|成本極高：pro 推理可能會把隱藏推理作為輸出計費。請避免用於例行 CMS 文字。|推理模型：隱藏推理可能會使用輸出 token。請保持 token 上限較低並留意計費。|高階模型：只有在低成本模型不足以完成困難編輯時才使用。|較高成本模型：保留給複雜提示，不要用於例行短建議。|較高成本模型：當較小的 Mistral 模型不足時使用。|高階模型：為頻繁編輯器動作啟用前，請檢查使用成本。",
  ar: "افتراضي|داكن|بسيط|مؤسسي|سايبربانك|أنيق|غابة|محيط|غروب|باستيل|فاخر|سبج|منتصف الليل|شفق|شمالي|غرافيت|ورق|ميرمية|تيراكوتا|لافندر|أحادي اللون|طرفية|وردي|تباين عال|عرض كامل|محتوى محدود|ضيق|واسع|واسع جدًا|النظام|Sans|Serif|Mono|Display|إنساني|لا شيء|صغير|متوسط|كبير|مستدير|ناعم|قوي|منشئ بعرض كامل|منشئ بعرض كامل|محتوى مؤطر|منشئ محدود|منشئ مؤطر|وضع الهبوط|قائمة|بطاقات|شبكة مجلة|أرشيف مضغوط|المميز أولاً|ضمن السطر|مكدس|عنوان علوي|مضغوط|الأعلى|بعد العنوان|Hero|تمهيد|خفيف|نداء بارز|بعد المحتوى|قبل المحتوى|العنوان ضمن السطر|إجراءات الرأس|إجراءات التذييل|اسم مستعار ديناميكي: قد تغيّر OpenAI النموذج الأساسي والأسعار والسلوك. استخدم نموذجًا مثبتًا لتكاليف CMS متوقعة.|تكلفة عالية جدًا: قد يفرض pro reasoning رسومًا على التفكير المخفي كمخرجات. تجنب ذلك لنصوص CMS الروتينية.|نموذج تفكير: قد يستخدم التفكير المخفي رموز إخراج. أبق حد الرموز منخفضًا وراقب الفوترة.|نموذج مميز: استخدمه فقط للتعديلات الصعبة عندما لا تكفي النماذج الأقل تكلفة.|نموذج أعلى تكلفة: خصصه للمطالبات المعقدة، لا للاقتراحات القصيرة الروتينية.|نموذج أعلى تكلفة: استخدمه عندما لا تكفي نماذج Mistral الأصغر.|نموذج مميز: تحقق من تكاليف الاستخدام قبل تمكينه لإجراءات المحرر المتكررة.",
  id: "Default|Gelap|Minimal|Korporat|Cyberpunk|Elegan|Hutan|Samudra|Matahari terbenam|Pastel|Mewah|Obsidian|Tengah malam|Aurora|Nordik|Grafit|Kertas|Sage|Terracotta|Lavender|Monokrom|Terminal|Mawar|Kontras tinggi|Lebar penuh|Terbatas|Sempit|Lebar|Ultra lebar|Sistem|Sans|Serif|Mono|Display|Humanis|Tidak ada|Kecil|Sedang|Besar|Membulat|Lembut|Kuat|Builder lebar penuh|Builder lebar penuh|Konten berbingkai|Builder terbatas|Builder berbingkai|Mode landing|Daftar|Kartu|Grid majalah|Arsip ringkas|Unggulan dulu|Inline|Bertumpuk|Eyebrow|Ringkas|Atas|Setelah judul|Hero|Lead|Halus|Sorotan|Setelah konten|Sebelum konten|Judul inline|Aksi header|Aksi footer|Alias dinamis: OpenAI dapat mengubah model dasar, harga, dan perilaku. Gunakan model yang dipatok untuk biaya CMS yang dapat diprediksi.|BIAYA SANGAT TINGGI: reasoning pro dapat menagih reasoning tersembunyi sebagai output. Hindari untuk teks CMS rutin.|Model reasoning: reasoning tersembunyi dapat menggunakan token output. Jaga batas token tetap rendah dan pantau penagihan.|Model premium: gunakan hanya untuk edit sulit ketika model berbiaya lebih rendah tidak cukup.|Model biaya lebih tinggi: simpan untuk prompt kompleks, bukan saran pendek rutin.|Model biaya lebih tinggi: gunakan ketika model Mistral yang lebih kecil tidak cukup.|Model premium: periksa biaya penggunaan sebelum mengaktifkan untuk aksi editor yang sering.",
  cs: "Výchozí|Tmavé|Minimální|Firemní|Cyberpunk|Elegantní|Les|Oceán|Západ slunce|Pastelové|Luxusní|Obsidián|Půlnoc|Aurora|Severské|Grafit|Papír|Šalvěj|Terakota|Levandule|Monochromatické|Terminál|Růže|Vysoký kontrast|Plná šířka|Omezené|Úzké|Široké|Ultra široké|Systémové|Sans|Serif|Mono|Display|Humanistické|Žádné|Malé|Střední|Velké|Zaoblené|Měkké|Silné|Builder přes celou šířku|Builder přes celou šířku|Orámovaný obsah|Omezený builder|Orámovaný builder|Landing režim|Seznam|Karty|Magazínová mřížka|Kompaktní archiv|Doporučené první|Inline|Skládané|Nadpisek|Kompaktní|Nahoře|Po názvu|Hero|Úvod|Jemné|Zvýraznění|Po obsahu|Před obsahem|Název inline|Akce záhlaví|Akce zápatí|Dynamický alias: OpenAI může změnit základní model, ceny a chování. Pro předvídatelné náklady CMS použijte připnutý model.|VELMI VYSOKÉ NÁKLADY: pro reasoning může účtovat skryté reasoning jako výstup. Vyhněte se tomu pro rutinní CMS text.|Reasoning model: skryté reasoning může používat výstupní tokeny. Držte limit tokenů nízko a sledujte účtování.|Prémiový model: používejte pouze pro obtížné úpravy, když levnější modely nestačí.|Dražší model: rezervujte pro složité prompty, ne pro rutinní krátké návrhy.|Dražší model: použijte, když menší modely Mistral nestačí.|Prémiový model: před zapnutím pro časté akce editoru zkontrolujte náklady na používání.",
  ro: "Implicit|Întunecat|Minimal|Corporate|Cyberpunk|Elegant|Pădure|Ocean|Apus|Pastel|Lux|Obsidian|Miezul nopții|Aurora|Nordic|Grafit|Hârtie|Salvie|Teracotă|Lavandă|Monocrom|Terminal|Roz|Contrast ridicat|Lățime completă|Conținut limitat|Îngust|Lat|Ultra lat|Sistem|Sans|Serif|Mono|Display|Umanist|Niciuna|Mic|Mediu|Mare|Rotunjit|Moale|Puternic|Builder pe toată lățimea|Builder pe toată lățimea|Conținut încadrat|Builder limitat|Builder încadrat|Mod landing|Listă|Carduri|Grilă de revistă|Arhivă compactă|Recomandat primul|Inline|Stivuit|Supratitlu|Compact|Sus|După titlu|Hero|Lead|Subtil|Casetă evidențiată|După conținut|Înainte de conținut|Titlu inline|Acțiuni antet|Acțiuni subsol|Alias dinamic: OpenAI poate schimba modelul de bază, prețurile și comportamentul. Folosiți un model fixat pentru costuri CMS previzibile.|COST FOARTE RIDICAT: raționamentul pro poate taxa raționamentul ascuns ca ieșire. Evitați pentru text CMS de rutină.|Model de raționament: raționamentul ascuns poate folosi tokeni de ieșire. Mențineți limita de tokeni mică și urmăriți facturarea.|Model premium: folosiți doar pentru editări dificile când modelele mai ieftine nu sunt suficiente.|Model mai costisitor: rezervați pentru prompturi complexe, nu pentru sugestii scurte de rutină.|Model mai costisitor: folosiți când modelele Mistral mai mici nu sunt suficiente.|Model premium: verificați costurile de utilizare înainte de activare pentru acțiuni frecvente în editor.",
  el: "Προεπιλογή|Σκούρο|Ελάχιστο|Εταιρικό|Cyberpunk|Κομψό|Δάσος|Ωκεανός|Ηλιοβασίλεμα|Παστέλ|Πολυτελές|Οψιδιανός|Μεσάνυχτα|Σέλας|Σκανδιναβικό|Γραφίτης|Χαρτί|Φασκόμηλο|Τερακότα|Λεβάντα|Μονόχρωμο|Τερματικό|Ροζ|Υψηλή αντίθεση|Πλήρες πλάτος|Περιορισμένο|Στενό|Πλατύ|Υπερπλατύ|Σύστημα|Sans|Serif|Mono|Display|Humanist|Κανένα|Μικρό|Μεσαίο|Μεγάλο|Στρογγυλεμένο|Απαλό|Έντονο|Builder πλήρους πλάτους|Builder πλήρους πλάτους|Πλαισιωμένο περιεχόμενο|Περιορισμένος builder|Πλαισιωμένος builder|Λειτουργία landing|Λίστα|Κάρτες|Πλέγμα περιοδικού|Συμπαγές αρχείο|Πρώτα τα προτεινόμενα|Ενσωματωμένο|Στοιβαγμένο|Υπέρτιτλος|Συμπαγές|Πάνω|Μετά τον τίτλο|Hero|Εισαγωγή|Διακριτικό|Πλαίσιο έμφασης|Μετά το περιεχόμενο|Πριν από το περιεχόμενο|Τίτλος ενσωματωμένος|Ενέργειες κεφαλίδας|Ενέργειες υποσέλιδου|Δυναμικό alias: η OpenAI μπορεί να αλλάξει το υποκείμενο μοντέλο, την τιμολόγηση και τη συμπεριφορά. Χρησιμοποιήστε καρφιτσωμένο μοντέλο για προβλέψιμα κόστη CMS.|ΠΟΛΥ ΥΨΗΛΟ ΚΟΣΤΟΣ: το pro reasoning μπορεί να χρεώσει κρυφή συλλογιστική ως έξοδο. Αποφύγετε για συνηθισμένο CMS κείμενο.|Μοντέλο συλλογιστικής: η κρυφή συλλογιστική μπορεί να χρησιμοποιεί output tokens. Κρατήστε χαμηλό το όριο token και παρακολουθήστε τη χρέωση.|Premium μοντέλο: χρησιμοποιήστε μόνο για δύσκολες επεξεργασίες όταν τα φθηνότερα μοντέλα δεν αρκούν.|Μοντέλο υψηλότερου κόστους: κρατήστε το για σύνθετα prompt, όχι για σύντομες συνηθισμένες προτάσεις.|Μοντέλο υψηλότερου κόστους: χρησιμοποιήστε όταν τα μικρότερα μοντέλα Mistral δεν αρκούν.|Premium μοντέλο: ελέγξτε τα κόστη χρήσης πριν το ενεργοποιήσετε για συχνές ενέργειες editor.",
  da: "Standard|Mørk|Minimal|Corporate|Cyberpunk|Elegant|Skov|Ocean|Solnedgang|Pastel|Luksus|Obsidian|Midnat|Aurora|Nordisk|Grafit|Papir|Salvie|Terracotta|Lavendel|Monokrom|Terminal|Rose|Høj kontrast|Fuld bredde|Indrammet bredde|Smal|Bred|Ultra bred|System|Sans|Serif|Mono|Display|Humanistisk|Ingen|Lille|Medium|Stor|Afrundet|Blød|Stærk|Builder i fuld bredde|Builder i fuld bredde|Indrammet indhold|Indrammet builder|Builder med ramme|Landing-tilstand|Liste|Kort|Magasingitter|Kompakt arkiv|Fremhævet først|Inline|Stablet|Overrubrik|Kompakt|Top|Efter titel|Hero|Lead|Diskret|Fremhævning|Efter indhold|Før indhold|Titel inline|Headerhandlinger|Footerhandlinger|Dynamisk alias: OpenAI kan ændre den underliggende model, priser og adfærd. Brug en fastgjort model for forudsigelige CMS-omkostninger.|MEGET HØJ OMKOSTNING: pro reasoning kan fakturere skjult reasoning som output. Undgå til rutinemæssig CMS-tekst.|Reasoning-model: skjult reasoning kan bruge outputtokens. Hold tokenloftet lavt og overvåg fakturering.|Premium-model: brug kun til vanskelige redigeringer, hvor billigere modeller ikke er nok.|Dyrere model: reserver til komplekse prompts, ikke rutinemæssige korte forslag.|Dyrere model: brug når mindre Mistral-modeller ikke er nok.|Premium-model: tjek brugsomkostninger før aktivering til hyppige editorhandlinger.",
  sv: "Standard|Mörk|Minimal|Företag|Cyberpunk|Elegant|Skog|Ocean|Solnedgång|Pastell|Lyx|Obsidian|Midnatt|Aurora|Nordisk|Grafit|Papper|Salvia|Terrakotta|Lavendel|Monokrom|Terminal|Ros|Hög kontrast|Full bredd|Innesluten|Smal|Bred|Ultrabred|System|Sans|Serif|Mono|Display|Humanistisk|Ingen|Liten|Medium|Stor|Rundad|Mjuk|Stark|Builder i full bredd|Builder i full bredd|Inramat innehåll|Innesluten builder|Inramad builder|Landing-läge|Lista|Kort|Magasinrutnät|Kompakt arkiv|Utvalt först|Inline|Staplad|Överrubrik|Kompakt|Överst|Efter titel|Hero|Ingress|Subtil|Callout|Efter innehåll|Före innehåll|Titel inline|Headeråtgärder|Footeråtgärder|Dynamiskt alias: OpenAI kan ändra underliggande modell, prissättning och beteende. Använd en låst modell för förutsägbara CMS-kostnader.|MYCKET HÖG KOSTNAD: pro reasoning kan debitera dold reasoning som output. Undvik för rutinmässig CMS-text.|Reasoningmodell: dold reasoning kan använda outputtokens. Håll tokengränsen låg och bevaka faktureringen.|Premium-modell: använd endast för svåra redigeringar där billigare modeller inte räcker.|Dyrare modell: reservera för komplexa prompts, inte rutinmässiga korta förslag.|Dyrare modell: använd när mindre Mistral-modeller inte räcker.|Premium-modell: kontrollera användningskostnader innan den aktiveras för frekventa editoråtgärder.",
  nb: "Standard|Mørk|Minimal|Bedrift|Cyberpunk|Elegant|Skog|Hav|Solnedgang|Pastell|Luksus|Obsidian|Midnatt|Aurora|Nordisk|Grafitt|Papir|Salvie|Terrakotta|Lavendel|Monokrom|Terminal|Rose|Høy kontrast|Full bredde|Innholdsbundet|Smal|Bred|Ultrabred|System|Sans|Serif|Mono|Display|Humanistisk|Ingen|Liten|Medium|Stor|Avrundet|Myk|Sterk|Builder i full bredde|Builder i full bredde|Innrammet innhold|Innholdsbundet builder|Innrammet builder|Landing-modus|Liste|Kort|Magasinrutenett|Kompakt arkiv|Fremhevet først|Inline|Stablet|Overtittel|Kompakt|Øverst|Etter tittel|Hero|Ingress|Diskret|Utheving|Etter innhold|Før innhold|Tittel inline|Header-handlinger|Footer-handlinger|Dynamisk alias: OpenAI kan endre underliggende modell, priser og oppførsel. Bruk en festet modell for forutsigbare CMS-kostnader.|SVÆRT HØY KOSTNAD: pro reasoning kan fakturere skjult reasoning som output. Unngå for rutinemessig CMS-tekst.|Reasoning-modell: skjult reasoning kan bruke outputtokens. Hold tokengrenser lave og følg med på fakturering.|Premium-modell: bruk bare til vanskelige redigeringer når rimeligere modeller ikke er nok.|Dyrere modell: reserver for komplekse prompts, ikke rutinemessige korte forslag.|Dyrere modell: bruk når mindre Mistral-modeller ikke er nok.|Premium-modell: sjekk brukskostnader før aktivering for hyppige editorhandlinger.",
  nn: "Standard|Mørk|Minimal|Bedrift|Cyberpunk|Elegant|Skog|Hav|Solnedgang|Pastell|Luksus|Obsidian|Midnatt|Aurora|Nordisk|Grafitt|Papir|Salvie|Terrakotta|Lavendel|Monokrom|Terminal|Rose|Høg kontrast|Full breidd|Innhaldsbunde|Smal|Breid|Ultrabreid|System|Sans|Serif|Mono|Display|Humanistisk|Ingen|Liten|Medium|Stor|Avrunda|Mjukt|Sterkt|Builder i full breidd|Builder i full breidd|Innramma innhald|Innhaldsbunden builder|Innramma builder|Landing-modus|Liste|Kort|Magasinrutenett|Kompakt arkiv|Framheva først|Inline|Stabla|Overtittel|Kompakt|Øvst|Etter tittel|Hero|Ingress|Diskret|Utheving|Etter innhald|Før innhald|Tittel inline|Header-handlingar|Footer-handlingar|Dynamisk alias: OpenAI kan endre underliggjande modell, prisar og åtferd. Bruk ein festa modell for føreseielege CMS-kostnader.|SVÆRT HØG KOSTNAD: pro reasoning kan fakturere skjult reasoning som output. Unngå for rutinemessig CMS-tekst.|Reasoning-modell: skjult reasoning kan bruke outputtokens. Hald tokengrensene låge og følg med på fakturering.|Premium-modell: bruk berre til vanskelege redigeringar når rimelegare modellar ikkje er nok.|Dyrare modell: reserver for komplekse promptar, ikkje rutinemessige korte forslag.|Dyrare modell: bruk når mindre Mistral-modellar ikkje er nok.|Premium-modell: sjekk brukskostnader før aktivering for hyppige editorhandlingar.",
  fi: "Oletus|Tumma|Minimaalinen|Yritys|Cyberpunk|Elegantti|Metsä|Meri|Auringonlasku|Pastelli|Luksus|Obsidiaani|Keskiyö|Revontuli|Pohjoismainen|Grafiitti|Paperi|Salvia|Terrakotta|Laventeli|Monokromi|Pääte|Ruusu|Korkea kontrasti|Täysi leveys|Rajattu|Kapea|Leveä|Ultraleveä|Järjestelmä|Sans|Serif|Mono|Display|Humanistinen|Ei mitään|Pieni|Keskikokoinen|Suuri|Pyöristetty|Pehmeä|Vahva|Täyden leveyden builder|Täyden leveyden builder|Kehystetty sisältö|Rajattu builder|Kehystetty builder|Landing-tila|Lista|Kortit|Lehtiruudukko|Kompakti arkisto|Nostettu ensin|Inline|Pinottu|Yläotsikko|Kompakti|Ylhäällä|Otsikon jälkeen|Hero|Ingressi|Hillitty|Nosto|Sisällön jälkeen|Ennen sisältöä|Otsikko inline|Ylätunnisteen toiminnot|Alatunnisteen toiminnot|Dynaaminen alias: OpenAI voi muuttaa taustalla olevaa mallia, hinnoittelua ja käyttäytymistä. Käytä kiinnitettyä mallia ennakoitaviin CMS-kustannuksiin.|ERITTÄIN KORKEA KUSTANNUS: pro reasoning voi laskuttaa piilotetun reasoningin outputina. Vältä rutiininomaisessa CMS-tekstissä.|Reasoning-malli: piilotettu reasoning voi käyttää output-tokeneita. Pidä tokenraja matalana ja seuraa laskutusta.|Premium-malli: käytä vain vaikeisiin muokkauksiin, kun halvemmat mallit eivät riitä.|Kalliimpi malli: varaa monimutkaisiin prompteihin, ei rutiininomaisiin lyhyisiin ehdotuksiin.|Kalliimpi malli: käytä, kun pienemmät Mistral-mallit eivät riitä.|Premium-malli: tarkista käyttökustannukset ennen aktivointia toistuviin editoritoimintoihin.",
  is: "Sjálfgefið|Dökkt|Lágmarks|Fyrirtækja|Cyberpunk|Glæsilegt|Skógur|Haf|Sólsetur|Pastel|Lúxus|Hrafntinna|Miðnætti|Norðurljós|Norrænt|Grafít|Pappír|Salvía|Terrakotta|Lavender|Einlitt|Terminal|Rós|Mikil birtuskil|Full breidd|Afmarkað|Þröngt|Breitt|Ofurbreitt|Kerfi|Sans|Serif|Mono|Display|Humanist|Ekkert|Lítið|Miðlungs|Stórt|Rúnnað|Mjúkt|Sterkt|Builder í fullri breidd|Builder í fullri breidd|Innrammað efni|Afmarkaður builder|Innrammaður builder|Landing-hamur|Listi|Spjöld|Tímaritsnet|Þétt safn|Valið fyrst|Inline|Staflað|Yfirfyrirsögn|Þétt|Efst|Eftir titil|Hero|Lead|Fíngert|Áherslukassi|Eftir efni|Fyrir efni|Titill inline|Hausaðgerðir|Fótaraðgerðir|Kvikur alias: OpenAI getur breytt undirliggjandi líkani, verðlagningu og hegðun. Notaðu fest líkan fyrir fyrirsjáanlegan CMS-kostnað.|MJÖG HÁR KOSTNAÐUR: pro reasoning getur rukkað falið reasoning sem úttak. Forðastu fyrir venjubundinn CMS-texta.|Reasoning-líkan: falið reasoning getur notað úttakstóka. Haltu token-mörkum lágum og fylgstu með reikningum.|Premium-líkan: notaðu aðeins fyrir erfiðar breytingar þegar ódýrari líkön duga ekki.|Dýrara líkan: geymdu fyrir flókin prompt, ekki venjulegar stuttar tillögur.|Dýrara líkan: notaðu þegar minni Mistral-líkön duga ekki.|Premium-líkan: athugaðu notkunarkostnað áður en það er virkjað fyrir tíðar aðgerðir í ritli.",
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<OptionSource, string> {
  const translations = row.split("|");
  if (translations.length !== GLOBAL_SETTINGS_OPTION_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} global settings option translations must have ${GLOBAL_SETTINGS_OPTION_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    GLOBAL_SETTINGS_OPTION_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<OptionSource, string>;
}

export const GLOBAL_SETTINGS_OPTION_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<OptionSource, string>>;
