import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const GLOBAL_SETTINGS_PRESET_SOURCE_STRINGS = [
  "Cyber Journal",
  "Classic CMS",
  "Editorial",
  "Portfolio",
  "Documentation",
  "SaaS/Product",
  "Magazine",
  "Campaign",
  "Cyberpunk theme, contained content, normal surface, magazine footer.",
  "Left brand, horizontal menu, contained content, simple footer.",
  "Masthead header, category rail, article measure, column footer.",
  "Minimal top chrome, full-bleed canvas, quiet footer.",
  "Compact app bar, narrow reading surface, sitemap footer.",
  "App-style header, CTA, card-forward surface, footer columns.",
  "Split navigation, category surfaces, dense footer links.",
  "Minimal landing shell, full-bleed builder, strong CTA option.",
  "cyberpunk",
  "journal",
  "magazine",
  "classic",
  "cms",
  "safe",
  "publishing",
  "articles",
  "visual",
  "work",
  "docs",
  "reading",
  "product",
  "cta",
  "categories",
  "landing",
  "campaign",
] as const;

type PresetSource = (typeof GLOBAL_SETTINGS_PRESET_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "Sajber žurnal|Klasični CMS|Urednički|Portfelj|Dokumentacija|SaaS/Proizvod|Magazin|Kampanja|Sajberpank tema, ograničen sadržaj, normalna površina, magazinsko podnožje.|Brend levo, horizontalni meni, ograničen sadržaj, jednostavno podnožje.|Masthead zaglavlje, traka kategorija, mera članka, podnožje u kolonama.|Minimalna gornja traka, full-bleed platno, mirno podnožje.|Kompaktna app traka, uska površina za čitanje, sitemap podnožje.|Zaglavlje u stilu aplikacije, CTA, površina sa karticama, kolone podnožja.|Podeljena navigacija, površine kategorija, gusto podnožje sa linkovima.|Minimalna landing školjka, full-bleed builder, jaka CTA opcija.|sajberpank|žurnal|magazin|klasično|CMS|bezbedno|objavljivanje|članci|vizuelno|rad|dokumentacija|čitanje|proizvod|CTA|kategorije|landing|kampanja",
  "sr-Cyrl":
    "Сајбер журнал|Класични CMS|Уреднички|Портфолио|Документација|SaaS/Производ|Магазин|Кампања|Сајберпанк тема, ограничен садржај, нормална површина, магазинско подножје.|Бренд лево, хоризонтални мени, ограничен садржај, једноставно подножје.|Masthead заглавље, трака категорија, мера чланка, подножје у колонама.|Минимална горња трака, full-bleed платно, мирно подножје.|Компактна app трака, уска површина за читање, sitemap подножје.|Заглавље у стилу апликације, CTA, површина са картицама, колоне подножја.|Подељена навигација, површине категорија, густо подножје са линковима.|Минимална landing љуска, full-bleed builder, јака CTA опција.|сајберпанк|журнал|магазин|класично|CMS|безбедно|објављивање|чланци|визуелно|рад|документација|читање|производ|CTA|категорије|landing|кампања",
  hr: "Cyber žurnal|Klasični CMS|Urednički|Portfelj|Dokumentacija|SaaS/Proizvod|Magazin|Kampanja|Cyberpunk tema, ograničen sadržaj, normalna površina, magazinsko podnožje.|Brend lijevo, horizontalni izbornik, ograničen sadržaj, jednostavno podnožje.|Masthead zaglavlje, traka kategorija, mjera članka, podnožje u stupcima.|Minimalna gornja traka, full-bleed platno, mirno podnožje.|Kompaktna app traka, uska površina za čitanje, sitemap podnožje.|Zaglavlje u stilu aplikacije, CTA, površina s karticama, stupci podnožja.|Podijeljena navigacija, površine kategorija, gusto podnožje s poveznicama.|Minimalna landing ljuska, full-bleed builder, jaka CTA opcija.|cyberpunk|žurnal|magazin|klasično|CMS|sigurno|objavljivanje|članci|vizualno|rad|dokumentacija|čitanje|proizvod|CTA|kategorije|landing|kampanja",
  de: "Cyber-Journal|Klassisches CMS|Redaktionell|Projektmappe|Dokumentation|SaaS/Produkt|Magazin|Kampagne|Cyberpunk-Theme, begrenzter Inhalt, normale Oberfläche, Magazin-Footer.|Marke links, horizontales Menü, begrenzter Inhalt, einfacher Footer.|Masthead-Header, Kategorienleiste, Artikelbreite, Spalten-Footer.|Minimale obere Leiste, vollflächige Canvas, dezenter Footer.|Kompakte App-Leiste, schmale Lesefläche, Sitemap-Footer.|App-artiger Header, CTA, kartenorientierte Oberfläche, Footer-Spalten.|Geteilte Navigation, Kategorieflächen, dichte Footer-Links.|Minimale Landing-Shell, vollflächiger Builder, starke CTA-Option.|Cyberpunk|Journal|Magazin|klassisch|CMS|sicher|Publishing|Artikel|visuell|Arbeit|Dokumentation|Lesen|Produkt|CTA|Kategorien|Landing|Kampagne",
  fr: "Journal cyber|CMS classique|Éditorial|Portefeuille|Documentation|SaaS/Produit|Magazine|Campagne|Thème cyberpunk, contenu cadré, surface normale, pied de page magazine.|Marque à gauche, menu horizontal, contenu cadré, pied de page simple.|En-tête masthead, rail de catégories, largeur d'article, pied de page en colonnes.|Chrome supérieur minimal, canevas pleine largeur, pied de page discret.|Barre d'application compacte, surface de lecture étroite, pied de page sitemap.|En-tête style application, CTA, surface orientée cartes, colonnes de pied de page.|Navigation scindée, surfaces de catégories, liens de pied de page denses.|Shell landing minimal, builder pleine largeur, option CTA forte.|cyberpunk|journal|magazine|classique|CMS|sûr|publication|articles|visuel|travail|docs|lecture|produit|CTA|catégories|landing|campagne",
  es: "Diario cyber|CMS clásico|Editorial|Portafolio|Documentación|SaaS/Producto|Revista|Campaña|Tema cyberpunk, contenido contenido, superficie normal, pie de revista.|Marca izquierda, menú horizontal, contenido contenido, pie simple.|Cabecera masthead, carril de categorías, medida de artículo, pie en columnas.|Cromo superior mínimo, lienzo full-bleed, pie tranquilo.|Barra de app compacta, superficie de lectura estrecha, pie de mapa del sitio.|Cabecera estilo app, CTA, superficie orientada a tarjetas, columnas de pie.|Navegación dividida, superficies de categorías, enlaces de pie densos.|Shell landing mínimo, builder full-bleed, opción CTA fuerte.|cyberpunk|diario|revista|clásico|CMS|seguro|publicación|artículos|visual|trabajo|docs|lectura|producto|CTA|categorías|landing|campaña",
  it: "Giornale cyber|CMS classico|Editoriale|Portafoglio|Documentazione|SaaS/Prodotto|Rivista|Campagna|Tema cyberpunk, contenuto contenuto, superficie normale, footer magazine.|Marchio a sinistra, menu orizzontale, contenuto contenuto, footer semplice.|Testata masthead, barra categorie, misura articolo, footer a colonne.|Chrome superiore minimale, canvas full-bleed, footer discreto.|Barra app compatta, superficie di lettura stretta, footer sitemap.|Header stile app, CTA, superficie a schede, colonne footer.|Navigazione divisa, superfici categorie, link footer densi.|Shell landing minimale, builder full-bleed, opzione CTA forte.|cyberpunk|giornale|rivista|classico|CMS|sicuro|pubblicazione|articoli|visivo|lavoro|docs|lettura|prodotto|CTA|categorie|landing|campagna",
  pt: "Jornal cyber|CMS clássico|Editorial|Portefólio|Documentação|SaaS/Produto|Revista|Campanha|Tema cyberpunk, conteúdo contido, superfície normal, rodapé de revista.|Marca à esquerda, menu horizontal, conteúdo contido, rodapé simples.|Cabeçalho masthead, faixa de categorias, medida de artigo, rodapé em colunas.|Chrome superior minimal, canvas full-bleed, rodapé discreto.|Barra de app compacta, superfície de leitura estreita, rodapé sitemap.|Cabeçalho estilo app, CTA, superfície orientada a cartões, colunas de rodapé.|Navegação dividida, superfícies de categorias, links de rodapé densos.|Shell landing minimal, builder full-bleed, opção CTA forte.|cyberpunk|jornal|revista|clássico|CMS|seguro|publicação|artigos|visual|trabalho|docs|leitura|produto|CTA|categorias|landing|campanha",
  "pt-BR":
    "Jornal cyber|CMS clássico|Editorial|Portfólio|Documentação|SaaS/Produto|Revista|Campanha|Tema cyberpunk, conteúdo contido, superfície normal, rodapé de revista.|Marca à esquerda, menu horizontal, conteúdo contido, rodapé simples.|Cabeçalho masthead, trilho de categorias, medida de artigo, rodapé em colunas.|Chrome superior mínimo, canvas full-bleed, rodapé discreto.|Barra de app compacta, superfície de leitura estreita, rodapé sitemap.|Cabeçalho estilo app, CTA, superfície com foco em cards, colunas de rodapé.|Navegação dividida, superfícies de categorias, links densos no rodapé.|Shell landing mínimo, builder full-bleed, opção CTA forte.|cyberpunk|jornal|revista|clássico|CMS|seguro|publicação|artigos|visual|trabalho|docs|leitura|produto|CTA|categorias|landing|campanha",
  nl: "Cyberjournaal|Klassiek CMS|Redactioneel|Portefeuille|Documentatie|SaaS/Product|Magazine|Campagne|Cyberpunk-thema, ingeperkte inhoud, normaal oppervlak, magazinevoettekst.|Merk links, horizontaal menu, ingeperkte inhoud, eenvoudige voettekst.|Masthead-kop, categorierail, artikelbreedte, kolomvoettekst.|Minimale bovenbalk, full-bleed canvas, rustige voettekst.|Compacte appbalk, smal leesoppervlak, sitemap-voettekst.|App-achtige kop, CTA, kaartgericht oppervlak, voettekstkolommen.|Gesplitste navigatie, categorieoppervlakken, dichte voettekstlinks.|Minimale landing-shell, full-bleed builder, sterke CTA-optie.|cyberpunk|journaal|magazine|klassiek|CMS|veilig|publiceren|artikelen|visueel|werk|docs|lezen|product|CTA|categorieën|landing|campagne",
  pl: "Cyber-dziennik|Klasyczny CMS|Redakcyjny|Portfolio|Dokumentacja|SaaS/Produkt|Magazyn|Kampania|Motyw cyberpunk, ograniczona treść, normalna powierzchnia, stopka magazynu.|Marka po lewej, menu poziome, ograniczona treść, prosta stopka.|Nagłówek masthead, pasek kategorii, miara artykułu, stopka kolumnowa.|Minimalny górny chrome, płótno full-bleed, spokojna stopka.|Kompaktowy pasek aplikacji, wąska powierzchnia czytania, stopka sitemap.|Nagłówek w stylu aplikacji, CTA, powierzchnia kart, kolumny stopki.|Podzielona nawigacja, powierzchnie kategorii, gęste linki stopki.|Minimalna powłoka landing, builder full-bleed, mocna opcja CTA.|cyberpunk|dziennik|magazyn|klasyczny|CMS|bezpieczny|publikowanie|artykuły|wizualny|praca|docs|czytanie|produkt|CTA|kategorie|landing|kampania",
  tr: "Siber günlük|Klasik CMS|Editoryal|Portföy|Dokümantasyon|SaaS/Ürün|Dergi|Kampanya|Cyberpunk tema, sınırlı içerik, normal yüzey, dergi footer'ı.|Sol marka, yatay menü, sınırlı içerik, sade footer.|Masthead başlık, kategori rayı, makale ölçüsü, sütunlu footer.|Minimal üst chrome, full-bleed tuval, sakin footer.|Kompakt app çubuğu, dar okuma yüzeyi, sitemap footer.|App tarzı başlık, CTA, kart odaklı yüzey, footer sütunları.|Bölünmüş navigasyon, kategori yüzeyleri, yoğun footer linkleri.|Minimal landing kabuğu, full-bleed builder, güçlü CTA seçeneği.|cyberpunk|günlük|dergi|klasik|CMS|güvenli|yayınlama|makaleler|görsel|iş|docs|okuma|ürün|CTA|kategoriler|landing|kampanya",
  mk: "Сајбер журнал|Класичен CMS|Уреднички|Портфолио|Документација|SaaS/Производ|Магазин|Кампања|Cyberpunk тема, ограничена содржина, нормална површина, магазинско подножје.|Бренд лево, хоризонтално мени, ограничена содржина, едноставно подножје.|Masthead заглавје, лента со категории, мера на напис, подножје во колони.|Минимална горна лента, full-bleed платно, мирно подножје.|Компактна app лента, тесна површина за читање, sitemap подножје.|Заглавје во стил на апликација, CTA, површина со картички, колони во подножјето.|Поделена навигација, површини за категории, густо подножје со линкови.|Минимална landing школка, full-bleed builder, силна CTA опција.|сајберпанк|журнал|магазин|класично|CMS|безбедно|објавување|написи|визуелно|работа|документација|читање|производ|CTA|категории|landing|кампања",
  bs: "Sajber žurnal|Klasični CMS|Urednički|Portfolio|Dokumentacija|SaaS/Proizvod|Magazin|Kampanja|Sajberpank tema, ograničen sadržaj, normalna površina, magazinsko podnožje.|Brend lijevo, horizontalni meni, ograničen sadržaj, jednostavno podnožje.|Masthead zaglavlje, traka kategorija, mjera članka, podnožje u kolonama.|Minimalna gornja traka, full-bleed platno, mirno podnožje.|Kompaktna app traka, uska površina za čitanje, sitemap podnožje.|Zaglavlje u stilu aplikacije, CTA, površina s karticama, kolone podnožja.|Podijeljena navigacija, površine kategorija, gusto podnožje s linkovima.|Minimalna landing školjka, full-bleed builder, jaka CTA opcija.|sajberpank|žurnal|magazin|klasično|CMS|sigurno|objavljivanje|članci|vizuelno|rad|dokumentacija|čitanje|proizvod|CTA|kategorije|landing|kampanja",
  sl: "Cyber dnevnik|Klasični CMS|Uredniško|Portfelj|Dokumentacija|SaaS/Izdelek|Revija|Kampanja|Cyberpunk tema, omejena vsebina, običajna površina, revijalna noga.|Blagovna znamka levo, vodoravni meni, omejena vsebina, preprosta noga.|Masthead glava, pas kategorij, širina članka, noga v stolpcih.|Minimalna zgornja vrstica, full-bleed platno, mirna noga.|Kompaktna app vrstica, ozka bralna površina, sitemap noga.|Glava v slogu aplikacije, CTA, površina s karticami, stolpci noge.|Deljena navigacija, površine kategorij, gosto podnožje s povezavami.|Minimalna landing lupina, full-bleed builder, močna CTA možnost.|cyberpunk|dnevnik|revija|klasično|CMS|varno|objavljanje|članki|vizualno|delo|dokumenti|branje|izdelek|CTA|kategorije|landing|kampanja",
  ru: "Кибер-журнал|Классическая CMS|Редакционный|Портфолио|Документация|SaaS/Продукт|Журнал|Кампания|Киберпанк-тема, ограниченный контент, обычная поверхность, журнальный футер.|Бренд слева, горизонтальное меню, ограниченный контент, простой футер.|Masthead-заголовок, лента категорий, ширина статьи, футер колонками.|Минимальная верхняя панель, full-bleed холст, спокойный футер.|Компактная панель приложения, узкая область чтения, футер sitemap.|Заголовок в стиле приложения, CTA, карточная поверхность, колонки футера.|Разделенная навигация, поверхности категорий, плотные ссылки футера.|Минимальная landing-оболочка, full-bleed builder, сильная CTA-опция.|киберпанк|журнал|магазин|классический|CMS|безопасно|публикация|статьи|визуально|работа|документация|чтение|продукт|CTA|категории|landing|кампания",
  hu: "Kiber napló|Klasszikus CMS|Szerkesztőségi|Portfólió|Dokumentáció|SaaS/Termék|Magazin|Kampány|Cyberpunk téma, korlátozott tartalom, normál felület, magazin lábléc.|Márka bal oldalon, vízszintes menü, korlátozott tartalom, egyszerű lábléc.|Masthead fejléc, kategóriasáv, cikk-szélesség, oszlopos lábléc.|Minimális felső sáv, full-bleed vászon, nyugodt lábléc.|Kompakt app sáv, keskeny olvasási felület, sitemap lábléc.|App-stílusú fejléc, CTA, kártyaközpontú felület, láblécoszlopok.|Osztott navigáció, kategóriafelületek, sűrű lábléclinkek.|Minimális landing héj, full-bleed builder, erős CTA opció.|cyberpunk|napló|magazin|klasszikus|CMS|biztonságos|publikálás|cikkek|vizuális|munka|dokuk|olvasás|termék|CTA|kategóriák|landing|kampány",
  bg: "Кибер журнал|Класическа CMS|Редакционен|Портфолио|Документация|SaaS/Продукт|Списание|Кампания|Киберпънк тема, ограничено съдържание, нормална повърхност, списателен футър.|Бранд вляво, хоризонтално меню, ограничено съдържание, прост футър.|Masthead заглавка, лента с категории, ширина на статия, футър в колони.|Минимална горна лента, full-bleed платно, спокоен футър.|Компактна app лента, тясна зона за четене, sitemap футър.|Заглавка в стил приложение, CTA, повърхност с карти, колони във футъра.|Разделена навигация, повърхности за категории, плътни футър връзки.|Минимална landing обвивка, full-bleed builder, силна CTA опция.|киберпънк|журнал|списание|класически|CMS|безопасно|публикуване|статии|визуално|работа|документация|четене|продукт|CTA|категории|landing|кампания",
  ja: "サイバー・ジャーナル|クラシック CMS|エディトリアル|ポートフォリオ|ドキュメント|SaaS/製品|マガジン|キャンペーン|サイバーパンクテーマ、制限付きコンテンツ、通常サーフェス、マガジン型フッター。|左にブランド、水平メニュー、制限付きコンテンツ、シンプルなフッター。|マストヘッドヘッダー、カテゴリーレール、記事幅、カラムフッター。|最小限の上部クローム、full-bleed キャンバス、静かなフッター。|コンパクトなアプリバー、狭い読書面、サイトマップフッター。|アプリ風ヘッダー、CTA、カード中心のサーフェス、フッターカラム。|分割ナビゲーション、カテゴリー面、密なフッターリンク。|最小限のランディングシェル、full-bleed builder、強い CTA オプション。|サイバーパンク|ジャーナル|マガジン|クラシック|CMS|安全|公開|記事|ビジュアル|作品|ドキュメント|読書|製品|CTA|カテゴリー|ランディング|キャンペーン",
  "zh-Hans":
    "赛博期刊|经典 CMS|编辑版式|作品集|文档|SaaS/产品|杂志|活动|赛博朋克主题、受限内容、普通表面、杂志式页脚。|左侧品牌、水平菜单、受限内容、简单页脚。|报头式页眉、分类栏、文章宽度、列式页脚。|极简顶部框架、全宽画布、安静页脚。|紧凑应用栏、窄阅读表面、站点地图页脚。|应用风格页眉、CTA、卡片优先表面、页脚列。|分割导航、分类表面、密集页脚链接。|极简落地页外壳、全宽构建器、强 CTA 选项。|赛博朋克|期刊|杂志|经典|CMS|安全|发布|文章|视觉|作品|文档|阅读|产品|CTA|分类|落地页|活动",
  "zh-Hant":
    "賽博期刊|經典 CMS|編輯版式|作品集|文件|SaaS/產品|雜誌|活動|賽博龐克主題、受限內容、一般表面、雜誌式頁尾。|左側品牌、水平選單、受限內容、簡單頁尾。|報頭式頁首、分類列、文章寬度、欄式頁尾。|極簡頂部框架、全寬畫布、安靜頁尾。|緊湊應用列、窄閱讀表面、網站地圖頁尾。|應用風格頁首、CTA、卡片優先表面、頁尾欄。|分割導覽、分類表面、密集頁尾連結。|極簡 landing 外殼、全寬建構器、強 CTA 選項。|賽博龐克|期刊|雜誌|經典|CMS|安全|發布|文章|視覺|作品|文件|閱讀|產品|CTA|分類|landing|活動",
  ar: "يومية سايبر|CMS كلاسيكي|تحريري|معرض أعمال|توثيق|SaaS/منتج|مجلة|حملة|سمة سايبربانك، محتوى محدود، سطح عادي، تذييل مجلة.|علامة على اليسار، قائمة أفقية، محتوى محدود، تذييل بسيط.|ترويسة masthead، مسار فئات، عرض مقال، تذييل بأعمدة.|شريط علوي بسيط، لوحة full-bleed، تذييل هادئ.|شريط تطبيق مدمج، سطح قراءة ضيق، تذييل sitemap.|ترويسة بأسلوب التطبيق، CTA، سطح قائم على البطاقات، أعمدة تذييل.|تنقل مقسوم، أسطح فئات، روابط تذييل كثيفة.|غلاف landing بسيط، builder full-bleed، خيار CTA قوي.|سايبربانك|يومية|مجلة|كلاسيكي|CMS|آمن|نشر|مقالات|مرئي|عمل|توثيق|قراءة|منتج|CTA|فئات|landing|حملة",
  id: "Jurnal siber|CMS klasik|Editorial|Portofolio|Dokumentasi|SaaS/Produk|Majalah|Kampanye|Tema cyberpunk, konten terbatas, permukaan normal, footer majalah.|Merek di kiri, menu horizontal, konten terbatas, footer sederhana.|Header masthead, rel kategori, ukuran artikel, footer kolom.|Chrome atas minimal, kanvas full-bleed, footer tenang.|Bilah app ringkas, permukaan baca sempit, footer sitemap.|Header bergaya app, CTA, permukaan berbasis kartu, kolom footer.|Navigasi terbagi, permukaan kategori, tautan footer padat.|Shell landing minimal, builder full-bleed, opsi CTA kuat.|cyberpunk|jurnal|majalah|klasik|CMS|aman|penerbitan|artikel|visual|karya|dokumen|membaca|produk|CTA|kategori|landing|kampanye",
  cs: "Kyber deník|Klasické CMS|Redakční|Portfolium|Dokumentace|SaaS/Produkt|Magazín|Kampaň|Cyberpunk téma, omezený obsah, normální plocha, magazínové zápatí.|Značka vlevo, vodorovné menu, omezený obsah, jednoduché zápatí.|Masthead záhlaví, lišta kategorií, šířka článku, sloupcové zápatí.|Minimální horní chrome, full-bleed plátno, klidné zápatí.|Kompaktní app lišta, úzká čtecí plocha, sitemap zápatí.|Záhlaví ve stylu aplikace, CTA, plocha s kartami, sloupce zápatí.|Rozdělená navigace, plochy kategorií, husté odkazy v zápatí.|Minimální landing shell, full-bleed builder, silná CTA volba.|cyberpunk|deník|magazín|klasické|CMS|bezpečné|publikování|články|vizuální|práce|dokumentace|čtení|produkt|CTA|kategorie|landing|kampaň",
  ro: "Jurnal cyber|CMS clasic|Editorial|Portofoliu|Documentație|SaaS/Produs|Revistă|Campanie|Temă cyberpunk, conținut limitat, suprafață normală, subsol de revistă.|Marcă în stânga, meniu orizontal, conținut limitat, subsol simplu.|Antet masthead, bandă de categorii, măsură articol, subsol pe coloane.|Chrome superior minimal, canvas full-bleed, subsol discret.|Bară app compactă, suprafață de citire îngustă, subsol sitemap.|Antet tip aplicație, CTA, suprafață cu carduri, coloane de subsol.|Navigare împărțită, suprafețe de categorii, linkuri dense în subsol.|Shell landing minimal, builder full-bleed, opțiune CTA puternică.|cyberpunk|jurnal|revistă|clasic|CMS|sigur|publicare|articole|vizual|lucru|docs|citire|produs|CTA|categorii|landing|campanie",
  el: "Cyber ημερολόγιο|Κλασικό CMS|Εκδοτικό|Χαρτοφυλάκιο|Τεκμηρίωση|SaaS/Προϊόν|Περιοδικό|Καμπάνια|Cyberpunk θέμα, περιορισμένο περιεχόμενο, κανονική επιφάνεια, υποσέλιδο περιοδικού.|Επωνυμία αριστερά, οριζόντιο μενού, περιορισμένο περιεχόμενο, απλό υποσέλιδο.|Κεφαλίδα masthead, γραμμή κατηγοριών, μέτρο άρθρου, υποσέλιδο στηλών.|Ελάχιστο επάνω chrome, full-bleed καμβάς, ήσυχο υποσέλιδο.|Συμπαγής γραμμή app, στενή επιφάνεια ανάγνωσης, υποσέλιδο sitemap.|Κεφαλίδα τύπου εφαρμογής, CTA, επιφάνεια καρτών, στήλες υποσέλιδου.|Διαιρεμένη πλοήγηση, επιφάνειες κατηγοριών, πυκνοί σύνδεσμοι υποσέλιδου.|Ελάχιστο landing shell, full-bleed builder, ισχυρή επιλογή CTA.|cyberpunk|ημερολόγιο|περιοδικό|κλασικό|CMS|ασφαλές|δημοσίευση|άρθρα|οπτικό|εργασία|τεκμηρίωση|ανάγνωση|προϊόν|CTA|κατηγορίες|landing|καμπάνια",
  da: "Cyber-journal|Klassisk CMS|Redaktionel|Portefølje|Dokumentation|SaaS/Produkt|Magasin|Kampagne|Cyberpunk-tema, indrammet indhold, normal flade, magasin-footer.|Mærke til venstre, vandret menu, indrammet indhold, enkel footer.|Masthead-header, kategoribane, artikelmål, kolonne-footer.|Minimal top-chrome, full-bleed lærred, rolig footer.|Kompakt appbjælke, smal læseflade, sitemap-footer.|App-lignende header, CTA, kortfokuseret flade, footer-kolonner.|Delt navigation, kategoriflader, tætte footer-links.|Minimal landing-shell, full-bleed builder, stærk CTA-mulighed.|cyberpunk|journal|magasin|klassisk|CMS|sikker|publicering|artikler|visuel|arbejde|docs|læsning|produkt|CTA|kategorier|landing|kampagne",
  sv: "Cyberjournal|Klassiskt CMS|Redaktionell|Portfölj|Dokumentation|SaaS/Produkt|Magasin|Kampanj|Cyberpunk-tema, inneslutet innehåll, normal yta, magasinsidfot.|Varumärke till vänster, horisontell meny, inneslutet innehåll, enkel sidfot.|Masthead-sidhuvud, kategoriräls, artikelmått, kolumnsidfot.|Minimal toppchrome, full-bleed canvas, lugn sidfot.|Kompakt apprad, smal läsyta, sitemap-sidfot.|App-liknande sidhuvud, CTA, kortfokuserad yta, sidfotskolumner.|Delad navigering, kategoriytor, täta sidfotslänkar.|Minimal landing-shell, full-bleed builder, stark CTA-möjlighet.|cyberpunk|journal|magasin|klassisk|CMS|säker|publicering|artiklar|visuell|arbete|docs|läsning|produkt|CTA|kategorier|landing|kampanj",
  nb: "Cyber-journal|Klassisk CMS|Redaksjonell|Portefølje|Dokumentasjon|SaaS/Produkt|Magasin|Kampanje|Cyberpunk-tema, innholdsbundet innhold, normal flate, magasin-bunntekst.|Merkevare til venstre, horisontal meny, innholdsbundet innhold, enkel bunntekst.|Masthead-toppfelt, kategoribane, artikkelmål, bunntekst i kolonner.|Minimal toppchrome, full-bleed lerret, rolig bunntekst.|Kompakt applinje, smal leseflate, sitemap-bunntekst.|App-lignende toppfelt, CTA, kortfokusert flate, bunntekstkolonner.|Delt navigasjon, kategoriflater, tette bunntekstlenker.|Minimal landing-shell, full-bleed builder, sterk CTA-mulighet.|cyberpunk|journal|magasin|klassisk|CMS|trygg|publisering|artikler|visuell|arbeid|docs|lesing|produkt|CTA|kategorier|landing|kampanje",
  nn: "Cyber-journal|Klassisk CMS|Redaksjonell|Portefølje|Dokumentasjon|SaaS/Produkt|Magasin|Kampanje|Cyberpunk-tema, innhaldsbunde innhald, normal flate, magasin-botntekst.|Merkevare til venstre, horisontal meny, innhaldsbunde innhald, enkel botntekst.|Masthead-toppfelt, kategoribane, artikkelmål, botntekst i kolonnar.|Minimal toppchrome, full-bleed lerret, roleg botntekst.|Kompakt applinje, smal leseflate, sitemap-botntekst.|App-liknande toppfelt, CTA, kortfokusert flate, botntekstkolonnar.|Delt navigasjon, kategoriflater, tette botntekstlenkjer.|Minimal landing-shell, full-bleed builder, sterk CTA-moglegheit.|cyberpunk|journal|magasin|klassisk|CMS|trygg|publisering|artiklar|visuell|arbeid|docs|lesing|produkt|CTA|kategoriar|landing|kampanje",
  fi: "Cyber-journal|Klassinen CMS|Toimituksellinen|Portfolio|Dokumentaatio|SaaS/Tuote|Aikakauslehti|Kampanja|Cyberpunk-teema, rajattu sisältö, normaali pinta, lehtimäinen alatunniste.|Brändi vasemmalla, vaakavalikko, rajattu sisältö, yksinkertainen alatunniste.|Masthead-ylätunniste, kategoriakaista, artikkelin leveys, sarakealatunniste.|Minimaalinen ylächrome, full-bleed-kangas, rauhallinen alatunniste.|Kompakti app-palkki, kapea lukupinta, sitemap-alatunniste.|App-tyylinen ylätunniste, CTA, korttipainotteinen pinta, alatunnistesarakkeet.|Jaettu navigaatio, kategoriapinnat, tiheät alatunnistelinkit.|Minimaalinen landing-kuori, full-bleed builder, vahva CTA-vaihtoehto.|cyberpunk|journal|aikakauslehti|klassinen|CMS|turvallinen|julkaisu|artikkelit|visuaalinen|työ|dokut|lukeminen|tuote|CTA|kategoriat|landing|kampanja",
  is: "Cyber-dagbók|Klassískt CMS|Ritstjórnarlegt|Verkasafn|Skjölun|SaaS/Vara|Tímarit|Herferð|Cyberpunk-þema, afmarkað efni, venjulegt yfirborð, tímaritsfótur.|Vörumerki til vinstri, lárétt valmynd, afmarkað efni, einfaldur fótur.|Masthead-haus, flokkarönd, greinarmál, dálkafótur.|Lágmarks toppchrome, full-bleed strigi, rólegur fótur.|Þétt appstika, þröng lesflötur, sitemap-fótur.|App-líkur haus, CTA, spjaldamiðað yfirborð, fótdálkar.|Skipt leiðsögn, flokkayfirborð, þéttir fótartenglar.|Lágmarks landing-skel, full-bleed builder, sterkur CTA-valkostur.|cyberpunk|dagbók|tímarit|klassískt|CMS|öruggt|útgáfa|greinar|sjónrænt|vinna|skjöl|lestur|vara|CTA|flokkar|landing|herferð",
} satisfies Record<LocalizedLanguage, string>;

function createMap(language: string, row: string): Record<PresetSource, string> {
  const translations = row.split("|");
  if (translations.length !== GLOBAL_SETTINGS_PRESET_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} global settings preset translations must have ${GLOBAL_SETTINGS_PRESET_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    GLOBAL_SETTINGS_PRESET_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<PresetSource, string>;
}

export const GLOBAL_SETTINGS_PRESET_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<PresetSource, string>>;
