import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const GLOBAL_SETTINGS_FORM_SOURCE_STRINGS = [
  "Enter a valid hex color like #349aee or leave it blank.",
  "custom (px)",
  "e.g. 1200",
  "No matches found.",
  "Max-width in pixels. Layout stays responsive and centered (width: 100%, mx-auto).",
  "Show everywhere",
  "Show only on selected locations",
  "Deselect all",
  "Select all",
  "No options available.",
  "System Pages",
  "Pages",
  "Blog Posts",
  "Hero Sliders",
  "Webshops",
  "Blog Categories",
  "Blog category",
  "Admin/backend Pages",
  "Without menu",
  "Enter a valid hex color like #fff or #ffffff.",
  "Enter a valid hex color like #fff or #ffffff, or leave it blank.",
  "{bytes} bytes",
] as const;

type FormSource = (typeof GLOBAL_SETTINGS_FORM_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "Unesi važeću hex boju kao #349aee ili ostavi prazno.|prilagođeno (px)|npr. 1200|Nema rezultata.|Maksimalna širina u pikselima. Raspored ostaje responzivan i centriran (width: 100%, mx-auto).|Prikaži svuda|Prikaži samo na izabranim lokacijama|Poništi izbor svega|Izaberi sve|Nema dostupnih opcija.|Sistemske stranice|Stranice|Blog postovi|Hero slajderi|Webshopovi|Blog kategorije|Blog kategorija|Admin/backend stranice|Bez menija|Unesi važeću hex boju kao #fff ili #ffffff.|Unesi važeću hex boju kao #fff ili #ffffff, ili ostavi prazno.|{bytes} bajtova",
  "sr-Cyrl":
    "Унеси важећу hex боју као #349aee или остави празно.|прилагођено (px)|нпр. 1200|Нема резултата.|Максимална ширина у пикселима. Распоред остаје респонзиван и центриран (width: 100%, mx-auto).|Прикажи свуда|Прикажи само на изабраним локацијама|Поништи избор свега|Изабери све|Нема доступних опција.|Системске странице|Странице|Блог постови|Hero слајдери|Webshopови|Блог категорије|Блог категорија|Admin/backend странице|Без менија|Унеси важећу hex боју као #fff или #ffffff.|Унеси важећу hex боју као #fff или #ffffff, или остави празно.|{bytes} бајтова",
  hr: "Unesite valjanu hex boju kao #349aee ili ostavite prazno.|prilagođeno (px)|npr. 1200|Nema rezultata.|Maksimalna širina u pikselima. Raspored ostaje responzivan i centriran (width: 100%, mx-auto).|Prikaži svugdje|Prikaži samo na odabranim lokacijama|Poništi odabir svega|Odaberi sve|Nema dostupnih opcija.|Sistemske stranice|Stranice|Blog objave|Hero slajderi|Web-trgovine|Blog kategorije|Blog kategorija|Admin/backend stranice|Bez izbornika|Unesite valjanu hex boju kao #fff ili #ffffff.|Unesite valjanu hex boju kao #fff ili #ffffff, ili ostavite prazno.|{bytes} bajtova",
  de: "Gib eine gültige Hex-Farbe wie #349aee ein oder lasse das Feld leer.|benutzerdefiniert (px)|z. B. 1200|Keine Treffer gefunden.|Maximale Breite in Pixeln. Das Layout bleibt responsiv und zentriert (width: 100%, mx-auto).|Überall anzeigen|Nur an ausgewählten Orten anzeigen|Alle abwählen|Alle auswählen|Keine Optionen verfügbar.|Systemseiten|Seiten|Blogbeiträge|Hero-Slider|Webshops|Blogkategorien|Blogkategorie|Admin-/Backend-Seiten|Ohne Menü|Gib eine gültige Hex-Farbe wie #fff oder #ffffff ein.|Gib eine gültige Hex-Farbe wie #fff oder #ffffff ein oder lasse das Feld leer.|{bytes} Byte",
  fr: "Saisissez une couleur hex valide comme #349aee ou laissez vide.|personnalisé (px)|p. ex. 1200|Aucun résultat trouvé.|Largeur maximale en pixels. La mise en page reste responsive et centrée (width: 100%, mx-auto).|Afficher partout|Afficher uniquement aux emplacements sélectionnés|Tout désélectionner|Tout sélectionner|Aucune option disponible.|Pages système|Pages du site|Articles de blog|Sliders hero|Boutiques web|Catégories de blog|Catégorie de blog|Pages admin/backend|Sans menu|Saisissez une couleur hex valide comme #fff ou #ffffff.|Saisissez une couleur hex valide comme #fff ou #ffffff, ou laissez vide.|{bytes} octets",
  es: "Introduce un color hex válido como #349aee o déjalo vacío.|personalizado (px)|p. ej. 1200|No se encontraron coincidencias.|Ancho máximo en píxeles. El diseño sigue siendo adaptable y centrado (width: 100%, mx-auto).|Mostrar en todas partes|Mostrar solo en ubicaciones seleccionadas|Deseleccionar todo|Seleccionar todo|No hay opciones disponibles.|Páginas del sistema|Páginas|Entradas de blog|Sliders hero|Tiendas web|Categorías de blog|Categoría de blog|Páginas admin/backend|Sin menú|Introduce un color hex válido como #fff o #ffffff.|Introduce un color hex válido como #fff o #ffffff, o déjalo vacío.|{bytes} octetos",
  it: "Inserisci un colore hex valido come #349aee o lascia vuoto.|personalizzato (px)|es. 1200|Nessuna corrispondenza trovata.|Larghezza massima in pixel. Il layout resta responsive e centrato (width: 100%, mx-auto).|Mostra ovunque|Mostra solo nelle posizioni selezionate|Deseleziona tutto|Seleziona tutto|Nessuna opzione disponibile.|Pagine di sistema|Pagine|Post del blog|Slider hero|Webshop|Categorie blog|Categoria blog|Pagine admin/backend|Senza menu|Inserisci un colore hex valido come #fff o #ffffff.|Inserisci un colore hex valido come #fff o #ffffff, oppure lascia vuoto.|{bytes} byte",
  pt: "Introduza uma cor hex válida como #349aee ou deixe em branco.|personalizado (px)|ex. 1200|Nenhuma correspondência encontrada.|Largura máxima em píxeis. O layout permanece responsivo e centrado (width: 100%, mx-auto).|Mostrar em todo o lado|Mostrar apenas nas localizações selecionadas|Desselecionar tudo|Selecionar tudo|Nenhuma opção disponível.|Páginas do sistema|Páginas|Publicações do blog|Sliders hero|Lojas web|Categorias do blog|Categoria do blog|Páginas admin/backend|Sem menu|Introduza uma cor hex válida como #fff ou #ffffff.|Introduza uma cor hex válida como #fff ou #ffffff, ou deixe em branco.|{bytes} octetos",
  "pt-BR":
    "Informe uma cor hex válida como #349aee ou deixe em branco.|personalizado (px)|ex. 1200|Nenhuma correspondência encontrada.|Largura máxima em pixels. O layout permanece responsivo e centralizado (width: 100%, mx-auto).|Mostrar em todos os lugares|Mostrar apenas nos locais selecionados|Desmarcar tudo|Selecionar tudo|Nenhuma opção disponível.|Páginas do sistema|Páginas|Posts do blog|Sliders hero|Lojas virtuais|Categorias do blog|Categoria do blog|Páginas admin/backend|Sem menu|Informe uma cor hex válida como #fff ou #ffffff.|Informe uma cor hex válida como #fff ou #ffffff, ou deixe em branco.|{bytes} octetos",
  nl: "Voer een geldige hex-kleur in zoals #349aee of laat leeg.|aangepast (px)|bijv. 1200|Geen overeenkomsten gevonden.|Maximale breedte in pixels. De layout blijft responsief en gecentreerd (width: 100%, mx-auto).|Overal weergeven|Alleen op geselecteerde locaties weergeven|Alles deselecteren|Alles selecteren|Geen opties beschikbaar.|Systeempagina's|Pagina's|Blogberichten|Hero-sliders|Webshops|Blogcategorieën|Blogcategorie|Admin/backend-pagina's|Zonder menu|Voer een geldige hex-kleur in zoals #fff of #ffffff.|Voer een geldige hex-kleur in zoals #fff of #ffffff, of laat leeg.|{bytes} byte",
  pl: "Wpisz prawidłowy kolor hex, np. #349aee, albo zostaw puste.|niestandardowe (px)|np. 1200|Nie znaleziono dopasowań.|Maksymalna szerokość w pikselach. Układ pozostaje responsywny i wyśrodkowany (width: 100%, mx-auto).|Pokaż wszędzie|Pokaż tylko w wybranych lokalizacjach|Odznacz wszystko|Zaznacz wszystko|Brak dostępnych opcji.|Strony systemowe|Strony|Wpisy bloga|Slidery hero|Sklepy web|Kategorie bloga|Kategoria bloga|Strony admin/backend|Bez menu|Wpisz prawidłowy kolor hex, np. #fff lub #ffffff.|Wpisz prawidłowy kolor hex, np. #fff lub #ffffff, albo zostaw puste.|{bytes} bajtów",
  tr: "#349aee gibi geçerli bir hex renk girin veya boş bırakın.|özel (px)|örn. 1200|Eşleşme bulunamadı.|Piksel cinsinden maksimum genişlik. Düzen duyarlı ve ortalanmış kalır (width: 100%, mx-auto).|Her yerde göster|Yalnızca seçilen konumlarda göster|Tüm seçimleri kaldır|Tümünü seç|Kullanılabilir seçenek yok.|Sistem sayfaları|Sayfalar|Blog yazıları|Hero kaydırıcıları|Web mağazaları|Blog kategorileri|Blog kategorisi|Admin/backend sayfaları|Menüsüz|#fff veya #ffffff gibi geçerli bir hex renk girin.|#fff veya #ffffff gibi geçerli bir hex renk girin ya da boş bırakın.|{bytes} bayt",
  mk: "Внесете валидна hex боја како #349aee или оставете празно.|прилагодено (px)|на пр. 1200|Нема пронајдени совпаѓања.|Максимална ширина во пиксели. Распоредот останува респонзивен и центриран (width: 100%, mx-auto).|Прикажи насекаде|Прикажи само на избрани локации|Откажи избор на сите|Избери сите|Нема достапни опции.|Системски страници|Страници|Блог објави|Hero слајдери|Webshopови|Блог категории|Блог категорија|Admin/backend страници|Без мени|Внесете валидна hex боја како #fff или #ffffff.|Внесете валидна hex боја како #fff или #ffffff, или оставете празно.|{bytes} бајти",
  bs: "Unesite važeću hex boju kao #349aee ili ostavite prazno.|prilagođeno (px)|npr. 1200|Nema rezultata.|Maksimalna širina u pikselima. Raspored ostaje responzivan i centriran (width: 100%, mx-auto).|Prikaži svuda|Prikaži samo na odabranim lokacijama|Poništi odabir svega|Izaberi sve|Nema dostupnih opcija.|Sistemske stranice|Stranice|Blog objave|Hero slajderi|Webshopovi|Blog kategorije|Blog kategorija|Admin/backend stranice|Bez menija|Unesite važeću hex boju kao #fff ili #ffffff.|Unesite važeću hex boju kao #fff ili #ffffff, ili ostavite prazno.|{bytes} bajtova",
  sl: "Vnesite veljavno hex barvo, npr. #349aee, ali pustite prazno.|po meri (px)|npr. 1200|Ni zadetkov.|Največja širina v slikovnih pikah. Postavitev ostane odzivna in centrirana (width: 100%, mx-auto).|Prikaži povsod|Prikaži samo na izbranih lokacijah|Počisti izbor vseh|Izberi vse|Ni razpoložljivih možnosti.|Sistemske strani|Strani|Blog objave|Hero drsniki|Spletne trgovine|Blog kategorije|Blog kategorija|Admin/backend strani|Brez menija|Vnesite veljavno hex barvo, npr. #fff ali #ffffff.|Vnesite veljavno hex barvo, npr. #fff ali #ffffff, ali pustite prazno.|{bytes} bajtov",
  ru: "Введите допустимый hex-цвет, например #349aee, или оставьте пустым.|пользовательское (px)|например, 1200|Совпадений не найдено.|Максимальная ширина в пикселях. Макет остаётся адаптивным и центрированным (width: 100%, mx-auto).|Показывать везде|Показывать только в выбранных местах|Снять выбор со всего|Выбрать всё|Нет доступных вариантов.|Системные страницы|Страницы|Записи блога|Hero-слайдеры|Веб-магазины|Категории блога|Категория блога|Страницы admin/backend|Без меню|Введите допустимый hex-цвет, например #fff или #ffffff.|Введите допустимый hex-цвет, например #fff или #ffffff, или оставьте пустым.|{bytes} байт",
  hu: "Adjon meg érvényes hex színt, például #349aee, vagy hagyja üresen.|egyéni (px)|pl. 1200|Nincs találat.|Maximális szélesség pixelben. Az elrendezés reszponzív és középre igazított marad (width: 100%, mx-auto).|Megjelenítés mindenhol|Megjelenítés csak a kiválasztott helyeken|Összes kijelölés törlése|Összes kijelölése|Nincs elérhető opció.|Rendszeroldalak|Oldalak|Blogbejegyzések|Hero sliderek|Webshopok|Blogkategóriák|Blogkategória|Admin/backend oldalak|Menü nélkül|Adjon meg érvényes hex színt, például #fff vagy #ffffff.|Adjon meg érvényes hex színt, például #fff vagy #ffffff, vagy hagyja üresen.|{bytes} bájt",
  bg: "Въведете валиден hex цвят като #349aee или оставете празно.|персонализирано (px)|напр. 1200|Няма намерени съвпадения.|Максимална ширина в пиксели. Оформлението остава адаптивно и центрирано (width: 100%, mx-auto).|Показвай навсякъде|Показвай само на избрани места|Премахни избора на всички|Избери всички|Няма налични опции.|Системни страници|Страници|Блог публикации|Hero слайдери|Webshop-и|Блог категории|Блог категория|Admin/backend страници|Без меню|Въведете валиден hex цвят като #fff или #ffffff.|Въведете валиден hex цвят като #fff или #ffffff, или оставете празно.|{bytes} байта",
  ja: "#349aee のような有効な hex カラーを入力するか、空欄にしてください。|カスタム (px)|例: 1200|一致する結果がありません。|ピクセル単位の最大幅です。レイアウトはレスポンシブで中央揃えのままです (width: 100%, mx-auto)。|すべての場所に表示|選択した場所のみに表示|すべて選択解除|すべて選択|利用可能なオプションはありません。|システムページ|ページ|ブログ投稿|Hero スライダー|Webショップ|ブログカテゴリ|ブログカテゴリ|Admin/backend ページ|メニューなし|#fff または #ffffff のような有効な hex カラーを入力してください。|#fff または #ffffff のような有効な hex カラーを入力するか、空欄にしてください。|{bytes} バイト",
  "zh-Hans":
    "请输入有效的 hex 颜色，例如 #349aee，或留空。|自定义 (px)|例如 1200|未找到匹配项。|以像素为单位的最大宽度。布局会保持响应式并居中 (width: 100%, mx-auto)。|在所有位置显示|仅在所选位置显示|取消全选|全选|没有可用选项。|系统页面|页面|博客文章|Hero 轮播|网上商店|博客分类|博客分类|Admin/backend 页面|不使用菜单|请输入有效的 hex 颜色，例如 #fff 或 #ffffff。|请输入有效的 hex 颜色，例如 #fff 或 #ffffff，或留空。|{bytes} 字节",
  "zh-Hant":
    "請輸入有效的 hex 顏色，例如 #349aee，或留空。|自訂 (px)|例如 1200|找不到相符項目。|以像素為單位的最大寬度。版面會保持響應式並置中 (width: 100%, mx-auto)。|在所有位置顯示|僅在所選位置顯示|取消全選|全選|沒有可用選項。|系統頁面|頁面|部落格文章|Hero 輪播|網路商店|部落格分類|部落格分類|Admin/backend 頁面|不使用選單|請輸入有效的 hex 顏色，例如 #fff 或 #ffffff。|請輸入有效的 hex 顏色，例如 #fff 或 #ffffff，或留空。|{bytes} 位元組",
  ar: "أدخل لون hex صالحًا مثل #349aee أو اتركه فارغًا.|مخصص (px)|مثل 1200|لم يتم العثور على مطابقات.|أقصى عرض بالبكسل. يبقى التخطيط متجاوبًا وموسّطًا (width: 100%, mx-auto).|إظهار في كل مكان|إظهار في المواقع المحددة فقط|إلغاء تحديد الكل|تحديد الكل|لا توجد خيارات متاحة.|صفحات النظام|الصفحات|مقالات المدونة|شرائح Hero|متاجر الويب|فئات المدونة|فئة المدونة|صفحات admin/backend|بدون قائمة|أدخل لون hex صالحًا مثل #fff أو #ffffff.|أدخل لون hex صالحًا مثل #fff أو #ffffff، أو اتركه فارغًا.|{bytes} بايت",
  id: "Masukkan warna hex yang valid seperti #349aee atau biarkan kosong.|khusus (px)|mis. 1200|Tidak ada kecocokan ditemukan.|Lebar maksimum dalam piksel. Tata letak tetap responsif dan berada di tengah (width: 100%, mx-auto).|Tampilkan di semua tempat|Tampilkan hanya di lokasi yang dipilih|Batalkan pilih semua|Pilih semua|Tidak ada opsi tersedia.|Halaman sistem|Halaman|Posting blog|Slider hero|Webshop|Kategori blog|Kategori blog|Halaman admin/backend|Tanpa menu|Masukkan warna hex yang valid seperti #fff atau #ffffff.|Masukkan warna hex yang valid seperti #fff atau #ffffff, atau biarkan kosong.|{bytes} byte",
  cs: "Zadejte platnou hex barvu, například #349aee, nebo nechte prázdné.|vlastní (px)|např. 1200|Nebyla nalezena žádná shoda.|Maximální šířka v pixelech. Rozvržení zůstane responzivní a vycentrované (width: 100%, mx-auto).|Zobrazit všude|Zobrazit pouze ve vybraných umístěních|Zrušit výběr všeho|Vybrat vše|Nejsou dostupné žádné možnosti.|Systémové stránky|Stránky|Blogové příspěvky|Hero slidery|Webshopy|Kategorie blogu|Kategorie blogu|Admin/backend stránky|Bez menu|Zadejte platnou hex barvu, například #fff nebo #ffffff.|Zadejte platnou hex barvu, například #fff nebo #ffffff, nebo nechte prázdné.|{bytes} bajtů",
  ro: "Introduceți o culoare hex validă, precum #349aee, sau lăsați gol.|personalizat (px)|ex. 1200|Nu s-au găsit potriviri.|Lățime maximă în pixeli. Aspectul rămâne responsiv și centrat (width: 100%, mx-auto).|Afișează peste tot|Afișează doar în locațiile selectate|Deselectează tot|Selectează tot|Nu există opțiuni disponibile.|Pagini de sistem|Pagini|Articole de blog|Slidere hero|Magazine web|Categorii blog|Categorie blog|Pagini admin/backend|Fără meniu|Introduceți o culoare hex validă, precum #fff sau #ffffff.|Introduceți o culoare hex validă, precum #fff sau #ffffff, sau lăsați gol.|{bytes} octeți",
  el: "Εισαγάγετε έγκυρο hex χρώμα όπως #349aee ή αφήστε το κενό.|προσαρμοσμένο (px)|π.χ. 1200|Δεν βρέθηκαν αντιστοιχίες.|Μέγιστο πλάτος σε pixel. Η διάταξη παραμένει responsive και κεντραρισμένη (width: 100%, mx-auto).|Εμφάνιση παντού|Εμφάνιση μόνο στις επιλεγμένες τοποθεσίες|Αποεπιλογή όλων|Επιλογή όλων|Δεν υπάρχουν διαθέσιμες επιλογές.|Σελίδες συστήματος|Σελίδες|Αναρτήσεις blog|Hero sliders|Webshops|Κατηγορίες blog|Κατηγορία blog|Σελίδες admin/backend|Χωρίς μενού|Εισαγάγετε έγκυρο hex χρώμα όπως #fff ή #ffffff.|Εισαγάγετε έγκυρο hex χρώμα όπως #fff ή #ffffff, ή αφήστε το κενό.|{bytes} byte",
  da: "Indtast en gyldig hex-farve som #349aee, eller lad feltet være tomt.|brugerdefineret (px)|f.eks. 1200|Ingen matches fundet.|Maksimal bredde i pixels. Layoutet forbliver responsivt og centreret (width: 100%, mx-auto).|Vis overalt|Vis kun på valgte placeringer|Fravælg alle|Vælg alle|Ingen tilgængelige muligheder.|Systemsider|Sider|Blogindlæg|Hero-slidere|Webshops|Blogkategorier|Blogkategori|Admin/backend-sider|Uden menu|Indtast en gyldig hex-farve som #fff eller #ffffff.|Indtast en gyldig hex-farve som #fff eller #ffffff, eller lad feltet være tomt.|{bytes} byte",
  sv: "Ange en giltig hex-färg som #349aee eller lämna tomt.|anpassad (px)|t.ex. 1200|Inga träffar hittades.|Maximal bredd i pixlar. Layouten förblir responsiv och centrerad (width: 100%, mx-auto).|Visa överallt|Visa endast på valda platser|Avmarkera alla|Markera alla|Inga alternativ tillgängliga.|Systemsidor|Sidor|Blogginlägg|Hero-bildspel|Webbshoppar|Bloggkategorier|Bloggkategori|Admin/backend-sidor|Utan meny|Ange en giltig hex-färg som #fff eller #ffffff.|Ange en giltig hex-färg som #fff eller #ffffff, eller lämna tomt.|{bytes} byte",
  nb: "Skriv inn en gyldig hex-farge som #349aee, eller la feltet stå tomt.|egendefinert (px)|f.eks. 1200|Ingen treff funnet.|Maksimal bredde i piksler. Oppsettet forblir responsivt og sentrert (width: 100%, mx-auto).|Vis overalt|Vis bare på valgte plasseringer|Fjern alle valg|Velg alle|Ingen alternativer tilgjengelig.|Systemsider|Sider|Blogginnlegg|Hero-slidere|Webshops|Bloggkategorier|Bloggkategori|Admin/backend-sider|Uten meny|Skriv inn en gyldig hex-farge som #fff eller #ffffff.|Skriv inn en gyldig hex-farge som #fff eller #ffffff, eller la feltet stå tomt.|{bytes} byte",
  nn: "Skriv inn ein gyldig hex-farge som #349aee, eller la feltet stå tomt.|eigendefinert (px)|t.d. 1200|Ingen treff funne.|Maksimal breidd i pikslar. Oppsettet held seg responsivt og sentrert (width: 100%, mx-auto).|Vis overalt|Vis berre på valde plasseringar|Fjern alle val|Vel alle|Ingen alternativ tilgjengelege.|Systemsider|Sider|Blogginnlegg|Hero-slidarar|Webshops|Bloggkategoriar|Bloggkategori|Admin/backend-sider|Utan meny|Skriv inn ein gyldig hex-farge som #fff eller #ffffff.|Skriv inn ein gyldig hex-farge som #fff eller #ffffff, eller la feltet stå tomt.|{bytes} byte",
  fi: "Anna kelvollinen hex-väri, kuten #349aee, tai jätä tyhjäksi.|mukautettu (px)|esim. 1200|Osumia ei löytynyt.|Enimmäisleveys pikseleinä. Asettelu pysyy responsiivisena ja keskitettynä (width: 100%, mx-auto).|Näytä kaikkialla|Näytä vain valituissa sijainneissa|Poista kaikki valinnat|Valitse kaikki|Vaihtoehtoja ei ole saatavilla.|Järjestelmäsivut|Sivut|Blogikirjoitukset|Hero-liukusäätimet|Verkkokaupat|Blogikategoriat|Blogikategoria|Admin/backend-sivut|Ilman valikkoa|Anna kelvollinen hex-väri, kuten #fff tai #ffffff.|Anna kelvollinen hex-väri, kuten #fff tai #ffffff, tai jätä tyhjäksi.|{bytes} tavua",
  is: "Sláðu inn gildan hex-lit eins og #349aee eða skildu eftir autt.|sérsniðið (px)|t.d. 1200|Engar samsvaranir fundust.|Hámarksbreidd í pixlum. Útlitið helst svarvirkt og miðjað (width: 100%, mx-auto).|Sýna alls staðar|Sýna aðeins á völdum stöðum|Afvelja allt|Velja allt|Engir valkostir í boði.|Kerfissíður|Síður|Bloggfærslur|Hero-rennur|Vefverslanir|Bloggflokkar|Bloggflokkur|Admin/backend-síður|Án valmyndar|Sláðu inn gildan hex-lit eins og #fff eða #ffffff.|Sláðu inn gildan hex-lit eins og #fff eða #ffffff, eða skildu eftir autt.|{bytes} bæti",
} satisfies Record<LocalizedLanguage, string>;

function createMap(language: string, row: string): Record<FormSource, string> {
  const translations = row.split("|");
  if (translations.length !== GLOBAL_SETTINGS_FORM_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} global settings form translations must have ${GLOBAL_SETTINGS_FORM_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    GLOBAL_SETTINGS_FORM_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<FormSource, string>;
}

export const GLOBAL_SETTINGS_FORM_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<FormSource, string>>;
