import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const GLOBAL_SETTINGS_SESSION_SOURCE_STRINGS = [
  "{minutes} minutes = {human}. Absolute lifetime - user is signed out when this elapses regardless of activity.",
  "Enter a whole number between {min} and {max}.",
  "Users are signed out after {minutes} minutes without activity.",
  "{minutes} minutes = {human}. Sliding window - reset by user activity; a warning appears before sign-out.",
  "Enter a whole number of at least {min}.",
  "Idle logout cannot exceed max session duration.",
  "Note: for hard server-side enforcement, also configure Clerk's session token lifetime in the Clerk dashboard to match the max session duration.",
] as const;

type SessionSource = (typeof GLOBAL_SETTINGS_SESSION_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "{minutes} minuta = {human}. Apsolutno trajanje - korisnik se odjavljuje kada ovo vreme istekne, bez obzira na aktivnost.|Unesi ceo broj između {min} i {max}.|Korisnici se odjavljuju posle {minutes} minuta bez aktivnosti.|{minutes} minuta = {human}. Klizni prozor - resetuje se aktivnošću korisnika; upozorenje se prikazuje pre odjave.|Unesi ceo broj od najmanje {min}.|Odjava zbog neaktivnosti ne može biti duža od maksimalnog trajanja sesije.|Napomena: za čvrstu serversku primenu, podesi i trajanje Clerk session tokena u Clerk kontrolnoj tabli tako da odgovara maksimalnom trajanju sesije.",
  "sr-Cyrl":
    "{minutes} минута = {human}. Апсолутно трајање - корисник се одјављује када ово време истекне, без обзира на активност.|Унеси цео број између {min} и {max}.|Корисници се одјављују после {minutes} минута без активности.|{minutes} минута = {human}. Клизни прозор - ресетује се активношћу корисника; упозорење се приказује пре одјаве.|Унеси цео број од најмање {min}.|Одјава због неактивности не може бити дужа од максималног трајања сесије.|Напомена: за чврсту серверску примену, подеси и трајање Clerk session tokenа у Clerk контролној табли тако да одговара максималном трајању сесије.",
  hr: "{minutes} minuta = {human}. Apsolutno trajanje - korisnik se odjavljuje kada to vrijeme istekne, bez obzira na aktivnost.|Unesite cijeli broj između {min} i {max}.|Korisnici se odjavljuju nakon {minutes} minuta bez aktivnosti.|{minutes} minuta = {human}. Klizni prozor - resetira se korisničkom aktivnošću; upozorenje se prikazuje prije odjave.|Unesite cijeli broj od najmanje {min}.|Odjava zbog neaktivnosti ne može premašiti maksimalno trajanje sesije.|Napomena: za strogu provedbu na serveru, u Clerk nadzornoj ploči podesite i trajanje Clerk tokena sesije tako da odgovara maksimalnom trajanju sesije.",
  de: "{minutes} Minuten = {human}. Absolute Laufzeit - der Benutzer wird unabhängig von Aktivität abgemeldet, sobald diese Zeit abläuft.|Gib eine ganze Zahl zwischen {min} und {max} ein.|Benutzer werden nach {minutes} Minuten ohne Aktivität abgemeldet.|{minutes} Minuten = {human}. Gleitendes Fenster - wird durch Benutzeraktivität zurückgesetzt; vor der Abmeldung erscheint eine Warnung.|Gib eine ganze Zahl von mindestens {min} ein.|Die Inaktivitätsabmeldung darf die maximale Sitzungsdauer nicht überschreiten.|Hinweis: Für eine strikte serverseitige Durchsetzung konfiguriere auch die Lebensdauer des Clerk-Sitzungstokens im Clerk-Dashboard passend zur maximalen Sitzungsdauer.",
  fr: "{minutes} minutes = {human}. Durée absolue - l'utilisateur est déconnecté lorsque ce délai expire, quelle que soit son activité.|Saisissez un nombre entier entre {min} et {max}.|Les utilisateurs sont déconnectés après {minutes} minutes sans activité.|{minutes} minutes = {human}. Fenêtre glissante - réinitialisée par l'activité de l'utilisateur; un avertissement s'affiche avant la déconnexion.|Saisissez un nombre entier d'au moins {min}.|La déconnexion pour inactivité ne peut pas dépasser la durée maximale de session.|Remarque : pour une application stricte côté serveur, configurez aussi la durée de vie du jeton de session Clerk dans le tableau de bord Clerk afin qu'elle corresponde à la durée maximale de session.",
  es: "{minutes} minutos = {human}. Duración absoluta - el usuario se desconecta cuando vence este tiempo, sin importar la actividad.|Introduce un número entero entre {min} y {max}.|Los usuarios se desconectan después de {minutes} minutos sin actividad.|{minutes} minutos = {human}. Ventana deslizante - se reinicia con la actividad del usuario; aparece una advertencia antes de cerrar sesión.|Introduce un número entero de al menos {min}.|El cierre por inactividad no puede superar la duración máxima de la sesión.|Nota: para una aplicación estricta del lado del servidor, configura también la duración del token de sesión de Clerk en el panel de Clerk para que coincida con la duración máxima de la sesión.",
  it: "{minutes} minuti = {human}. Durata assoluta - l'utente viene disconnesso allo scadere di questo tempo, indipendentemente dall'attività.|Inserisci un numero intero tra {min} e {max}.|Gli utenti vengono disconnessi dopo {minutes} minuti senza attività.|{minutes} minuti = {human}. Finestra mobile - viene reimpostata dall'attività dell'utente; prima della disconnessione appare un avviso.|Inserisci un numero intero di almeno {min}.|La disconnessione per inattività non può superare la durata massima della sessione.|Nota: per un'applicazione rigorosa lato server, configura anche la durata del token di sessione Clerk nel dashboard Clerk in modo che corrisponda alla durata massima della sessione.",
  pt: "{minutes} minutos = {human}. Duração absoluta - o utilizador termina sessão quando este tempo expira, independentemente da atividade.|Introduza um número inteiro entre {min} e {max}.|Os utilizadores terminam sessão após {minutes} minutos sem atividade.|{minutes} minutos = {human}. Janela deslizante - é reposta pela atividade do utilizador; surge um aviso antes de terminar sessão.|Introduza um número inteiro de pelo menos {min}.|A saída por inatividade não pode exceder a duração máxima da sessão.|Nota: para aplicação rígida do lado do servidor, configure também a duração do token de sessão do Clerk no painel do Clerk para corresponder à duração máxima da sessão.",
  "pt-BR":
    "{minutes} minutos = {human}. Duração absoluta - o usuário sai da sessão quando esse tempo expira, independentemente da atividade.|Informe um número inteiro entre {min} e {max}.|Os usuários saem da sessão após {minutes} minutos sem atividade.|{minutes} minutos = {human}. Janela deslizante - reiniciada pela atividade do usuário; um aviso aparece antes da saída.|Informe um número inteiro de pelo menos {min}.|A saída por inatividade não pode exceder a duração máxima da sessão.|Observação: para aplicação rígida no servidor, configure também a duração do token de sessão do Clerk no painel do Clerk para corresponder à duração máxima da sessão.",
  nl: "{minutes} minuten = {human}. Absolute duur - de gebruiker wordt afgemeld zodra deze tijd verstrijkt, ongeacht activiteit.|Voer een geheel getal tussen {min} en {max} in.|Gebruikers worden afgemeld na {minutes} minuten zonder activiteit.|{minutes} minuten = {human}. Schuivend venster - wordt opnieuw ingesteld door gebruikersactiviteit; er verschijnt een waarschuwing vóór het afmelden.|Voer een geheel getal van minimaal {min} in.|Afmelden wegens inactiviteit mag de maximale sessieduur niet overschrijden.|Opmerking: configureer voor strikte server-side handhaving ook de levensduur van het Clerk-sessietoken in het Clerk-dashboard zodat die overeenkomt met de maximale sessieduur.",
  pl: "{minutes} minut = {human}. Bezwzględny czas trwania - użytkownik zostanie wylogowany po jego upływie, niezależnie od aktywności.|Wpisz liczbę całkowitą od {min} do {max}.|Użytkownicy są wylogowywani po {minutes} minutach braku aktywności.|{minutes} minut = {human}. Okno przesuwne - resetowane przez aktywność użytkownika; przed wylogowaniem pojawi się ostrzeżenie.|Wpisz liczbę całkowitą co najmniej {min}.|Wylogowanie z powodu bezczynności nie może przekraczać maksymalnego czasu trwania sesji.|Uwaga: aby wymuszać to rygorystycznie po stronie serwera, skonfiguruj też czas życia tokena sesji Clerk w panelu Clerk tak, aby odpowiadał maksymalnemu czasowi trwania sesji.",
  tr: "{minutes} dakika = {human}. Mutlak süre - bu süre dolduğunda kullanıcı etkinlikten bağımsız olarak oturumdan çıkarılır.|{min} ile {max} arasında bir tam sayı girin.|Kullanıcılar {minutes} dakika işlem yapmadığında oturumdan çıkarılır.|{minutes} dakika = {human}. Kayan pencere - kullanıcı etkinliğiyle sıfırlanır; oturum kapatılmadan önce uyarı gösterilir.|En az {min} olan bir tam sayı girin.|Boşta kalma çıkışı en uzun oturum süresini aşamaz.|Not: sunucu tarafında kesin uygulama için Clerk panosunda Clerk oturum token ömrünü de en uzun oturum süresiyle eşleşecek şekilde yapılandırın.",
  mk: "{minutes} минути = {human}. Апсолутно траење - корисникот се одјавува кога ќе истече ова време, без оглед на активноста.|Внесете цел број помеѓу {min} и {max}.|Корисниците се одјавуваат по {minutes} минути без активност.|{minutes} минути = {human}. Лизгачки прозорец - се ресетира со корисничка активност; предупредување се прикажува пред одјавување.|Внесете цел број од најмалку {min}.|Одјавата поради неактивност не може да го надмине максималното траење на сесијата.|Напомена: за строга серверска примена, во Clerk контролната табла конфигурирајте го и траењето на Clerk session token да одговара на максималното траење на сесијата.",
  bs: "{minutes} minuta = {human}. Apsolutno trajanje - korisnik se odjavljuje kada ovo vrijeme istekne, bez obzira na aktivnost.|Unesite cijeli broj između {min} i {max}.|Korisnici se odjavljuju nakon {minutes} minuta bez aktivnosti.|{minutes} minuta = {human}. Klizni prozor - resetuje se korisničkom aktivnošću; upozorenje se prikazuje prije odjave.|Unesite cijeli broj od najmanje {min}.|Odjava zbog neaktivnosti ne može premašiti maksimalno trajanje sesije.|Napomena: za strogu serversku primjenu, u Clerk kontrolnoj tabli podesite i trajanje Clerk session tokena tako da odgovara maksimalnom trajanju sesije.",
  sl: "{minutes} minut = {human}. Absolutno trajanje - uporabnik je odjavljen, ko ta čas poteče, ne glede na aktivnost.|Vnesite celo število med {min} in {max}.|Uporabniki so odjavljeni po {minutes} minutah brez aktivnosti.|{minutes} minut = {human}. Drseče okno - ponastavi se z uporabnikovo aktivnostjo; pred odjavo se prikaže opozorilo.|Vnesite celo število najmanj {min}.|Odjava zaradi nedejavnosti ne sme presegati najdaljšega trajanja seje.|Opomba: za strogo uveljavljanje na strežniku v nadzorni plošči Clerk nastavite tudi življenjsko dobo žetona seje Clerk, da se ujema z najdaljšim trajanjem seje.",
  ru: "{minutes} минут = {human}. Абсолютный срок действия - пользователь выходит из системы по истечении этого времени независимо от активности.|Введите целое число от {min} до {max}.|Пользователи выходят из системы после {minutes} минут без активности.|{minutes} минут = {human}. Скользящее окно - сбрасывается активностью пользователя; перед выходом показывается предупреждение.|Введите целое число не меньше {min}.|Выход из-за бездействия не может превышать максимальную длительность сеанса.|Примечание: для строгого серверного применения также настройте срок жизни токена сеанса Clerk в панели Clerk так, чтобы он совпадал с максимальной длительностью сеанса.",
  hu: "{minutes} perc = {human}. Abszolút élettartam - a felhasználó kijelentkezik, amikor ez lejár, aktivitástól függetlenül.|Adjon meg egy egész számot {min} és {max} között.|A felhasználók {minutes} perc inaktivitás után kijelentkeznek.|{minutes} perc = {human}. Csúszó időablak - a felhasználói aktivitás visszaállítja; kijelentkezés előtt figyelmeztetés jelenik meg.|Adjon meg legalább {min} értékű egész számot.|Az inaktivitási kijelentkezés nem haladhatja meg a maximális munkamenet-időt.|Megjegyzés: szigorú szerveroldali érvényesítéshez a Clerk irányítópultján állítsa be a Clerk munkamenet-token élettartamát is a maximális munkamenet-időhöz igazítva.",
  bg: "{minutes} минути = {human}. Абсолютна продължителност - потребителят се отписва, когато това време изтече, независимо от активността.|Въведете цяло число между {min} и {max}.|Потребителите се отписват след {minutes} минути без активност.|{minutes} минути = {human}. Плъзгащ прозорец - нулира се от активността на потребителя; предупреждение се показва преди отписване.|Въведете цяло число поне {min}.|Отписването при неактивност не може да надвишава максималната продължителност на сесията.|Забележка: за строго прилагане от страна на сървъра, конфигурирайте и живота на Clerk session token в таблото на Clerk така, че да съответства на максималната продължителност на сесията.",
  ja: "{minutes} 分 = {human}。絶対有効期間 - この時間が経過すると、アクティビティに関係なくユーザーはサインアウトされます。|{min} から {max} までの整数を入力してください。|ユーザーは {minutes} 分間操作がないとサインアウトされます。|{minutes} 分 = {human}。スライディングウィンドウ - ユーザー操作でリセットされ、サインアウト前に警告が表示されます。|少なくとも {min} の整数を入力してください。|アイドル時のサインアウトは最大セッション時間を超えることはできません。|注: サーバー側で厳密に適用するには、Clerk ダッシュボードで Clerk セッショントークンの有効期間も最大セッション時間に合わせて設定してください。",
  "zh-Hans":
    "{minutes} 分钟 = {human}。绝对有效期 - 到达此时间后，无论是否有活动，用户都会被登出。|请输入 {min} 到 {max} 之间的整数。|用户在 {minutes} 分钟无活动后会被登出。|{minutes} 分钟 = {human}。滑动窗口 - 会由用户活动重置；登出前会显示警告。|请输入至少为 {min} 的整数。|空闲登出不能超过最大会话时长。|注意：如需严格的服务器端强制执行，还要在 Clerk 控制台中将 Clerk 会话令牌生命周期配置为与最大会话时长一致。",
  "zh-Hant":
    "{minutes} 分鐘 = {human}。絕對有效期 - 到達此時間後，無論是否有活動，使用者都會被登出。|請輸入 {min} 到 {max} 之間的整數。|使用者在 {minutes} 分鐘沒有活動後會被登出。|{minutes} 分鐘 = {human}。滑動視窗 - 會由使用者活動重設；登出前會顯示警告。|請輸入至少為 {min} 的整數。|閒置登出不能超過最大工作階段時長。|注意：若要嚴格由伺服器端強制執行，也請在 Clerk 控制台中將 Clerk 工作階段權杖生命週期設定為與最大工作階段時長一致。",
  ar: "{minutes} دقيقة = {human}. مدة مطلقة - يتم تسجيل خروج المستخدم عند انتهاء هذه المدة بغض النظر عن النشاط.|أدخل عددًا صحيحًا بين {min} و{max}.|يتم تسجيل خروج المستخدمين بعد {minutes} دقيقة دون نشاط.|{minutes} دقيقة = {human}. نافذة منزلقة - يعيد نشاط المستخدم ضبطها؛ يظهر تحذير قبل تسجيل الخروج.|أدخل عددًا صحيحًا لا يقل عن {min}.|لا يمكن أن يتجاوز تسجيل الخروج بسبب الخمول الحد الأقصى لمدة الجلسة.|ملاحظة: للتطبيق الصارم من جهة الخادم، قم أيضًا بضبط مدة صلاحية رمز جلسة Clerk في لوحة Clerk لتطابق الحد الأقصى لمدة الجلسة.",
  id: "{minutes} menit = {human}. Masa berlaku absolut - pengguna keluar saat waktu ini habis, terlepas dari aktivitas.|Masukkan bilangan bulat antara {min} dan {max}.|Pengguna keluar setelah {minutes} menit tanpa aktivitas.|{minutes} menit = {human}. Jendela geser - direset oleh aktivitas pengguna; peringatan muncul sebelum keluar.|Masukkan bilangan bulat minimal {min}.|Logout karena idle tidak boleh melebihi durasi sesi maksimum.|Catatan: untuk penerapan sisi server yang ketat, konfigurasikan juga masa berlaku token sesi Clerk di dasbor Clerk agar sesuai dengan durasi sesi maksimum.",
  cs: "{minutes} minut = {human}. Absolutní životnost - uživatel je po jejím uplynutí odhlášen bez ohledu na aktivitu.|Zadejte celé číslo mezi {min} a {max}.|Uživatelé jsou odhlášeni po {minutes} minutách bez aktivity.|{minutes} minut = {human}. Posuvné okno - resetuje se aktivitou uživatele; před odhlášením se zobrazí upozornění.|Zadejte celé číslo alespoň {min}.|Odhlášení při nečinnosti nesmí překročit maximální délku relace.|Poznámka: pro striktní vynucení na serveru nastavte v panelu Clerk také životnost tokenu relace Clerk tak, aby odpovídala maximální délce relace.",
  ro: "{minutes} minute = {human}. Durată absolută - utilizatorul este deconectat când acest timp expiră, indiferent de activitate.|Introduceți un număr întreg între {min} și {max}.|Utilizatorii sunt deconectați după {minutes} minute fără activitate.|{minutes} minute = {human}. Fereastră glisantă - este resetată de activitatea utilizatorului; apare un avertisment înainte de deconectare.|Introduceți un număr întreg de cel puțin {min}.|Deconectarea la inactivitate nu poate depăși durata maximă a sesiunii.|Notă: pentru aplicare strictă pe server, configurați și durata de viață a tokenului de sesiune Clerk în panoul Clerk ca să corespundă duratei maxime a sesiunii.",
  el: "{minutes} λεπτά = {human}. Απόλυτη διάρκεια - ο χρήστης αποσυνδέεται όταν λήξει αυτός ο χρόνος, ανεξάρτητα από τη δραστηριότητα.|Εισαγάγετε ακέραιο αριθμό μεταξύ {min} και {max}.|Οι χρήστες αποσυνδέονται μετά από {minutes} λεπτά χωρίς δραστηριότητα.|{minutes} λεπτά = {human}. Κυλιόμενο παράθυρο - επαναφέρεται από τη δραστηριότητα του χρήστη· εμφανίζεται προειδοποίηση πριν από την αποσύνδεση.|Εισαγάγετε ακέραιο αριθμό τουλάχιστον {min}.|Η αποσύνδεση λόγω αδράνειας δεν μπορεί να υπερβαίνει τη μέγιστη διάρκεια συνεδρίας.|Σημείωση: για αυστηρή εφαρμογή από τον διακομιστή, ρυθμίστε επίσης τη διάρκεια ζωής του token συνεδρίας Clerk στον πίνακα Clerk ώστε να ταιριάζει με τη μέγιστη διάρκεια συνεδρίας.",
  da: "{minutes} minutter = {human}. Absolut levetid - brugeren logges ud, når denne tid udløber, uanset aktivitet.|Indtast et helt tal mellem {min} og {max}.|Brugere logges ud efter {minutes} minutter uden aktivitet.|{minutes} minutter = {human}. Glidende vindue - nulstilles af brugeraktivitet; der vises en advarsel før logout.|Indtast et helt tal på mindst {min}.|Logout ved inaktivitet må ikke overstige den maksimale sessionsvarighed.|Bemærk: For streng håndhævelse på serversiden skal du også konfigurere levetiden for Clerk-sessionstokenet i Clerk-dashboardet, så den matcher den maksimale sessionsvarighed.",
  sv: "{minutes} minuter = {human}. Absolut livslängd - användaren loggas ut när denna tid löper ut, oavsett aktivitet.|Ange ett heltal mellan {min} och {max}.|Användare loggas ut efter {minutes} minuter utan aktivitet.|{minutes} minuter = {human}. Glidande fönster - återställs av användaraktivitet; en varning visas före utloggning.|Ange ett heltal på minst {min}.|Utloggning vid inaktivitet får inte överstiga maximal sessionslängd.|Obs: för strikt server-side-tillämpning ska du också konfigurera livslängden för Clerk-sessionstoken i Clerk-panelen så att den matchar maximal sessionslängd.",
  nb: "{minutes} minutter = {human}. Absolutt levetid - brukeren logges ut når denne tiden utløper, uavhengig av aktivitet.|Skriv inn et heltall mellom {min} og {max}.|Brukere logges ut etter {minutes} minutter uten aktivitet.|{minutes} minutter = {human}. Glidende vindu - tilbakestilles av brukeraktivitet; en advarsel vises før utlogging.|Skriv inn et heltall på minst {min}.|Utlogging ved inaktivitet kan ikke overstige maksimal øktvarighet.|Merk: For streng håndheving på serversiden må du også konfigurere levetiden for Clerk-øktstokenet i Clerk-dashbordet slik at den samsvarer med maksimal øktvarighet.",
  nn: "{minutes} minutt = {human}. Absolutt levetid - brukaren blir logga ut når denne tida går ut, uavhengig av aktivitet.|Skriv inn eit heiltal mellom {min} og {max}.|Brukarar blir logga ut etter {minutes} minutt utan aktivitet.|{minutes} minutt = {human}. Glidande vindauge - blir nullstilt av brukaraktivitet; ei åtvaring blir vist før utlogging.|Skriv inn eit heiltal på minst {min}.|Utlogging ved inaktivitet kan ikkje overstige maksimal øktlengd.|Merk: For streng handheving på serversida må du òg konfigurere levetida for Clerk-øktstokenet i Clerk-dashbordet slik at ho samsvarer med maksimal øktlengd.",
  fi: "{minutes} minuuttia = {human}. Absoluuttinen kesto - käyttäjä kirjataan ulos, kun tämä aika täyttyy, aktiivisuudesta riippumatta.|Syötä kokonaisluku väliltä {min} - {max}.|Käyttäjät kirjataan ulos {minutes} minuutin toimettomuuden jälkeen.|{minutes} minuuttia = {human}. Liukuva ikkuna - käyttäjän toiminta nollaa sen; varoitus näytetään ennen uloskirjausta.|Syötä kokonaisluku, joka on vähintään {min}.|Toimettomuuden uloskirjaus ei voi ylittää istunnon enimmäiskestoa.|Huomautus: tiukkaa palvelinpuolen valvontaa varten määritä myös Clerk-istuntotunnuksen elinikä Clerk-hallintapaneelissa vastaamaan istunnon enimmäiskestoa.",
  is: "{minutes} mínútur = {human}. Algildur gildistími - notandinn er skráður út þegar þessi tími rennur út, óháð virkni.|Sláðu inn heiltölu á milli {min} og {max}.|Notendur eru skráðir út eftir {minutes} mínútur án virkni.|{minutes} mínútur = {human}. Rennandi gluggi - endurstillist við virkni notanda; viðvörun birtist fyrir útskráningu.|Sláðu inn heiltölu sem er að minnsta kosti {min}.|Útskráning vegna óvirkni má ekki fara yfir hámarkslengd setu.|Athugið: Fyrir stranga framfylgd á þjónshlið skaltu einnig stilla líftíma Clerk-setutákns í Clerk-stjórnborðinu þannig að hann passi við hámarkslengd setu.",
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<SessionSource, string> {
  const translations = row.split("|");
  if (translations.length !== GLOBAL_SETTINGS_SESSION_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} global settings session translations must have ${GLOBAL_SETTINGS_SESSION_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    GLOBAL_SETTINGS_SESSION_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<SessionSource, string>;
}

export const GLOBAL_SETTINGS_SESSION_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<SessionSource, string>>;
