import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const GLOBAL_SETTINGS_APPEARANCE_SOURCE_STRINGS = [
  "Classic",
  "Centered",
  "Split",
  "Compact App",
  "Editorial Masthead",
  "Minimal",
  "Multi-column",
  "Brand",
  "Menu",
  "Auth",
  "Page content",
  "Card",
  "Aside",
  "Links",
  "Legal",
  "Social",
  "Copyright",
  "Brand on the left, CustomHtml in the middle, navigation and actions on the right.",
  "Centered vertical header: brand first, then menu, search, CTA, and auth controls.",
  "Three-zone grid: brand left, navigation centered, CustomHtml and actions right.",
  "Short app-style bar with brand left and dense controls on the right.",
  "Magazine masthead: search/auth top row, centered brand, menu row below.",
  "Quiet header with brand left and only essential controls on the right.",
  "Simple legacy footer: CustomHtml and copyright only.",
  "Compact row: CustomHtml and copyright on the left, links and CTA on the right.",
  "Three-column footer for content, navigation, and actions.",
  "Centered vertical stack for balanced, quiet pages.",
  "Two-sided footer with content on the left and action on the right.",
  "No footer is rendered on the public site.",
  "Presets are starting points. Mix Theme, content widths, font, radius, shadow, main surface, and content templates to shape the public pages and blog posts exactly how you want.",
  "{count} errors",
  "{count} warnings",
  "No quality gate issues detected.",
  "Normal Content",
  "Framed Content",
  "Full-bleed Builder",
  "Editorial Article",
  "Category Grid",
  "Use System Preference",
  "Always Reduce Motion",
  "Circle",
  "Square",
  "Use theme border color",
  "Custom border color",
] as const;

type AppearanceSource =
  (typeof GLOBAL_SETTINGS_APPEARANCE_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "Klasično|Centrirano|Podeljeno|Kompaktna aplikacija|Uredničko zaglavlje|Minimalno|Više kolona|Brend|Meni|Autentikacija|Sadržaj stranice|Kartica|Bočna oblast|Linkovi|Pravno|Društveno|Autorska prava|Brend levo, CustomHtml u sredini, navigacija i akcije desno.|Centrirano vertikalno zaglavlje: prvo brend, zatim meni, pretraga, CTA i kontrole autentikacije.|Mreža od tri zone: brend levo, navigacija centrirana, CustomHtml i akcije desno.|Kratka traka u stilu aplikacije sa brendom levo i gustim kontrolama desno.|Magazinsko zaglavlje: red pretrage/autentikacije gore, centriran brend, red menija ispod.|Mirno zaglavlje sa brendom levo i samo osnovnim kontrolama desno.|Jednostavno nasleđeno podnožje: samo CustomHtml i autorska prava.|Kompaktan red: CustomHtml i autorska prava levo, linkovi i CTA desno.|Podnožje sa tri kolone za sadržaj, navigaciju i akcije.|Centriran vertikalni niz za uravnotežene, mirne stranice.|Dvostrano podnožje sa sadržajem levo i akcijom desno.|Podnožje se ne prikazuje na javnom sajtu.|Preseti su početne tačke. Pomešaj temu, širine sadržaja, font, radijus, senku, glavnu površinu i šablone sadržaja da oblikuješ javne stranice i blog postove tačno kako želiš.|{count} grešaka|{count} upozorenja|Nema problema u kontrolama kvaliteta.|Normalan sadržaj|Uokviren sadržaj|Full-bleed builder|Urednički članak|Mreža kategorija|Koristi sistemsko podešavanje|Uvek smanji pokret|Krug|Kvadrat|Koristi boju ivice iz teme|Prilagođena boja ivice",
  "sr-Cyrl":
    "Класично|Центрирано|Подељено|Компактна апликација|Уредничко заглавље|Минимално|Више колона|Бренд|Мени|Аутентикација|Садржај странице|Картица|Бочна област|Линкови|Правно|Друштвено|Ауторска права|Бренд лево, CustomHtml у средини, навигација и акције десно.|Центрирано вертикално заглавље: прво бренд, затим мени, претрага, CTA и контроле аутентикације.|Мрежа од три зоне: бренд лево, навигација центрирана, CustomHtml и акције десно.|Кратка трака у стилу апликације са брендом лево и густим контролама десно.|Магазинско заглавље: ред претраге/аутентикације горе, центриран бренд, ред менија испод.|Мирно заглавље са брендом лево и само основним контролама десно.|Једноставно наслеђено подножје: само CustomHtml и ауторска права.|Компактан ред: CustomHtml и ауторска права лево, линкови и CTA десно.|Подножје са три колоне за садржај, навигацију и акције.|Центриран вертикални низ за уравнотежене, мирне странице.|Двострано подножје са садржајем лево и акцијом десно.|Подножје се не приказује на јавном сајту.|Пресети су почетне тачке. Помешај тему, ширине садржаја, фонт, радијус, сенку, главну површину и шаблоне садржаја да обликујеш јавне странице и блог постове тачно како желиш.|{count} грешака|{count} упозорења|Нема проблема у контролама квалитета.|Нормалан садржај|Уоквирен садржај|Full-bleed builder|Уреднички чланак|Мрежа категорија|Користи системско подешавање|Увек смањи покрет|Круг|Квадрат|Користи боју ивице из теме|Прилагођена боја ивице",
  hr: "Klasično|Centrirano|Podijeljeno|Kompaktna aplikacija|Uredničko zaglavlje|Minimalno|Više stupaca|Brend|Izbornik|Autentikacija|Sadržaj stranice|Kartica|Bočna oblast|Poveznice|Pravno|Društveno|Autorska prava|Brend lijevo, CustomHtml u sredini, navigacija i akcije desno.|Centrirano vertikalno zaglavlje: najprije brend, zatim izbornik, pretraga, CTA i kontrole autentikacije.|Mreža od tri zone: brend lijevo, navigacija centrirana, CustomHtml i akcije desno.|Kratka traka u stilu aplikacije s brendom lijevo i gustim kontrolama desno.|Magazinsko zaglavlje: red pretrage/autentikacije gore, centriran brend, red izbornika ispod.|Mirno zaglavlje s brendom lijevo i samo osnovnim kontrolama desno.|Jednostavno naslijeđeno podnožje: samo CustomHtml i autorska prava.|Kompaktan red: CustomHtml i autorska prava lijevo, poveznice i CTA desno.|Podnožje s tri stupca za sadržaj, navigaciju i akcije.|Centrirani vertikalni niz za uravnotežene, mirne stranice.|Dvostrano podnožje sa sadržajem lijevo i akcijom desno.|Podnožje se ne prikazuje na javnoj stranici.|Preseti su početne točke. Pomiješajte temu, širine sadržaja, font, radijus, sjenu, glavnu površinu i predloške sadržaja kako biste javne stranice i blog objave oblikovali točno kako želite.|{count} pogrešaka|{count} upozorenja|Nema problema u kontrolama kvalitete.|Normalan sadržaj|Uokviren sadržaj|Full-bleed builder|Urednički članak|Mreža kategorija|Koristi postavku sustava|Uvijek smanji pokret|Krug|Kvadrat|Koristi boju obruba iz teme|Prilagođena boja obruba",
  de: "Klassisch|Zentriert|Geteilt|Kompakte App|Editorial-Masthead|Minimal|Mehrspaltig|Marke|Menü|Authentifizierung|Seiteninhalt|Karte|Seitenleiste|Links|Rechtliches|Social|Copyright|Marke links, CustomHtml in der Mitte, Navigation und Aktionen rechts.|Zentrierter vertikaler Header: zuerst Marke, dann Menü, Suche, CTA und Auth-Steuerung.|Dreizonenraster: Marke links, Navigation zentriert, CustomHtml und Aktionen rechts.|Kurze App-Leiste mit Marke links und kompakten Steuerelementen rechts.|Magazin-Masthead: Suche/Auth oben, Marke zentriert, Menüzeile darunter.|Ruhiger Header mit Marke links und nur den wichtigsten Steuerelementen rechts.|Einfacher Legacy-Footer: nur CustomHtml und Copyright.|Kompakte Zeile: CustomHtml und Copyright links, Links und CTA rechts.|Dreispaltiger Footer für Inhalte, Navigation und Aktionen.|Zentrierter vertikaler Stapel für ausgewogene, ruhige Seiten.|Zweiseitiger Footer mit Inhalt links und Aktion rechts.|Auf der öffentlichen Website wird kein Footer gerendert.|Presets sind Startpunkte. Kombiniere Theme, Inhaltsbreiten, Schrift, Radius, Schatten, Hauptfläche und Inhaltsvorlagen, um öffentliche Seiten und Blogbeiträge genau nach Wunsch zu formen.|{count} Fehler|{count} Warnungen|Keine Quality-Gate-Probleme erkannt.|Normaler Inhalt|Gerahmter Inhalt|Full-Bleed-Builder|Editorial-Artikel|Kategorieraster|Systemeinstellung verwenden|Bewegung immer reduzieren|Kreis|Quadrat|Rahmenfarbe des Themes verwenden|Benutzerdefinierte Rahmenfarbe",
  fr: "Classique|Centré|Scindé|Application compacte|En-tête éditorial|Minimal|Multi-colonnes|Marque|Menu|Authentification|Contenu de page|Carte|À-côté|Liens|Juridique|Social|Copyright|Marque à gauche, CustomHtml au centre, navigation et actions à droite.|En-tête vertical centré : marque d'abord, puis menu, recherche, CTA et contrôles d'authentification.|Grille à trois zones : marque à gauche, navigation centrée, CustomHtml et actions à droite.|Barre courte de type application avec marque à gauche et contrôles denses à droite.|En-tête magazine : recherche/authentification en haut, marque centrée, ligne de menu dessous.|En-tête discret avec marque à gauche et seulement les contrôles essentiels à droite.|Pied de page hérité simple : CustomHtml et copyright uniquement.|Ligne compacte : CustomHtml et copyright à gauche, liens et CTA à droite.|Pied de page en trois colonnes pour contenu, navigation et actions.|Pile verticale centrée pour des pages équilibrées et calmes.|Pied de page à deux côtés avec contenu à gauche et action à droite.|Aucun pied de page n'est rendu sur le site public.|Les préréglages sont des points de départ. Mélangez thème, largeurs de contenu, police, rayon, ombre, surface principale et modèles de contenu pour façonner les pages publiques et les articles de blog exactement comme vous le souhaitez.|{count} erreurs|{count} avertissements|Aucun problème de contrôle qualité détecté.|Contenu normal|Contenu encadré|Builder pleine largeur|Article éditorial|Grille de catégories|Utiliser la préférence système|Toujours réduire le mouvement|Cercle|Carré|Utiliser la couleur de bordure du thème|Couleur de bordure personnalisée",
  es: "Clásico|Centrado|Dividido|Aplicación compacta|Cabecera editorial|Mínimo|Multicolumna|Marca|Menú|Autenticación|Contenido de página|Tarjeta|Lateral|Enlaces|Legal|Social|Copyright|Marca a la izquierda, CustomHtml en el centro, navegación y acciones a la derecha.|Encabezado vertical centrado: primero la marca, luego menú, búsqueda, CTA y controles de autenticación.|Cuadrícula de tres zonas: marca a la izquierda, navegación centrada, CustomHtml y acciones a la derecha.|Barra corta estilo app con marca a la izquierda y controles densos a la derecha.|Cabecera de revista: fila superior de búsqueda/autenticación, marca centrada y menú debajo.|Encabezado tranquilo con marca a la izquierda y solo controles esenciales a la derecha.|Pie heredado simple: solo CustomHtml y copyright.|Fila compacta: CustomHtml y copyright a la izquierda, enlaces y CTA a la derecha.|Pie de página de tres columnas para contenido, navegación y acciones.|Pila vertical centrada para páginas equilibradas y tranquilas.|Pie de dos lados con contenido a la izquierda y acción a la derecha.|No se muestra pie de página en el sitio público.|Los preajustes son puntos de partida. Mezcla tema, anchos de contenido, fuente, radio, sombra, superficie principal y plantillas de contenido para dar forma a las páginas públicas y entradas de blog exactamente como quieras.|{count} errores|{count} advertencias|No se detectaron problemas en los controles de calidad.|Contenido normal|Contenido enmarcado|Builder a sangre completa|Artículo editorial|Cuadrícula de categorías|Usar preferencia del sistema|Reducir siempre el movimiento|Círculo|Cuadrado|Usar color de borde del tema|Color de borde personalizado",
  it: "Classico|Centrato|Diviso|App compatta|Testata editoriale|Minimale|Multi-colonna|Marchio|Menu|Autenticazione|Contenuto pagina|Scheda|Laterale|Link|Legale|Social|Copyright|Marchio a sinistra, CustomHtml al centro, navigazione e azioni a destra.|Intestazione verticale centrata: prima il marchio, poi menu, ricerca, CTA e controlli di autenticazione.|Griglia a tre zone: marchio a sinistra, navigazione centrata, CustomHtml e azioni a destra.|Barra breve stile app con marchio a sinistra e controlli densi a destra.|Testata magazine: ricerca/autenticazione in alto, marchio centrato, riga menu sotto.|Intestazione discreta con marchio a sinistra e solo controlli essenziali a destra.|Footer legacy semplice: solo CustomHtml e copyright.|Riga compatta: CustomHtml e copyright a sinistra, link e CTA a destra.|Footer a tre colonne per contenuto, navigazione e azioni.|Stack verticale centrato per pagine equilibrate e tranquille.|Footer a due lati con contenuto a sinistra e azione a destra.|Nessun footer viene renderizzato sul sito pubblico.|I preset sono punti di partenza. Mescola tema, larghezze contenuto, font, raggio, ombra, superficie principale e template contenuto per modellare pagine pubbliche e post del blog esattamente come vuoi.|{count} errori|{count} avvisi|Nessun problema di controllo qualità rilevato.|Contenuto normale|Contenuto incorniciato|Builder full-bleed|Articolo editoriale|Griglia categorie|Usa preferenza di sistema|Riduci sempre il movimento|Cerchio|Quadrato|Usa colore bordo del tema|Colore bordo personalizzato",
  pt: "Clássico|Centrado|Dividido|Aplicação compacta|Cabeçalho editorial|Minimal|Multicoluna|Marca|Menu|Autenticação|Conteúdo da página|Cartão|Lateral|Links|Legal|Social|Copyright|Marca à esquerda, CustomHtml no meio, navegação e ações à direita.|Cabeçalho vertical centrado: primeiro a marca, depois menu, pesquisa, CTA e controlos de autenticação.|Grelha de três zonas: marca à esquerda, navegação centrada, CustomHtml e ações à direita.|Barra curta estilo app com marca à esquerda e controlos densos à direita.|Cabeçalho de revista: pesquisa/autenticação na linha superior, marca centrada, menu abaixo.|Cabeçalho discreto com marca à esquerda e apenas controlos essenciais à direita.|Rodapé legado simples: apenas CustomHtml e copyright.|Linha compacta: CustomHtml e copyright à esquerda, links e CTA à direita.|Rodapé de três colunas para conteúdo, navegação e ações.|Pilha vertical centrada para páginas equilibradas e tranquilas.|Rodapé de dois lados com conteúdo à esquerda e ação à direita.|Nenhum rodapé é apresentado no site público.|As predefinições são pontos de partida. Misture tema, larguras de conteúdo, fonte, raio, sombra, superfície principal e modelos de conteúdo para moldar as páginas públicas e publicações do blog exatamente como quiser.|{count} erros|{count} avisos|Não foram detetados problemas nos controlos de qualidade.|Conteúdo normal|Conteúdo emoldurado|Builder full-bleed|Artigo editorial|Grelha de categorias|Usar preferência do sistema|Reduzir sempre o movimento|Círculo|Quadrado|Usar cor de borda do tema|Cor de borda personalizada",
  "pt-BR":
    "Clássico|Centralizado|Dividido|Aplicativo compacto|Cabeçalho editorial|Mínimo|Multicoluna|Marca|Menu|Autenticação|Conteúdo da página|Cartão|Lateral|Links|Legal|Social|Copyright|Marca à esquerda, CustomHtml no meio, navegação e ações à direita.|Cabeçalho vertical centralizado: primeiro a marca, depois menu, busca, CTA e controles de autenticação.|Grade de três zonas: marca à esquerda, navegação centralizada, CustomHtml e ações à direita.|Barra curta estilo app com marca à esquerda e controles densos à direita.|Cabeçalho de revista: busca/autenticação na linha superior, marca centralizada, menu abaixo.|Cabeçalho discreto com marca à esquerda e apenas controles essenciais à direita.|Rodapé legado simples: apenas CustomHtml e copyright.|Linha compacta: CustomHtml e copyright à esquerda, links e CTA à direita.|Rodapé de três colunas para conteúdo, navegação e ações.|Pilha vertical centralizada para páginas equilibradas e tranquilas.|Rodapé de dois lados com conteúdo à esquerda e ação à direita.|Nenhum rodapé é renderizado no site público.|As predefinições são pontos de partida. Misture tema, larguras de conteúdo, fonte, raio, sombra, superfície principal e modelos de conteúdo para moldar as páginas públicas e posts do blog exatamente como quiser.|{count} erros|{count} avisos|Nenhum problema nos controles de qualidade detectado.|Conteúdo normal|Conteúdo emoldurado|Builder full-bleed|Artigo editorial|Grade de categorias|Usar preferência do sistema|Sempre reduzir movimento|Círculo|Quadrado|Usar cor de borda do tema|Cor de borda personalizada",
  nl: "Klassiek|Gecentreerd|Gesplitst|Compacte app|Redactionele masthead|Minimaal|Meerkoloms|Merk|Menu|Authenticatie|Pagina-inhoud|Kaart|Zijgedeelte|Links|Juridisch|Sociaal|Copyright|Merk links, CustomHtml in het midden, navigatie en acties rechts.|Gecentreerde verticale koptekst: eerst merk, daarna menu, zoeken, CTA en authenticatieknoppen.|Driezoneraster: merk links, navigatie gecentreerd, CustomHtml en acties rechts.|Korte appbalk met merk links en compacte knoppen rechts.|Magazine-masthead: zoeken/authenticatie bovenaan, merk gecentreerd, menurij eronder.|Rustige koptekst met merk links en alleen essentiële knoppen rechts.|Eenvoudige legacy-voettekst: alleen CustomHtml en copyright.|Compacte rij: CustomHtml en copyright links, links en CTA rechts.|Voettekst met drie kolommen voor inhoud, navigatie en acties.|Gecentreerde verticale stapel voor evenwichtige, rustige pagina's.|Tweezijdige voettekst met inhoud links en actie rechts.|Er wordt geen voettekst op de openbare site weergegeven.|Presets zijn startpunten. Mix thema, inhoudsbreedtes, lettertype, radius, schaduw, hoofdoppervlak en inhoudssjablonen om publieke pagina's en blogberichten precies te vormen zoals je wilt.|{count} fouten|{count} waarschuwingen|Geen problemen met kwaliteitscontroles gevonden.|Normale inhoud|Ingekaderde inhoud|Full-bleed builder|Redactioneel artikel|Categorieraster|Systeemvoorkeur gebruiken|Beweging altijd verminderen|Cirkel|Vierkant|Randkleur van thema gebruiken|Aangepaste randkleur",
  pl: "Klasyczny|Wyśrodkowany|Podzielony|Kompaktowa aplikacja|Nagłówek redakcyjny|Minimalny|Wielokolumnowy|Marka|Menu|Uwierzytelnianie|Treść strony|Karta|Panel boczny|Linki|Prawne|Społecznościowe|Copyright|Marka po lewej, CustomHtml pośrodku, nawigacja i akcje po prawej.|Wyśrodkowany pionowy nagłówek: najpierw marka, potem menu, wyszukiwanie, CTA i kontrolki uwierzytelniania.|Siatka trzech stref: marka po lewej, nawigacja wyśrodkowana, CustomHtml i akcje po prawej.|Krótki pasek w stylu aplikacji z marką po lewej i gęstymi kontrolkami po prawej.|Nagłówek magazynowy: wyszukiwanie/uwierzytelnianie u góry, marka wyśrodkowana, menu poniżej.|Spokojny nagłówek z marką po lewej i tylko podstawowymi kontrolkami po prawej.|Prosta starsza stopka: tylko CustomHtml i copyright.|Kompaktowy wiersz: CustomHtml i copyright po lewej, linki i CTA po prawej.|Trzykolumnowa stopka dla treści, nawigacji i akcji.|Wyśrodkowany pionowy stos dla zrównoważonych, spokojnych stron.|Dwustronna stopka z treścią po lewej i akcją po prawej.|Stopka nie jest renderowana na stronie publicznej.|Presety są punktami startowymi. Mieszaj motyw, szerokości treści, font, promień, cień, główną powierzchnię i szablony treści, aby ukształtować publiczne strony i wpisy bloga dokładnie tak, jak chcesz.|{count} błędów|{count} ostrzeżeń|Nie wykryto problemów w kontrolach jakości.|Normalna treść|Treść w ramce|Builder pełnej szerokości|Artykuł redakcyjny|Siatka kategorii|Użyj preferencji systemowej|Zawsze ogranicz ruch|Koło|Kwadrat|Użyj koloru obramowania motywu|Niestandardowy kolor obramowania",
  tr: "Klasik|Ortalanmış|Bölünmüş|Kompakt uygulama|Editoryal başlık|Minimal|Çok sütunlu|Marka|Menü|Kimlik doğrulama|Sayfa içeriği|Kart|Yan alan|Bağlantılar|Yasal|Sosyal|Telif hakkı|Marka solda, CustomHtml ortada, gezinme ve işlemler sağda.|Ortalanmış dikey üst bilgi: önce marka, sonra menü, arama, CTA ve kimlik doğrulama kontrolleri.|Üç bölgeli ızgara: marka solda, gezinme ortada, CustomHtml ve işlemler sağda.|Solda marka, sağda yoğun kontroller olan kısa uygulama çubuğu.|Dergi başlığı: üstte arama/kimlik doğrulama, ortada marka, altta menü satırı.|Solda marka ve sağda yalnızca temel kontroller olan sade üst bilgi.|Basit eski alt bilgi: yalnızca CustomHtml ve telif hakkı.|Kompakt satır: solda CustomHtml ve telif hakkı, sağda bağlantılar ve CTA.|İçerik, gezinme ve işlemler için üç sütunlu alt bilgi.|Dengeli, sakin sayfalar için ortalanmış dikey yığın.|Solda içerik ve sağda işlem olan çift taraflı alt bilgi.|Genel sitede alt bilgi oluşturulmaz.|Ön ayarlar başlangıç noktalarıdır. Genel sayfaları ve blog yazılarını tam istediğiniz gibi şekillendirmek için tema, içerik genişlikleri, yazı tipi, yarıçap, gölge, ana yüzey ve içerik şablonlarını karıştırın.|{count} hata|{count} uyarı|Kalite kontrol sorunu algılanmadı.|Normal içerik|Çerçeveli içerik|Tam taşan builder|Editoryal makale|Kategori ızgarası|Sistem tercihini kullan|Hareketi her zaman azalt|Daire|Kare|Tema kenarlık rengini kullan|Özel kenarlık rengi",
  mk: "Класично|Центрирано|Поделено|Компактна апликација|Уредничко заглавје|Минимално|Повеќе колони|Бренд|Мени|Автентикација|Содржина на страница|Картичка|Странична област|Линкови|Правно|Социјално|Copyright|Бренд лево, CustomHtml во средина, навигација и акции десно.|Центрирано вертикално заглавје: прво бренд, потоа мени, пребарување, CTA и контроли за автентикација.|Мрежа со три зони: бренд лево, навигација центрирана, CustomHtml и акции десно.|Кратка лента во стил на апликација со бренд лево и густи контроли десно.|Магазинско заглавје: пребарување/автентикација горе, центриран бренд, ред со мени подолу.|Мирно заглавје со бренд лево и само основни контроли десно.|Едноставно наследено подножје: само CustomHtml и copyright.|Компактен ред: CustomHtml и copyright лево, линкови и CTA десно.|Подножје со три колони за содржина, навигација и акции.|Центриран вертикален стек за избалансирани, мирни страници.|Двострано подножје со содржина лево и акција десно.|Подножјето не се прикажува на јавниот сајт.|Пресетите се почетни точки. Измешај тема, ширини на содржина, фонт, радиус, сенка, главна површина и шаблони за содржина за да ги обликуваш јавните страници и блог објави точно како што сакаш.|{count} грешки|{count} предупредувања|Не се откриени проблеми во контролите за квалитет.|Нормална содржина|Врамена содржина|Full-bleed builder|Уредничка статија|Мрежа на категории|Користи системска поставка|Секогаш намали движење|Круг|Квадрат|Користи боја на рамка од темата|Прилагодена боја на рамка",
  bs: "Klasično|Centrirano|Podijeljeno|Kompaktna aplikacija|Uredničko zaglavlje|Minimalno|Više kolona|Brend|Meni|Autentikacija|Sadržaj stranice|Kartica|Bočna oblast|Linkovi|Pravno|Društveno|Autorska prava|Brend lijevo, CustomHtml u sredini, navigacija i akcije desno.|Centrirano vertikalno zaglavlje: prvo brend, zatim meni, pretraga, CTA i kontrole autentikacije.|Mreža od tri zone: brend lijevo, navigacija centrirana, CustomHtml i akcije desno.|Kratka traka u stilu aplikacije s brendom lijevo i gustim kontrolama desno.|Magazinsko zaglavlje: red pretrage/autentikacije gore, centriran brend, red menija ispod.|Mirno zaglavlje s brendom lijevo i samo osnovnim kontrolama desno.|Jednostavno naslijeđeno podnožje: samo CustomHtml i autorska prava.|Kompaktan red: CustomHtml i autorska prava lijevo, linkovi i CTA desno.|Podnožje sa tri kolone za sadržaj, navigaciju i akcije.|Centriran vertikalni niz za uravnotežene, mirne stranice.|Dvostrano podnožje sa sadržajem lijevo i akcijom desno.|Podnožje se ne prikazuje na javnom sajtu.|Preseti su početne tačke. Pomiješaj temu, širine sadržaja, font, radijus, sjenku, glavnu površinu i šablone sadržaja da oblikuješ javne stranice i blog objave tačno kako želiš.|{count} grešaka|{count} upozorenja|Nema problema u kontrolama kvaliteta.|Normalan sadržaj|Uokviren sadržaj|Full-bleed builder|Urednički članak|Mreža kategorija|Koristi sistemsku postavku|Uvijek smanji pokret|Krug|Kvadrat|Koristi boju ivice iz teme|Prilagođena boja ivice",
  sl: "Klasično|Centrirano|Razdeljeno|Kompaktna aplikacija|Uredniška glava|Minimalno|Več stolpcev|Blagovna znamka|Meni|Avtentikacija|Vsebina strani|Kartica|Stransko območje|Povezave|Pravno|Družbeno|Avtorske pravice|Blagovna znamka levo, CustomHtml na sredini, navigacija in dejanja desno.|Centrirana navpična glava: najprej znamka, nato meni, iskanje, CTA in kontrolniki avtentikacije.|Mreža treh območij: znamka levo, navigacija centrirana, CustomHtml in dejanja desno.|Kratka vrstica v slogu aplikacije z znamko levo in gostimi kontrolniki desno.|Revijalna glava: iskanje/avtentikacija v zgornji vrstici, znamka centrirana, meni spodaj.|Mirna glava z znamko levo in samo osnovnimi kontrolniki desno.|Preprosta starejša noga: samo CustomHtml in avtorske pravice.|Kompaktna vrstica: CustomHtml in avtorske pravice levo, povezave in CTA desno.|Noga s tremi stolpci za vsebino, navigacijo in dejanja.|Centriran navpični sklad za uravnotežene, mirne strani.|Dvostranska noga z vsebino levo in dejanjem desno.|Noga se na javnem mestu ne prikaže.|Prednastavitve so izhodišča. Zmešajte temo, širine vsebine, pisavo, radij, senco, glavno površino in predloge vsebine, da javne strani in blog objave oblikujete natanko po želji.|{count} napak|{count} opozoril|Ni zaznanih težav pri preverjanjih kakovosti.|Običajna vsebina|Uokvirjena vsebina|Full-bleed builder|Uredniški članek|Mreža kategorij|Uporabi sistemsko nastavitev|Vedno zmanjšaj gibanje|Krog|Kvadrat|Uporabi barvo obrobe teme|Barva obrobe po meri",
  ru: "Классический|По центру|Разделенный|Компактное приложение|Редакционный заголовок|Минимальный|Многоколоночный|Бренд|Меню|Аутентификация|Содержимое страницы|Карточка|Боковая область|Ссылки|Правовое|Социальное|Copyright|Бренд слева, CustomHtml посередине, навигация и действия справа.|Центрированная вертикальная шапка: сначала бренд, затем меню, поиск, CTA и элементы аутентификации.|Сетка из трех зон: бренд слева, навигация по центру, CustomHtml и действия справа.|Короткая панель в стиле приложения с брендом слева и плотными элементами управления справа.|Журнальная шапка: поиск/аутентификация в верхнем ряду, бренд по центру, меню ниже.|Спокойная шапка с брендом слева и только основными элементами управления справа.|Простой устаревший подвал: только CustomHtml и copyright.|Компактная строка: CustomHtml и copyright слева, ссылки и CTA справа.|Подвал из трех колонок для содержимого, навигации и действий.|Центрированный вертикальный стек для сбалансированных, спокойных страниц.|Двусторонний подвал с содержимым слева и действием справа.|Подвал не отображается на публичном сайте.|Пресеты — это отправные точки. Смешивайте тему, ширину контента, шрифт, радиус, тень, основную поверхность и шаблоны контента, чтобы публичные страницы и записи блога выглядели именно так, как нужно.|{count} ошибок|{count} предупреждений|Проблемы в проверках качества не обнаружены.|Обычный контент|Контент в рамке|Full-bleed builder|Редакционная статья|Сетка категорий|Использовать системные настройки|Всегда уменьшать движение|Круг|Квадрат|Использовать цвет рамки темы|Пользовательский цвет рамки",
  hu: "Klasszikus|Középre igazított|Osztott|Kompakt alkalmazás|Szerkesztőségi fejléc|Minimális|Többoszlopos|Márka|Menü|Hitelesítés|Oldaltartalom|Kártya|Oldalsáv|Linkek|Jogi|Közösségi|Copyright|Márka balra, CustomHtml középen, navigáció és műveletek jobbra.|Középre igazított függőleges fejléc: először márka, majd menü, keresés, CTA és hitelesítési vezérlők.|Háromzónás rács: márka balra, navigáció középen, CustomHtml és műveletek jobbra.|Rövid alkalmazásszerű sáv bal oldali márkával és jobb oldali sűrű vezérlőkkel.|Magazin fejléc: keresés/hitelesítés felső sorban, márka középen, menüsor alatta.|Nyugodt fejléc bal oldali márkával és csak alapvető vezérlőkkel jobbra.|Egyszerű örökölt lábléc: csak CustomHtml és copyright.|Kompakt sor: CustomHtml és copyright balra, linkek és CTA jobbra.|Háromoszlopos lábléc tartalomhoz, navigációhoz és műveletekhez.|Középre igazított függőleges lista kiegyensúlyozott, nyugodt oldalakhoz.|Kétoldalas lábléc bal oldali tartalommal és jobb oldali művelettel.|A nyilvános oldalon nem jelenik meg lábléc.|A presetek kiindulópontok. Keverje a témát, tartalomszélességeket, betűtípust, sugarat, árnyékot, fő felületet és tartalomsablonokat, hogy a nyilvános oldalakat és blogbejegyzéseket pontosan kívánság szerint formálja.|{count} hiba|{count} figyelmeztetés|Nem találhatók minőségellenőrzési problémák.|Normál tartalom|Keretezett tartalom|Full-bleed builder|Szerkesztőségi cikk|Kategóriarács|Rendszerbeállítás használata|Mindig csökkentse a mozgást|Kör|Négyzet|Téma keretszínének használata|Egyéni keretszín",
  bg: "Класически|Центриран|Разделен|Компактно приложение|Редакционен мастхед|Минимален|Многоколонен|Бранд|Меню|Автентикация|Съдържание на страница|Карта|Странична област|Връзки|Правно|Социално|Copyright|Бранд вляво, CustomHtml в средата, навигация и действия вдясно.|Центриран вертикален хедър: първо бранд, после меню, търсене, CTA и контроли за автентикация.|Мрежа от три зони: бранд вляво, навигация центрирана, CustomHtml и действия вдясно.|Къса лента в стил приложение с бранд вляво и плътни контроли вдясно.|Магазинен мастхед: търсене/автентикация горе, центриран бранд, ред меню отдолу.|Тих хедър с бранд вляво и само основни контроли вдясно.|Прост наследен футър: само CustomHtml и copyright.|Компактен ред: CustomHtml и copyright вляво, връзки и CTA вдясно.|Футър с три колони за съдържание, навигация и действия.|Центриран вертикален стек за балансирани, спокойни страници.|Двустранен футър със съдържание вляво и действие вдясно.|Футърът не се показва на публичния сайт.|Пресетите са начални точки. Смесвайте тема, ширини на съдържанието, шрифт, радиус, сянка, основна повърхност и шаблони за съдържание, за да оформите публичните страници и блог публикациите точно както искате.|{count} грешки|{count} предупреждения|Не са открити проблеми в проверките за качество.|Нормално съдържание|Съдържание в рамка|Full-bleed builder|Редакционна статия|Мрежа от категории|Използвай системната настройка|Винаги намалявай движението|Кръг|Квадрат|Използвай цвета на рамката от темата|Персонализиран цвят на рамката",
  ja: "クラシック|中央揃え|分割|コンパクトアプリ|エディトリアル見出し|ミニマル|複数列|ブランド|メニュー|認証|ページコンテンツ|カード|サイド領域|リンク|法務|ソーシャル|著作権|ブランドを左、CustomHtml を中央、ナビゲーションとアクションを右に配置します。|中央揃えの縦型ヘッダー: ブランド、メニュー、検索、CTA、認証コントロールの順に表示します。|3 ゾーンのグリッド: ブランドを左、ナビゲーションを中央、CustomHtml とアクションを右に配置します。|左にブランド、右に密なコントロールを持つ短いアプリ風バー。|マガジン見出し: 上段に検索/認証、中央にブランド、下にメニュー行。|左にブランド、右に必要最小限のコントロールだけを置く静かなヘッダー。|シンプルなレガシーフッター: CustomHtml と著作権のみ。|コンパクト行: 左に CustomHtml と著作権、右にリンクと CTA。|コンテンツ、ナビゲーション、アクション用の 3 列フッター。|バランスのよい静かなページ向けの中央縦積み。|左にコンテンツ、右にアクションを置く両側型フッター。|公開サイトにフッターは表示されません。|プリセットは出発点です。テーマ、コンテンツ幅、フォント、角丸、影、メインサーフェス、コンテンツテンプレートを組み合わせて、公開ページとブログ記事を思いどおりに形作れます。|{count} 件のエラー|{count} 件の警告|品質ゲートの問題は検出されませんでした。|通常コンテンツ|フレーム付きコンテンツ|フルブリードビルダー|エディトリアル記事|カテゴリグリッド|システム設定を使用|常にモーションを減らす|円|四角|テーマの枠線色を使用|カスタム枠線色",
  "zh-Hans":
    "经典|居中|分栏|紧凑应用|编辑部页眉|极简|多列|品牌|菜单|认证|页面内容|卡片|侧栏|链接|法律|社交|版权|品牌在左侧，CustomHtml 在中间，导航和操作在右侧。|居中的垂直页眉：先显示品牌，然后是菜单、搜索、CTA 和认证控件。|三区网格：品牌在左，导航居中，CustomHtml 和操作在右。|短应用式栏：品牌在左，密集控件在右。|杂志式页眉：顶部搜索/认证，中间品牌，下方菜单行。|安静页眉：品牌在左，右侧仅保留必要控件。|简单旧版页脚：仅 CustomHtml 和版权。|紧凑行：CustomHtml 和版权在左，链接和 CTA 在右。|三列页脚，用于内容、导航和操作。|居中的垂直堆叠，适合均衡安静的页面。|双侧页脚：内容在左，操作在右。|公共站点不会渲染页脚。|预设只是起点。混合主题、内容宽度、字体、圆角、阴影、主表面和内容模板，按你的想法塑造公共页面和博客文章。|{count} 个错误|{count} 个警告|未检测到质量检查问题。|普通内容|带框内容|全出血构建器|编辑部文章|分类网格|使用系统偏好|始终减少动效|圆形|方形|使用主题边框颜色|自定义边框颜色",
  "zh-Hant":
    "經典|置中|分割|精簡應用|編輯式頁首|極簡|多欄|品牌|選單|驗證|頁面內容|卡片|側欄|連結|法律|社群|版權|品牌在左側，CustomHtml 在中間，導覽和操作在右側。|置中的垂直頁首：先顯示品牌，接著是選單、搜尋、CTA 和驗證控制項。|三區網格：品牌在左，導覽置中，CustomHtml 和操作在右。|短應用式列：品牌在左，密集控制項在右。|雜誌式頁首：頂部搜尋/驗證，中間品牌，下方選單列。|安靜頁首：品牌在左，右側只保留必要控制項。|簡單舊版頁尾：僅 CustomHtml 和版權。|精簡列：CustomHtml 和版權在左，連結和 CTA 在右。|三欄頁尾，用於內容、導覽和操作。|置中的垂直堆疊，適合平衡安靜的頁面。|雙側頁尾：內容在左，操作在右。|公開網站不會呈現頁尾。|預設只是起點。混合主題、內容寬度、字型、圓角、陰影、主表面和內容範本，依你的想法塑造公開頁面和部落格文章。|{count} 個錯誤|{count} 個警告|未偵測到品質檢查問題。|一般內容|帶框內容|全出血建構器|編輯式文章|分類網格|使用系統偏好|一律減少動效|圓形|方形|使用主題邊框顏色|自訂邊框顏色",
  ar: "كلاسيكي|موسّط|مقسّم|تطبيق مضغوط|ترويسة تحريرية|بسيط|متعدد الأعمدة|العلامة|القائمة|المصادقة|محتوى الصفحة|بطاقة|منطقة جانبية|روابط|قانوني|اجتماعي|حقوق النشر|العلامة على اليسار، وCustomHtml في الوسط، والتنقل والإجراءات على اليمين.|ترويسة عمودية موسّطة: العلامة أولاً، ثم القائمة والبحث وCTA وعناصر المصادقة.|شبكة بثلاث مناطق: العلامة يسارًا، التنقل في الوسط، وCustomHtml والإجراءات يمينًا.|شريط قصير بأسلوب التطبيق مع العلامة يسارًا وعناصر تحكم كثيفة يمينًا.|ترويسة مجلة: صف بحث/مصادقة علوي، علامة في الوسط، وصف قائمة أسفله.|ترويسة هادئة مع العلامة يسارًا والعناصر الأساسية فقط يمينًا.|تذييل قديم بسيط: CustomHtml وحقوق النشر فقط.|صف مضغوط: CustomHtml وحقوق النشر يسارًا، والروابط وCTA يمينًا.|تذييل بثلاثة أعمدة للمحتوى والتنقل والإجراءات.|تكديس عمودي موسّط لصفحات متوازنة وهادئة.|تذييل ذو جانبين مع المحتوى يسارًا والإجراء يمينًا.|لا يتم عرض تذييل على الموقع العام.|الإعدادات المسبقة نقاط بداية. امزج السمة وعروض المحتوى والخط ونصف القطر والظل والسطح الرئيسي وقوالب المحتوى لتشكيل الصفحات العامة ومقالات المدونة كما تريد تمامًا.|{count} أخطاء|{count} تحذيرات|لم يتم اكتشاف مشكلات في بوابات الجودة.|محتوى عادي|محتوى مؤطر|منشئ بعرض كامل|مقال تحريري|شبكة فئات|استخدام تفضيل النظام|تقليل الحركة دائمًا|دائرة|مربع|استخدام لون حد السمة|لون حد مخصص",
  id: "Klasik|Tengah|Terpisah|Aplikasi ringkas|Masthead editorial|Minimal|Multi-kolom|Merek|Menu|Autentikasi|Konten halaman|Kartu|Area samping|Tautan|Legal|Sosial|Copyright|Merek di kiri, CustomHtml di tengah, navigasi dan tindakan di kanan.|Header vertikal tengah: merek dulu, lalu menu, pencarian, CTA, dan kontrol autentikasi.|Grid tiga zona: merek kiri, navigasi tengah, CustomHtml dan tindakan kanan.|Bilah pendek bergaya aplikasi dengan merek di kiri dan kontrol padat di kanan.|Masthead majalah: baris pencarian/autentikasi atas, merek di tengah, baris menu di bawah.|Header tenang dengan merek di kiri dan hanya kontrol penting di kanan.|Footer legacy sederhana: hanya CustomHtml dan copyright.|Baris ringkas: CustomHtml dan copyright di kiri, tautan dan CTA di kanan.|Footer tiga kolom untuk konten, navigasi, dan tindakan.|Tumpukan vertikal tengah untuk halaman yang seimbang dan tenang.|Footer dua sisi dengan konten di kiri dan tindakan di kanan.|Footer tidak dirender di situs publik.|Preset adalah titik awal. Campur tema, lebar konten, font, radius, bayangan, permukaan utama, dan templat konten untuk membentuk halaman publik dan posting blog persis seperti yang Anda inginkan.|{count} kesalahan|{count} peringatan|Tidak ada masalah gerbang kualitas terdeteksi.|Konten normal|Konten berbingkai|Builder full-bleed|Artikel editorial|Grid kategori|Gunakan preferensi sistem|Selalu kurangi gerakan|Lingkaran|Persegi|Gunakan warna batas tema|Warna batas khusus",
  cs: "Klasické|Na střed|Rozdělené|Kompaktní aplikace|Redakční masthead|Minimální|Vícesloupcové|Značka|Menu|Ověření|Obsah stránky|Karta|Postranní oblast|Odkazy|Právní|Sociální|Copyright|Značka vlevo, CustomHtml uprostřed, navigace a akce vpravo.|Vystředěné svislé záhlaví: nejprve značka, potom menu, hledání, CTA a ověřovací ovládání.|Mřížka tří zón: značka vlevo, navigace uprostřed, CustomHtml a akce vpravo.|Krátký panel ve stylu aplikace se značkou vlevo a hustými ovládacími prvky vpravo.|Magazínový masthead: nahoře hledání/ověření, značka uprostřed, řádek menu pod tím.|Klidné záhlaví se značkou vlevo a jen základními ovládacími prvky vpravo.|Jednoduché starší zápatí: pouze CustomHtml a copyright.|Kompaktní řádek: CustomHtml a copyright vlevo, odkazy a CTA vpravo.|Třísloupcové zápatí pro obsah, navigaci a akce.|Vystředěný svislý stack pro vyvážené, klidné stránky.|Oboustranné zápatí s obsahem vlevo a akcí vpravo.|Na veřejném webu se zápatí nevykreslí.|Presety jsou výchozí body. Kombinujte téma, šířky obsahu, písmo, poloměr, stín, hlavní plochu a šablony obsahu, abyste veřejné stránky a blogové příspěvky vytvarovali přesně podle potřeby.|{count} chyb|{count} varování|Nebyly zjištěny žádné problémy v kontrolách kvality.|Normální obsah|Orámovaný obsah|Full-bleed builder|Redakční článek|Mřížka kategorií|Použít systémovou předvolbu|Vždy omezit pohyb|Kruh|Čtverec|Použít barvu ohraničení tématu|Vlastní barva ohraničení",
  ro: "Clasic|Centrat|Împărțit|Aplicație compactă|Antet editorial|Minimal|Multi-coloană|Marcă|Meniu|Autentificare|Conținut pagină|Card|Zonă laterală|Linkuri|Legal|Social|Copyright|Marca în stânga, CustomHtml la mijloc, navigare și acțiuni în dreapta.|Antet vertical centrat: întâi marca, apoi meniul, căutarea, CTA și controalele de autentificare.|Grilă cu trei zone: marca stânga, navigare centrată, CustomHtml și acțiuni dreapta.|Bară scurtă tip aplicație cu marca în stânga și controale dense în dreapta.|Antet de revistă: rând superior căutare/autentificare, marca centrată, rând meniu dedesubt.|Antet discret cu marca în stânga și doar controale esențiale în dreapta.|Subsol legacy simplu: doar CustomHtml și copyright.|Rând compact: CustomHtml și copyright în stânga, linkuri și CTA în dreapta.|Subsol cu trei coloane pentru conținut, navigare și acțiuni.|Stivă verticală centrată pentru pagini echilibrate și calme.|Subsol pe două părți cu conținut în stânga și acțiune în dreapta.|Nu se redă niciun subsol pe site-ul public.|Presetările sunt puncte de plecare. Combinați tema, lățimile de conținut, fontul, raza, umbra, suprafața principală și șabloanele de conținut pentru a modela paginile publice și articolele de blog exact cum doriți.|{count} erori|{count} avertismente|Nu au fost detectate probleme la verificările de calitate.|Conținut normal|Conținut încadrat|Builder full-bleed|Articol editorial|Grilă categorii|Folosește preferința sistemului|Reduce întotdeauna mișcarea|Cerc|Pătrat|Folosește culoarea chenarului din temă|Culoare chenar personalizată",
  el: "Κλασικό|Κεντραρισμένο|Διαιρεμένο|Συμπαγής εφαρμογή|Εκδοτική κεφαλίδα|Ελάχιστο|Πολλαπλών στηλών|Επωνυμία|Μενού|Έλεγχος ταυτότητας|Περιεχόμενο σελίδας|Κάρτα|Πλευρική περιοχή|Σύνδεσμοι|Νομικά|Κοινωνικά|Copyright|Η επωνυμία αριστερά, το CustomHtml στο κέντρο, η πλοήγηση και οι ενέργειες δεξιά.|Κεντραρισμένη κάθετη κεφαλίδα: πρώτα η επωνυμία, μετά μενού, αναζήτηση, CTA και έλεγχοι ταυτότητας.|Πλέγμα τριών ζωνών: επωνυμία αριστερά, πλοήγηση στο κέντρο, CustomHtml και ενέργειες δεξιά.|Σύντομη γραμμή τύπου εφαρμογής με επωνυμία αριστερά και πυκνούς ελέγχους δεξιά.|Κεφαλίδα περιοδικού: αναζήτηση/ταυτότητα επάνω, κεντραρισμένη επωνυμία, γραμμή μενού από κάτω.|Ήσυχη κεφαλίδα με επωνυμία αριστερά και μόνο βασικούς ελέγχους δεξιά.|Απλό παλιό υποσέλιδο: μόνο CustomHtml και copyright.|Συμπαγής γραμμή: CustomHtml και copyright αριστερά, σύνδεσμοι και CTA δεξιά.|Υποσέλιδο τριών στηλών για περιεχόμενο, πλοήγηση και ενέργειες.|Κεντραρισμένη κάθετη στοίβα για ισορροπημένες, ήσυχες σελίδες.|Διπλό υποσέλιδο με περιεχόμενο αριστερά και ενέργεια δεξιά.|Δεν αποδίδεται υποσέλιδο στον δημόσιο ιστότοπο.|Τα preset είναι σημεία εκκίνησης. Αναμείξτε θέμα, πλάτη περιεχομένου, γραμματοσειρά, ακτίνα, σκιά, κύρια επιφάνεια και πρότυπα περιεχομένου για να διαμορφώσετε δημόσιες σελίδες και αναρτήσεις blog όπως ακριβώς θέλετε.|{count} σφάλματα|{count} προειδοποιήσεις|Δεν εντοπίστηκαν προβλήματα στους ελέγχους ποιότητας.|Κανονικό περιεχόμενο|Πλαισιωμένο περιεχόμενο|Full-bleed builder|Εκδοτικό άρθρο|Πλέγμα κατηγοριών|Χρήση προτίμησης συστήματος|Πάντα μείωση κίνησης|Κύκλος|Τετράγωνο|Χρήση χρώματος περιγράμματος θέματος|Προσαρμοσμένο χρώμα περιγράμματος",
  da: "Klassisk|Centreret|Delt|Kompakt app|Redaktionel masthead|Minimal|Flere kolonner|Mærke|Menu|Godkendelse|Sideindhold|Kort|Sideområde|Links|Juridisk|Social|Copyright|Mærke til venstre, CustomHtml i midten, navigation og handlinger til højre.|Centreret lodret header: mærke først, derefter menu, søgning, CTA og godkendelseskontroller.|Trezonet gitter: mærke til venstre, navigation centreret, CustomHtml og handlinger til højre.|Kort app-lignende bjælke med mærke til venstre og tætte kontroller til højre.|Magasin-masthead: søgning/godkendelse øverst, centreret mærke, menurække nedenunder.|Rolig header med mærke til venstre og kun vigtige kontroller til højre.|Enkel legacy-footer: kun CustomHtml og copyright.|Kompakt række: CustomHtml og copyright til venstre, links og CTA til højre.|Tre-kolonne footer til indhold, navigation og handlinger.|Centreret lodret stak til balancerede, rolige sider.|Tosidet footer med indhold til venstre og handling til højre.|Der vises ingen footer på det offentlige site.|Presets er startpunkter. Bland tema, indholdsbredder, skrifttype, radius, skygge, hovedflade og indholdsskabeloner for at forme offentlige sider og blogindlæg præcis som ønsket.|{count} fejl|{count} advarsler|Ingen kvalitetskontrolproblemer registreret.|Normalt indhold|Indrammet indhold|Full-bleed builder|Redaktionel artikel|Kategorigitter|Brug systempræference|Reducer altid bevægelse|Cirkel|Firkant|Brug temaets kantfarve|Brugerdefineret kantfarve",
  sv: "Klassisk|Centrerad|Delad|Kompakt app|Redaktionellt sidhuvud|Minimal|Flerkolumn|Varumärke|Meny|Autentisering|Sidinnehåll|Kort|Sidoområde|Länkar|Juridiskt|Socialt|Copyright|Varumärke till vänster, CustomHtml i mitten, navigering och åtgärder till höger.|Centrerat vertikalt sidhuvud: först varumärke, sedan meny, sök, CTA och autentiseringskontroller.|Trezonsrutnät: varumärke till vänster, navigering centrerad, CustomHtml och åtgärder till höger.|Kort app-liknande rad med varumärke till vänster och täta kontroller till höger.|Magasinhuvud: sök/autentisering högst upp, varumärke centrerat, menyrad under.|Lugnt sidhuvud med varumärke till vänster och endast viktiga kontroller till höger.|Enkel äldre sidfot: endast CustomHtml och copyright.|Kompakt rad: CustomHtml och copyright till vänster, länkar och CTA till höger.|Tre-kolumners sidfot för innehåll, navigering och åtgärder.|Centrerad vertikal stapel för balanserade, lugna sidor.|Tvåsidig sidfot med innehåll till vänster och åtgärd till höger.|Ingen sidfot renderas på den offentliga webbplatsen.|Presets är startpunkter. Blanda tema, innehållsbredder, typsnitt, radie, skugga, huvudyta och innehållsmallar för att forma publika sidor och blogginlägg precis som du vill.|{count} fel|{count} varningar|Inga kvalitetskontrollproblem upptäcktes.|Normalt innehåll|Inramat innehåll|Full-bleed builder|Redaktionell artikel|Kategoriraster|Använd systeminställning|Minska alltid rörelse|Cirkel|Kvadrat|Använd temats ramfärg|Anpassad ramfärg",
  nb: "Klassisk|Sentrert|Delt|Kompakt app|Redaksjonelt toppfelt|Minimal|Flere kolonner|Merkevare|Meny|Autentisering|Sideinnhold|Kort|Sideområde|Lenker|Juridisk|Sosialt|Copyright|Merkevare til venstre, CustomHtml i midten, navigasjon og handlinger til høyre.|Sentrert vertikal topptekst: merkevare først, deretter meny, søk, CTA og autentiseringskontroller.|Tre-soners rutenett: merkevare til venstre, navigasjon sentrert, CustomHtml og handlinger til høyre.|Kort applignende linje med merkevare til venstre og tette kontroller til høyre.|Magasin-toppfelt: søk/autentisering øverst, merkevare sentrert, menylinje under.|Rolig topptekst med merkevare til venstre og bare viktige kontroller til høyre.|Enkel eldre bunntekst: bare CustomHtml og copyright.|Kompakt rad: CustomHtml og copyright til venstre, lenker og CTA til høyre.|Tre-kolonners bunntekst for innhold, navigasjon og handlinger.|Sentrert vertikal stabel for balanserte, rolige sider.|Tosidig bunntekst med innhold til venstre og handling til høyre.|Ingen bunntekst gjengis på det offentlige nettstedet.|Presets er startpunkter. Bland tema, innholdsbredder, skrifttype, radius, skygge, hovedflate og innholdsmaler for å forme offentlige sider og blogginnlegg akkurat slik du vil.|{count} feil|{count} advarsler|Ingen kvalitetskontrollproblemer oppdaget.|Normalt innhold|Innrammet innhold|Full-bleed builder|Redaksjonell artikkel|Kategorirutenett|Bruk systeminnstilling|Reduser alltid bevegelse|Sirkel|Firkant|Bruk temaets kantfarge|Egendefinert kantfarge",
  nn: "Klassisk|Sentrert|Delt|Kompakt app|Redaksjonelt toppfelt|Minimal|Fleire kolonnar|Merkevare|Meny|Autentisering|Sideinnhald|Kort|Sideområde|Lenkjer|Juridisk|Sosialt|Copyright|Merkevare til venstre, CustomHtml i midten, navigasjon og handlingar til høgre.|Sentrert vertikal topptekst: merkevare først, deretter meny, søk, CTA og autentiseringskontrollar.|Tre-soners rutenett: merkevare til venstre, navigasjon sentrert, CustomHtml og handlingar til høgre.|Kort appliknande linje med merkevare til venstre og tette kontrollar til høgre.|Magasin-toppfelt: søk/autentisering øvst, merkevare sentrert, menylinje under.|Rolig topptekst med merkevare til venstre og berre viktige kontrollar til høgre.|Enkel eldre botntekst: berre CustomHtml og copyright.|Kompakt rad: CustomHtml og copyright til venstre, lenkjer og CTA til høgre.|Tre-kolonnars botntekst for innhald, navigasjon og handlingar.|Sentrert vertikal stabel for balanserte, rolege sider.|Tosidig botntekst med innhald til venstre og handling til høgre.|Ingen botntekst blir vist på den offentlege nettstaden.|Presets er startpunkt. Bland tema, innhaldsbreidder, skrift, radius, skugge, hovudflate og innhaldsmalar for å forme offentlege sider og blogginnlegg akkurat slik du vil.|{count} feil|{count} åtvaringar|Ingen kvalitetskontrollproblem oppdaga.|Normalt innhald|Innramma innhald|Full-bleed builder|Redaksjonell artikkel|Kategorirutenett|Bruk systeminnstilling|Reduser alltid rørsle|Sirkel|Firkant|Bruk temakantfarge|Eigendefinert kantfarge",
  fi: "Klassinen|Keskitetty|Jaettu|Kompakti sovellus|Toimituksellinen otsake|Minimaalinen|Monisarakkeinen|Brändi|Valikko|Tunnistautuminen|Sivun sisältö|Kortti|Sivualue|Linkit|Lakiosio|Sosiaalinen|Copyright|Brändi vasemmalla, CustomHtml keskellä, navigaatio ja toiminnot oikealla.|Keskitetty pystysuuntainen ylätunniste: ensin brändi, sitten valikko, haku, CTA ja tunnistautumisen ohjaimet.|Kolmen alueen ruudukko: brändi vasemmalla, navigaatio keskellä, CustomHtml ja toiminnot oikealla.|Lyhyt sovellustyylinen palkki, jossa brändi vasemmalla ja tiiviit ohjaimet oikealla.|Lehtimäinen otsake: haku/tunnistautuminen yläreunassa, brändi keskellä, valikkorivi alla.|Rauhallinen ylätunniste, jossa brändi vasemmalla ja vain olennaiset ohjaimet oikealla.|Yksinkertainen vanha alatunniste: vain CustomHtml ja copyright.|Kompakti rivi: CustomHtml ja copyright vasemmalla, linkit ja CTA oikealla.|Kolmisarakkeinen alatunniste sisällölle, navigaatiolle ja toiminnoille.|Keskitetty pystypino tasapainoisille, rauhallisille sivuille.|Kaksipuolinen alatunniste, jossa sisältö vasemmalla ja toiminto oikealla.|Julkisella sivustolla ei näytetä alatunnistetta.|Esiasetukset ovat lähtökohtia. Sekoita teemaa, sisältöleveyksiä, fonttia, sädettä, varjoa, pääpintaa ja sisältömalleja muotoillaksesi julkiset sivut ja blogikirjoitukset juuri haluamallasi tavalla.|{count} virhettä|{count} varoitusta|Laatutarkistuksissa ei havaittu ongelmia.|Normaali sisältö|Kehystetty sisältö|Full-bleed builder|Toimituksellinen artikkeli|Kategorian ruudukko|Käytä järjestelmäasetusta|Vähennä liikettä aina|Ympyrä|Neliö|Käytä teeman reunaväriä|Mukautettu reunaväri",
  is: "Klassískt|Miðjað|Skipt|Þétt app|Ritstjórnarhaus|Lágmarks|Margir dálkar|Vörumerki|Valmynd|Auðkenning|Efni síðu|Spjald|Hliðarsvæði|Tenglar|Lagalegt|Samfélagslegt|Copyright|Vörumerki til vinstri, CustomHtml í miðju, leiðsögn og aðgerðir til hægri.|Miðjaður lóðréttur haus: fyrst vörumerki, síðan valmynd, leit, CTA og auðkenningarstýringar.|Þriggja svæða grind: vörumerki til vinstri, leiðsögn í miðju, CustomHtml og aðgerðir til hægri.|Stutt app-lík stika með vörumerki til vinstri og þéttum stýringum til hægri.|Tímaritshaus: leit/auðkenning efst, vörumerki miðjað, valmyndarröð fyrir neðan.|Rólegur haus með vörumerki til vinstri og aðeins nauðsynlegum stýringum til hægri.|Einfaldur eldri fótur: aðeins CustomHtml og copyright.|Þétt röð: CustomHtml og copyright til vinstri, tenglar og CTA til hægri.|Þriggja dálka fótur fyrir efni, leiðsögn og aðgerðir.|Miðjuð lóðrétt stafla fyrir jafnvægar, rólegar síður.|Tvíhliða fótur með efni til vinstri og aðgerð til hægri.|Enginn fótur er birtur á opinbera vefnum.|Forstillingar eru upphafspunktar. Blandaðu þema, efnisbreiddum, letri, radíus, skugga, aðalyfirborði og efnissniðmátum til að móta opinberar síður og bloggfærslur nákvæmlega eins og þú vilt.|{count} villur|{count} viðvaranir|Engin gæðaprófunarvandamál fundust.|Venjulegt efni|Innramað efni|Full-bleed builder|Ritstjórnargrein|Flokkanet|Nota kerfisstillingu|Minnka alltaf hreyfingu|Hringur|Ferningur|Nota rammalit þema|Sérsniðinn rammalitur",
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<AppearanceSource, string> {
  const translations = row.split("|");
  if (
    translations.length !== GLOBAL_SETTINGS_APPEARANCE_SOURCE_STRINGS.length
  ) {
    throw new Error(
      `${language} global settings appearance translations must have ${GLOBAL_SETTINGS_APPEARANCE_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    GLOBAL_SETTINGS_APPEARANCE_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<AppearanceSource, string>;
}

export const GLOBAL_SETTINGS_APPEARANCE_SOURCE_TRANSLATIONS =
  Object.fromEntries(
    Object.entries(ROWS).map(([language, row]) => [
      language,
      createMap(language, row),
    ]),
  ) as Record<LocalizedLanguage, Record<AppearanceSource, string>>;
