import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const MENU_MANAGEMENT_SOURCE_STRINGS = [
  "Create and manage reusable navigation menus. Admin access only.",
  "Search menus...",
  "No menus found.",
  "Create Menu",
  "Menu names must be unique across the system.",
  "Menu Name",
  "Rename Menu",
  "Reassign Menu",
  'Change the owner of "{name}".',
  "Delete menu?",
  "This will permanently delete {name} and all of its menu items. This action cannot be undone.",
  'Select another menu or "Without menu" in Header Settings before deleting.',
  'This menu is assigned to the Header. Select another menu or "Without menu" in Header Settings before deleting it.',
  'Drag content items from the left into the menu on the right. Reorder by dragging existing items up/down or sideways to nest. Use "Add blog category" to link to a list of posts in a category, or "Add custom link" for a free-form URL. Admin access only.',
  "Search content...",
  "No content items found.",
  "Menu structure",
  'No menu items yet. Drag a content item from the left, or click "Add custom link".',
  "Drag horizontally while moving an item to nest it under the row above. Drag a content item from the left panel onto the menu to create a new linked item.",
  "Menu item",
  "Add custom link",
  "Add a menu item with a custom URL (external or internal path).",
  "Edit menu item",
  "Edit the label, URL, and link target.",
  "URL is locked because this item is linked to content or a category. It will follow the source automatically.",
  "Label is required.",
  "e.g. Documentation",
  "URL is required.",
  "Enter an external URL, an internal path starting with /, or an anchor starting with #.",
  "https://example.com, /path, or #",
  "Open in",
  "Same tab",
  "New tab",
  "Add blog category",
  "Pick a blog category. The menu item will link to a page that lists all published blog posts in that category.",
  "No blog categories available.",
  "Label (optional)",
  "Defaults to the category name",
  "Pick a category.",
  "Delete menu item?",
  "This will permanently delete {label} and all {count} nested items. This action cannot be undone.",
  "This will permanently delete {label}. This action cannot be undone.",
  "Drag handle",
  "External",
  "Custom",
  "new tab",
] as const;

type MenuManagementSource = (typeof MENU_MANAGEMENT_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn": `Kreiraj i upravljaj višekratnim navigacionim menijima. Samo za admine.|Pretraži menije...|Nema pronađenih menija.|Kreiraj meni|Nazivi menija moraju biti jedinstveni u sistemu.|Naziv menija|Preimenuj meni|Dodeli meni drugome|Promeni vlasnika za "{name}".|Obrisati meni?|Ovo će trajno obrisati {name} i sve njegove stavke menija. Ova radnja se ne može opozvati.|Izaberi drugi meni ili "Bez menija" u podešavanjima zaglavlja pre brisanja.|Ovaj meni je dodeljen zaglavlju. Izaberi drugi meni ili "Bez menija" u podešavanjima zaglavlja pre brisanja.|Prevuci stavke sadržaja s leve strane u meni s desne strane. Promeni redosled prevlačenjem postojećih stavki gore-dole ili bočno za ugnježđivanje. Koristi "Dodaj blog kategoriju" za link ka listi objava u kategoriji ili "Dodaj prilagođeni link" za slobodan URL. Samo za admine.|Pretraži sadržaj...|Nema pronađenih stavki sadržaja.|Struktura menija|Još nema stavki menija. Prevuci stavku sadržaja s leve strane ili klikni "Dodaj prilagođeni link".|Prevuci vodoravno tokom pomeranja stavke da je ugnjezdiš ispod reda iznad. Prevuci stavku sadržaja iz levog panela na meni da napraviš novu povezanu stavku.|Stavka menija|Dodaj prilagođeni link|Dodaj stavku menija sa prilagođenim URL-om (spoljašnja ili interna putanja).|Uredi stavku menija|Uredi oznaku, URL i cilj linka.|URL je zaključan jer je ova stavka povezana sa sadržajem ili kategorijom. Automatski će pratiti izvor.|Oznaka je obavezna.|npr. Dokumentacija|URL je obavezan.|Unesi spoljašnji URL, internu putanju koja počinje sa / ili sidro koje počinje sa #.|https://primer.com, /putanja ili #|Otvori u|Ista kartica|Nova kartica|Dodaj blog kategoriju|Izaberi blog kategoriju. Stavka menija će voditi ka stranici koja prikazuje sve objavljene blog objave u toj kategoriji.|Nema dostupnih blog kategorija.|Oznaka (opciono)|Podrazumevano je naziv kategorije|Izaberi kategoriju.|Obrisati stavku menija?|Ovo će trajno obrisati {label} i svih {count} ugnježđenih stavki. Ova radnja se ne može opozvati.|Ovo će trajno obrisati {label}. Ova radnja se ne može opozvati.|Ručka za prevlačenje|Spoljašnje|Prilagođeno|nova kartica`,
  "sr-Cyrl": `Креирај и управљај вишекратним навигационим менијима. Само за администраторе.|Претражи меније...|Нема пронађених менија.|Креирај мени|Називи менија морају бити јединствени у систему.|Назив менија|Преименуј мени|Додели мени другоме|Промени власника за "{name}".|Обрисати мени?|Ово ће трајно обрисати {name} и све његове ставке менија. Ова радња се не може опозвати.|Изабери други мени или "Без менија" у подешавањима заглавља пре брисања.|Овај мени је додељен заглављу. Изабери други мени или "Без менија" у подешавањима заглавља пре брисања.|Превуци ставке садржаја с леве стране у мени с десне стране. Промени редослед превлачењем постојећих ставки горе-доле или бочно за угнежђивање. Користи "Додај блог категорију" за линк ка листи објава у категорији или "Додај прилагођени линк" за слободан URL. Само за администраторе.|Претражи садржај...|Нема пронађених ставки садржаја.|Структура менија|Још нема ставки менија. Превуци ставку садржаја с леве стране или кликни "Додај прилагођени линк".|Превуци водоравно током померања ставке да је угнездиш испод реда изнад. Превуци ставку садржаја из левог панела на мени да направиш нову повезану ставку.|Ставка менија|Додај прилагођени линк|Додај ставку менија са прилагођеним URL-ом (спољашња или интерна путања).|Уреди ставку менија|Уреди ознаку, URL и циљ линка.|URL је закључан јер је ова ставка повезана са садржајем или категоријом. Аутоматски ће пратити извор.|Ознака је обавезна.|нпр. Документација|URL је обавезан.|Унеси спољашњи URL, интерну путању која почиње са / или сидро које почиње са #.|https://primer.com, /putanja или #|Отвори у|Иста картица|Нова картица|Додај блог категорију|Изабери блог категорију. Ставка менија ће водити ка страници која приказује све објављене блог објаве у тој категорији.|Нема доступних блог категорија.|Ознака (опционо)|Подразумевано је назив категорије|Изабери категорију.|Обрисати ставку менија?|Ово ће трајно обрисати {label} и свих {count} угнежђених ставки. Ова радња се не може опозвати.|Ово ће трајно обрисати {label}. Ова радња се не може опозвати.|Ручка за превлачење|Спољашње|Прилагођено|нова картица`,
  hr: `Stvarajte i upravljajte višekratnim navigacijskim izbornicima. Samo za administratore.|Pretraži izbornike...|Nema pronađenih izbornika.|Stvori izbornik|Nazivi izbornika moraju biti jedinstveni u sustavu.|Naziv izbornika|Preimenuj izbornik|Dodijeli izbornik drugome|Promijeni vlasnika za "{name}".|Izbrisati izbornik?|Ovo će trajno izbrisati {name} i sve njegove stavke izbornika. Ova se radnja ne može poništiti.|Odaberite drugi izbornik ili "Bez izbornika" u postavkama zaglavlja prije brisanja.|Ovaj je izbornik dodijeljen zaglavlju. Odaberite drugi izbornik ili "Bez izbornika" u postavkama zaglavlja prije brisanja.|Povucite stavke sadržaja s lijeve strane u izbornik s desne strane. Promijenite redoslijed povlačenjem postojećih stavki gore-dolje ili bočno za ugnježđivanje. Koristite "Dodaj blog kategoriju" za poveznicu na popis objava u kategoriji ili "Dodaj prilagođenu poveznicu" za slobodan URL. Samo za administratore.|Pretraži sadržaj...|Nema pronađenih stavki sadržaja.|Struktura izbornika|Još nema stavki izbornika. Povucite stavku sadržaja s lijeve strane ili kliknite "Dodaj prilagođenu poveznicu".|Povucite vodoravno dok pomičete stavku kako biste je ugnijezdili ispod retka iznad. Povucite stavku sadržaja iz lijevog panela na izbornik za stvaranje nove povezane stavke.|Stavka izbornika|Dodaj prilagođenu poveznicu|Dodaj stavku izbornika s prilagođenim URL-om (vanjska ili interna putanja).|Uredi stavku izbornika|Uredi oznaku, URL i cilj poveznice.|URL je zaključan jer je ova stavka povezana sa sadržajem ili kategorijom. Automatski će pratiti izvor.|Oznaka je obavezna.|npr. Dokumentacija|URL je obavezan.|Unesite vanjski URL, internu putanju koja počinje s / ili sidro koje počinje s #.|https://primjer.com, /putanja ili #|Otvori u|Ista kartica|Nova kartica|Dodaj blog kategoriju|Odaberite blog kategoriju. Stavka izbornika povezivat će na stranicu koja prikazuje sve objavljene blog objave u toj kategoriji.|Nema dostupnih blog kategorija.|Oznaka (opcionalno)|Zadano je naziv kategorije|Odaberite kategoriju.|Izbrisati stavku izbornika?|Ovo će trajno izbrisati {label} i svih {count} ugniježđenih stavki. Ova se radnja ne može poništiti.|Ovo će trajno izbrisati {label}. Ova se radnja ne može poništiti.|Ručka za povlačenje|Vanjsko|Prilagođeno|nova kartica`,
  de: `Erstelle und verwalte wiederverwendbare Navigationsmenüs. Nur Adminzugriff.|Menüs suchen...|Keine Menüs gefunden.|Menü erstellen|Menünamen müssen im System eindeutig sein.|Menüname|Menü umbenennen|Menü neu zuweisen|Ändere den Besitzer von "{name}".|Menü löschen?|Dies löscht {name} und alle zugehörigen Menüeinträge dauerhaft. Diese Aktion kann nicht rückgängig gemacht werden.|Wähle vor dem Löschen in den Header-Einstellungen ein anderes Menü oder "Ohne Menü" aus.|Dieses Menü ist dem Header zugewiesen. Wähle vor dem Löschen in den Header-Einstellungen ein anderes Menü oder "Ohne Menü" aus.|Ziehe Inhaltselemente von links in das Menü rechts. Sortiere vorhandene Einträge per Ziehen nach oben, unten oder seitlich, um sie zu verschachteln. Nutze "Blogkategorie hinzufügen", um auf eine Liste von Beiträgen in einer Kategorie zu verlinken, oder "Benutzerdefinierten Link hinzufügen" für eine freie URL. Nur Adminzugriff.|Inhalt suchen...|Keine Inhaltselemente gefunden.|Menüstruktur|Noch keine Menüeinträge. Ziehe ein Inhaltselement von links hinein oder klicke auf "Benutzerdefinierten Link hinzufügen".|Ziehe beim Verschieben horizontal, um einen Eintrag unter der Zeile darüber zu verschachteln. Ziehe ein Inhaltselement aus dem linken Panel auf das Menü, um einen neuen verknüpften Eintrag zu erstellen.|Menüeintrag|Benutzerdefinierten Link hinzufügen|Füge einen Menüeintrag mit einer benutzerdefinierten URL hinzu (extern oder interner Pfad).|Menüeintrag bearbeiten|Bearbeite Beschriftung, URL und Linkziel.|Die URL ist gesperrt, weil dieser Eintrag mit Inhalt oder einer Kategorie verknüpft ist. Sie folgt automatisch der Quelle.|Beschriftung ist erforderlich.|z. B. Dokumentation|URL ist erforderlich.|Gib eine externe URL, einen internen Pfad beginnend mit / oder einen Anker beginnend mit # ein.|https://beispiel.de, /pfad oder #|Öffnen in|Gleicher Tab|Neuer Tab|Blogkategorie hinzufügen|Wähle eine Blogkategorie. Der Menüeintrag verlinkt auf eine Seite, die alle veröffentlichten Blogbeiträge dieser Kategorie auflistet.|Keine Blogkategorien verfügbar.|Beschriftung (optional)|Standardmäßig der Kategoriename|Kategorie auswählen.|Menüeintrag löschen?|Dies löscht {label} und alle {count} verschachtelten Einträge dauerhaft. Diese Aktion kann nicht rückgängig gemacht werden.|Dies löscht {label} dauerhaft. Diese Aktion kann nicht rückgängig gemacht werden.|Ziehgriff|Extern|Benutzerdefiniert|neuer Tab`,
  fr: `Créez et gérez des menus de navigation réutilisables. Accès administrateur uniquement.|Rechercher des menus...|Aucun menu trouvé.|Créer un menu|Les noms de menu doivent être uniques dans le système.|Nom du menu|Renommer le menu|Réattribuer le menu|Changer le propriétaire de "{name}".|Supprimer le menu ?|Cela supprimera définitivement {name} et tous ses éléments de menu. Cette action est irréversible.|Sélectionnez un autre menu ou "Sans menu" dans les paramètres d'en-tête avant de supprimer.|Ce menu est attribué à l'en-tête. Sélectionnez un autre menu ou "Sans menu" dans les paramètres d'en-tête avant de le supprimer.|Faites glisser les éléments de contenu depuis la gauche vers le menu à droite. Réorganisez les éléments en les faisant glisser vers le haut, le bas ou sur le côté pour les imbriquer. Utilisez "Ajouter une catégorie de blog" pour créer un lien vers une liste d'articles d'une catégorie, ou "Ajouter un lien personnalisé" pour une URL libre. Accès administrateur uniquement.|Rechercher du contenu...|Aucun élément de contenu trouvé.|Structure du menu|Aucun élément de menu pour le moment. Faites glisser un élément de contenu depuis la gauche ou cliquez sur "Ajouter un lien personnalisé".|Faites glisser horizontalement pendant le déplacement d'un élément pour l'imbriquer sous la ligne au-dessus. Faites glisser un élément de contenu depuis le panneau gauche vers le menu pour créer un nouvel élément lié.|Élément de menu|Ajouter un lien personnalisé|Ajoutez un élément de menu avec une URL personnalisée (externe ou chemin interne).|Modifier l'élément de menu|Modifiez le libellé, l'URL et la cible du lien.|L'URL est verrouillée car cet élément est lié à un contenu ou une catégorie. Elle suivra automatiquement la source.|Le libellé est obligatoire.|p. ex. Documentation|L'URL est obligatoire.|Saisissez une URL externe, un chemin interne commençant par / ou une ancre commençant par #.|https://exemple.com, /chemin ou #|Ouvrir dans|Même onglet|Nouvel onglet|Ajouter une catégorie de blog|Choisissez une catégorie de blog. L'élément de menu mènera à une page listant tous les articles publiés dans cette catégorie.|Aucune catégorie de blog disponible.|Libellé (facultatif)|Par défaut, le nom de la catégorie|Sélectionnez une catégorie.|Supprimer l'élément de menu ?|Cela supprimera définitivement {label} et les {count} éléments imbriqués. Cette action est irréversible.|Cela supprimera définitivement {label}. Cette action est irréversible.|Poignée de glisser-déposer|Externe|Personnalisé|nouvel onglet`,
  es: `Crea y administra menús de navegación reutilizables. Solo acceso de administradores.|Buscar menús...|No se encontraron menús.|Crear menú|Los nombres de menú deben ser únicos en el sistema.|Nombre del menú|Renombrar menú|Reasignar menú|Cambiar el propietario de "{name}".|¿Eliminar menú?|Esto eliminará permanentemente {name} y todos sus elementos de menú. Esta acción no se puede deshacer.|Selecciona otro menú o "Sin menú" en la configuración del encabezado antes de eliminar.|Este menú está asignado al encabezado. Selecciona otro menú o "Sin menú" en la configuración del encabezado antes de eliminarlo.|Arrastra elementos de contenido desde la izquierda al menú de la derecha. Reordena arrastrando elementos existentes arriba, abajo o hacia los lados para anidarlos. Usa "Agregar categoría de blog" para enlazar a una lista de publicaciones de una categoría, o "Agregar enlace personalizado" para una URL libre. Solo acceso de administradores.|Buscar contenido...|No se encontraron elementos de contenido.|Estructura del menú|Aún no hay elementos de menú. Arrastra un elemento de contenido desde la izquierda o haz clic en "Agregar enlace personalizado".|Arrastra horizontalmente al mover un elemento para anidarlo bajo la fila superior. Arrastra un elemento de contenido desde el panel izquierdo al menú para crear un nuevo elemento enlazado.|Elemento de menú|Agregar enlace personalizado|Agrega un elemento de menú con una URL personalizada (externa o ruta interna).|Editar elemento de menú|Edita la etiqueta, la URL y el destino del enlace.|La URL está bloqueada porque este elemento está vinculado a contenido o a una categoría. Seguirá automáticamente la fuente.|La etiqueta es obligatoria.|p. ej. Documentación|La URL es obligatoria.|Introduce una URL externa, una ruta interna que empiece por / o un ancla que empiece por #.|https://ejemplo.com, /ruta o #|Abrir en|Misma pestaña|Nueva pestaña|Agregar categoría de blog|Elige una categoría de blog. El elemento de menú enlazará a una página que lista todas las publicaciones publicadas en esa categoría.|No hay categorías de blog disponibles.|Etiqueta (opcional)|Por defecto, el nombre de la categoría|Selecciona una categoría.|¿Eliminar elemento de menú?|Esto eliminará permanentemente {label} y los {count} elementos anidados. Esta acción no se puede deshacer.|Esto eliminará permanentemente {label}. Esta acción no se puede deshacer.|Asa para arrastrar|Externo|Personalizado|nueva pestaña`,
  it: `Crea e gestisci menu di navigazione riutilizzabili. Accesso solo amministratori.|Cerca menu...|Nessun menu trovato.|Crea menu|I nomi dei menu devono essere univoci nel sistema.|Nome menu|Rinomina menu|Riassegna menu|Cambia il proprietario di "{name}".|Eliminare il menu?|Questo eliminerà definitivamente {name} e tutti i suoi elementi di menu. Questa azione non può essere annullata.|Seleziona un altro menu o "Senza menu" nelle impostazioni dell'intestazione prima di eliminare.|Questo menu è assegnato all'intestazione. Seleziona un altro menu o "Senza menu" nelle impostazioni dell'intestazione prima di eliminarlo.|Trascina gli elementi di contenuto da sinistra nel menu a destra. Riordina trascinando gli elementi esistenti su, giù o lateralmente per annidarli. Usa "Aggiungi categoria blog" per collegare una lista di post in una categoria, oppure "Aggiungi link personalizzato" per un URL libero. Accesso solo amministratori.|Cerca contenuti...|Nessun elemento di contenuto trovato.|Struttura menu|Nessun elemento di menu ancora. Trascina un elemento di contenuto da sinistra oppure fai clic su "Aggiungi link personalizzato".|Trascina orizzontalmente mentre sposti un elemento per annidarlo sotto la riga sopra. Trascina un elemento di contenuto dal pannello sinistro nel menu per creare un nuovo elemento collegato.|Elemento di menu|Aggiungi link personalizzato|Aggiungi un elemento di menu con un URL personalizzato (esterno o percorso interno).|Modifica elemento di menu|Modifica etichetta, URL e destinazione del link.|L'URL è bloccato perché questo elemento è collegato a contenuto o categoria. Seguirà automaticamente la fonte.|L'etichetta è obbligatoria.|es. Documentazione|L'URL è obbligatorio.|Inserisci un URL esterno, un percorso interno che inizia con / o un'ancora che inizia con #.|https://esempio.com, /percorso o #|Apri in|Stessa scheda|Nuova scheda|Aggiungi categoria blog|Scegli una categoria blog. L'elemento di menu collegherà a una pagina che elenca tutti i post pubblicati in quella categoria.|Nessuna categoria blog disponibile.|Etichetta (opzionale)|Predefinito al nome della categoria|Seleziona una categoria.|Eliminare elemento di menu?|Questo eliminerà definitivamente {label} e tutti i {count} elementi annidati. Questa azione non può essere annullata.|Questo eliminerà definitivamente {label}. Questa azione non può essere annullata.|Maniglia di trascinamento|Esterno|Personalizzato|nuova scheda`,
  pt: `Crie e gira menus de navegação reutilizáveis. Acesso apenas para administradores.|Pesquisar menus...|Nenhum menu encontrado.|Criar menu|Os nomes dos menus têm de ser únicos no sistema.|Nome do menu|Renomear menu|Reatribuir menu|Alterar o proprietário de "{name}".|Eliminar menu?|Isto eliminará permanentemente {name} e todos os seus itens de menu. Esta ação não pode ser anulada.|Selecione outro menu ou "Sem menu" nas definições do cabeçalho antes de eliminar.|Este menu está atribuído ao cabeçalho. Selecione outro menu ou "Sem menu" nas definições do cabeçalho antes de o eliminar.|Arraste itens de conteúdo da esquerda para o menu à direita. Reordene arrastando itens existentes para cima, para baixo ou lateralmente para os aninhar. Use "Adicionar categoria de blog" para ligar a uma lista de publicações numa categoria, ou "Adicionar ligação personalizada" para um URL livre. Acesso apenas para administradores.|Pesquisar conteúdo...|Nenhum item de conteúdo encontrado.|Estrutura do menu|Ainda não há itens de menu. Arraste um item de conteúdo da esquerda ou clique em "Adicionar ligação personalizada".|Arraste horizontalmente ao mover um item para o aninhar sob a linha acima. Arraste um item de conteúdo do painel esquerdo para o menu para criar um novo item ligado.|Item de menu|Adicionar ligação personalizada|Adicione um item de menu com um URL personalizado (externo ou caminho interno).|Editar item de menu|Edite a etiqueta, o URL e o destino da ligação.|O URL está bloqueado porque este item está ligado a conteúdo ou categoria. Seguirá automaticamente a origem.|A etiqueta é obrigatória.|ex. Documentação|O URL é obrigatório.|Introduza um URL externo, um caminho interno iniciado por / ou uma âncora iniciada por #.|https://exemplo.com, /caminho ou #|Abrir em|Mesmo separador|Novo separador|Adicionar categoria de blog|Escolha uma categoria de blog. O item de menu ligará a uma página que lista todas as publicações publicadas nessa categoria.|Não há categorias de blog disponíveis.|Etiqueta (opcional)|Por predefinição, o nome da categoria|Selecione uma categoria.|Eliminar item de menu?|Isto eliminará permanentemente {label} e todos os {count} itens aninhados. Esta ação não pode ser anulada.|Isto eliminará permanentemente {label}. Esta ação não pode ser anulada.|Pega de arrastar|Externo|Personalizado|novo separador`,
  "pt-BR": `Crie e gerencie menus de navegação reutilizáveis. Acesso apenas para administradores.|Pesquisar menus...|Nenhum menu encontrado.|Criar menu|Os nomes dos menus devem ser únicos no sistema.|Nome do menu|Renomear menu|Reatribuir menu|Alterar o proprietário de "{name}".|Excluir menu?|Isso excluirá permanentemente {name} e todos os seus itens de menu. Esta ação não pode ser desfeita.|Selecione outro menu ou "Sem menu" nas configurações do cabeçalho antes de excluir.|Este menu está atribuído ao cabeçalho. Selecione outro menu ou "Sem menu" nas configurações do cabeçalho antes de excluí-lo.|Arraste itens de conteúdo da esquerda para o menu à direita. Reordene arrastando itens existentes para cima, para baixo ou lateralmente para aninhá-los. Use "Adicionar categoria de blog" para vincular a uma lista de posts em uma categoria, ou "Adicionar link personalizado" para uma URL livre. Acesso apenas para administradores.|Pesquisar conteúdo...|Nenhum item de conteúdo encontrado.|Estrutura do menu|Ainda não há itens de menu. Arraste um item de conteúdo da esquerda ou clique em "Adicionar link personalizado".|Arraste horizontalmente ao mover um item para aninhá-lo sob a linha acima. Arraste um item de conteúdo do painel esquerdo para o menu para criar um novo item vinculado.|Item de menu|Adicionar link personalizado|Adicione um item de menu com uma URL personalizada (externa ou caminho interno).|Editar item de menu|Edite o rótulo, a URL e o destino do link.|A URL está bloqueada porque este item está vinculado a conteúdo ou categoria. Ela seguirá automaticamente a origem.|O rótulo é obrigatório.|ex. Documentação|A URL é obrigatória.|Insira uma URL externa, um caminho interno começando com / ou uma âncora começando com #.|https://exemplo.com, /caminho ou #|Abrir em|Mesma aba|Nova aba|Adicionar categoria de blog|Escolha uma categoria de blog. O item de menu vinculará a uma página que lista todos os posts publicados nessa categoria.|Não há categorias de blog disponíveis.|Rótulo (opcional)|Por padrão, o nome da categoria|Selecione uma categoria.|Excluir item de menu?|Isso excluirá permanentemente {label} e todos os {count} itens aninhados. Esta ação não pode ser desfeita.|Isso excluirá permanentemente {label}. Esta ação não pode ser desfeita.|Alça de arrastar|Externo|Personalizado|nova aba`,
  nl: `Maak en beheer herbruikbare navigatiemenu's. Alleen voor beheerders.|Menu's zoeken...|Geen menu's gevonden.|Menu maken|Menunamen moeten uniek zijn binnen het systeem.|Menunaam|Menu hernoemen|Menu opnieuw toewijzen|Wijzig de eigenaar van "{name}".|Menu verwijderen?|Dit verwijdert {name} en alle menu-items permanent. Deze actie kan niet ongedaan worden gemaakt.|Selecteer voor het verwijderen een ander menu of "Zonder menu" in de headerinstellingen.|Dit menu is toegewezen aan de header. Selecteer voor het verwijderen een ander menu of "Zonder menu" in de headerinstellingen.|Sleep inhoudsitems van links naar het menu rechts. Wijzig de volgorde door bestaande items omhoog, omlaag of zijwaarts te slepen om ze te nesten. Gebruik "Blogcategorie toevoegen" om te linken naar een lijst met berichten in een categorie, of "Aangepaste link toevoegen" voor een vrije URL. Alleen voor beheerders.|Inhoud zoeken...|Geen inhoudsitems gevonden.|Menustructuur|Nog geen menu-items. Sleep een inhoudsitem van links of klik op "Aangepaste link toevoegen".|Sleep horizontaal tijdens het verplaatsen van een item om het onder de rij erboven te nesten. Sleep een inhoudsitem uit het linkerpaneel naar het menu om een nieuw gekoppeld item te maken.|Menu-item|Aangepaste link toevoegen|Voeg een menu-item toe met een aangepaste URL (extern of intern pad).|Menu-item bewerken|Bewerk het label, de URL en het linkdoel.|De URL is vergrendeld omdat dit item is gekoppeld aan inhoud of een categorie. Het volgt automatisch de bron.|Label is verplicht.|bijv. Documentatie|URL is verplicht.|Voer een externe URL, een intern pad beginnend met / of een anker beginnend met # in.|https://voorbeeld.nl, /pad of #|Openen in|Zelfde tabblad|Nieuw tabblad|Blogcategorie toevoegen|Kies een blogcategorie. Het menu-item linkt naar een pagina met alle gepubliceerde blogberichten in die categorie.|Geen blogcategorieën beschikbaar.|Label (optioneel)|Standaard de categorienaam|Selecteer een categorie.|Menu-item verwijderen?|Dit verwijdert {label} en alle {count} geneste items permanent. Deze actie kan niet ongedaan worden gemaakt.|Dit verwijdert {label} permanent. Deze actie kan niet ongedaan worden gemaakt.|Sleepgreep|Extern|Aangepast|nieuw tabblad`,
  pl: `Twórz i zarządzaj wielokrotnego użytku menu nawigacyjnymi. Tylko administratorzy.|Szukaj menu...|Nie znaleziono menu.|Utwórz menu|Nazwy menu muszą być unikalne w systemie.|Nazwa menu|Zmień nazwę menu|Przypisz menu ponownie|Zmień właściciela "{name}".|Usunąć menu?|To trwale usunie {name} i wszystkie jego pozycje menu. Tej akcji nie można cofnąć.|Przed usunięciem wybierz inne menu lub "Bez menu" w ustawieniach nagłówka.|To menu jest przypisane do nagłówka. Przed usunięciem wybierz inne menu lub "Bez menu" w ustawieniach nagłówka.|Przeciągaj elementy treści z lewej strony do menu po prawej. Zmieniaj kolejność, przeciągając istniejące elementy w górę, w dół lub na bok, aby je zagnieździć. Użyj "Dodaj kategorię bloga", aby połączyć z listą wpisów w kategorii, albo "Dodaj link niestandardowy" dla dowolnego URL. Tylko administratorzy.|Szukaj treści...|Nie znaleziono elementów treści.|Struktura menu|Nie ma jeszcze pozycji menu. Przeciągnij element treści z lewej albo kliknij "Dodaj link niestandardowy".|Przeciągnij poziomo podczas przenoszenia elementu, aby zagnieździć go pod wierszem powyżej. Przeciągnij element treści z lewego panelu na menu, aby utworzyć nową powiązaną pozycję.|Pozycja menu|Dodaj link niestandardowy|Dodaj pozycję menu z niestandardowym URL-em (zewnętrznym lub ścieżką wewnętrzną).|Edytuj pozycję menu|Edytuj etykietę, URL i cel linku.|URL jest zablokowany, ponieważ ta pozycja jest powiązana z treścią lub kategorią. Będzie automatycznie podążać za źródłem.|Etykieta jest wymagana.|np. Dokumentacja|URL jest wymagany.|Wprowadź zewnętrzny URL, ścieżkę wewnętrzną zaczynającą się od / lub kotwicę zaczynającą się od #.|https://przyklad.pl, /sciezka lub #|Otwórz w|Ta sama karta|Nowa karta|Dodaj kategorię bloga|Wybierz kategorię bloga. Pozycja menu połączy z podstroną pokazującą wszystkie opublikowane wpisy w tej kategorii.|Brak dostępnych kategorii bloga.|Etykieta (opcjonalnie)|Domyślnie nazwa kategorii|Wybierz kategorię.|Usunąć pozycję menu?|To trwale usunie {label} i wszystkie {count} zagnieżdżone pozycje. Tej akcji nie można cofnąć.|To trwale usunie {label}. Tej akcji nie można cofnąć.|Uchwyt przeciągania|Zewnętrzne|Niestandardowe|nowa karta`,
  tr: `Yeniden kullanılabilir gezinme menüleri oluşturun ve yönetin. Yalnızca yönetici erişimi.|Menülerde ara...|Menü bulunamadı.|Menü oluştur|Menü adları sistem genelinde benzersiz olmalıdır.|Menü adı|Menüyü yeniden adlandır|Menüyü yeniden ata|"{name}" sahibini değiştir.|Menü silinsin mi?|Bu, {name} menüsünü ve tüm menü öğelerini kalıcı olarak siler. Bu işlem geri alınamaz.|Silmeden önce Başlık Ayarları'nda başka bir menü veya "Menüsüz" seçin.|Bu menü başlığa atanmış. Silmeden önce Başlık Ayarları'nda başka bir menü veya "Menüsüz" seçin.|İçerik öğelerini soldan sağdaki menüye sürükleyin. Mevcut öğeleri yukarı-aşağı veya yana sürükleyerek yeniden sıralayın ve iç içe yerleştirin. Bir kategorideki gönderi listesine bağlanmak için "Blog kategorisi ekle", serbest URL için "Özel bağlantı ekle" kullanın. Yalnızca yönetici erişimi.|İçerikte ara...|İçerik öğesi bulunamadı.|Menü yapısı|Henüz menü öğesi yok. Soldan bir içerik öğesi sürükleyin veya "Özel bağlantı ekle"ye tıklayın.|Bir öğeyi taşırken üst satırın altına iç içe yerleştirmek için yatay sürükleyin. Yeni bağlı öğe oluşturmak için sol panelden bir içerik öğesini menüye sürükleyin.|Menü öğesi|Özel bağlantı ekle|Özel URL'li bir menü öğesi ekleyin (harici veya dahili yol).|Menü öğesini düzenle|Etiketi, URL'yi ve bağlantı hedefini düzenleyin.|Bu öğe içerik veya kategoriye bağlı olduğu için URL kilitli. Kaynağı otomatik izler.|Etiket gereklidir.|örn. Dokümantasyon|URL gereklidir.|Harici URL, / ile başlayan dahili yol veya # ile başlayan çapa girin.|https://ornek.com, /yol veya #|Şurada aç|Aynı sekme|Yeni sekme|Blog kategorisi ekle|Bir blog kategorisi seçin. Menü öğesi, o kategorideki tüm yayımlanmış blog gönderilerini listeleyen sayfaya bağlanır.|Kullanılabilir blog kategorisi yok.|Etiket (isteğe bağlı)|Varsayılan olarak kategori adı|Kategori seçin.|Menü öğesi silinsin mi?|Bu, {label} ve {count} iç içe öğeyi kalıcı olarak siler. Bu işlem geri alınamaz.|Bu, {label} öğesini kalıcı olarak siler. Bu işlem geri alınamaz.|Sürükleme tutamacı|Harici|Özel|yeni sekme`,
  mk: `Креирајте и управувајте со повеќекратни навигациски менија. Само за администратори.|Пребарај менија...|Нема пронајдени менија.|Креирај мени|Имињата на менијата мора да бидат единствени во системот.|Име на мени|Преименувај мени|Прераспредели мени|Промени го сопственикот на "{name}".|Да се избрише мени?|Ова трајно ќе го избрише {name} и сите негови ставки од менито. Ова дејство не може да се врати.|Изберете друго мени или "Без мени" во поставките за заглавје пред бришење.|Ова мени е доделено на заглавјето. Изберете друго мени или "Без мени" во поставките за заглавје пред да го избришете.|Повлечете ставки со содржина од левата страна во менито десно. Прередувајте ги постојните ставки со влечење нагоре, надолу или странично за вгнездување. Користете "Додај блог категорија" за врска кон листа на објави во категорија или "Додај прилагодена врска" за слободен URL. Само за администратори.|Пребарај содржина...|Нема пронајдени ставки со содржина.|Структура на мени|Сè уште нема ставки во менито. Повлечете ставка со содржина од левата страна или кликнете "Додај прилагодена врска".|Повлечете хоризонтално додека поместувате ставка за да ја вгнездите под редот над неа. Повлечете ставка со содржина од левиот панел во менито за да креирате нова поврзана ставка.|Ставка од мени|Додај прилагодена врска|Додајте ставка од мени со прилагоден URL (надворешна или внатрешна патека).|Уреди ставка од мени|Уредете ја ознаката, URL-то и целта на врската.|URL-то е заклучено бидејќи оваа ставка е поврзана со содржина или категорија. Автоматски ќе го следи изворот.|Ознаката е задолжителна.|на пр. Документација|URL-то е задолжително.|Внесете надворешен URL, внатрешна патека што почнува со / или сидро што почнува со #.|https://primer.com, /pateka или #|Отвори во|Иста картичка|Нова картичка|Додај блог категорија|Изберете блог категорија. Ставката од менито ќе води до страница што ги прикажува сите објавени блог објави во таа категорија.|Нема достапни блог категории.|Ознака (опционално)|Стандардно е името на категоријата|Изберете категорија.|Да се избрише ставка од мени?|Ова трајно ќе го избрише {label} и сите {count} вгнездени ставки. Ова дејство не може да се врати.|Ова трајно ќе го избрише {label}. Ова дејство не може да се врати.|Рачка за влечење|Надворешно|Прилагодено|нова картичка`,
  bs: `Kreirajte i upravljajte višekratnim navigacijskim menijima. Samo za administratore.|Pretraži menije...|Nema pronađenih menija.|Kreiraj meni|Nazivi menija moraju biti jedinstveni u sistemu.|Naziv menija|Preimenuj meni|Dodijeli meni drugome|Promijeni vlasnika za "{name}".|Obrisati meni?|Ovo će trajno obrisati {name} i sve njegove stavke menija. Ova radnja se ne može poništiti.|Izaberite drugi meni ili "Bez menija" u postavkama zaglavlja prije brisanja.|Ovaj meni je dodijeljen zaglavlju. Izaberite drugi meni ili "Bez menija" u postavkama zaglavlja prije brisanja.|Prevucite stavke sadržaja s lijeve strane u meni s desne strane. Promijenite redoslijed prevlačenjem postojećih stavki gore-dolje ili bočno za ugnježđivanje. Koristite "Dodaj blog kategoriju" za link ka listi objava u kategoriji ili "Dodaj prilagođeni link" za slobodan URL. Samo za administratore.|Pretraži sadržaj...|Nema pronađenih stavki sadržaja.|Struktura menija|Još nema stavki menija. Prevucite stavku sadržaja s lijeve strane ili kliknite "Dodaj prilagođeni link".|Prevucite vodoravno tokom pomjeranja stavke da je ugnijezdite ispod reda iznad. Prevucite stavku sadržaja iz lijevog panela na meni da kreirate novu povezanu stavku.|Stavka menija|Dodaj prilagođeni link|Dodajte stavku menija sa prilagođenim URL-om (vanjska ili interna putanja).|Uredi stavku menija|Uredite oznaku, URL i cilj linka.|URL je zaključan jer je ova stavka povezana sa sadržajem ili kategorijom. Automatski će pratiti izvor.|Oznaka je obavezna.|npr. Dokumentacija|URL je obavezan.|Unesite vanjski URL, internu putanju koja počinje sa / ili sidro koje počinje sa #.|https://primjer.com, /putanja ili #|Otvori u|Ista kartica|Nova kartica|Dodaj blog kategoriju|Izaberite blog kategoriju. Stavka menija će voditi ka stranici koja prikazuje sve objavljene blog objave u toj kategoriji.|Nema dostupnih blog kategorija.|Oznaka (opcionalno)|Zadano je naziv kategorije|Izaberite kategoriju.|Obrisati stavku menija?|Ovo će trajno obrisati {label} i svih {count} ugniježđenih stavki. Ova radnja se ne može poništiti.|Ovo će trajno obrisati {label}. Ova radnja se ne može poništiti.|Ručka za prevlačenje|Vanjsko|Prilagođeno|nova kartica`,
  sl: `Ustvarite in upravljajte ponovno uporabne navigacijske menije. Samo za skrbnike.|Išči menije...|Ni najdenih menijev.|Ustvari meni|Imena menijev morajo biti v sistemu enolična.|Ime menija|Preimenuj meni|Znova dodeli meni|Spremeni lastnika za "{name}".|Izbrisati meni?|To bo trajno izbrisalo {name} in vse njegove elemente menija. Tega dejanja ni mogoče razveljaviti.|Pred brisanjem v nastavitvah glave izberite drug meni ali "Brez menija".|Ta meni je dodeljen glavi. Pred brisanjem v nastavitvah glave izberite drug meni ali "Brez menija".|Povlecite elemente vsebine z leve strani v meni na desni. Preurejajte obstoječe elemente z vlečenjem gor, dol ali vstran za gnezdenje. Uporabite "Dodaj kategorijo bloga" za povezavo na seznam objav v kategoriji ali "Dodaj povezavo po meri" za prost URL. Samo za skrbnike.|Išči vsebino...|Ni najdenih elementov vsebine.|Struktura menija|Elementov menija še ni. Povlecite element vsebine z leve strani ali kliknite "Dodaj povezavo po meri".|Med premikanjem element povlecite vodoravno, da ga ugnezdite pod vrstico zgoraj. Povlecite element vsebine iz levega panela na meni, da ustvarite nov povezan element.|Element menija|Dodaj povezavo po meri|Dodajte element menija s prilagojenim URL-jem (zunanji ali notranja pot).|Uredi element menija|Uredite oznako, URL in cilj povezave.|URL je zaklenjen, ker je ta element povezan z vsebino ali kategorijo. Samodejno bo sledil viru.|Oznaka je obvezna.|npr. Dokumentacija|URL je obvezen.|Vnesite zunanji URL, notranjo pot, ki se začne z /, ali sidro, ki se začne z #.|https://primer.si, /pot ali #|Odpri v|Isti zavihek|Nov zavihek|Dodaj kategorijo bloga|Izberite kategorijo bloga. Element menija bo povezoval na stran, ki prikazuje vse objavljene blog objave v tej kategoriji.|Ni razpoložljivih kategorij bloga.|Oznaka (neobvezno)|Privzeto ime kategorije|Izberite kategorijo.|Izbrisati element menija?|To bo trajno izbrisalo {label} in vseh {count} ugnezdenih elementov. Tega dejanja ni mogoče razveljaviti.|To bo trajno izbrisalo {label}. Tega dejanja ni mogoče razveljaviti.|Ročica za vlečenje|Zunanje|Po meri|nov zavihek`,
  ru: `Создавайте и управляйте повторно используемыми навигационными меню. Только для администраторов.|Поиск меню...|Меню не найдены.|Создать меню|Названия меню должны быть уникальными в системе.|Название меню|Переименовать меню|Переназначить меню|Изменить владельца "{name}".|Удалить меню?|Это навсегда удалит {name} и все его пункты меню. Это действие нельзя отменить.|Перед удалением выберите другое меню или "Без меню" в настройках заголовка.|Это меню назначено заголовку. Перед удалением выберите другое меню или "Без меню" в настройках заголовка.|Перетащите элементы содержимого слева в меню справа. Меняйте порядок, перетаскивая существующие элементы вверх, вниз или в сторону для вложения. Используйте "Добавить категорию блога" для ссылки на список записей категории или "Добавить пользовательскую ссылку" для произвольного URL. Только для администраторов.|Поиск содержимого...|Элементы содержимого не найдены.|Структура меню|Пунктов меню пока нет. Перетащите элемент содержимого слева или нажмите "Добавить пользовательскую ссылку".|При перемещении перетащите элемент горизонтально, чтобы вложить его под строку выше. Перетащите элемент содержимого из левой панели в меню, чтобы создать новый связанный пункт.|Пункт меню|Добавить пользовательскую ссылку|Добавьте пункт меню с пользовательским URL (внешним или внутренним путем).|Редактировать пункт меню|Измените метку, URL и цель ссылки.|URL заблокирован, потому что этот пункт связан с содержимым или категорией. Он будет автоматически следовать источнику.|Метка обязательна.|например, Документация|URL обязателен.|Введите внешний URL, внутренний путь, начинающийся с /, или якорь, начинающийся с #.|https://primer.ru, /put или #|Открыть в|Та же вкладка|Новая вкладка|Добавить категорию блога|Выберите категорию блога. Пункт меню будет вести на страницу со всеми опубликованными записями этой категории.|Нет доступных категорий блога.|Метка (необязательно)|По умолчанию название категории|Выберите категорию.|Удалить пункт меню?|Это навсегда удалит {label} и все {count} вложенные пункты. Это действие нельзя отменить.|Это навсегда удалит {label}. Это действие нельзя отменить.|Ручка перетаскивания|Внешнее|Пользовательское|новая вкладка`,
  hu: `Hozz létre és kezelj újrahasználható navigációs menüket. Csak adminisztrátoroknak.|Menük keresése...|Nem találhatók menük.|Menü létrehozása|A menüneveknek egyedinek kell lenniük a rendszerben.|Menü neve|Menü átnevezése|Menü újra hozzárendelése|"{name}" tulajdonosának módosítása.|Menü törlése?|Ez végleg törli a(z) {name} menüt és annak összes menüelemét. Ez a művelet nem vonható vissza.|Törlés előtt válassz másik menüt vagy "Menü nélkül" opciót a fejlécbeállításokban.|Ez a menü a fejléchez van rendelve. Törlés előtt válassz másik menüt vagy "Menü nélkül" opciót a fejlécbeállításokban.|Húzd a tartalomelemeket balról a jobb oldali menübe. Rendezd át a meglévő elemeket fel-le vagy oldalra húzással a beágyazáshoz. Használd a "Blogkategória hozzáadása" opciót kategória bejegyzéslistájához, vagy az "Egyedi hivatkozás hozzáadása" opciót szabad URL-hez. Csak adminisztrátoroknak.|Tartalom keresése...|Nem találhatók tartalomelemek.|Menüszerkezet|Még nincsenek menüelemek. Húzz be egy tartalomelemet balról, vagy kattints az "Egyedi hivatkozás hozzáadása" gombra.|Mozgatás közben húzd vízszintesen az elemet, hogy a felette lévő sor alá ágyazd. Húzz egy tartalomelemet a bal panelről a menübe új kapcsolt elem létrehozásához.|Menüelem|Egyedi hivatkozás hozzáadása|Adj hozzá menüelemet egyedi URL-lel (külső vagy belső útvonal).|Menüelem szerkesztése|Szerkeszd a címkét, URL-t és a hivatkozás célját.|Az URL zárolva van, mert ez az elem tartalomhoz vagy kategóriához kapcsolódik. Automatikusan követi a forrást.|A címke kötelező.|pl. Dokumentáció|Az URL kötelező.|Adj meg külső URL-t, / jellel kezdődő belső útvonalat vagy # jellel kezdődő horgonyt.|https://pelda.hu, /utvonal vagy #|Megnyitás itt|Ugyanazon a lapon|Új lapon|Blogkategória hozzáadása|Válassz blogkategóriát. A menüelem egy olyan oldalra mutat, amely felsorolja az adott kategória összes közzétett blogbejegyzését.|Nincsenek elérhető blogkategóriák.|Címke (opcionális)|Alapértelmezés szerint a kategória neve|Válassz kategóriát.|Menüelem törlése?|Ez végleg törli a(z) {label} elemet és mind a(z) {count} beágyazott elemet. Ez a művelet nem vonható vissza.|Ez végleg törli a(z) {label} elemet. Ez a művelet nem vonható vissza.|Húzófogantyú|Külső|Egyedi|új lap`,
  bg: `Създавайте и управлявайте многократно използваеми навигационни менюта. Само за администратори.|Търсене на менюта...|Няма намерени менюта.|Създай меню|Имената на менютата трябва да са уникални в системата.|Име на меню|Преименувай меню|Преназначи меню|Промяна на собственика на "{name}".|Изтриване на меню?|Това ще изтрие завинаги {name} и всички негови елементи от менюто. Това действие не може да се отмени.|Изберете друго меню или "Без меню" в настройките на хедъра преди изтриване.|Това меню е зададено към хедъра. Изберете друго меню или "Без меню" в настройките на хедъра преди да го изтриете.|Плъзнете елементи със съдържание отляво към менюто вдясно. Пренареждайте съществуващите елементи чрез плъзгане нагоре, надолу или настрани за влагане. Използвайте "Добави блог категория" за връзка към списък с публикации в категория или "Добави персонализирана връзка" за свободен URL. Само за администратори.|Търсене на съдържание...|Няма намерени елементи със съдържание.|Структура на менюто|Все още няма елементи от менюто. Плъзнете елемент със съдържание отляво или щракнете "Добави персонализирана връзка".|Плъзнете хоризонтално, докато местите елемент, за да го вложите под реда отгоре. Плъзнете елемент със съдържание от левия панел към менюто, за да създадете нов свързан елемент.|Елемент от меню|Добави персонализирана връзка|Добавете елемент от меню с персонализиран URL (външен или вътрешен път).|Редактирай елемент от меню|Редактирайте етикета, URL адреса и целта на връзката.|URL адресът е заключен, защото този елемент е свързан със съдържание или категория. Той автоматично ще следва източника.|Етикетът е задължителен.|напр. Документация|URL адресът е задължителен.|Въведете външен URL, вътрешен път, започващ с /, или котва, започваща с #.|https://primer.com, /put или #|Отвори в|Същия раздел|Нов раздел|Добави блог категория|Изберете блог категория. Елементът от менюто ще води към страница, която изброява всички публикувани блог публикации в тази категория.|Няма налични блог категории.|Етикет (по избор)|По подразбиране името на категорията|Изберете категория.|Изтриване на елемент от меню?|Това ще изтрие завинаги {label} и всички {count} вложени елементи. Това действие не може да се отмени.|Това ще изтрие завинаги {label}. Това действие не може да се отмени.|Дръжка за плъзгане|Външен|Персонализиран|нов раздел`,
  ja: `再利用可能なナビゲーションメニューを作成および管理します。管理者のみアクセスできます。|メニューを検索...|メニューが見つかりません。|メニューを作成|メニュー名はシステム内で一意である必要があります。|メニュー名|メニュー名を変更|メニューを再割り当て|"{name}" の所有者を変更します。|メニューを削除しますか？|{name} とそのすべてのメニュー項目を完全に削除します。この操作は元に戻せません。|削除する前に、ヘッダー設定で別のメニューまたは「メニューなし」を選択してください。|このメニューはヘッダーに割り当てられています。削除する前に、ヘッダー設定で別のメニューまたは「メニューなし」を選択してください。|左側のコンテンツ項目を右側のメニューへドラッグします。既存の項目を上下または横にドラッグして並べ替え、入れ子にできます。「ブログカテゴリを追加」でカテゴリ内の記事一覧にリンクするか、「カスタムリンクを追加」で任意の URL を設定します。管理者のみアクセスできます。|コンテンツを検索...|コンテンツ項目が見つかりません。|メニュー構造|メニュー項目はまだありません。左からコンテンツ項目をドラッグするか、「カスタムリンクを追加」をクリックしてください。|項目を移動中に水平にドラッグすると、上の行の下に入れ子にできます。左パネルのコンテンツ項目をメニューへドラッグすると、新しいリンク項目を作成できます。|メニュー項目|カスタムリンクを追加|カスタム URL（外部または内部パス）のメニュー項目を追加します。|メニュー項目を編集|ラベル、URL、リンク先を編集します。|この項目はコンテンツまたはカテゴリにリンクされているため、URL はロックされています。URL は自動的に元の内容に従います。|ラベルは必須です。|例: ドキュメント|URL は必須です。|外部 URL、/ で始まる内部パス、または # で始まるアンカーを入力してください。|https://example.com、/path、または #|開く場所|同じタブ|新しいタブ|ブログカテゴリを追加|ブログカテゴリを選択します。メニュー項目は、そのカテゴリで公開済みのすべてのブログ記事を一覧するページにリンクします。|利用可能なブログカテゴリはありません。|ラベル（任意）|既定ではカテゴリ名|カテゴリを選択してください。|メニュー項目を削除しますか？|{label} と {count} 件の入れ子項目を完全に削除します。この操作は元に戻せません。|{label} を完全に削除します。この操作は元に戻せません。|ドラッグハンドル|外部|カスタム|新しいタブ`,
  "zh-Hans": `创建和管理可复用的导航菜单。仅限管理员访问。|搜索菜单...|未找到菜单。|创建菜单|菜单名称在系统中必须唯一。|菜单名称|重命名菜单|重新分配菜单|更改 "{name}" 的所有者。|删除菜单？|这将永久删除 {name} 及其所有菜单项。此操作无法撤销。|删除前，请在页眉设置中选择另一个菜单或“无菜单”。|此菜单已分配给页眉。删除前，请在页眉设置中选择另一个菜单或“无菜单”。|将左侧的内容项拖入右侧菜单。通过向上、向下或横向拖动现有项来重新排序或嵌套。使用“添加博客分类”链接到某个分类的文章列表，或使用“添加自定义链接”填写自由 URL。仅限管理员访问。|搜索内容...|未找到内容项。|菜单结构|还没有菜单项。请从左侧拖入内容项，或点击“添加自定义链接”。|移动项目时横向拖动，可将其嵌套到上方行下面。将左侧面板的内容项拖到菜单中，可创建新的关联项。|菜单项|添加自定义链接|添加带自定义 URL 的菜单项（外部或内部路径）。|编辑菜单项|编辑标签、URL 和链接目标。|此项已关联到内容或分类，因此 URL 已锁定。它会自动跟随来源。|标签为必填项。|例如：文档|URL 为必填项。|输入外部 URL、以 / 开头的内部路径，或以 # 开头的锚点。|https://example.com、/path 或 #|打开方式|同一标签页|新标签页|添加博客分类|选择博客分类。菜单项将链接到列出该分类所有已发布博客文章的页面。|没有可用的博客分类。|标签（可选）|默认使用分类名称|选择分类。|删除菜单项？|这将永久删除 {label} 以及所有 {count} 个嵌套项。此操作无法撤销。|这将永久删除 {label}。此操作无法撤销。|拖动手柄|外部|自定义|新标签页`,
  "zh-Hant": `建立和管理可重複使用的導覽選單。僅限管理員存取。|搜尋選單...|找不到選單。|建立選單|選單名稱在系統中必須唯一。|選單名稱|重新命名選單|重新指派選單|變更 "{name}" 的擁有者。|刪除選單？|這會永久刪除 {name} 及其所有選單項目。此動作無法復原。|刪除前，請在頁首設定中選擇另一個選單或「無選單」。|此選單已指派給頁首。刪除前，請在頁首設定中選擇另一個選單或「無選單」。|將左側的內容項目拖到右側選單。透過向上、向下或橫向拖曳既有項目來重新排序或巢狀化。使用「新增部落格分類」連結到某分類的文章列表，或使用「新增自訂連結」輸入自由 URL。僅限管理員存取。|搜尋內容...|找不到內容項目。|選單結構|還沒有選單項目。請從左側拖入內容項目，或點擊「新增自訂連結」。|移動項目時橫向拖曳，可將其巢狀放在上方列下。將左側面板的內容項目拖到選單，可建立新的連結項目。|選單項目|新增自訂連結|新增含自訂 URL 的選單項目（外部或內部路徑）。|編輯選單項目|編輯標籤、URL 與連結目標。|此項目已連結到內容或分類，因此 URL 已鎖定。它會自動跟隨來源。|標籤為必填。|例如：文件|URL 為必填。|輸入外部 URL、以 / 開頭的內部路徑，或以 # 開頭的錨點。|https://example.com、/path 或 #|開啟於|同一分頁|新分頁|新增部落格分類|選擇部落格分類。選單項目會連結到列出該分類所有已發布部落格文章的頁面。|沒有可用的部落格分類。|標籤（選填）|預設為分類名稱|選擇分類。|刪除選單項目？|這會永久刪除 {label} 以及所有 {count} 個巢狀項目。此動作無法復原。|這會永久刪除 {label}。此動作無法復原。|拖曳控制柄|外部|自訂|新分頁`,
  ar: `أنشئ قوائم تنقل قابلة لإعادة الاستخدام وأدرها. وصول المسؤولين فقط.|البحث في القوائم...|لم يتم العثور على قوائم.|إنشاء قائمة|يجب أن تكون أسماء القوائم فريدة في النظام.|اسم القائمة|إعادة تسمية القائمة|إعادة تعيين القائمة|تغيير مالك "{name}".|حذف القائمة؟|سيؤدي هذا إلى حذف {name} وكل عناصر القائمة التابعة لها نهائيا. لا يمكن التراجع عن هذا الإجراء.|اختر قائمة أخرى أو "بدون قائمة" في إعدادات الرأس قبل الحذف.|هذه القائمة معيّنة للرأس. اختر قائمة أخرى أو "بدون قائمة" في إعدادات الرأس قبل حذفها.|اسحب عناصر المحتوى من اليسار إلى القائمة على اليمين. أعد الترتيب بسحب العناصر الموجودة للأعلى أو الأسفل أو جانبا للتداخل. استخدم "إضافة فئة مدونة" للربط بقائمة منشورات في فئة، أو "إضافة رابط مخصص" لعنوان URL حر. وصول المسؤولين فقط.|البحث في المحتوى...|لم يتم العثور على عناصر محتوى.|بنية القائمة|لا توجد عناصر قائمة بعد. اسحب عنصر محتوى من اليسار أو انقر "إضافة رابط مخصص".|اسحب أفقيا أثناء نقل العنصر لتداخله تحت الصف أعلاه. اسحب عنصر محتوى من اللوحة اليسرى إلى القائمة لإنشاء عنصر مرتبط جديد.|عنصر قائمة|إضافة رابط مخصص|أضف عنصر قائمة بعنوان URL مخصص (خارجي أو مسار داخلي).|تعديل عنصر القائمة|عدّل التسمية وعنوان URL وهدف الرابط.|عنوان URL مقفل لأن هذا العنصر مرتبط بمحتوى أو فئة. سيتبع المصدر تلقائيا.|التسمية مطلوبة.|مثلا: الوثائق|عنوان URL مطلوب.|أدخل عنوان URL خارجيا، أو مسارا داخليا يبدأ بـ /، أو مرساة تبدأ بـ #.|https://example.com أو /path أو #|فتح في|نفس التبويب|تبويب جديد|إضافة فئة مدونة|اختر فئة مدونة. سيرتبط عنصر القائمة بصفحة تسرد كل منشورات المدونة المنشورة في تلك الفئة.|لا توجد فئات مدونة متاحة.|التسمية (اختياري)|الافتراضي هو اسم الفئة|اختر فئة.|حذف عنصر القائمة؟|سيؤدي هذا إلى حذف {label} وكل العناصر المتداخلة البالغ عددها {count} نهائيا. لا يمكن التراجع عن هذا الإجراء.|سيؤدي هذا إلى حذف {label} نهائيا. لا يمكن التراجع عن هذا الإجراء.|مقبض السحب|خارجي|مخصص|تبويب جديد`,
  id: `Buat dan kelola menu navigasi yang dapat digunakan kembali. Hanya akses admin.|Cari menu...|Tidak ada menu ditemukan.|Buat menu|Nama menu harus unik di seluruh sistem.|Nama menu|Ganti nama menu|Tetapkan ulang menu|Ubah pemilik "{name}".|Hapus menu?|Ini akan menghapus {name} dan semua item menunya secara permanen. Tindakan ini tidak dapat dibatalkan.|Pilih menu lain atau "Tanpa menu" di Pengaturan Header sebelum menghapus.|Menu ini ditetapkan ke Header. Pilih menu lain atau "Tanpa menu" di Pengaturan Header sebelum menghapusnya.|Seret item konten dari kiri ke menu di kanan. Ubah urutan dengan menyeret item yang ada ke atas, bawah, atau samping untuk membuat sarang. Gunakan "Tambah kategori blog" untuk menautkan ke daftar posting dalam kategori, atau "Tambah tautan khusus" untuk URL bebas. Hanya akses admin.|Cari konten...|Tidak ada item konten ditemukan.|Struktur menu|Belum ada item menu. Seret item konten dari kiri, atau klik "Tambah tautan khusus".|Seret secara horizontal saat memindahkan item untuk menyarangkannya di bawah baris di atas. Seret item konten dari panel kiri ke menu untuk membuat item tertaut baru.|Item menu|Tambah tautan khusus|Tambahkan item menu dengan URL khusus (eksternal atau jalur internal).|Edit item menu|Edit label, URL, dan target tautan.|URL dikunci karena item ini ditautkan ke konten atau kategori. URL akan mengikuti sumber secara otomatis.|Label wajib diisi.|mis. Dokumentasi|URL wajib diisi.|Masukkan URL eksternal, jalur internal yang dimulai dengan /, atau jangkar yang dimulai dengan #.|https://contoh.com, /jalur atau #|Buka di|Tab yang sama|Tab baru|Tambah kategori blog|Pilih kategori blog. Item menu akan menaut ke halaman yang mencantumkan semua posting blog yang diterbitkan dalam kategori itu.|Tidak ada kategori blog tersedia.|Label (opsional)|Default ke nama kategori|Pilih kategori.|Hapus item menu?|Ini akan menghapus {label} dan semua {count} item bersarang secara permanen. Tindakan ini tidak dapat dibatalkan.|Ini akan menghapus {label} secara permanen. Tindakan ini tidak dapat dibatalkan.|Pegangan seret|Eksternal|Khusus|tab baru`,
  cs: `Vytvářejte a spravujte opakovaně použitelná navigační menu. Přístup pouze pro administrátory.|Hledat menu...|Nebyla nalezena žádná menu.|Vytvořit menu|Názvy menu musí být v systému jedinečné.|Název menu|Přejmenovat menu|Znovu přiřadit menu|Změnit vlastníka "{name}".|Smazat menu?|Tím trvale smažete {name} a všechny jeho položky menu. Tuto akci nelze vrátit zpět.|Před smazáním vyberte v nastavení hlavičky jiné menu nebo "Bez menu".|Toto menu je přiřazeno k hlavičce. Před smazáním vyberte v nastavení hlavičky jiné menu nebo "Bez menu".|Přetáhněte položky obsahu zleva do menu vpravo. Změňte pořadí přetažením existujících položek nahoru, dolů nebo do strany pro vnoření. Použijte "Přidat kategorii blogu" pro odkaz na seznam příspěvků v kategorii nebo "Přidat vlastní odkaz" pro volnou URL. Přístup pouze pro administrátory.|Hledat obsah...|Nebyly nalezeny žádné položky obsahu.|Struktura menu|Zatím nejsou žádné položky menu. Přetáhněte položku obsahu zleva nebo klikněte na "Přidat vlastní odkaz".|Při přesouvání položky táhněte vodorovně, abyste ji vnořili pod řádek nad ní. Přetáhněte položku obsahu z levého panelu do menu a vytvořte novou propojenou položku.|Položka menu|Přidat vlastní odkaz|Přidejte položku menu s vlastní URL (externí nebo interní cesta).|Upravit položku menu|Upravte popisek, URL a cíl odkazu.|URL je uzamčena, protože tato položka je propojena s obsahem nebo kategorií. Bude automaticky následovat zdroj.|Popisek je povinný.|např. Dokumentace|URL je povinná.|Zadejte externí URL, interní cestu začínající / nebo kotvu začínající #.|https://priklad.cz, /cesta nebo #|Otevřít v|Stejná karta|Nová karta|Přidat kategorii blogu|Vyberte kategorii blogu. Položka menu bude odkazovat na stránku se všemi publikovanými blogovými příspěvky v dané kategorii.|Nejsou dostupné žádné kategorie blogu.|Popisek (volitelné)|Výchozí je název kategorie|Vyberte kategorii.|Smazat položku menu?|Tím trvale smažete {label} a všech {count} vnořených položek. Tuto akci nelze vrátit zpět.|Tím trvale smažete {label}. Tuto akci nelze vrátit zpět.|Úchyt pro přetažení|Externí|Vlastní|nová karta`,
  ro: `Creează și gestionează meniuri de navigare reutilizabile. Acces doar pentru administratori.|Caută meniuri...|Nu s-au găsit meniuri.|Creează meniu|Numele meniurilor trebuie să fie unice în sistem.|Nume meniu|Redenumește meniul|Reatribuie meniul|Schimbă proprietarul pentru "{name}".|Ștergi meniul?|Aceasta va șterge definitiv {name} și toate elementele sale de meniu. Această acțiune nu poate fi anulată.|Selectează alt meniu sau "Fără meniu" în setările antetului înainte de ștergere.|Acest meniu este atribuit antetului. Selectează alt meniu sau "Fără meniu" în setările antetului înainte de a-l șterge.|Trage elementele de conținut din stânga în meniul din dreapta. Reordonează elementele existente trăgându-le sus, jos sau lateral pentru imbricare. Folosește "Adaugă categorie blog" pentru a crea un link către lista de articole dintr-o categorie, sau "Adaugă link personalizat" pentru un URL liber. Acces doar pentru administratori.|Caută conținut...|Nu s-au găsit elemente de conținut.|Structura meniului|Nu există încă elemente de meniu. Trage un element de conținut din stânga sau apasă "Adaugă link personalizat".|Trage orizontal în timp ce muți un element pentru a-l imbrica sub rândul de deasupra. Trage un element de conținut din panoul stâng pe meniu pentru a crea un nou element legat.|Element de meniu|Adaugă link personalizat|Adaugă un element de meniu cu URL personalizat (extern sau cale internă).|Editează elementul de meniu|Editează eticheta, URL-ul și ținta linkului.|URL-ul este blocat deoarece acest element este legat de conținut sau de o categorie. Va urma automat sursa.|Eticheta este obligatorie.|ex. Documentație|URL-ul este obligatoriu.|Introdu un URL extern, o cale internă care începe cu / sau o ancoră care începe cu #.|https://exemplu.com, /cale sau #|Deschide în|Aceeași filă|Filă nouă|Adaugă categorie blog|Alege o categorie de blog. Elementul de meniu va trimite către o pagină care listează toate articolele de blog publicate în acea categorie.|Nu există categorii de blog disponibile.|Etichetă (opțional)|Implicit este numele categoriei|Selectează o categorie.|Ștergi elementul de meniu?|Aceasta va șterge definitiv {label} și toate cele {count} elemente imbricate. Această acțiune nu poate fi anulată.|Aceasta va șterge definitiv {label}. Această acțiune nu poate fi anulată.|Mâner de tragere|Extern|Personalizat|filă nouă`,
  el: `Δημιουργήστε και διαχειριστείτε επαναχρησιμοποιήσιμα μενού πλοήγησης. Πρόσβαση μόνο για διαχειριστές.|Αναζήτηση μενού...|Δεν βρέθηκαν μενού.|Δημιουργία μενού|Τα ονόματα μενού πρέπει να είναι μοναδικά στο σύστημα.|Όνομα μενού|Μετονομασία μενού|Εκ νέου ανάθεση μενού|Αλλαγή ιδιοκτήτη του "{name}".|Να διαγραφεί το μενού;|Αυτό θα διαγράψει οριστικά το {name} και όλα τα στοιχεία μενού του. Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.|Επιλέξτε άλλο μενού ή "Χωρίς μενού" στις ρυθμίσεις κεφαλίδας πριν από τη διαγραφή.|Αυτό το μενού έχει ανατεθεί στην κεφαλίδα. Επιλέξτε άλλο μενού ή "Χωρίς μενού" στις ρυθμίσεις κεφαλίδας πριν το διαγράψετε.|Σύρετε στοιχεία περιεχομένου από αριστερά στο μενού δεξιά. Αναδιατάξτε σύροντας υπάρχοντα στοιχεία πάνω, κάτω ή πλάγια για ένθεση. Χρησιμοποιήστε "Προσθήκη κατηγορίας blog" για σύνδεση σε λίστα άρθρων μιας κατηγορίας ή "Προσθήκη προσαρμοσμένου συνδέσμου" για ελεύθερο URL. Πρόσβαση μόνο για διαχειριστές.|Αναζήτηση περιεχομένου...|Δεν βρέθηκαν στοιχεία περιεχομένου.|Δομή μενού|Δεν υπάρχουν ακόμη στοιχεία μενού. Σύρετε ένα στοιχείο περιεχομένου από αριστερά ή πατήστε "Προσθήκη προσαρμοσμένου συνδέσμου".|Σύρετε οριζόντια ενώ μετακινείτε ένα στοιχείο για να το ενθέσετε κάτω από την παραπάνω σειρά. Σύρετε ένα στοιχείο περιεχομένου από το αριστερό πάνελ στο μενού για να δημιουργήσετε νέο συνδεδεμένο στοιχείο.|Στοιχείο μενού|Προσθήκη προσαρμοσμένου συνδέσμου|Προσθέστε στοιχείο μενού με προσαρμοσμένο URL (εξωτερικό ή εσωτερική διαδρομή).|Επεξεργασία στοιχείου μενού|Επεξεργαστείτε την ετικέτα, το URL και τον στόχο του συνδέσμου.|Το URL είναι κλειδωμένο επειδή αυτό το στοιχείο συνδέεται με περιεχόμενο ή κατηγορία. Θα ακολουθεί αυτόματα την πηγή.|Η ετικέτα είναι υποχρεωτική.|π.χ. Τεκμηρίωση|Το URL είναι υποχρεωτικό.|Εισαγάγετε εξωτερικό URL, εσωτερική διαδρομή που αρχίζει με / ή άγκυρα που αρχίζει με #.|https://example.com, /path ή #|Άνοιγμα σε|Ίδια καρτέλα|Νέα καρτέλα|Προσθήκη κατηγορίας blog|Επιλέξτε κατηγορία blog. Το στοιχείο μενού θα συνδέεται με σελίδα που εμφανίζει όλα τα δημοσιευμένα άρθρα blog αυτής της κατηγορίας.|Δεν υπάρχουν διαθέσιμες κατηγορίες blog.|Ετικέτα (προαιρετικά)|Προεπιλογή στο όνομα της κατηγορίας|Επιλέξτε κατηγορία.|Να διαγραφεί το στοιχείο μενού;|Αυτό θα διαγράψει οριστικά το {label} και όλα τα {count} ένθετα στοιχεία. Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.|Αυτό θα διαγράψει οριστικά το {label}. Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.|Λαβή μεταφοράς|Εξωτερικό|Προσαρμοσμένο|νέα καρτέλα`,
  da: `Opret og administrer genbrugelige navigationsmenuer. Kun administratoradgang.|Søg i menuer...|Ingen menuer fundet.|Opret menu|Menunavne skal være unikke i systemet.|Menunavn|Omdøb menu|Tildel menu igen|Skift ejeren af "{name}".|Slet menu?|Dette sletter {name} og alle dens menupunkter permanent. Handlingen kan ikke fortrydes.|Vælg en anden menu eller "Uden menu" i headerindstillingerne før sletning.|Denne menu er tildelt headeren. Vælg en anden menu eller "Uden menu" i headerindstillingerne, før du sletter den.|Træk indholdselementer fra venstre ind i menuen til højre. Omarranger ved at trække eksisterende elementer op, ned eller sidelæns for at indlejre. Brug "Tilføj blogkategori" til at linke til en liste over indlæg i en kategori, eller "Tilføj brugerdefineret link" til en fri URL. Kun administratoradgang.|Søg i indhold...|Ingen indholdselementer fundet.|Menustruktur|Ingen menupunkter endnu. Træk et indholdselement fra venstre, eller klik på "Tilføj brugerdefineret link".|Træk vandret, mens du flytter et element, for at indlejre det under rækken ovenover. Træk et indholdselement fra venstre panel til menuen for at oprette et nyt linket element.|Menupunkt|Tilføj brugerdefineret link|Tilføj et menupunkt med en brugerdefineret URL (ekstern eller intern sti).|Rediger menupunkt|Rediger label, URL og linkmål.|URL'en er låst, fordi dette element er linket til indhold eller en kategori. Den følger automatisk kilden.|Label er påkrævet.|f.eks. Dokumentation|URL er påkrævet.|Indtast en ekstern URL, en intern sti der starter med /, eller et anker der starter med #.|https://eksempel.dk, /sti eller #|Åbn i|Samme fane|Ny fane|Tilføj blogkategori|Vælg en blogkategori. Menupunktet linker til en side, der viser alle publicerede blogindlæg i den kategori.|Ingen blogkategorier tilgængelige.|Label (valgfri)|Standard er kategorinavnet|Vælg en kategori.|Slet menupunkt?|Dette sletter {label} og alle {count} indlejrede elementer permanent. Handlingen kan ikke fortrydes.|Dette sletter {label} permanent. Handlingen kan ikke fortrydes.|Trækhåndtag|Ekstern|Brugerdefineret|ny fane`,
  sv: `Skapa och hantera återanvändbara navigeringsmenyer. Endast administratörer.|Sök menyer...|Inga menyer hittades.|Skapa meny|Menynamn måste vara unika i systemet.|Menynamn|Byt namn på meny|Tilldela om meny|Ändra ägare för "{name}".|Ta bort meny?|Detta tar permanent bort {name} och alla dess menyalternativ. Åtgärden kan inte ångras.|Välj en annan meny eller "Utan meny" i headerinställningarna innan du tar bort.|Den här menyn är tilldelad headern. Välj en annan meny eller "Utan meny" i headerinställningarna innan du tar bort den.|Dra innehållsobjekt från vänster till menyn till höger. Ändra ordning genom att dra befintliga objekt uppåt, nedåt eller åt sidan för att nästla. Använd "Lägg till bloggkategori" för att länka till en lista med inlägg i en kategori, eller "Lägg till anpassad länk" för en fri URL. Endast administratörer.|Sök innehåll...|Inga innehållsobjekt hittades.|Menystruktur|Inga menyalternativ ännu. Dra ett innehållsobjekt från vänster eller klicka på "Lägg till anpassad länk".|Dra horisontellt när du flyttar ett objekt för att nästla det under raden ovanför. Dra ett innehållsobjekt från vänster panel till menyn för att skapa ett nytt länkat objekt.|Menyalternativ|Lägg till anpassad länk|Lägg till ett menyalternativ med en anpassad URL (extern eller intern sökväg).|Redigera menyalternativ|Redigera etikett, URL och länkmål.|URL:en är låst eftersom detta objekt är länkat till innehåll eller en kategori. Den följer automatiskt källan.|Etikett krävs.|t.ex. Dokumentation|URL krävs.|Ange en extern URL, en intern sökväg som börjar med / eller ett ankare som börjar med #.|https://exempel.se, /sokvag eller #|Öppna i|Samma flik|Ny flik|Lägg till bloggkategori|Välj en bloggkategori. Menyalternativet länkar till en sida som listar alla publicerade blogginlägg i den kategorin.|Inga bloggkategorier tillgängliga.|Etikett (valfritt)|Standard är kategorinamnet|Välj en kategori.|Ta bort menyalternativ?|Detta tar permanent bort {label} och alla {count} nästlade objekt. Åtgärden kan inte ångras.|Detta tar permanent bort {label}. Åtgärden kan inte ångras.|Draghandtag|Extern|Anpassad|ny flik`,
  nb: `Opprett og administrer gjenbrukbare navigasjonsmenyer. Kun administratorer.|Søk i menyer...|Ingen menyer funnet.|Opprett meny|Menynavn må være unike i systemet.|Menynavn|Gi meny nytt navn|Tildel meny på nytt|Endre eieren av "{name}".|Slette meny?|Dette sletter {name} og alle menyelementene permanent. Handlingen kan ikke angres.|Velg en annen meny eller "Uten meny" i headerinnstillingene før sletting.|Denne menyen er tilordnet headeren. Velg en annen meny eller "Uten meny" i headerinnstillingene før du sletter den.|Dra innholdselementer fra venstre inn i menyen til høyre. Endre rekkefølge ved å dra eksisterende elementer opp, ned eller sidelengs for å nøste dem. Bruk "Legg til bloggkategori" for å lenke til en liste over innlegg i en kategori, eller "Legg til egendefinert lenke" for en fri URL. Kun administratorer.|Søk i innhold...|Ingen innholdselementer funnet.|Menystruktur|Ingen menyelementer ennå. Dra et innholdselement fra venstre, eller klikk "Legg til egendefinert lenke".|Dra horisontalt mens du flytter et element for å nøste det under raden over. Dra et innholdselement fra venstre panel til menyen for å opprette et nytt lenket element.|Menyelement|Legg til egendefinert lenke|Legg til et menyelement med en egendefinert URL (ekstern eller intern sti).|Rediger menyelement|Rediger etikett, URL og lenkemål.|URL-en er låst fordi dette elementet er lenket til innhold eller en kategori. Den følger automatisk kilden.|Etikett er påkrevd.|f.eks. Dokumentasjon|URL er påkrevd.|Skriv inn en ekstern URL, en intern sti som starter med /, eller et anker som starter med #.|https://eksempel.no, /sti eller #|Åpne i|Samme fane|Ny fane|Legg til bloggkategori|Velg en bloggkategori. Menyelementet lenker til en side som viser alle publiserte blogginnlegg i den kategorien.|Ingen bloggkategorier tilgjengelige.|Etikett (valgfritt)|Standard er kategorinavnet|Velg en kategori.|Slette menyelement?|Dette sletter {label} og alle {count} nøstede elementer permanent. Handlingen kan ikke angres.|Dette sletter {label} permanent. Handlingen kan ikke angres.|Drahåndtak|Ekstern|Egendefinert|ny fane`,
  nn: `Opprett og administrer gjenbrukbare navigasjonsmenyar. Berre administratorar.|Søk i menyar...|Ingen menyar funne.|Opprett meny|Menynamn må vere unike i systemet.|Menynamn|Gje meny nytt namn|Tildel meny på nytt|Endre eigaren av "{name}".|Slette meny?|Dette slettar {name} og alle menyelementa permanent. Handlinga kan ikkje angrast.|Vel ein annan meny eller "Utan meny" i topptekstinnstillingane før sletting.|Denne menyen er tilordna toppteksten. Vel ein annan meny eller "Utan meny" i topptekstinnstillingane før du slettar han.|Dra innhaldselement frå venstre inn i menyen til høgre. Endre rekkjefølgje ved å dra eksisterande element opp, ned eller sidelengs for å nøste dei. Bruk "Legg til bloggkategori" for å lenkje til ei liste over innlegg i ein kategori, eller "Legg til tilpassa lenkje" for ein fri URL. Berre administratorar.|Søk i innhald...|Ingen innhaldselement funne.|Menystruktur|Ingen menyelement enno. Dra eit innhaldselement frå venstre, eller klikk "Legg til tilpassa lenkje".|Dra vassrett medan du flyttar eit element for å nøste det under rada over. Dra eit innhaldselement frå venstre panel til menyen for å opprette eit nytt lenkja element.|Menyelement|Legg til tilpassa lenkje|Legg til eit menyelement med ein tilpassa URL (ekstern eller intern sti).|Rediger menyelement|Rediger etikett, URL og lenkjemål.|URL-en er låst fordi dette elementet er lenkja til innhald eller ein kategori. Han følgjer automatisk kjelda.|Etikett er påkravd.|t.d. Dokumentasjon|URL er påkravd.|Skriv inn ein ekstern URL, ein intern sti som startar med /, eller eit anker som startar med #.|https://domeine.no, /sti eller #|Opne i|Same fane|Ny fane|Legg til bloggkategori|Vel ein bloggkategori. Menyelementet lenkjer til ei side som viser alle publiserte blogginnlegg i den kategorien.|Ingen bloggkategoriar tilgjengelege.|Etikett (valfritt)|Standard er kategorinamnet|Vel ein kategori.|Slette menyelement?|Dette slettar {label} og alle {count} nøsta element permanent. Handlinga kan ikkje angrast.|Dette slettar {label} permanent. Handlinga kan ikkje angrast.|Drahandtak|Ekstern|Tilpassa|ny fane`,
  fi: `Luo ja hallitse uudelleenkäytettäviä navigointivalikoita. Vain ylläpitäjille.|Hae valikoita...|Valikoita ei löytynyt.|Luo valikko|Valikoiden nimien on oltava yksilöllisiä järjestelmässä.|Valikon nimi|Nimeä valikko uudelleen|Määritä valikko uudelleen|Vaihda kohteen "{name}" omistaja.|Poistetaanko valikko?|Tämä poistaa kohteen {name} ja kaikki sen valikkokohteet pysyvästi. Toimintoa ei voi kumota.|Valitse toinen valikko tai "Ilman valikkoa" ylätunnisteen asetuksissa ennen poistamista.|Tämä valikko on määritetty ylätunnisteeseen. Valitse toinen valikko tai "Ilman valikkoa" ylätunnisteen asetuksissa ennen poistamista.|Vedä sisältökohteita vasemmalta oikealla olevaan valikkoon. Järjestä kohteita vetämällä niitä ylös, alas tai sivulle sisäkkäistämistä varten. Käytä "Lisää blogikategoria" linkittääksesi kategorian artikkeliluetteloon tai "Lisää mukautettu linkki" vapaata URL-osoitetta varten. Vain ylläpitäjille.|Hae sisältöä...|Sisältökohteita ei löytynyt.|Valikon rakenne|Valikkokohteita ei vielä ole. Vedä sisältökohde vasemmalta tai napsauta "Lisää mukautettu linkki".|Vedä kohdetta vaakasuunnassa siirtämisen aikana, jotta se sijoittuu sisäkkäin yllä olevan rivin alle. Vedä sisältökohde vasemmasta paneelista valikkoon luodaksesi uuden linkitetyn kohteen.|Valikkokohde|Lisää mukautettu linkki|Lisää valikkokohde mukautetulla URL-osoitteella (ulkoinen tai sisäinen polku).|Muokkaa valikkokohdetta|Muokkaa tunnistetta, URL-osoitetta ja linkin kohdetta.|URL on lukittu, koska tämä kohde on linkitetty sisältöön tai kategoriaan. Se seuraa lähdettä automaattisesti.|Tunniste on pakollinen.|esim. Dokumentaatio|URL on pakollinen.|Anna ulkoinen URL, sisäinen polku joka alkaa /-merkillä, tai ankkuri joka alkaa #-merkillä.|https://esimerkki.fi, /polku tai #|Avaa kohteessa|Sama välilehti|Uusi välilehti|Lisää blogikategoria|Valitse blogikategoria. Valikkokohde linkittää sivulle, joka listaa kaikki kyseisessä kategoriassa julkaistut blogiartikkelit.|Blogikategorioita ei ole saatavilla.|Tunniste (valinnainen)|Oletuksena kategorian nimi|Valitse kategoria.|Poistetaanko valikkokohde?|Tämä poistaa kohteen {label} ja kaikki {count} sisäkkäistä kohdetta pysyvästi. Toimintoa ei voi kumota.|Tämä poistaa kohteen {label} pysyvästi. Toimintoa ei voi kumota.|Vetokahva|Ulkoinen|Mukautettu|uusi välilehti`,
  is: `Búðu til og stjórnaðu endurnýtanlegum leiðsagnarvalmyndum. Aðeins stjórnendur.|Leita í valmyndum...|Engar valmyndir fundust.|Búa til valmynd|Nöfn valmynda verða að vera einstök í kerfinu.|Nafn valmyndar|Endurnefna valmynd|Endurúthluta valmynd|Breyta eiganda "{name}".|Eyða valmynd?|Þetta eyðir {name} og öllum valmyndaratriðum hennar varanlega. Ekki er hægt að afturkalla þessa aðgerð.|Veldu aðra valmynd eða "Án valmyndar" í stillingum hauss áður en eytt er.|Þessi valmynd er úthlutuð hausnum. Veldu aðra valmynd eða "Án valmyndar" í stillingum hauss áður en henni er eytt.|Dragðu efnisatriði frá vinstri inn í valmyndina hægra megin. Endurraðaðu með því að draga fyrirliggjandi atriði upp, niður eða til hliðar til að hreiðra þau. Notaðu "Bæta við bloggflokki" til að tengja við lista yfir færslur í flokki, eða "Bæta við sérsniðnum tengli" fyrir frjálsa slóð. Aðeins stjórnendur.|Leita í efni...|Engin efnisatriði fundust.|Uppbygging valmyndar|Engin valmyndaratriði enn. Dragðu efnisatriði frá vinstri eða smelltu á "Bæta við sérsniðnum tengli".|Dragðu lárétt þegar þú færir atriði til að hreiðra það undir röðinni fyrir ofan. Dragðu efnisatriði úr vinstri spjaldinu á valmyndina til að búa til nýtt tengt atriði.|Valmyndaratriði|Bæta við sérsniðnum tengli|Bættu við valmyndaratriði með sérsniðinni slóð (ytri eða innri slóð).|Breyta valmyndaratriði|Breyttu merkimiða, slóð og tengimarki.|Slóðin er læst vegna þess að þetta atriði er tengt efni eða flokki. Hún fylgir upprunanum sjálfkrafa.|Merkimiði er nauðsynlegur.|t.d. Skjölun|Slóð er nauðsynleg.|Sláðu inn ytri slóð, innri slóð sem byrjar á / eða akkeri sem byrjar á #.|https://daemi.is, /slod eða #|Opna í|Sama flipa|Nýjum flipa|Bæta við bloggflokki|Veldu bloggflokk. Valmyndaratriðið tengir á síðu sem sýnir allar birtar bloggfærslur í þeim flokki.|Engir bloggflokkar tiltækir.|Merkimiði (valfrjálst)|Sjálfgefið er heiti flokks|Veldu flokk.|Eyða valmyndaratriði?|Þetta eyðir {label} og öllum {count} hreiðruðum atriðum varanlega. Ekki er hægt að afturkalla þessa aðgerð.|Þetta eyðir {label} varanlega. Ekki er hægt að afturkalla þessa aðgerð.|Dráttarhandfang|Ytra|Sérsniðið|nýr flipi`,
} satisfies Record<LocalizedLanguage, string>;

const MENU_MANAGEMENT_ERROR_SOURCE_STRINGS = [
  "A menu with that name already exists.",
  "Menu not found.",
  "Invalid menu id.",
  "Parent menu item does not exist.",
  "Selected content item does not exist.",
  "Selected category does not exist.",
  "Only blog post categories can be linked.",
  "URL cannot be edited for linked items -- it follows the linked content or category.",
  "Cycle detected in menu hierarchy.",
  "Menu item not found.",
  "Menu name is required.",
  "Selected menu item does not exist.",
  "Selected parent menu item does not exist.",
  "An item cannot be its own parent.",
  "Owner is required.",
  "Target user must be a backend user.",
] as const;

type MenuManagementErrorSource =
  (typeof MENU_MANAGEMENT_ERROR_SOURCE_STRINGS)[number];

const ERROR_ROWS = {
  "sr-Latn": `Meni sa tim nazivom već postoji.|Meni nije pronađen.|Neispravan ID menija.|Nadređena stavka menija ne postoji.|Izabrana stavka sadržaja ne postoji.|Izabrana kategorija ne postoji.|Mogu se povezati samo kategorije blog objava.|URL se ne može uređivati za povezane stavke -- prati povezani sadržaj ili kategoriju.|Otkriven je ciklus u hijerarhiji menija.|Stavka menija nije pronađena.|Naziv menija je obavezan.|Izabrana stavka menija ne postoji.|Izabrana nadređena stavka menija ne postoji.|Stavka ne može biti sopstveni roditelj.|Vlasnik je obavezan.|Ciljni korisnik mora biti backend korisnik.`,
  "sr-Cyrl": `Мени са тим називом већ постоји.|Мени није пронађен.|Неисправан ID менија.|Надређена ставка менија не постоји.|Изабрана ставка садржаја не постоји.|Изабрана категорија не постоји.|Могу се повезати само категорије блог објава.|URL се не може уређивати за повезане ставке -- прати повезани садржај или категорију.|Откривен је циклус у хијерархији менија.|Ставка менија није пронађена.|Назив менија је обавезан.|Изабрана ставка менија не постоји.|Изабрана надређена ставка менија не постоји.|Ставка не може бити сопствени родитељ.|Власник је обавезан.|Циљни корисник мора бити backend корисник.`,
  hr: `Izbornik s tim nazivom već postoji.|Izbornik nije pronađen.|Neispravan ID izbornika.|Nadređena stavka izbornika ne postoji.|Odabrana stavka sadržaja ne postoji.|Odabrana kategorija ne postoji.|Mogu se povezati samo kategorije blog objava.|URL se ne može uređivati za povezane stavke -- prati povezani sadržaj ili kategoriju.|Otkriven je ciklus u hijerarhiji izbornika.|Stavka izbornika nije pronađena.|Naziv izbornika je obavezan.|Odabrana stavka izbornika ne postoji.|Odabrana nadređena stavka izbornika ne postoji.|Stavka ne može biti vlastiti roditelj.|Vlasnik je obavezan.|Ciljni korisnik mora biti backend korisnik.`,
  de: `Ein Menü mit diesem Namen existiert bereits.|Menü nicht gefunden.|Ungültige Menü-ID.|Übergeordneter Menüeintrag existiert nicht.|Ausgewähltes Inhaltselement existiert nicht.|Ausgewählte Kategorie existiert nicht.|Es können nur Blogbeitragskategorien verlinkt werden.|Die URL kann für verknüpfte Einträge nicht bearbeitet werden -- sie folgt dem verknüpften Inhalt oder der Kategorie.|Zyklus in der Menühierarchie erkannt.|Menüeintrag nicht gefunden.|Menüname ist erforderlich.|Ausgewählter Menüeintrag existiert nicht.|Ausgewählter übergeordneter Menüeintrag existiert nicht.|Ein Eintrag kann nicht sein eigener Elternknoten sein.|Besitzer ist erforderlich.|Der Zielbenutzer muss ein Backend-Benutzer sein.`,
  fr: `Un menu portant ce nom existe déjà.|Menu introuvable.|ID de menu invalide.|L'élément de menu parent n'existe pas.|L'élément de contenu sélectionné n'existe pas.|La catégorie sélectionnée n'existe pas.|Seules les catégories d'articles de blog peuvent être liées.|L'URL ne peut pas être modifiée pour les éléments liés -- elle suit le contenu ou la catégorie liée.|Cycle détecté dans la hiérarchie du menu.|Élément de menu introuvable.|Le nom du menu est obligatoire.|L'élément de menu sélectionné n'existe pas.|L'élément de menu parent sélectionné n'existe pas.|Un élément ne peut pas être son propre parent.|Le propriétaire est obligatoire.|L'utilisateur cible doit être un utilisateur backend.`,
  es: `Ya existe un menú con ese nombre.|Menú no encontrado.|ID de menú no válido.|El elemento de menú padre no existe.|El elemento de contenido seleccionado no existe.|La categoría seleccionada no existe.|Solo se pueden enlazar categorías de entradas de blog.|La URL no se puede editar en elementos vinculados -- sigue el contenido o la categoría vinculada.|Se detectó un ciclo en la jerarquía del menú.|Elemento de menú no encontrado.|El nombre del menú es obligatorio.|El elemento de menú seleccionado no existe.|El elemento de menú padre seleccionado no existe.|Un elemento no puede ser su propio padre.|El propietario es obligatorio.|El usuario de destino debe ser un usuario backend.`,
  it: `Esiste già un menu con questo nome.|Menu non trovato.|ID menu non valido.|L'elemento di menu padre non esiste.|L'elemento di contenuto selezionato non esiste.|La categoria selezionata non esiste.|È possibile collegare solo categorie di post del blog.|L'URL non può essere modificato per gli elementi collegati -- segue il contenuto o la categoria collegata.|Rilevato un ciclo nella gerarchia del menu.|Elemento di menu non trovato.|Il nome del menu è obbligatorio.|L'elemento di menu selezionato non esiste.|L'elemento di menu padre selezionato non esiste.|Un elemento non può essere il proprio genitore.|Il proprietario è obbligatorio.|L'utente di destinazione deve essere un utente backend.`,
  pt: `Já existe um menu com esse nome.|Menu não encontrado.|ID de menu inválido.|O item de menu pai não existe.|O item de conteúdo selecionado não existe.|A categoria selecionada não existe.|Só podem ser ligadas categorias de publicações de blog.|O URL não pode ser editado em itens ligados -- segue o conteúdo ou a categoria ligada.|Foi detetado um ciclo na hierarquia do menu.|Item de menu não encontrado.|O nome do menu é obrigatório.|O item de menu selecionado não existe.|O item de menu pai selecionado não existe.|Um item não pode ser o seu próprio pai.|O proprietário é obrigatório.|O utilizador de destino tem de ser um utilizador backend.`,
  "pt-BR": `Já existe um menu com esse nome.|Menu não encontrado.|ID de menu inválido.|O item de menu pai não existe.|O item de conteúdo selecionado não existe.|A categoria selecionada não existe.|Só é possível vincular categorias de posts do blog.|A URL não pode ser editada para itens vinculados -- ela segue o conteúdo ou a categoria vinculada.|Foi detectado um ciclo na hierarquia do menu.|Item de menu não encontrado.|O nome do menu é obrigatório.|O item de menu selecionado não existe.|O item de menu pai selecionado não existe.|Um item não pode ser seu próprio pai.|O proprietário é obrigatório.|O usuário de destino deve ser um usuário backend.`,
  nl: `Er bestaat al een menu met die naam.|Menu niet gevonden.|Ongeldige menu-ID.|Bovenliggend menu-item bestaat niet.|Geselecteerd inhoudsitem bestaat niet.|Geselecteerde categorie bestaat niet.|Alleen blogberichtcategorieën kunnen worden gelinkt.|De URL kan niet worden bewerkt voor gekoppelde items -- deze volgt de gekoppelde inhoud of categorie.|Cyclus gedetecteerd in de menuhierarchie.|Menu-item niet gevonden.|Menunaam is verplicht.|Geselecteerd menu-item bestaat niet.|Geselecteerd bovenliggend menu-item bestaat niet.|Een item kan niet zijn eigen ouder zijn.|Eigenaar is verplicht.|De doelgebruiker moet een backend-gebruiker zijn.`,
  pl: `Menu o tej nazwie już istnieje.|Nie znaleziono menu.|Nieprawidłowy identyfikator menu.|Nadrzędna pozycja menu nie istnieje.|Wybrany element treści nie istnieje.|Wybrana kategoria nie istnieje.|Można linkować tylko kategorie wpisów bloga.|Nie można edytować URL dla powiązanych pozycji -- podąża za powiązaną treścią lub kategorią.|Wykryto cykl w hierarchii menu.|Nie znaleziono pozycji menu.|Nazwa menu jest wymagana.|Wybrana pozycja menu nie istnieje.|Wybrana nadrzędna pozycja menu nie istnieje.|Pozycja nie może być własnym rodzicem.|Właściciel jest wymagany.|Docelowy użytkownik musi być użytkownikiem backendu.`,
  tr: `Bu ada sahip bir menü zaten var.|Menü bulunamadı.|Geçersiz menü kimliği.|Üst menü öğesi mevcut değil.|Seçilen içerik öğesi mevcut değil.|Seçilen kategori mevcut değil.|Yalnızca blog gönderisi kategorileri bağlanabilir.|Bağlı öğeler için URL düzenlenemez -- bağlı içerik veya kategoriyi izler.|Menü hiyerarşisinde döngü algılandı.|Menü öğesi bulunamadı.|Menü adı gereklidir.|Seçilen menü öğesi mevcut değil.|Seçilen üst menü öğesi mevcut değil.|Bir öğe kendi ebeveyni olamaz.|Sahip gereklidir.|Hedef kullanıcı bir backend kullanıcısı olmalıdır.`,
  mk: `Мени со тоа име веќе постои.|Менито не е пронајдено.|Невалиден ID на мени.|Надредената ставка од менито не постои.|Избраната ставка со содржина не постои.|Избраната категорија не постои.|Може да се поврзуваат само категории на блог објави.|URL-то не може да се уредува за поврзани ставки -- го следи поврзаниот содржај или категорија.|Откриен е циклус во хиерархијата на менито.|Ставката од менито не е пронајдена.|Името на менито е задолжително.|Избраната ставка од менито не постои.|Избраната надредена ставка од менито не постои.|Ставка не може да биде сопствен родител.|Сопственикот е задолжителен.|Целниот корисник мора да биде backend корисник.`,
  bs: `Meni s tim nazivom već postoji.|Meni nije pronađen.|Neispravan ID menija.|Nadređena stavka menija ne postoji.|Izabrana stavka sadržaja ne postoji.|Izabrana kategorija ne postoji.|Mogu se povezati samo kategorije blog objava.|URL se ne može uređivati za povezane stavke -- prati povezani sadržaj ili kategoriju.|Otkriven je ciklus u hijerarhiji menija.|Stavka menija nije pronađena.|Naziv menija je obavezan.|Izabrana stavka menija ne postoji.|Izabrana nadređena stavka menija ne postoji.|Stavka ne može biti vlastiti roditelj.|Vlasnik je obavezan.|Ciljni korisnik mora biti backend korisnik.`,
  sl: `Meni s tem imenom že obstaja.|Meni ni najden.|Neveljaven ID menija.|Nadrejeni element menija ne obstaja.|Izbrani element vsebine ne obstaja.|Izbrana kategorija ne obstaja.|Povezati je mogoče samo kategorije blog objav.|URL-ja ni mogoče urejati za povezane elemente -- sledi povezani vsebini ali kategoriji.|Zaznan je cikel v hierarhiji menija.|Element menija ni najden.|Ime menija je obvezno.|Izbrani element menija ne obstaja.|Izbrani nadrejeni element menija ne obstaja.|Element ne more biti svoj starš.|Lastnik je obvezen.|Ciljni uporabnik mora biti backend uporabnik.`,
  ru: `Меню с таким названием уже существует.|Меню не найдено.|Недопустимый ID меню.|Родительский пункт меню не существует.|Выбранный элемент содержимого не существует.|Выбранная категория не существует.|Можно связывать только категории записей блога.|URL нельзя редактировать для связанных элементов -- он следует связанному содержимому или категории.|Обнаружен цикл в иерархии меню.|Пункт меню не найден.|Название меню обязательно.|Выбранный пункт меню не существует.|Выбранный родительский пункт меню не существует.|Элемент не может быть собственным родителем.|Владелец обязателен.|Целевой пользователь должен быть backend-пользователем.`,
  hu: `Ilyen nevű menü már létezik.|A menü nem található.|Érvénytelen menüazonosító.|A szülő menüelem nem létezik.|A kiválasztott tartalomelem nem létezik.|A kiválasztott kategória nem létezik.|Csak blogbejegyzés-kategóriák kapcsolhatók.|A kapcsolt elemek URL-je nem szerkeszthető -- a kapcsolt tartalmat vagy kategóriát követi.|Ciklus észlelve a menühierarchiában.|A menüelem nem található.|A menü neve kötelező.|A kiválasztott menüelem nem létezik.|A kiválasztott szülő menüelem nem létezik.|Egy elem nem lehet a saját szülője.|Tulajdonos megadása kötelező.|A célfelhasználónak backend-felhasználónak kell lennie.`,
  bg: `Вече съществува меню с това име.|Менюто не е намерено.|Невалиден ID на меню.|Родителският елемент от менюто не съществува.|Избраният елемент със съдържание не съществува.|Избраната категория не съществува.|Могат да се свързват само категории на блог публикации.|URL адресът не може да се редактира за свързани елементи -- следва свързаното съдържание или категория.|Открит е цикъл в йерархията на менюто.|Елементът от менюто не е намерен.|Името на менюто е задължително.|Избраният елемент от менюто не съществува.|Избраният родителски елемент от менюто не съществува.|Елемент не може да бъде собствен родител.|Собственикът е задължителен.|Целевият потребител трябва да бъде backend потребител.`,
  ja: `その名前のメニューは既に存在します。|メニューが見つかりません。|メニュー ID が無効です。|親メニュー項目が存在しません。|選択したコンテンツ項目が存在しません。|選択したカテゴリが存在しません。|リンクできるのはブログ記事カテゴリのみです。|リンク済み項目の URL は編集できません -- リンクされたコンテンツまたはカテゴリに従います。|メニュー階層で循環が検出されました。|メニュー項目が見つかりません。|メニュー名は必須です。|選択したメニュー項目が存在しません。|選択した親メニュー項目が存在しません。|項目を自分自身の親にすることはできません。|所有者は必須です。|対象ユーザーは backend ユーザーである必要があります。`,
  "zh-Hans": `已存在同名菜单。|未找到菜单。|菜单 ID 无效。|父菜单项不存在。|所选内容项不存在。|所选分类不存在。|只能链接博客文章分类。|关联项的 URL 无法编辑 -- 它会跟随关联内容或分类。|菜单层级中检测到循环。|未找到菜单项。|菜单名称为必填项。|所选菜单项不存在。|所选父菜单项不存在。|项目不能作为自己的父项。|所有者为必填项。|目标用户必须是 backend 用户。`,
  "zh-Hant": `已存在同名選單。|找不到選單。|選單 ID 無效。|父層選單項目不存在。|所選內容項目不存在。|所選分類不存在。|只能連結部落格文章分類。|連結項目的 URL 無法編輯 -- 它會跟隨連結內容或分類。|選單階層中偵測到循環。|找不到選單項目。|選單名稱為必填。|所選選單項目不存在。|所選父層選單項目不存在。|項目不能作為自己的父項。|擁有者為必填。|目標使用者必須是 backend 使用者。`,
  ar: `توجد قائمة بهذا الاسم بالفعل.|لم يتم العثور على القائمة.|معرّف القائمة غير صالح.|عنصر القائمة الأب غير موجود.|عنصر المحتوى المحدد غير موجود.|الفئة المحددة غير موجودة.|يمكن ربط فئات منشورات المدونة فقط.|لا يمكن تعديل عنوان URL للعناصر المرتبطة -- فهو يتبع المحتوى أو الفئة المرتبطة.|تم اكتشاف حلقة في تسلسل القائمة.|لم يتم العثور على عنصر القائمة.|اسم القائمة مطلوب.|عنصر القائمة المحدد غير موجود.|عنصر القائمة الأب المحدد غير موجود.|لا يمكن أن يكون العنصر أبا لنفسه.|المالك مطلوب.|يجب أن يكون المستخدم الهدف مستخدم backend.`,
  id: `Menu dengan nama itu sudah ada.|Menu tidak ditemukan.|ID menu tidak valid.|Item menu induk tidak ada.|Item konten yang dipilih tidak ada.|Kategori yang dipilih tidak ada.|Hanya kategori posting blog yang dapat ditautkan.|URL tidak dapat diedit untuk item tertaut -- URL mengikuti konten atau kategori tertaut.|Siklus terdeteksi dalam hierarki menu.|Item menu tidak ditemukan.|Nama menu wajib diisi.|Item menu yang dipilih tidak ada.|Item menu induk yang dipilih tidak ada.|Item tidak dapat menjadi induknya sendiri.|Pemilik wajib diisi.|Pengguna target harus menjadi pengguna backend.`,
  cs: `Menu s tímto názvem již existuje.|Menu nebylo nalezeno.|Neplatné ID menu.|Nadřazená položka menu neexistuje.|Vybraná položka obsahu neexistuje.|Vybraná kategorie neexistuje.|Lze propojit pouze kategorie blogových příspěvků.|URL nelze u propojených položek upravit -- následuje propojený obsah nebo kategorii.|V hierarchii menu byl zjištěn cyklus.|Položka menu nebyla nalezena.|Název menu je povinný.|Vybraná položka menu neexistuje.|Vybraná nadřazená položka menu neexistuje.|Položka nemůže být sama sobě nadřazená.|Vlastník je povinný.|Cílový uživatel musí být backend uživatel.`,
  ro: `Există deja un meniu cu acest nume.|Meniul nu a fost găsit.|ID meniu nevalid.|Elementul de meniu părinte nu există.|Elementul de conținut selectat nu există.|Categoria selectată nu există.|Pot fi legate doar categoriile de articole blog.|URL-ul nu poate fi editat pentru elementele legate -- urmează conținutul sau categoria legată.|A fost detectat un ciclu în ierarhia meniului.|Elementul de meniu nu a fost găsit.|Numele meniului este obligatoriu.|Elementul de meniu selectat nu există.|Elementul de meniu părinte selectat nu există.|Un element nu poate fi propriul părinte.|Proprietarul este obligatoriu.|Utilizatorul țintă trebuie să fie utilizator backend.`,
  el: `Υπάρχει ήδη μενού με αυτό το όνομα.|Το μενού δεν βρέθηκε.|Μη έγκυρο ID μενού.|Το γονικό στοιχείο μενού δεν υπάρχει.|Το επιλεγμένο στοιχείο περιεχομένου δεν υπάρχει.|Η επιλεγμένη κατηγορία δεν υπάρχει.|Μπορούν να συνδεθούν μόνο κατηγορίες άρθρων blog.|Το URL δεν μπορεί να επεξεργαστεί για συνδεδεμένα στοιχεία -- ακολουθεί το συνδεδεμένο περιεχόμενο ή κατηγορία.|Εντοπίστηκε κύκλος στην ιεραρχία του μενού.|Το στοιχείο μενού δεν βρέθηκε.|Το όνομα μενού είναι υποχρεωτικό.|Το επιλεγμένο στοιχείο μενού δεν υπάρχει.|Το επιλεγμένο γονικό στοιχείο μενού δεν υπάρχει.|Ένα στοιχείο δεν μπορεί να είναι γονέας του εαυτού του.|Ο ιδιοκτήτης είναι υποχρεωτικός.|Ο χρήστης στόχος πρέπει να είναι χρήστης backend.`,
  da: `Der findes allerede en menu med det navn.|Menuen blev ikke fundet.|Ugyldigt menu-ID.|Overordnet menupunkt findes ikke.|Det valgte indholdselement findes ikke.|Den valgte kategori findes ikke.|Kun blogindlægskategorier kan linkes.|URL'en kan ikke redigeres for linkede elementer -- den følger det linkede indhold eller den linkede kategori.|Der blev fundet en cyklus i menuhierarkiet.|Menupunkt blev ikke fundet.|Menunavn er påkrævet.|Det valgte menupunkt findes ikke.|Det valgte overordnede menupunkt findes ikke.|Et element kan ikke være sin egen forælder.|Ejer er påkrævet.|Målbrugeren skal være en backend-bruger.`,
  sv: `Det finns redan en meny med det namnet.|Menyn hittades inte.|Ogiltigt meny-ID.|Överordnat menyalternativ finns inte.|Det valda innehållsobjektet finns inte.|Den valda kategorin finns inte.|Endast bloggpostkategorier kan länkas.|URL:en kan inte redigeras för länkade objekt -- den följer det länkade innehållet eller kategorin.|En cykel upptäcktes i menyhierarkin.|Menyalternativ hittades inte.|Menynamn krävs.|Det valda menyalternativet finns inte.|Det valda överordnade menyalternativet finns inte.|Ett objekt kan inte vara sin egen förälder.|Ägare krävs.|Målanvändaren måste vara en backend-användare.`,
  nb: `Det finnes allerede en meny med det navnet.|Menyen ble ikke funnet.|Ugyldig meny-ID.|Overordnet menyelement finnes ikke.|Valgt innholdselement finnes ikke.|Valgt kategori finnes ikke.|Bare blogginnleggskategorier kan lenkes.|URL-en kan ikke redigeres for lenkede elementer -- den følger lenket innhold eller kategori.|Det ble oppdaget en syklus i menyhierarkiet.|Menyelementet ble ikke funnet.|Menynavn er påkrevd.|Valgt menyelement finnes ikke.|Valgt overordnet menyelement finnes ikke.|Et element kan ikke være sin egen forelder.|Eier er påkrevd.|Målbrukeren må være en backend-bruker.`,
  nn: `Det finst allereie ein meny med det namnet.|Menyen vart ikkje funnen.|Ugyldig meny-ID.|Overordna menyelement finst ikkje.|Valt innhaldselement finst ikkje.|Vald kategori finst ikkje.|Berre blogginnleggskategoriar kan lenkjast.|URL-en kan ikkje redigerast for lenkja element -- han følgjer lenkja innhald eller kategori.|Det vart oppdaga ein syklus i menyhierarkiet.|Menyelementet vart ikkje funne.|Menynamn er påkravd.|Valt menyelement finst ikkje.|Valt overordna menyelement finst ikkje.|Eit element kan ikkje vere sin eigen forelder.|Eigar er påkravd.|Målbrukaren må vere ein backend-brukar.`,
  fi: `Samanniminen valikko on jo olemassa.|Valikkoa ei löytynyt.|Virheellinen valikon ID.|Ylätason valikkokohdetta ei ole olemassa.|Valittua sisältökohdetta ei ole olemassa.|Valittua kategoriaa ei ole olemassa.|Vain blogiartikkelien kategorioita voidaan linkittää.|URL-osoitetta ei voi muokata linkitetyille kohteille -- se seuraa linkitettyä sisältöä tai kategoriaa.|Valikkohierarkiassa havaittiin silmukka.|Valikkokohdetta ei löytynyt.|Valikon nimi on pakollinen.|Valittua valikkokohdetta ei ole olemassa.|Valittua ylätason valikkokohdetta ei ole olemassa.|Kohde ei voi olla oma ylätasonsa.|Omistaja on pakollinen.|Kohdekäyttäjän on oltava backend-käyttäjä.`,
  is: `Valmynd með þessu nafni er þegar til.|Valmynd fannst ekki.|Ógilt auðkenni valmyndar.|Yfirvalmyndaratriði er ekki til.|Valið efnisatriði er ekki til.|Valinn flokkur er ekki til.|Aðeins er hægt að tengja flokka bloggfærslna.|Ekki er hægt að breyta slóð fyrir tengd atriði -- hún fylgir tengdu efni eða flokki.|Hringur fannst í stigveldi valmyndar.|Valmyndaratriði fannst ekki.|Nafn valmyndar er nauðsynlegt.|Valið valmyndaratriði er ekki til.|Valið yfirvalmyndaratriði er ekki til.|Atriði getur ekki verið eigið foreldri.|Eigandi er nauðsynlegur.|Marknotandi verður að vera backend-notandi.`,
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<MenuManagementSource, string> {
  const translations = row.split("|");
  if (translations.length !== MENU_MANAGEMENT_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} menu management translations must have ${MENU_MANAGEMENT_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    MENU_MANAGEMENT_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<MenuManagementSource, string>;
}

function createErrorMap(
  language: string,
  row: string,
): Record<MenuManagementErrorSource, string> {
  const translations = row.split("|");
  if (translations.length !== MENU_MANAGEMENT_ERROR_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} menu management error translations must have ${MENU_MANAGEMENT_ERROR_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    MENU_MANAGEMENT_ERROR_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<MenuManagementErrorSource, string>;
}

export const MENU_MANAGEMENT_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    {
      ...createMap(language, row),
      ...createErrorMap(language, ERROR_ROWS[language as LocalizedLanguage]),
    },
  ]),
) as Record<
  LocalizedLanguage,
  Record<MenuManagementSource | MenuManagementErrorSource, string>
>;
