import type { CmsLanguage } from "@/lib/i18n/languages";

type LocalizedLanguage = Exclude<CmsLanguage, "en">;

export const WEBSHOP_ADMIN_DASHBOARD_SOURCE_STRINGS = [
  "Nested categories, images, SEO, and product filters.",
  "Products, variants, SKUs, pricing, media, and inventory.",
  "Orders, payments, fulfillment, refunds, and support notes.",
  "Coupons, discount rules, eligibility, and usage tracking.",
  "Customer wishlist overview and existing-list edits.",
  "Wishlists",
  "Moderate verified product ratings and comments.",
  "Reviews",
  "Storefront browsing presets, filters, and product pages.",
  "Store-wide defaults for checkout, payments, tax, and orders.",
  "Licensed",
  "Private commerce add-on dashboard.",
  "Manage categories",
  "Payments are in test mode",
  "Checkout can be exercised safely, but production payment capture should wait until WEBSHOP_PAYMENTS_MODE is set to live and provider credentials are verified.",
  "Later phase",
] as const;

type WebshopAdminDashboardSource =
  (typeof WEBSHOP_ADMIN_DASHBOARD_SOURCE_STRINGS)[number];

const ROWS = {
  "sr-Latn":
    "Ugnježđene kategorije, slike, SEO i filteri proizvoda.|Proizvodi, varijante, SKU-ovi, cene, mediji i zalihe.|Porudžbine, plaćanja, ispunjenje, refundacije i beleške podrške.|Kuponi, pravila popusta, uslovi podobnosti i praćenje korišćenja.|Pregled lista želja kupaca i izmene postojećih lista.|Liste želja|Moderacija verifikovanih ocena proizvoda i komentara.|Recenzije|Preseti izloga za pregledanje, filteri i stranice proizvoda.|Podrazumevane postavke prodavnice za checkout, plaćanja, porez i porudžbine.|Licencirano|Privatna kontrolna tabla commerce add-ona.|Upravljaj kategorijama|Plaćanja su u test modu|Checkout može bezbedno da se testira, ali produkciono naplaćivanje treba da sačeka dok WEBSHOP_PAYMENTS_MODE ne bude podešen na live i dok se kredencijali provajdera ne provere.|Kasnija faza",
  "sr-Cyrl":
    "Угнежђене категорије, слике, SEO и филтери производа.|Производи, варијанте, SKU-ови, цене, медији и залихе.|Поруџбине, плаћања, испуњење, рефундације и белешке подршке.|Купони, правила попуста, услови подобности и праћење коришћења.|Преглед листа жеља купаца и измене постојећих листа.|Листе жеља|Модерација верификованих оцена производа и коментара.|Рецензије|Пресети излога за прегледање, филтери и странице производа.|Подразумеване поставке продавнице за checkout, плаћања, порез и поруџбине.|Лиценцирано|Приватна контролна табла commerce додатка.|Управљај категоријама|Плаћања су у тест моду|Checkout може безбедно да се тестира, али продукционо наплаћивање треба да сачека док WEBSHOP_PAYMENTS_MODE не буде подешен на live и док се креденцијали провајдера не провере.|Каснија фаза",
  hr: "Ugniježđene kategorije, slike, SEO i filtri proizvoda.|Proizvodi, varijante, SKU-ovi, cijene, mediji i zalihe.|Narudžbe, plaćanja, ispunjenje, povrati i bilješke podrške.|Kuponi, pravila popusta, podobnost i praćenje korištenja.|Pregled popisa želja kupaca i izmjene postojećih popisa.|Popisi želja|Moderiranje potvrđenih ocjena proizvoda i komentara.|Recenzije|Postavke izloga za pregledavanje, filtri i stranice proizvoda.|Zadane postavke trgovine za checkout, plaćanja, porez i narudžbe.|Licencirano|Privatna nadzorna ploča commerce dodatka.|Upravljaj kategorijama|Plaćanja su u testnom načinu|Checkout se može sigurno isprobati, ali produkcijska naplata treba pričekati dok WEBSHOP_PAYMENTS_MODE ne bude postavljen na live i dok se vjerodajnice pružatelja ne provjere.|Kasnija faza",
  de: "Verschachtelte Kategorien, Bilder, SEO und Produktfilter.|Produkte, Varianten, SKUs, Preise, Medien und Bestand.|Bestellungen, Zahlungen, Fulfillment, Rückerstattungen und Supportnotizen.|Gutscheine, Rabattregeln, Berechtigung und Nutzungsverfolgung.|Übersicht über Kundenwunschlisten und Bearbeitung bestehender Listen.|Wunschlisten|Moderation verifizierter Produktbewertungen und Kommentare.|Bewertungen|Storefront-Browse-Presets, Filter und Produktseiten.|Shopweite Standardwerte für Checkout, Zahlungen, Steuern und Bestellungen.|Lizenziert|Privates Commerce-Add-on-Dashboard.|Kategorien verwalten|Zahlungen sind im Testmodus|Der Checkout kann sicher getestet werden, aber die Zahlungserfassung in Produktion sollte warten, bis WEBSHOP_PAYMENTS_MODE auf live gesetzt ist und die Anbieter-Zugangsdaten geprüft sind.|Spätere Phase",
  fr: "Catégories imbriquées, images, SEO et filtres de produits.|Produits, variantes, SKU, prix, médias et stock.|Commandes, paiements, traitement, remboursements et notes de support.|Coupons, règles de remise, éligibilité et suivi d’utilisation.|Vue d’ensemble des listes de souhaits client et modification des listes existantes.|Listes de souhaits|Modération des avis produits vérifiés et des commentaires.|Avis|Presets de navigation de la vitrine, filtres et pages produits.|Valeurs par défaut de la boutique pour le checkout, les paiements, les taxes et les commandes.|Sous licence|Tableau de bord privé de l’add-on commerce.|Gérer les catégories|Les paiements sont en mode test|Le checkout peut être testé en sécurité, mais la capture des paiements en production doit attendre que WEBSHOP_PAYMENTS_MODE soit défini sur live et que les identifiants du fournisseur soient vérifiés.|Phase ultérieure",
  es: "Categorías anidadas, imágenes, SEO y filtros de productos.|Productos, variantes, SKU, precios, medios e inventario.|Pedidos, pagos, cumplimiento, reembolsos y notas de soporte.|Cupones, reglas de descuento, elegibilidad y seguimiento de uso.|Resumen de listas de deseos de clientes y edición de listas existentes.|Listas de deseos|Moderación de valoraciones verificadas de productos y comentarios.|Reseñas|Preajustes de navegación del escaparate, filtros y páginas de producto.|Valores predeterminados de la tienda para checkout, pagos, impuestos y pedidos.|Con licencia|Panel privado del add-on de comercio.|Gestionar categorías|Los pagos están en modo de prueba|El checkout se puede probar de forma segura, pero la captura de pagos en producción debe esperar hasta que WEBSHOP_PAYMENTS_MODE esté en live y las credenciales del proveedor estén verificadas.|Fase posterior",
  it: "Categorie annidate, immagini, SEO e filtri prodotto.|Prodotti, varianti, SKU, prezzi, media e inventario.|Ordini, pagamenti, evasione, rimborsi e note di supporto.|Coupon, regole di sconto, idoneità e tracciamento dell’utilizzo.|Panoramica delle liste desideri dei clienti e modifiche alle liste esistenti.|Liste desideri|Moderazione di valutazioni prodotto verificate e commenti.|Recensioni|Preset di navigazione storefront, filtri e pagine prodotto.|Impostazioni predefinite del negozio per checkout, pagamenti, tasse e ordini.|Con licenza|Dashboard privata dell’add-on commerce.|Gestisci categorie|I pagamenti sono in modalità test|Il checkout può essere provato in sicurezza, ma la cattura dei pagamenti in produzione deve attendere che WEBSHOP_PAYMENTS_MODE sia impostato su live e che le credenziali del provider siano verificate.|Fase successiva",
  pt: "Categorias aninhadas, imagens, SEO e filtros de produtos.|Produtos, variantes, SKUs, preços, media e inventário.|Encomendas, pagamentos, processamento, reembolsos e notas de suporte.|Cupões, regras de desconto, elegibilidade e acompanhamento de utilização.|Visão geral das listas de desejos dos clientes e edição de listas existentes.|Listas de desejos|Moderação de avaliações verificadas de produtos e comentários.|Avaliações|Predefinições de navegação da montra, filtros e páginas de produto.|Valores predefinidos da loja para checkout, pagamentos, impostos e encomendas.|Licenciado|Painel privado do add-on de comércio.|Gerir categorias|Os pagamentos estão em modo de teste|O checkout pode ser testado com segurança, mas a captura de pagamentos em produção deve esperar até WEBSHOP_PAYMENTS_MODE estar definido como live e as credenciais do fornecedor estarem verificadas.|Fase posterior",
  "pt-BR":
    "Categorias aninhadas, imagens, SEO e filtros de produtos.|Produtos, variantes, SKUs, preços, mídia e estoque.|Pedidos, pagamentos, atendimento, reembolsos e notas de suporte.|Cupons, regras de desconto, elegibilidade e acompanhamento de uso.|Visão geral das listas de desejos dos clientes e edição de listas existentes.|Listas de desejos|Moderação de avaliações verificadas de produtos e comentários.|Avaliações|Predefinições de navegação da vitrine, filtros e páginas de produto.|Padrões da loja para checkout, pagamentos, impostos e pedidos.|Licenciado|Painel privado do add-on de comércio.|Gerenciar categorias|Os pagamentos estão em modo de teste|O checkout pode ser testado com segurança, mas a captura de pagamentos em produção deve esperar até WEBSHOP_PAYMENTS_MODE estar definido como live e as credenciais do provedor estarem verificadas.|Fase posterior",
  nl: "Geneste categorieën, afbeeldingen, SEO en productfilters.|Producten, varianten, SKU's, prijzen, media en voorraad.|Bestellingen, betalingen, fulfillment, terugbetalingen en supportnotities.|Coupons, kortingsregels, geschiktheid en gebruikstracking.|Overzicht van klantverlanglijsten en bewerkingen van bestaande lijsten.|Verlanglijsten|Moderatie van geverifieerde productbeoordelingen en reacties.|Beoordelingen|Storefront-browsepresets, filters en productpagina's.|Winkelbrede standaardwaarden voor checkout, betalingen, belasting en bestellingen.|Gelicentieerd|Privé commerce-add-on dashboard.|Categorieën beheren|Betalingen staan in testmodus|Checkout kan veilig worden getest, maar productiebetaling vastleggen moet wachten tot WEBSHOP_PAYMENTS_MODE op live staat en providerreferenties zijn gecontroleerd.|Latere fase",
  pl: "Zagnieżdżone kategorie, obrazy, SEO i filtry produktów.|Produkty, warianty, SKU, ceny, media i stany magazynowe.|Zamówienia, płatności, realizacja, zwroty i notatki wsparcia.|Kupony, reguły rabatów, kwalifikacja i śledzenie użycia.|Przegląd list życzeń klientów i edycja istniejących list.|Listy życzeń|Moderacja zweryfikowanych ocen produktów i komentarzy.|Recenzje|Presety przeglądania witryny, filtry i strony produktów.|Domyślne ustawienia sklepu dla checkoutu, płatności, podatków i zamówień.|Licencjonowane|Prywatny panel dodatku commerce.|Zarządzaj kategoriami|Płatności są w trybie testowym|Checkout można bezpiecznie testować, ale produkcyjne pobieranie płatności powinno poczekać, aż WEBSHOP_PAYMENTS_MODE będzie ustawione na live, a dane dostawcy zostaną zweryfikowane.|Późniejsza faza",
  tr: "İç içe kategoriler, görseller, SEO ve ürün filtreleri.|Ürünler, varyantlar, SKU'lar, fiyatlandırma, medya ve stok.|Siparişler, ödemeler, teslimat, iadeler ve destek notları.|Kuponlar, indirim kuralları, uygunluk ve kullanım takibi.|Müşteri istek listesi özeti ve mevcut liste düzenlemeleri.|İstek listeleri|Doğrulanmış ürün puanları ve yorumların moderasyonu.|Değerlendirmeler|Storefront gezinme presetleri, filtreler ve ürün sayfaları.|Checkout, ödemeler, vergi ve siparişler için mağaza geneli varsayılanlar.|Lisanslı|Özel commerce eklentisi panosu.|Kategorileri yönet|Ödemeler test modunda|Checkout güvenle denenebilir, ancak üretim ödeme tahsilatı WEBSHOP_PAYMENTS_MODE live olarak ayarlanana ve sağlayıcı kimlik bilgileri doğrulanana kadar beklemelidir.|Sonraki aşama",
  mk: "Вгнездени категории, слики, SEO и филтри за производи.|Производи, варијанти, SKU-ови, цени, медиуми и залиха.|Нарачки, плаќања, исполнување, рефундации и белешки за поддршка.|Купони, правила за попуст, подобност и следење на користење.|Преглед на листите на желби на купувачите и измени на постојните листи.|Листи на желби|Модерирање на потврдени оценки на производи и коментари.|Рецензии|Пресети за прелистување на излог, филтри и страници на производи.|Подразбирани поставки за продавницата за checkout, плаќања, данок и нарачки.|Лиценцирано|Приватна контролна табла на commerce додатокот.|Управувај со категории|Плаќањата се во тест режим|Checkout може безбедно да се тестира, но продукциското наплатување треба да почека додека WEBSHOP_PAYMENTS_MODE не биде поставен на live и додека акредитивите на провајдерот не се проверат.|Подоцнежна фаза",
  bs: "Ugniježđene kategorije, slike, SEO i filteri proizvoda.|Proizvodi, varijante, SKU-ovi, cijene, mediji i zalihe.|Narudžbe, plaćanja, ispunjenje, povrati i bilješke podrške.|Kuponi, pravila popusta, podobnost i praćenje korištenja.|Pregled lista želja kupaca i izmjene postojećih lista.|Liste želja|Moderacija verifikovanih ocjena proizvoda i komentara.|Recenzije|Preseti izloga za pregledanje, filteri i stranice proizvoda.|Podrazumijevane postavke prodavnice za checkout, plaćanja, porez i narudžbe.|Licencirano|Privatna kontrolna tabla commerce dodatka.|Upravljaj kategorijama|Plaćanja su u testnom načinu|Checkout se može sigurno testirati, ali produkcijsko naplaćivanje treba sačekati dok WEBSHOP_PAYMENTS_MODE ne bude postavljen na live i dok se vjerodajnice provajdera ne provjere.|Kasnija faza",
  sl: "Ugnezdene kategorije, slike, SEO in filtri izdelkov.|Izdelki, različice, SKU-ji, cene, predstavnost in zaloga.|Naročila, plačila, izpolnitev, vračila in opombe podpore.|Kuponi, pravila popustov, upravičenost in sledenje uporabi.|Pregled seznamov želja strank in urejanje obstoječih seznamov.|Seznami želja|Moderiranje preverjenih ocen izdelkov in komentarjev.|Ocene|Prednastavitve brskanja po izložbi, filtri in strani izdelkov.|Privzete nastavitve trgovine za checkout, plačila, davke in naročila.|Licencirano|Zasebna nadzorna plošča commerce dodatka.|Upravljaj kategorije|Plačila so v testnem načinu|Checkout je mogoče varno preizkusiti, vendar naj produkcijski zajem plačil počaka, dokler WEBSHOP_PAYMENTS_MODE ni nastavljen na live in poverilnice ponudnika niso preverjene.|Poznejša faza",
  ru: "Вложенные категории, изображения, SEO и фильтры товаров.|Товары, варианты, SKU, цены, медиа и запасы.|Заказы, платежи, выполнение, возвраты и заметки поддержки.|Купоны, правила скидок, условия применения и отслеживание использования.|Обзор списков желаний клиентов и правки существующих списков.|Списки желаний|Модерация проверенных оценок товаров и комментариев.|Отзывы|Пресеты просмотра витрины, фильтры и страницы товаров.|Общие настройки магазина для checkout, платежей, налогов и заказов.|Лицензировано|Приватная панель commerce-дополнения.|Управлять категориями|Платежи в тестовом режиме|Checkout можно безопасно тестировать, но боевое списание платежей должно подождать, пока WEBSHOP_PAYMENTS_MODE не будет установлен в live и учетные данные провайдера не будут проверены.|Поздняя фаза",
  hu: "Beágyazott kategóriák, képek, SEO és termékszűrők.|Termékek, változatok, SKU-k, árak, média és készlet.|Rendelések, fizetések, teljesítés, visszatérítések és támogatási jegyzetek.|Kuponok, kedvezményszabályok, jogosultság és használatkövetés.|Vásárlói kívánságlisták áttekintése és meglévő listák szerkesztése.|Kívánságlisták|Ellenőrzött termékértékelések és megjegyzések moderálása.|Vélemények|Kirakati böngészési presetek, szűrők és termékoldalak.|Bolt szintű alapértékek checkouthoz, fizetésekhez, adóhoz és rendelésekhez.|Licencelve|Privát commerce bővítmény irányítópult.|Kategóriák kezelése|A fizetések teszt módban vannak|A checkout biztonságosan tesztelhető, de az éles fizetési terhelés várjon, amíg a WEBSHOP_PAYMENTS_MODE live értékre van állítva és a szolgáltatói hitelesítő adatok ellenőrizve vannak.|Későbbi fázis",
  bg: "Вложени категории, изображения, SEO и продуктови филтри.|Продукти, варианти, SKU, цени, медии и наличности.|Поръчки, плащания, изпълнение, възстановявания и бележки за поддръжка.|Купони, правила за отстъпки, допустимост и проследяване на употребата.|Преглед на списъците с желания на клиентите и редакции на съществуващи списъци.|Списъци с желания|Модериране на проверени оценки на продукти и коментари.|Отзиви|Пресети за преглед на витрината, филтри и продуктови страници.|Настройки по подразбиране за магазина за checkout, плащания, данъци и поръчки.|Лицензирано|Частно табло на commerce добавката.|Управление на категории|Плащанията са в тестов режим|Checkout може да се тества безопасно, но продукционното улавяне на плащания трябва да изчака, докато WEBSHOP_PAYMENTS_MODE бъде зададен на live и идентификационните данни на доставчика бъдат проверени.|По-късна фаза",
  ja: "入れ子カテゴリ、画像、SEO、商品フィルター。|商品、バリエーション、SKU、価格、メディア、在庫。|注文、支払い、フルフィルメント、返金、サポートメモ。|クーポン、割引ルール、適用条件、利用追跡。|顧客のウィッシュリスト概要と既存リストの編集。|ウィッシュリスト|確認済みの商品評価とコメントのモデレーション。|レビュー|ストアフロント閲覧プリセット、フィルター、商品ページ。|チェックアウト、支払い、税、注文のストア全体の既定値。|ライセンス済み|非公開のコマース add-on ダッシュボード。|カテゴリを管理|支払いはテストモードです|チェックアウトは安全にテストできますが、本番の決済取得は WEBSHOP_PAYMENTS_MODE が live に設定され、プロバイダー認証情報が確認されるまで待つ必要があります。|後続フェーズ",
  "zh-Hans":
    "嵌套分类、图片、SEO 和商品筛选。|商品、变体、SKU、定价、媒体和库存。|订单、付款、履约、退款和支持备注。|优惠券、折扣规则、适用条件和使用跟踪。|客户愿望清单概览和现有清单编辑。|愿望清单|审核已验证的商品评分和评论。|评价|店面浏览预设、筛选和商品页面。|用于 checkout、付款、税费和订单的全店默认值。|已授权|私有商务 add-on 仪表板。|管理分类|付款处于测试模式|可以安全测试 checkout，但生产付款捕获应等到 WEBSHOP_PAYMENTS_MODE 设置为 live 且提供商凭据已验证后再进行。|后续阶段",
  "zh-Hant":
    "巢狀分類、圖片、SEO 和商品篩選。|商品、變體、SKU、定價、媒體和庫存。|訂單、付款、履約、退款和支援備註。|優惠券、折扣規則、適用條件和使用追蹤。|客戶願望清單概覽和既有清單編輯。|願望清單|審核已驗證的商品評分和評論。|評價|店面瀏覽預設、篩選和商品頁面。|用於 checkout、付款、稅費和訂單的全店預設值。|已授權|私有 commerce add-on 儀表板。|管理分類|付款處於測試模式|可以安全測試 checkout，但生產付款擷取應等到 WEBSHOP_PAYMENTS_MODE 設定為 live 且供應商憑證已驗證後再進行。|後續階段",
  ar: "فئات متداخلة وصور وSEO وفلاتر المنتجات.|المنتجات والمتغيرات وSKU والتسعير والوسائط والمخزون.|الطلبات والمدفوعات والتنفيذ والمبالغ المستردة وملاحظات الدعم.|الكوبونات وقواعد الخصم والأهلية وتتبع الاستخدام.|نظرة عامة على قوائم أمنيات العملاء وتعديلات القوائم الحالية.|قوائم الأمنيات|مراجعة تقييمات المنتجات الموثقة والتعليقات.|المراجعات|إعدادات تصفح واجهة المتجر والفلاتر وصفحات المنتجات.|الإعدادات الافتراضية على مستوى المتجر للـ checkout والمدفوعات والضرائب والطلبات.|مرخص|لوحة تحكم خاصة لإضافة التجارة.|إدارة الفئات|المدفوعات في وضع الاختبار|يمكن اختبار checkout بأمان، لكن تحصيل المدفوعات في الإنتاج يجب أن ينتظر حتى يتم ضبط WEBSHOP_PAYMENTS_MODE على live والتحقق من بيانات اعتماد المزود.|مرحلة لاحقة",
  id: "Kategori bertingkat, gambar, SEO, dan filter produk.|Produk, varian, SKU, harga, media, dan inventaris.|Pesanan, pembayaran, pemenuhan, refund, dan catatan dukungan.|Kupon, aturan diskon, kelayakan, dan pelacakan penggunaan.|Ikhtisar daftar keinginan pelanggan dan edit daftar yang sudah ada.|Daftar keinginan|Moderasi rating produk terverifikasi dan komentar.|Ulasan|Preset penelusuran storefront, filter, dan halaman produk.|Default seluruh toko untuk checkout, pembayaran, pajak, dan pesanan.|Berlisensi|Dasbor add-on commerce privat.|Kelola kategori|Pembayaran berada dalam mode uji|Checkout dapat diuji dengan aman, tetapi penagihan pembayaran produksi harus menunggu sampai WEBSHOP_PAYMENTS_MODE disetel ke live dan kredensial penyedia diverifikasi.|Fase berikutnya",
  cs: "Vnořené kategorie, obrázky, SEO a filtry produktů.|Produkty, varianty, SKU, ceny, média a sklad.|Objednávky, platby, plnění, vratky a poznámky podpory.|Kupóny, pravidla slev, způsobilost a sledování použití.|Přehled zákaznických seznamů přání a úpravy existujících seznamů.|Seznamy přání|Moderace ověřených hodnocení produktů a komentářů.|Recenze|Presety procházení výlohy, filtry a produktové stránky.|Výchozí nastavení obchodu pro checkout, platby, daně a objednávky.|Licencováno|Soukromý dashboard commerce add-onu.|Spravovat kategorie|Platby jsou v testovacím režimu|Checkout lze bezpečně testovat, ale produkční zachycení plateb by mělo počkat, dokud nebude WEBSHOP_PAYMENTS_MODE nastaveno na live a přihlašovací údaje poskytovatele ověřeny.|Pozdější fáze",
  ro: "Categorii imbricate, imagini, SEO și filtre de produse.|Produse, variante, SKU-uri, prețuri, media și stoc.|Comenzi, plăți, îndeplinire, rambursări și note de suport.|Cupoane, reguli de reducere, eligibilitate și urmărirea utilizării.|Prezentare a listelor de dorințe ale clienților și editări ale listelor existente.|Liste de dorințe|Moderarea evaluărilor verificate ale produselor și a comentariilor.|Recenzii|Presetări de navigare în vitrină, filtre și pagini de produs.|Valori implicite ale magazinului pentru checkout, plăți, taxe și comenzi.|Licențiat|Tablou de bord privat pentru add-onul commerce.|Gestionează categoriile|Plățile sunt în modul de test|Checkout poate fi testat în siguranță, dar capturarea plăților în producție trebuie să aștepte până când WEBSHOP_PAYMENTS_MODE este setat la live și acreditările furnizorului sunt verificate.|Fază ulterioară",
  el: "Ένθετες κατηγορίες, εικόνες, SEO και φίλτρα προϊόντων.|Προϊόντα, παραλλαγές, SKU, τιμές, πολυμέσα και απόθεμα.|Παραγγελίες, πληρωμές, εκπλήρωση, επιστροφές και σημειώσεις υποστήριξης.|Κουπόνια, κανόνες έκπτωσης, επιλεξιμότητα και παρακολούθηση χρήσης.|Επισκόπηση λιστών επιθυμιών πελατών και αλλαγές σε υπάρχουσες λίστες.|Λίστες επιθυμιών|Συντονισμός επαληθευμένων αξιολογήσεων προϊόντων και σχολίων.|Κριτικές|Προεπιλογές περιήγησης βιτρίνας, φίλτρα και σελίδες προϊόντων.|Προεπιλογές καταστήματος για checkout, πληρωμές, φόρους και παραγγελίες.|Αδειοδοτημένο|Ιδιωτικός πίνακας ελέγχου commerce add-on.|Διαχείριση κατηγοριών|Οι πληρωμές είναι σε δοκιμαστική λειτουργία|Το checkout μπορεί να δοκιμαστεί με ασφάλεια, αλλά η χρέωση πληρωμών σε παραγωγή πρέπει να περιμένει μέχρι το WEBSHOP_PAYMENTS_MODE να οριστεί σε live και να επαληθευτούν τα διαπιστευτήρια του παρόχου.|Μεταγενέστερη φάση",
  da: "Indlejrede kategorier, billeder, SEO og produktfiltre.|Produkter, varianter, SKU'er, priser, medier og lager.|Ordrer, betalinger, fulfillment, refusioner og supportnoter.|Kuponer, rabatregler, berettigelse og brugssporing.|Oversigt over kunders ønskelister og redigering af eksisterende lister.|Ønskelister|Moderering af verificerede produktbedømmelser og kommentarer.|Anmeldelser|Storefront-browserpresets, filtre og produktsider.|Butiksstandarder for checkout, betalinger, skat og ordrer.|Licenseret|Privat commerce-add-on-dashboard.|Administrer kategorier|Betalinger er i testtilstand|Checkout kan testes sikkert, men produktionsbetaling bør vente, indtil WEBSHOP_PAYMENTS_MODE er sat til live, og udbyderens legitimationsoplysninger er verificeret.|Senere fase",
  sv: "Nästlade kategorier, bilder, SEO och produktfilter.|Produkter, varianter, SKU:er, prissättning, media och lager.|Beställningar, betalningar, fulfillment, återbetalningar och supportanteckningar.|Kuponger, rabattregler, behörighet och användningsspårning.|Översikt över kunders önskelistor och redigering av befintliga listor.|Önskelistor|Moderering av verifierade produktbetyg och kommentarer.|Recensioner|Storefront-bläddringspresets, filter och produktsidor.|Butiksgemensamma standardvärden för checkout, betalningar, skatt och beställningar.|Licensierad|Privat dashboard för commerce-tillägg.|Hantera kategorier|Betalningar är i testläge|Checkout kan testas säkert, men produktionsbetalningar bör vänta tills WEBSHOP_PAYMENTS_MODE är satt till live och leverantörens autentiseringsuppgifter är verifierade.|Senare fas",
  nb: "Nestede kategorier, bilder, SEO og produktfiltre.|Produkter, varianter, SKU-er, priser, medier og lager.|Bestillinger, betalinger, oppfyllelse, refusjoner og supportnotater.|Kuponger, rabattregler, kvalifisering og brukssporing.|Oversikt over kunders ønskelister og redigering av eksisterende lister.|Ønskelister|Moderering av verifiserte produktvurderinger og kommentarer.|Anmeldelser|Storefront-nettlesingspreseter, filtre og produktsider.|Butikkstandarder for checkout, betalinger, skatt og bestillinger.|Lisensiert|Privat commerce-tilleggsdashbord.|Administrer kategorier|Betalinger er i testmodus|Checkout kan testes trygt, men produksjonsbetaling bør vente til WEBSHOP_PAYMENTS_MODE er satt til live og leverandørens legitimasjon er verifisert.|Senere fase",
  nn: "Nøsta kategoriar, bilete, SEO og produktfilter.|Produkt, variantar, SKU-ar, prisar, medium og lager.|Tingingar, betalingar, oppfylling, refusjonar og støttenotat.|Kupongar, rabattreglar, kvalifisering og brukssporing.|Oversikt over ønskjelister frå kundar og redigering av eksisterande lister.|Ønskjelister|Moderering av verifiserte produktvurderingar og kommentarar.|Meldingar|Storefront-nettlesingspreset, filter og produktsider.|Butikkstandardar for checkout, betalingar, skatt og tingingar.|Lisensiert|Privat commerce-tilleggsdashbord.|Administrer kategoriar|Betalingar er i testmodus|Checkout kan testast trygt, men produksjonsbetaling bør vente til WEBSHOP_PAYMENTS_MODE er sett til live og leverandørlegitimasjonen er verifisert.|Seinare fase",
  fi: "Sisäkkäiset kategoriat, kuvat, SEO ja tuotesuodattimet.|Tuotteet, variantit, SKU:t, hinnoittelu, media ja varasto.|Tilaukset, maksut, toimitus, hyvitykset ja tukimuistiinpanot.|Kupongit, alennussäännöt, kelpoisuus ja käytön seuranta.|Asiakkaiden toivelistojen yleiskatsaus ja olemassa olevien listojen muokkaukset.|Toivelistat|Vahvistettujen tuotearvioiden ja kommenttien moderointi.|Arvostelut|Storefront-selauspresetit, suodattimet ja tuotesivut.|Kaupan oletukset checkoutille, maksuille, veroille ja tilauksille.|Lisensoitu|Yksityinen commerce-lisäosan hallintapaneeli.|Hallitse kategorioita|Maksut ovat testitilassa|Checkoutia voi testata turvallisesti, mutta tuotannon maksujen veloitus odottaa, kunnes WEBSHOP_PAYMENTS_MODE on asetettu arvoon live ja palveluntarjoajan tunnistetiedot on vahvistettu.|Myöhempi vaihe",
  is: "Undirflokkar, myndir, SEO og vörusíur.|Vörur, afbrigði, SKU, verð, miðlar og lager.|Pantanir, greiðslur, afgreiðsla, endurgreiðslur og þjónustunótur.|Afsláttarmiðar, afsláttarreglur, gjaldgengi og notkunarrakning.|Yfirlit yfir óskalista viðskiptavina og breytingar á núverandi listum.|Óskalistar|Yfirferð staðfestra vörueinkunna og athugasemda.|Umsagnir|Storefront-vafurspreset, síur og vörusíður.|Sjálfgefin verslunarstilling fyrir checkout, greiðslur, skatta og pantanir.|Leyfisbundið|Einkastjórnborð commerce-viðbótar.|Stjórna flokkum|Greiðslur eru í prófunarham|Checkout má prófa örugglega, en greiðsluinnheimta í framleiðslu ætti að bíða þar til WEBSHOP_PAYMENTS_MODE er stillt á live og auðkenni þjónustuveitanda hafa verið staðfest.|Seinni áfangi",
} satisfies Record<LocalizedLanguage, string>;

function createMap(
  language: string,
  row: string,
): Record<WebshopAdminDashboardSource, string> {
  const translations = row.split("|");
  if (translations.length !== WEBSHOP_ADMIN_DASHBOARD_SOURCE_STRINGS.length) {
    throw new Error(
      `${language} webshop admin dashboard translations must have ${WEBSHOP_ADMIN_DASHBOARD_SOURCE_STRINGS.length} entries, received ${translations.length}.`,
    );
  }

  return Object.fromEntries(
    WEBSHOP_ADMIN_DASHBOARD_SOURCE_STRINGS.map((source, index) => [
      source,
      translations[index] ?? source,
    ]),
  ) as Record<WebshopAdminDashboardSource, string>;
}

export const WEBSHOP_ADMIN_DASHBOARD_SOURCE_TRANSLATIONS = Object.fromEntries(
  Object.entries(ROWS).map(([language, row]) => [
    language,
    createMap(language, row),
  ]),
) as Record<LocalizedLanguage, Record<WebshopAdminDashboardSource, string>>;
